<template>
  <el-dialog :model-value="modelValue" :title="titles[form.kind]" width="min(760px, 95vw)" @update:model-value="$emit('update:modelValue',$event)" destroy-on-close>
    <el-form label-position="top" :model="form" class="care-entry">
      <el-form-item label="title / Name" required><el-input v-model="form.title" maxlength="200" placeholder="for example: weekfourkidneyinternal medicinefollow-up examination / dizziness / want to askClinician question"/></el-form-item>
      <template v-if="form.kind==='APPOINTMENT'">
        <div class="entry-grid"><el-form-item label="follow-up visit / follow-up examinationTime" required><el-date-picker v-model="form.eventAt" type="datetime" value-format="YYYY-MM-DD HH:mm:ss"/></el-form-item><el-form-item label="raisebefore ReminderTime"><el-date-picker v-model="form.notifyAt" type="datetime" value-format="YYYY-MM-DD HH:mm:ss" placeholder="leave blankthenraisebefore onedays"/></el-form-item><el-form-item label="Hospital"><el-input v-model="form.details.hospital"/></el-form-item><el-form-item label="Department"><el-input v-model="form.details.department"/></el-form-item><el-form-item label="Clinician"><el-input v-model="form.details.doctor"/></el-form-item><el-form-item label="visit companion / responsible forfamily caregiver"><el-select v-model="form.assignedUserId" clearable><el-option v-for="m in members" :key="m.userId" :value="m.userId" :label="m.name"/></el-select></el-form-item></div>
        <el-form-item label="Test Itemandaccuratebackupitem"><el-input v-model="form.details.preparation" type="textarea" placeholder="by HospitalNotificationfillwrite, needneedcarrywhat, to whichinhandlemanageetc."/></el-form-item>
        <el-form-item label="relatedthis timesExaminationReport"><el-select v-model="form.details.reportId" clearable filterable><el-option v-for="r in reports" :key="r.id" :value="r.id" :label="`${r.recordDate} ${r.hospitalName||''} ${r.recordType||''}`"/></el-select></el-form-item>
        <el-form-item label="down timesfollow-up examinationTime"><el-date-picker v-model="form.details.nextAt" type="datetime" value-format="YYYY-MM-DD HH:mm:ss" placeholder="markthis timescompleteafter , AutomaticCreatedown timesappointment"/></el-form-item>
      </template>
      <template v-if="form.kind==='ORDER'">
        <el-alert title="by Clinicianprovide prescriptionfillwrite, Savenewversionthis willin take effectDatesamestepMedication Reminders. legacyversionthis keep. " :closable="false" type="info"/>
        <div class="entry-grid"><el-form-item label="Medication" required><el-select v-model="form.details.medicationId" filterable><el-option v-for="m in medications" :key="m.id" :value="m.id" :label="m.drugName"/></el-select></el-form-item><el-form-item label="changetype"><el-radio-group v-model="form.details.action"><el-radio value="CHANGE">start / adjustmedication</el-radio><el-radio value="STOP">stop medication</el-radio></el-radio-group></el-form-item><el-form-item label="take effectDate" required><el-date-picker v-model="form.details.startDate" value-format="YYYY-MM-DD"/></el-form-item><el-form-item v-if="form.details.action!=='STOP'" label="therapyprocessEnd Date (can leave blank) "><el-date-picker v-model="form.details.endDate" clearable value-format="YYYY-MM-DD"/></el-form-item><el-form-item label="opentoolClinician"><el-input v-model="form.details.doctor"/></el-form-item><el-form-item label="countamountUnit"><el-input v-model="form.details.unit" placeholder="tablet / item / ml,  and InventoryUnitkeeponecause"/></el-form-item></div>
        <template v-if="form.details.action!=='STOP'"><el-form-item label="duplicatestarperiod"><el-checkbox-group v-model="days"><el-checkbox v-for="(d,i) in weekdays" :key="i" :value="String(i+1)">{{d}}</el-checkbox></el-checkbox-group></el-form-item>
          <el-form-item label="medication intakeTime and each timesdosage" required><div class="dose-list"><div v-for="(dose,i) in form.details.doses" :key="i" class="dose-row"><el-time-picker v-model="dose.time" value-format="HH:mm" format="HH:mm"/><el-input-number v-model="dose.quantity" :min="0.001" :precision="3"/><span>{{form.details.unit}}</span><el-button :disabled="form.details.doses.length===1" @click="form.details.doses.splice(i,1)">Delete</el-button></div><el-button @click="form.details.doses.push({time:'20:00',quantity:1})">increaseonetimes</el-button></div></el-form-item>
        </template>
        <el-form-item label="prescriptionoriginaltext / adjustreason"><el-input v-model="form.details.instructions" type="textarea" :rows="3"/></el-form-item>
        <el-form-item label="prescriptioncaretablet or PDF"><input type="file" accept="image/*,application/pdf" @change="attach"/><div v-for="(a,i) in form.details.attachments" :key="i"><a :href="a.dataUrl" :download="a.name">{{a.name}}</a><el-button link type="danger" @click="form.details.attachments.splice(i,1)">Remove</el-button></div></el-form-item>
        <el-checkbox v-model="form.details.confirmed">Ialready based onClinicianprescriptionverifyMedication, dosage and take effectDate</el-checkbox>
      </template>
      <template v-if="form.kind==='SYMPTOM'">
        <el-form-item label="occurTime" required><el-date-picker v-model="form.eventAt" type="datetime" value-format="YYYY-MM-DD HH:mm:ss"/></el-form-item>
        <el-form-item label="symptomlevel (0Nonediscomfort, 10most strong) "><el-slider v-model="form.details.severity" :min="0" :max="10" show-stops show-input/></el-form-item>
        <div class="entry-grid"><el-form-item label="durationmultiplelong"><el-input v-model="form.details.duration" placeholder="for example: about20minutes / durationonewholedays"/></el-form-item><el-form-item label="itembefore condition"><el-select v-model="form.details.progress"><el-option label="stillhas symptom" value="ONGOING"/><el-option label="already relieved" value="IMPROVED"/><el-option label="already disappear" value="RESOLVED"/></el-select></el-form-item></div>
        <el-form-item label="when timein what to do / companionfollowcondition"><el-input v-model="form.details.context" type="textarea"/></el-form-item><el-form-item label="what to do, validresultfor example what"><el-input v-model="form.details.response" type="textarea"/></el-form-item>
      </template>
      <template v-if="form.kind==='QUESTION'">
        <el-form-item label="accuratebackupin whichtimesfollow-up visitask"><el-select v-model="form.details.appointmentId" clearable><el-option v-for="a in appointments" :key="a.id" :value="a.id" :label="`${a.eventAt||''} ${a.title}`"/></el-select></el-form-item>
        <el-form-item label="questionadd details"><el-input v-model="form.details.description" type="textarea"/></el-form-item><el-form-item label="Clinician's answer"><el-input v-model="form.details.answer" type="textarea"/></el-form-item><el-form-item label="after continueneedwhat to do"><el-input v-model="form.details.followUp" type="textarea"/></el-form-item>
      </template>
      <template v-if="form.kind==='HANDOVER'">
        <el-form-item label="handovercontent"><el-input v-model="form.details.note" type="textarea" :rows="4" placeholder="for example: cleardaysExaminationsingleplacein living-room drawer, outputdoorbefore recordremember to bringup "/></el-form-item>
        <div class="entry-grid"><el-form-item label="Please whofollow-up"><el-select v-model="form.assignedUserId" clearable><el-option v-for="m in members" :key="m.userId" :value="m.userId" :label="m.name"/></el-select></el-form-item><el-form-item label="preferredtimecomplete"><el-date-picker v-model="form.eventAt" type="datetime" value-format="YYYY-MM-DD HH:mm:ss"/></el-form-item><el-form-item label="ReminderTime"><el-date-picker v-model="form.notifyAt" type="datetime" value-format="YYYY-MM-DD HH:mm:ss"/></el-form-item></div>
      </template>
    </el-form>
    <template #footer><el-button @click="$emit('update:modelValue',false)">Cancel</el-button><el-button type="primary" :loading="saving" @click="submit">Save</el-button></template>
  </el-dialog>
</template>
<script setup>
import {reactive,ref,watch} from 'vue'
import {ElMessage} from 'element-plus'
import {saveCareItem} from '@/api/care'
import {localDateKey} from '@/utils/familyHealth'
const props=defineProps({modelValue:Boolean,kind:String,row:Object,patientId:[Number,String],members:{type:Array,default:()=>[]},medications:{type:Array,default:()=>[]},reports:{type:Array,default:()=>[]},appointments:{type:Array,default:()=>[]}})
const emit=defineEmits(['update:modelValue','saved'])
const form=reactive({details:{}}),saving=ref(false),days=ref([]),weekdays=['weekone','weektwo','weekthree','weekfour','weekfive','weeksix','weekDay']
const titles={APPOINTMENT:'follow-up visit / follow-up examinationschedule',ORDER:'prescription and medication regimen',SYMPTOM:'recordsymptom',QUESTION:'follow-up visitquestion',HANDOVER:'carehandover'}
watch(()=>props.modelValue,open=>{if(!open)return;Object.keys(form).forEach(k=>delete form[k]);Object.assign(form,{kind:props.kind,title:'',eventAt:null,notifyAt:null,assignedUserId:null,details:{startDate:localDateKey(),endDate:null,action:'CHANGE',unit:'tablet',repeatDays:'1,2,3,4,5,6,7',doses:[{time:'08:00',quantity:1}],attachments:[],confirmed:false,severity:3,progress:'ONGOING'}},props.row?JSON.parse(JSON.stringify(props.row)):{});if(props.kind==='ORDER'){delete form.id;form.details.confirmed=false}days.value=String(form.details.repeatDays||'1,2,3,4,5,6,7').split(',');if(props.kind==='SYMPTOM'&&!form.eventAt)form.eventAt=localDateKey()+' '+new Date().toTimeString().slice(0,8)})
async function attach(e){const file=e.target.files?.[0];if(!file)return;if(file.size>5*1024*1024){ElMessage.warning('each copyAttachmentPlease controlin 5MBtowithin');return}const dataUrl=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)});form.details.attachments||=[];form.details.attachments.push({name:file.name,dataUrl});e.target.value=''}
async function submit(){if(!form.title.trim()){ElMessage.warning('Please fillwritetitle');return}if(['APPOINTMENT','SYMPTOM'].includes(form.kind)&&!form.eventAt){ElMessage.warning('SelectTime');return}saving.value=true;const pid=props.patientId;try{const data=JSON.parse(JSON.stringify(form));data.patientId=pid;if(data.kind==='ORDER')data.details.repeatDays=days.value.join(',');await saveCareItem(data);if(pid===props.patientId){emit('saved');emit('update:modelValue',false)}ElMessage.success('Saved successfully.')}finally{saving.value=false}}
</script>
<style scoped>.entry-grid{display:grid;grid-template-columns:1fr 1fr;gap:0 20px}.care-entry :deep(.el-select),.care-entry :deep(.el-date-editor){width:100%}.dose-list{width:100%}.dose-row{display:flex;gap:10px;align-items:center;margin-bottom:10px}.dose-row :deep(.el-date-editor){width:150px}@media(max-width:600px){.entry-grid{grid-template-columns:1fr}.dose-row{flex-wrap:wrap}}</style>
