<template>
  <el-dialog v-model="welcomeVisible" title="Welcome to your health workspace" width="min(480px, 94vw)" :close-on-click-modal="false">
    <div class="guide-welcome"><el-icon :size="34"><Guide /></el-icon><div><h3>Start an interactive walkthrough?</h3><p>A pointer will lead you to the real control, explain what it does, and wait for your confirmation at every step.</p></div></div>
    <template #footer><el-button @click="dismissWelcome">Maybe Later</el-button><el-button type="primary" @click="begin">Start Interactive Guide</el-button></template>
  </el-dialog>
  <div v-if="active" class="guide-layer" role="dialog" aria-modal="true" :aria-labelledby="`guide-title-${stepIndex}`">
    <div class="guide-anchor" :style="anchorStyle" aria-hidden="true"></div>
    <section class="guide-card" :class="`guide-card--${cardPlacement}`" :style="cardStyle">
      <button class="guide-close" type="button" aria-label="Pause guide" @click="pause">×</button>
      <span class="guide-kicker">GUIDED TOUR</span>
      <h2 :id="`guide-title-${stepIndex}`">{{ current.title }}</h2>
      <p>{{ current.description }}</p>
      <div class="guide-instruction"><strong>{{ current.gesture }}</strong><span>{{ current.action }}</span><small>Expected: {{ current.result }}</small></div>
      <footer><button type="button" :disabled="stepIndex===0" aria-label="Previous step" @click="previous">‹</button><span>{{stepIndex+1}} / {{steps.length}}</span><button type="button" :aria-label="stepIndex===steps.length-1?'Finish guide':'Confirm step and continue'" @click="confirmStep">{{stepIndex===steps.length-1?'✓':'›'}}</button></footer>
    </section>
  </div>
</template>

<script setup>
import { computed, nextTick, onBeforeUnmount, reactive, ref, watch } from 'vue';
import { useRouter } from 'vue-router';
import { Guide, Menu, Search, User, FirstAidKit, Odometer, House, Setting, Switch } from '@element-plus/icons-vue';
const props=defineProps({accountId:{type:[String,Number],default:''},roleCodes:{type:Array,default:()=>[]}}),router=useRouter();
const welcomeVisible=ref(false),active=ref(false),stepIndex=ref(0),targetBox=reactive({top:80,left:80,width:220,height:80}),viewport=reactive({width:1280,height:800}),cardPlacement=ref('right');
const role=computed(()=>['admin','doctor','patient','family'].find(code=>props.roleCodes.includes(code))||'patient');
const detail=(title,description,action,result,why,selector,icon,gesture,path)=>({title,description,action,result,why,selector,icon,gesture,path});
const commonEnd=[
  detail('Find any feature quickly','The feature finder searches the workspace without making you remember where each page lives.','Click the highlighted search control, type “medication” or “report”, then choose a result.','The matching page opens and the breadcrumb changes.','This is the quickest and safest route when you are unfamiliar with the menu.','.workspace-search',Search,'Click here'),
  detail('Confirm the current patient','Every clinical record and care action belongs to the patient selected here.','Open the highlighted patient selector and verify the name before entering data.','The selected patient name remains visible in the header.','Checking identity first prevents information from being added to the wrong record.','.patient-switcher',Switch,'Check this name'),
  detail('Manage your account safely','Password and sign-out actions are grouped in the account control.','Click the highlighted account area when you need to change your password or sign out.','The account panel opens with identity and security actions.','Every care-team member should use an individual, traceable account.','.workspace-account',User,'Open here')
];
const roleSteps={
  doctor:[detail('Review a clinical item','The doctor workspace brings pending records and AI-assisted summaries into one review queue.','Use the highlighted decision button only after checking the patient and source.','The item leaves the queue and the decision is recorded.','Clinical decisions remain explicit and auditable.','.review-actions .el-button',FirstAidKit,'Use this button','/doctor-workspace')],
  patient:[detail('Record a due measurement','The blood-pressure page stores readings against the selected patient and measurement time.','Enter the reading in the highlighted field, verify the time, and save.','The new reading appears in history and updates the trend.','Consistent measurements give the care team a usable longitudinal picture.','.entry-panel input',Odometer,'Type here','/bp-self-monitor')],
  family:[detail('Open a family care action','The family workspace combines medication, measurements, appointments, and handover work.','Use the highlighted action after selecting the correct family member.','The shared schedule updates for the care team.','This prevents incomplete or wrong-person handovers.','.care-toolbar .el-button',House,'Use this button','/care')],
  admin:[detail('Open an account action','User management controls identity and role assignment separately from clinical records.','Use the highlighted toolbar button after confirming the intended role scope.','The relevant administration workflow opens.','Least-privilege access protects sensitive health information.','.toolbar .el-button',Setting,'Use this button','/system/user')]
};
const steps=computed(()=>[...(roleSteps[role.value]||roleSteps.patient),...commonEnd]);
const current=computed(()=>steps.value[stepIndex.value]),storageKey=computed(()=>`care-onboarding:${props.accountId||'guest'}:${role.value}`),promptKey=computed(()=>`care-onboarding-prompt:${props.accountId||'guest'}:${role.value}`);
const anchorStyle=computed(()=>{const side=cardPlacement.value;return{left:`${side==='left'?targetBox.left:side==='right'?targetBox.left+targetBox.width:targetBox.left+targetBox.width/2}px`,top:`${side==='top'?targetBox.top+targetBox.height:side==='bottom'?targetBox.top:targetBox.top+targetBox.height/2}px`}});
const cardStyle=computed(()=>{const width=Math.min(370,viewport.width-24),height=285,gap=20;let left,top;if(viewport.width<720){cardPlacement.value='bottom';left=12;top=Math.max(12,viewport.height-height-12)}else if(targetBox.left+targetBox.width+gap+width<viewport.width){cardPlacement.value='right';left=targetBox.left+targetBox.width+gap;top=targetBox.top+targetBox.height/2-height/2}else if(targetBox.left-width-gap>0){cardPlacement.value='left';left=targetBox.left-width-gap;top=targetBox.top+targetBox.height/2-height/2}else if(targetBox.top+targetBox.height+gap+height<viewport.height){cardPlacement.value='top';left=targetBox.left+targetBox.width/2-width/2;top=targetBox.top+targetBox.height+gap}else{cardPlacement.value='bottom';left=targetBox.left+targetBox.width/2-width/2;top=targetBox.top-height-gap}return{left:`${Math.max(12,Math.min(left,viewport.width-width-12))}px`,top:`${Math.max(12,Math.min(top,viewport.height-height-12))}px`,width:`${width}px`}});
let highlighted,positionTimer;
function clearHighlight(){clearTimeout(positionTimer);highlighted?.classList.remove('guide-target');highlighted=null}
function positionGuide(){viewport.width=window.innerWidth;viewport.height=window.innerHeight;const rect=highlighted?.getBoundingClientRect();if(!rect){Object.assign(targetBox,{top:70,left:20,width:Math.min(260,viewport.width-40),height:90});return}const pad=8;Object.assign(targetBox,{top:Math.max(6,rect.top-pad),left:Math.max(6,rect.left-pad),width:Math.min(viewport.width-12,rect.width+pad*2),height:Math.min(viewport.height-12,rect.height+pad*2)})}
async function showStep(){clearHighlight();if(current.value.path&&router.currentRoute.value.path!==current.value.path)await router.push(current.value.path);await nextTick();positionTimer=setTimeout(()=>{highlighted=document.querySelector(current.value.selector)||document.querySelector('.workspace-content');highlighted?.scrollIntoView?.({block:'center',behavior:'smooth'});highlighted?.classList.add('guide-target');positionGuide()},260)}
function begin(){welcomeVisible.value=false;localStorage.setItem(promptKey.value,'seen');const saved=Number(localStorage.getItem(storageKey.value));stepIndex.value=Number.isInteger(saved)&&saved>=0&&saved<steps.value.length?saved:0;active.value=true;window.addEventListener('resize',positionGuide);showStep()}
function start(){const saved=Number(localStorage.getItem(storageKey.value));stepIndex.value=Number.isInteger(saved)&&saved>=0&&saved<steps.value.length?saved:0;active.value=true;welcomeVisible.value=false;window.addEventListener('resize',positionGuide);showStep()}
function dismissWelcome(){welcomeVisible.value=false;localStorage.setItem(promptKey.value,'seen')}function pause(){localStorage.setItem(storageKey.value,String(stepIndex.value));active.value=false;clearHighlight();window.removeEventListener('resize',positionGuide)}function previous(){if(stepIndex.value>0){stepIndex.value--;showStep()}}function confirmStep(){if(stepIndex.value===steps.value.length-1){localStorage.setItem(storageKey.value,'complete');active.value=false;clearHighlight();window.removeEventListener('resize',positionGuide);return}stepIndex.value++;localStorage.setItem(storageKey.value,String(stepIndex.value));showStep()}
watch(()=>[props.accountId,props.roleCodes.join(',')],()=>{if(props.accountId&&!localStorage.getItem(promptKey.value)&&localStorage.getItem(storageKey.value)!=='complete')welcomeVisible.value=true},{immediate:true});onBeforeUnmount(()=>{clearHighlight();window.removeEventListener('resize',positionGuide)});defineExpose({start});
</script>

<style scoped>
.guide-welcome{display:flex;gap:16px;align-items:flex-start}.guide-welcome .el-icon{padding:12px;border-radius:14px;background:#eeeafe;color:#51469a}.guide-welcome h3{margin:0 0 8px}.guide-welcome p{margin:0;color:#667b75;line-height:1.7}.guide-layer{position:fixed;inset:0;z-index:4800;background:rgb(38 31 76 / 8%);pointer-events:none}.guide-anchor{position:fixed;z-index:2;width:18px;height:18px;box-sizing:border-box;margin:-9px 0 0 -9px;border:5px solid #d9d4ff;border-radius:50%;background:#51469a;box-shadow:0 0 0 5px rgb(81 70 154 / 16%);transition:left .22s ease,top .22s ease}.guide-card{position:fixed;z-index:3;box-sizing:border-box;min-height:248px;max-height:calc(100vh - 24px);overflow:auto;padding:25px 28px 19px;border-radius:8px;background:#51469a;color:#fff;box-shadow:0 18px 45px rgb(41 33 91 / 30%);pointer-events:auto;transition:left .22s ease,top .22s ease}.guide-card::before{content:"";position:absolute;border:12px solid transparent}.guide-card--right::before{left:-24px;top:calc(50% - 12px);border-right-color:#51469a}.guide-card--left::before{right:-24px;top:calc(50% - 12px);border-left-color:#51469a}.guide-card--top::before{top:-24px;left:calc(50% - 12px);border-bottom-color:#51469a}.guide-card--bottom::before{bottom:-24px;left:calc(50% - 12px);border-top-color:#51469a}.guide-close{position:absolute;top:11px;right:13px;border:0;background:transparent;color:rgb(255 255 255 / 72%);font-size:21px;line-height:1;cursor:pointer}.guide-close:hover{color:#fff}.guide-kicker{font-size:10px;font-weight:800;letter-spacing:.13em;color:#dcd8ff}.guide-card h2{margin:12px 22px 9px 0;font-size:20px;line-height:1.35}.guide-card>p{margin:0;color:rgb(255 255 255 / 88%);font-size:14px;line-height:1.55}.guide-instruction{display:grid;gap:4px;margin-top:15px;padding-top:13px;border-top:1px solid rgb(255 255 255 / 18%)}.guide-instruction strong{font-size:13px}.guide-instruction span{font-size:13px;line-height:1.45}.guide-instruction small{color:rgb(255 255 255 / 70%);font-size:11px;line-height:1.4}.guide-card footer{display:flex;align-items:center;justify-content:flex-end;gap:10px;margin-top:16px}.guide-card footer button{display:grid;width:30px;height:30px;padding:0;border:0;border-radius:50%;background:transparent;color:#fff;font-size:26px;line-height:1;place-items:center;cursor:pointer}.guide-card footer button:hover:not(:disabled){background:rgb(255 255 255 / 14%)}.guide-card footer button:disabled{opacity:.28;cursor:default}.guide-card footer span{min-width:42px;text-align:center;font-size:13px;font-weight:700}.guide-card footer button:last-child{background:rgb(255 255 255 / 12%)}@media(max-width:719px){.guide-layer{background:rgb(38 31 76 / 12%)}.guide-card{min-height:0;padding:22px 22px 16px}.guide-card h2{font-size:18px}.guide-card--bottom::before,.guide-card--top::before{left:calc(50% - 12px)}}
</style>
<style>.guide-card{overflow:visible}.guide-target{position:relative!important;z-index:4801!important;outline:2px solid #6e62c7!important;outline-offset:4px!important;box-shadow:0 0 0 6px rgb(110 98 199 / 14%)!important;border-radius:8px!important}</style>
