(() => {
  const M = window.HealthDemo, zh = document.documentElement.lang.startsWith('zh');
  let state = M.createState(), range = 7, action = null, toastTimer, returnFocus;
  const $ = id => document.getElementById(id), l = value => value && typeof value === 'object' ? value[zh ? 'zh' : 'en'] : value;
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' }[c]));
  const tx = (en, cn) => zh ? cn : en, p = () => M.current(state);
  const copy = {
    doctor: { name:tx('Doctor','医生'), workspace:tx('Clinical workspace','医生工作台'), account:tx('Dr. Sarah Chen','陈医生'), avatar:tx('DR','医'), start:'overview', nav:{ overview:tx('Work overview','工作概览'), patients:tx('Patient panel','患者面板'), reviews:tx('Review queue','复核队列'), plans:tx('Care plans','照护计划'), records:tx('Health records','健康档案') } },
    patient: { name:tx('Patient','患者'), workspace:tx('My health workspace','我的健康工作台'), account:l(state.patients[0].name), avatar:tx('AZ','患'), start:'today', nav:{ today:tx('Today','今日任务'), vitals:tx('Vital signs','生命体征'), medications:tx('Medications','用药管理'), records:tx('Medical records','医疗记录'), dialysis:tx('Dialysis','透析管理'), nutrition:tx('Nutrition','营养管理') } },
    family: { name:tx('Family','家属'), workspace:tx('Family care workspace','家属照护工作台'), account:tx('Wei Zhang','张伟'), avatar:tx('WZ','家'), start:'care', nav:{ care:tx('Care schedule','照护日程'), medications:tx('Medication check-ins','用药打卡'), appointments:tx('Appointments','复诊安排'), handover:tx('Family handover','家庭交接'), records:tx('Shared records','共享档案') } }
  };
  const button = (label, act, secondary=false, data='') => `<button class="button${secondary?' secondary':''}" data-action="${act}" ${data}>${label}</button>`;
  function toast(message) { const el=$('toast'); el.textContent=message; el.hidden=false; clearTimeout(toastTimer); toastTimer=setTimeout(()=>{el.hidden=true;},3200); }
  function page() { const key=location.hash.slice(1), nav=copy[state.role].nav; return Object.hasOwn(nav,key)?key:copy[state.role].start; }
  function heading(kicker,title,subtitle,art='care-moments-small.webp',actions='') { return `<header class="page-heading"><div><span class="eyebrow">${kicker}</span><h1>${title}</h1><p>${subtitle}</p>${actions?`<div class="heading-actions">${actions}</div>`:''}</div><img class="heading-art" src="assets/${art}" alt="" width="180" height="120"></header>`; }
  function risk(value) { return `<span class="tag risk-${value}">${value==='critical'?tx('Needs review','需关注'):value==='watch'?tx('Watch','观察'):tx('Stable','稳定')}</span>`; }
  function stats() { const latest=p().records.at(-1), done=p().tasks.filter(t=>t.done).length, pending=state.reviews.filter(r=>r.status==='pending').length; return `<section class="stats"><article><span>${tx('Today’s tasks','今日任务')}</span><strong>${done}<small> / ${p().tasks.length}</small></strong><p>${tx('Care plan progress','照护计划进度')}</p></article><article><span>${tx('Latest blood pressure','最近血压')}</span><strong>${latest.systolic}<small> / ${latest.diastolic}</small></strong><p>mmHg · ${latest.date}</p></article><article><span>${tx('Pending clinical reviews','待临床复核')}</span><strong>${pending}<small> ${tx('items','项')}</small></strong><p>${tx('Records and AI summaries','记录与 AI 摘要')}</p></article><article><span>${tx('Next appointment','下次复诊')}</span><strong>${state.appointments[0].date.slice(5)}<small> ${state.appointments[0].time}</small></strong><p>${l(state.appointments[0].clinic)}</p></article></section>`; }
  function tasks(filter) { const rows=p().tasks.filter(t=>!filter||t.type===filter); return `<div class="task-list">${rows.map(t=>`<article class="task ${t.done?'done':''}"><span class="time">${t.time}</span><span class="task-mark">${t.done?'✓':'◷'}</span><div class="task-copy"><b>${l(t.title)}</b><small>${l(t.detail)}</small></div>${t.done?`<span class="tag">${tx('Completed','已完成')}</span>`:button(t.type==='medication'?tx('Mark taken','标记已服'):t.type==='vital'?tx('Record','记录'):tx('Complete','完成'),t.type==='vital'?'vital':'complete',true,`data-id="${t.id}"`)}</article>`).join('')}</div>`; }
  function chart() { const rows=p().records.slice(-range), x=i=>48+i*610/Math.max(1,rows.length-1), y=v=>210-(v-50)/110*175, line=k=>rows.map((r,i)=>`${x(i)},${y(r[k])}`).join(' '); return `<div class="chart-legend"><span>● ${tx('Systolic','收缩压')}</span><span>● ${tx('Diastolic','舒张压')}</span><small>mmHg · ${tx('fictional data','虚构数据')}</small></div><svg class="chart" viewBox="0 0 700 240" role="img" aria-label="${tx('Blood pressure trend','血压趋势')}"><g class="grid-lines">${[60,90,120,150].map(v=>`<line x1="48" y1="${y(v)}" x2="658" y2="${y(v)}"/><text x="8" y="${y(v)+4}">${v}</text>`).join('')}</g><polyline class="line-primary" points="${line('systolic')}"/><polyline class="line-secondary" points="${line('diastolic')}"/>${rows.map((r,i)=>`<circle cx="${x(i)}" cy="${y(r.systolic)}" r="3.5" fill="#267266"><title>${r.date}: ${r.systolic}/${r.diastolic}</title></circle>`).join('')}</svg>`; }
  const rangeControl = () => `<div class="segmented"><button data-action="range" data-days="7" aria-pressed="${range===7}">${tx('7 days','7 天')}</button><button data-action="range" data-days="30" aria-pressed="${range===30}">${tx('30 days','30 天')}</button></div>`;
  function patientCards() { return `<div class="patient-grid">${state.patients.map(person=>`<article class="patient-card ${person.id===state.patientId?'selected':''}"><div class="card-row"><span class="avatar light">${l(person.name).slice(0,1)}</span>${risk(person.risk)}</div><h3>${l(person.name)}</h3><p>${person.age} ${tx('years','岁')} · ${l(person.condition)}</p><div class="mini-metrics"><span><b>${person.records.at(-1).systolic}/${person.records.at(-1).diastolic}</b><small>${tx('Latest BP','最近血压')}</small></span><span><b>${person.tasks.filter(t=>!t.done).length}</b><small>${tx('Open tasks','待办')}</small></span></div>${button(tx('Open patient','查看患者'),'select-patient',true,`data-id="${person.id}"`)}</article>`).join('')}</div>`; }
  function reviewQueue() { const rows=state.reviews.filter(r=>r.status==='pending'); return rows.length?`<div class="review-list">${rows.map(r=>{const patient=state.patients.find(x=>x.id===r.patientId); return `<article class="review-card"><div><span class="eyebrow">${r.kind==='ai'?tx('AI-ASSISTED · REQUIRES CLINICIAN REVIEW','AI 辅助 · 须医生复核'):tx('IMPORTED RECORD','导入记录')}</span><h3>${l(patient.name)} · ${l(r.title)}</h3><p>${r.date} · ${tx('Extraction confidence','提取可信度')} ${r.confidence}%</p></div><div class="review-actions">${button(tx('Approve','通过'),'review-approve',true,`data-id="${r.id}"`)}${button(tx('Reject','驳回'),'review-reject',true,`data-id="${r.id}"`)}</div></article>`;}).join('')}</div>`:`<div class="empty"><b>${tx('Review queue cleared','复核队列已清空')}</b><p>${tx('There are no imported records or AI summaries waiting for a clinician.','暂无等待医生确认的导入记录或 AI 摘要。')}</p></div>`; }
  function doctorOverview() { return heading(tx('CLINICAL WORKSPACE','医生工作台'),tx('Start with what needs clinical attention','先处理真正需要临床关注的事项'),tx('Risk, review, and care-plan work are organized around assigned patients.','围绕已分配患者，集中处理风险、复核与照护计划。'),'health-journal-small.webp')+stats()+`<div class="columns"><section class="panel"><header class="panel-heading"><div><span class="eyebrow">${tx('PRIORITY','优先处理')}</span><h2>${tx('Clinical review queue','临床复核队列')}</h2></div><a href="#reviews">${tx('View all','查看全部')} →</a></header>${reviewQueue()}</section><section class="panel"><header class="panel-heading"><div><span class="eyebrow">${tx('SELECTED PATIENT','当前患者')}</span><h2>${l(p().name)}</h2></div>${risk(p().risk)}</header><p>${l(p().condition)}</p><div class="note"><span class="avatar light">${tx('DR','医')}</span><div><b>${l(state.notes[0].author)}</b><p>${l(state.notes[0].text)}</p></div></div>${button(tx('Create care plan','新建照护计划'),'plan')}</section></div>`; }
  function patients() { return heading(tx('CARE TEAM','医疗团队'),tx('Assigned patient panel','已分配患者面板'),tx('Each clinician sees only the patients assigned to their care team.','医生仅能看到已分配到当前医疗团队的患者。'),'care-moments-small.webp')+`<section class="panel">${patientCards()}</section>`; }
  function reviews() { return heading(tx('CLINICAL SAFETY','临床安全'),tx('Review before information becomes clinical truth','先复核，再让信息进入临床记录'),tx('Imported records and AI-assisted analysis remain pending until a clinician decides.','导入记录与 AI 辅助分析必须经医生确认后生效。'),'records-care-small.webp')+`<section class="notice">${tx('AI output is decision support, not an autonomous diagnosis. Every decision is recorded in the full application.','AI 输出仅用于辅助决策，不会自动诊断；正式系统会记录每次复核。')}</section><section class="panel">${reviewQueue()}</section>`; }
  function plans() { const rows=state.plans.filter(x=>x.patientId===state.patientId); return heading(tx('CONTINUOUS CARE','连续照护'),tx('Care plans with clear ownership','责任清晰的照护计划'),tx('Define goals, instructions, target dates, and follow-up ownership.','明确目标、执行说明、截止日期和随访责任。'),'care-moments-small.webp',button(tx('＋ New care plan','＋ 新建计划'),'plan'))+`<section class="panel"><div class="plan-grid">${rows.map(x=>`<article class="plan-card"><span class="tag">${tx('Active','执行中')}</span><h3>${l(x.title)}</h3><p>${tx('Owner','负责人')}：${l(x.owner)}</p><strong>${tx('Target','计划日期')} · ${x.target}</strong></article>`).join('')}</div></section>`; }
  function today() { return heading(tx('MY HEALTH','我的健康'),tx('A calm plan for today','从容完成今天的健康计划'),tx('Record readings, check medications, and follow clinician guidance one step at a time.','按步骤记录指标、完成用药并查看医生建议。'),'care-moments-small.webp',button(tx('＋ Record blood pressure','＋ 记录血压'),'vital'))+stats()+`<section class="panel"><header class="panel-heading"><h2>${tx('Today’s plan','今日计划')}</h2><span class="tag">${p().tasks.length} ${tx('items','项')}</span></header>${tasks()}</section>`; }
  function vitals() { return heading(tx('VITAL SIGNS','生命体征'),tx('See change, not just a single number','看见变化，而不只是一个数值'),tx('New entries update the timeline and can be exported for a follow-up visit.','新增记录会更新趋势，也可导出用于复诊。'),'health-journal-small.webp',button(tx('＋ Record reading','＋ 记录读数'),'vital'))+`<section class="panel"><header class="panel-heading"><h2>${tx('Blood-pressure trend','血压趋势')}</h2>${rangeControl()}</header>${chart()}</section><section class="panel"><header class="panel-heading"><h2>${tx('Recent readings','近期读数')}</h2>${button(tx('Export CSV','导出 CSV'),'export',true)}</header><div class="table-wrap"><table><thead><tr><th>${tx('Date','日期')}</th><th>${tx('Time','时间')}</th><th>${tx('Systolic','收缩压')}</th><th>${tx('Diastolic','舒张压')}</th></tr></thead><tbody>${p().records.slice(-7).reverse().map(r=>`<tr><td>${r.date}</td><td>${r.time}</td><td>${r.systolic} mmHg</td><td>${r.diastolic} mmHg</td></tr>`).join('')}</tbody></table></div></section>`; }
  function medications() { return heading(tx('MEDICATION SAFETY','用药安全'),tx('Make every check-in visible','让每次用药都有记录'),tx('Schedules, check-ins, and stock stay connected for the patient and family.','用药计划、服药打卡和库存对患者与家属保持同步。'),'medication-care-small.webp')+`<section class="notice">${tx('Medication names and doses here are fictional and are not treatment advice.','页面中的药名和剂量均为虚构，不构成用药建议。')}</section><section class="panel"><div class="drug-grid">${p().stocks.map((s,i)=>`<article class="drug"><div class="drug-icon">✚</div><div><span class="tag ${s<10?'warm':''}">${s<10?tx('Low stock','库存偏低'):tx('In stock','库存正常')}</span><h3>${tx('Demo Medication','演示药品')} ${i?'B':'A'}</h3><strong>${s} <small>${tx('tablets left','片剩余')}</small></strong></div></article>`).join('')}</div></section><section class="panel"><h2>${tx('Today’s check-ins','今日打卡')}</h2>${tasks('medication')}</section>`; }
  function records() { const names=[tx('Complete blood count','血常规报告'),tx('Metabolic panel','生化检验报告'),tx('Discharge summary','出院小结')]; return heading(tx('LONGITUDINAL RECORD','连续健康档案'),tx('A shared, reviewable health history','可共享、可复核的健康记录'),tx('Reports, visits, measurements, and clinician notes remain connected.','报告、就诊、测量和医生记录彼此关联。'),'records-care-small.webp')+`<section class="panel"><div class="report-grid">${names.map((name,i)=>`<button class="report-card" data-action="detail" data-id="${i}"><span class="report-icon">▤</span><span class="tag neutral">${i===2?tx('Visit document','就诊文书'):tx('Lab report','检验报告')}</span><h3>${name}</h3><p>${p().records.at(-1-i*4).date} · ${tx('Demo Medical Center','演示医疗中心')}</p><span class="report-open">${tx('View structured record','查看结构化记录')} →</span></button>`).join('')}</div></section>`; }
  function dialysis() { return heading(tx('DIALYSIS','透析管理'),tx('Treatment sessions in one timeline','集中管理每次治疗过程'),tx('Track pre/post weight, ultrafiltration, symptoms, and follow-up.','记录透析前后体重、超滤量、症状与随访。'),'health-journal-small.webp')+`<section class="stats"><article><span>${tx('Last session','最近一次')}</span><strong>09-19</strong><p>${tx('Completed','已完成')}</p></article><article><span>${tx('Pre / post weight','透析前 / 后体重')}</span><strong>62.4<small> / 60.2 kg</small></strong><p>${tx('Fictional session','虚构治疗记录')}</p></article><article><span>${tx('Ultrafiltration','超滤量')}</span><strong>2.2<small> L</small></strong><p>${tx('Within planned range','在计划范围内')}</p></article><article><span>${tx('Next session','下次治疗')}</span><strong>${tx('Tue','周二')}<small> 08:30</small></strong><p>${tx('Demo schedule','演示日程')}</p></article></section><section class="panel"><h2>${tx('Session notes','治疗记录')}</h2><div class="note"><span class="avatar light">✓</span><div><b>${tx('Session completed without reported discomfort','治疗完成，未报告明显不适')}</b><p>${tx('The full application records access condition, blood pressure, symptoms, medication, and clinician follow-up.','正式系统可记录通路情况、血压、症状、用药及医生随访。')}</p></div></div></section>`; }
  function nutrition() { return heading(tx('NUTRITION','营养管理'),tx('Daily choices linked to the care plan','让每日饮食与照护计划相连'),tx('Track fluid, sodium, protein guidance, and dietitian follow-up.','管理饮水、钠、蛋白建议及营养师随访。'),'care-moments-small.webp')+`<section class="stats"><article><span>${tx('Fluid today','今日饮水')}</span><strong>820<small> ml</small></strong><p>${tx('Target 1,200 ml','目标 1,200 ml')}</p></article><article><span>${tx('Meals logged','饮食记录')}</span><strong>2<small> / 3</small></strong><p>${tx('Breakfast and lunch','早餐与午餐')}</p></article><article><span>${tx('Sodium guidance','钠摄入建议')}</span><strong>&lt; 2<small> g</small></strong><p>${tx('Clinician-defined demo goal','医生设定的演示目标')}</p></article><article><span>${tx('Dietitian review','营养师复核')}</span><strong>${tx('Fri','周五')}</strong><p>${tx('Shared care plan','共享照护计划')}</p></article></section>`; }
  function care() { return heading(tx('FAMILY CARE','家属照护'),tx('Care together without losing context','共同照护，不丢失信息'),tx('See today’s plan, check in medication, and leave a clear handover.','查看今日计划、完成用药打卡并留下清晰交接。'),'care-moments-small.webp')+stats()+`<section class="panel"><header class="panel-heading"><h2>${tx('Care schedule','照护日程')}</h2><span class="tag">${l(p().relation)} · ${p().age}</span></header>${tasks()}</section>`; }
  function appointments() { return heading(tx('APPOINTMENTS','复诊安排'),tx('Prepare before the visit','复诊前就准备充分'),tx('Keep the time, reports, medication list, and questions together.','把时间、报告、用药清单和待咨询问题放在一起。'),'records-care-small.webp')+`<section class="panel"><article class="appointment"><div class="date-block"><b>${state.appointments[0].date.slice(8)}</b><span>${state.appointments[0].date.slice(5,7)}</span></div><div><span class="eyebrow">${tx('UPCOMING','即将到来')}</span><h2>${l(state.appointments[0].clinic)}</h2><p>${state.appointments[0].date} · ${state.appointments[0].time} · ${tx('Demo Medical Center','演示医疗中心')}</p><div class="checklist"><span>✓ ${tx('Recent reports attached','近期报告已整理')}</span><span>✓ ${tx('Medication list ready','用药清单已准备')}</span><span>○ ${tx('Add family questions','补充家属问题')}</span></div></div></article></section>`; }
  function handover() { const rows=state.handovers.filter(x=>x.patientId===state.patientId); return heading(tx('FAMILY HANDOVER','家庭交接'),tx('Leave the next caregiver a clear update','给下一位照护者留下清晰信息'),tx('A shared handover reduces repeated questions and missed tasks.','共享交接可减少重复沟通和遗漏。'),'care-moments-small.webp',button(tx('＋ Add handover','＋ 新增交接'),'handover'))+`<section class="panel"><div class="timeline">${rows.map(x=>`<article><span>${x.time}</span><div><b>${l(x.author)}</b><p>${l(x.text)}</p></div></article>`).join('')}</div></section>`; }
  const renderers={overview:doctorOverview,patients,reviews,plans,today,vitals,medications,records,dialysis,nutrition,care,appointments,handover};
  function shell() { const role=copy[state.role]; $('role-switch').innerHTML=Object.entries(copy).map(([k,v])=>`<button data-role="${k}" aria-pressed="${state.role===k}">${v.name}</button>`).join(''); $('nav').innerHTML=Object.entries(role.nav).map(([k,v])=>`<a href="#${k}" data-page="${k}"><span>${{overview:'⌂',patients:'♙',reviews:'✓',plans:'◇',today:'☀',vitals:'⌁',medications:'✚',records:'▤',dialysis:'◉',nutrition:'◌',care:'⌂',appointments:'◷',handover:'⇄'}[k]||'·'}</span>${v}</a>`).join(''); $('role-caption').textContent=role.workspace; $('workspace-label').textContent=role.workspace; $('account-name').textContent=state.role==='patient'?l(p().name):role.account; $('account-avatar').textContent=role.avatar; $('member-label').textContent=state.role==='family'?tx('Family member','家人'):tx('Patient','患者'); $('patient').innerHTML=state.patients.map(x=>`<option value="${x.id}" ${x.id===state.patientId?'selected':''}>${l(x.name)} (${tx('demo','演示')})</option>`).join(''); }
  function render() { shell(); const key=page(); $('breadcrumb').textContent=copy[state.role].nav[key]; document.querySelectorAll('[data-page]').forEach(a=>a.toggleAttribute('aria-current',a.dataset.page===key)); $('content').innerHTML=renderers[key](); document.title=`${copy[state.role].nav[key]} · ${tx('Chengxin Health','澄心健康')}`; }
  function openAction(kind) { action=kind; const config={vital:{title:tx('Record blood pressure','记录血压'),help:tx('The entry updates this demo only.','记录仅更新当前演示。'),fields:`<label>${tx('Systolic (mmHg)','收缩压 (mmHg)')}<input name="systolic" type="number" min="50" max="260" value="126" required></label><label>${tx('Diastolic (mmHg)','舒张压 (mmHg)')}<input name="diastolic" type="number" min="30" max="160" value="78" required></label>`},plan:{title:tx('Create care plan','新建照护计划'),help:tx('Assign a clear goal and target date.','设置清晰目标和计划日期。'),fields:`<label class="full">${tx('Plan title','计划名称')}<input name="title" value="${tx('Seven-day symptom review','七日症状复核计划')}" required></label><label>${tx('Target date','计划日期')}<input name="target" type="date" required></label>`},handover:{title:tx('Add family handover','新增家庭交接'),help:tx('Share only what the next caregiver needs.','只记录下一位照护者需要的信息。'),fields:`<label class="full">${tx('Handover note','交接内容')}<textarea name="text" rows="4" required>${tx('Medication check-in is complete. Please record the evening blood pressure.','用药打卡已完成，请记录晚间血压。')}</textarea></label>`}}[kind]; $('action-title').textContent=config.title; $('action-help').textContent=config.help; $('action-fields').innerHTML=config.fields; $('form-error').textContent=''; returnFocus=document.activeElement; $('action-dialog').showModal(); }
  function download() { const blob=new Blob([M.csv(state,zh?'zh':'en')],{type:'text/csv;charset=utf-8'}), url=URL.createObjectURL(blob), a=document.createElement('a'); a.href=url;a.download=`chengxin-health-${p().id}.csv`;a.click();URL.revokeObjectURL(url);toast(tx('CSV export created.','CSV 已导出。')); }
  document.addEventListener('click',e=>{ const role=e.target.closest('[data-role]'); if(role){state.role=role.dataset.role;location.hash=copy[state.role].start;render();return;} const el=e.target.closest('[data-action]'); if(!el)return; const a=el.dataset.action,id=el.dataset.id; if(a==='complete'){M.complete(state,id);toast(tx('Care task completed.','照护任务已完成。'));render();} if(a==='vital'||a==='plan'||a==='handover')openAction(a); if(a==='range'){range=Number(el.dataset.days);render();} if(a==='select-patient'){state.patientId=Number(id);render();} if(a.startsWith('review-')){M.review(state,id,a.endsWith('approve')?'approved':'rejected');toast(a.endsWith('approve')?tx('Item approved and audit event recorded.','已通过，并记录审核日志。'):tx('Item rejected for correction.','已驳回并退回修正。'));render();} if(a==='export')download(); if(a==='detail'){const names=[tx('Complete blood count','血常规报告'),tx('Metabolic panel','生化检验报告'),tx('Discharge summary','出院小结')];$('detail-title').textContent=names[Number(id)];$('record-detail').innerHTML=`<div class="record-summary"><span class="tag">${tx('Clinician reviewed','医生已复核')}</span><p>${tx('This fictional structured record demonstrates report metadata, extracted measurements, source traceability, and review status.','这份虚构的结构化记录演示报告元数据、提取指标、来源追踪和复核状态。')}</p><dl><dt>${tx('Patient','患者')}</dt><dd>${l(p().name)}</dd><dt>${tx('Source','来源')}</dt><dd>${tx('Demo Medical Center','演示医疗中心')}</dd><dt>${tx('Visibility','可见范围')}</dt><dd>${tx('Patient and care team','患者与照护团队')}</dd></dl></div>`;$('detail-dialog').showModal();}});
  $('patient').addEventListener('change',e=>{state.patientId=Number(e.target.value);render();});
  $('reset').addEventListener('click',()=>{state=M.createState();range=7;location.hash=copy[state.role].start;toast(tx('Demo reset.','演示已重置。'));render();});
  $('action-form').addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.target);try{if(action==='vital')M.addVital(state,Number(data.get('systolic')),Number(data.get('diastolic')));if(action==='plan')M.addPlan(state,data.get('title'),data.get('target'));if(action==='handover')M.addHandover(state,data.get('text'));$('action-dialog').close();toast(tx('Demo entry saved.','演示记录已保存。'));render();}catch{$('form-error').textContent=tx('Check the fields and try again. Systolic pressure must be higher than diastolic pressure.','请检查输入后重试，收缩压必须高于舒张压。');}});
  document.querySelectorAll('[data-close]').forEach(x=>x.addEventListener('click',()=>x.closest('dialog').close())); window.addEventListener('hashchange',render); render();
})();
