import request from '@/utils/request'

const base = '/care-journey'
export const listMeasurements = params => request({ url: `${base}/measurements`, params })
export const saveMeasurement = data => request({ url: `${base}/measurements`, method: 'post', data })
export const annotateMeasurement = (id, annotation) => request({ url: `${base}/measurements/${id}/annotations`, method: 'post', data: { annotation } })
export const listAccessGrants = patientId => request({ url: `${base}/access-grants`, params: { patientId } })
export const saveAccessGrant = data => request({ url: `${base}/access-grants`, method: 'post', data })
export const revokeAccessGrant = id => request({ url: `${base}/access-grants/${id}`, method: 'delete' })
export const listDoctorSchedules = params => request({ url: `${base}/doctor-schedules`, params })
export const listClinicians = () => request({ url: `${base}/clinicians` })
export const saveDoctorSchedule = data => request({ url: `${base}/doctor-schedules`, method: 'post', data })
export const listAppointments = patientId => request({ url: `${base}/appointments`, params: { patientId } })
export const listAppointmentInbox = () => request({ url: `${base}/appointment-inbox` })
export const completeAppointment = id => request({ url: `${base}/appointments/${id}/complete`, method: 'post' })
export const saveAppointment = data => request({ url: `${base}/appointments`, method: 'post', data })
export const cancelAppointment = (id, reason) => request({ url: `${base}/appointments/${id}/cancel`, method: 'post', data: { reason } })
export const listVisits = patientId => request({ url: `${base}/visits`, params: { patientId } })
export const saveVisit = data => request({ url: `${base}/visits`, method: 'post', data })
export const publishVisit = id => request({ url: `${base}/visits/${id}/publish`, method: 'post' })
export const savePrescription = data => request({ url: `${base}/prescriptions`, method: 'post', data })
export const listPrescriptions = patientId => request({ url: `${base}/prescriptions`, params: { patientId } })
export const listConsultations = patientId => request({ url: `${base}/consultations`, params: { patientId } })
export const listConsultationInbox = () => request({ url: `${base}/consultations/inbox` })
export const listConsultationInvitees = patientId => request({ url: `${base}/consultation-invitees`, params: { patientId } })
export const listConsultationRecordOptions = id => request({ url: `${base}/consultations/${id}/record-options` })
export const getConsultationAttachment = (id, attachmentId) => request({ url: `${base}/consultations/${id}/attachments/${attachmentId}` })
export const startConsultation = data => request({ url: `${base}/consultations`, method: 'post', data })
export const getConsultation = id => request({ url: `${base}/consultations/${id}` })
export const sendConsultationMessage = (id, data) => request({ url: `${base}/consultations/${id}/messages`, method: 'post', data })
export const listConsultationSignals = (id, afterId = 0) => request({ url: `${base}/consultations/${id}/signals`, params: { afterId } })
export const sendConsultationSignal = (id, data) => request({ url: `${base}/consultations/${id}/signals`, method: 'post', data })
export const closeConsultation = (id, transferAdvice) => request({ url: `${base}/consultations/${id}/close`, method: 'post', data: { transferAdvice } })
export const listTreatmentPlans = patientId => request({ url: `${base}/treatment-plans`, params: { patientId } })
export const saveTreatmentPlan = data => request({ url: `${base}/treatment-plans`, method: 'post', data })
export const listRehabCheckins = patientId => request({ url: `${base}/rehab-checkins`, params: { patientId } })
export const saveRehabCheckin = data => request({ url: `${base}/rehab-checkins`, method: 'post', data })
export const getEmergencyCard = patientId => request({ url: `${base}/emergency-card`, params: { patientId } })
export const triggerEmergency = data => request({ url: `${base}/emergencies`, method: 'post', data })
export const listSpecialty = (type, patientId) => request({ url: `${base}/specialty/${type}`, params: { patientId } })
export const saveSpecialty = (type, data) => request({ url: `${base}/specialty/${type}`, method: 'post', data })
export const listMentalAssessments = patientId => request({ url: `${base}/mental-assessments`, params: { patientId } })
export const saveMentalAssessment = data => request({ url: `${base}/mental-assessments`, method: 'post', data })
export const listMentalSchedules = patientId => request({ url: `${base}/mental-schedules`, params: { patientId } })
export const saveMentalSchedule = data => request({ url: `${base}/mental-schedules`, method: 'post', data })
export const listPatientGroups = () => request({ url: `${base}/patient-groups` })
export const savePatientGroup = data => request({ url: `${base}/patient-groups`, method: 'post', data })
export const addPatientToGroup = (id, patientId) => request({ url: `${base}/patient-groups/${id}/patients/${patientId}`, method: 'post' })
export const getOperationsReport = params => request({ url: `${base}/operations`, params })
