import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

// Regression coverage for the fixed labels, help text, and validation messages.
const expectedCopy = {
  "AuditLogManager": ["Action audit", "Review key API requests, response status, and duration for security audits and troubleshooting.", "Filter by API path", ">Search<", "label=\"User\"", "Method", "API path", "Duration (ms)", "Client IP"],
  "UserManager": ["Manage user accounts and role assignments", "Add user", "Edit user", ">Assign roles<", "title=\"Assign roles\"", "Reset password", "label=\"Full name\"", "Enter full name", "At least 10 characters, including letters, numbers, and special characters", "Confirm reset", "Password must contain at least 10 characters", "Password must include letters, numbers, and special characters", "New password must contain at least 10 characters, including letters, numbers, and special characters"],
  "RoleManager": ["Manage roles and menu permissions", "Add role", "Edit role", ">Configure menus<", "Configure menu permissions", "Administrator menu permissions cannot be edited here. Database maintenance is required to change them.", "label=\"Role code\"", "label=\"Role name\"", "For example: Editor", "Role description", "Enter a role code", "Enter a role name"],
  "MenuManager": ["Manage the navigation hierarchy, routes, permission identifiers, and display order.", "Add menu", "Edit menu", "Menu name", "Menu code", "Permission identifier", "Before deleting this parent menu, confirm that it has no child menus. Continue?", "Parent menu", "Top-level menu", "Page route, optionally with a query string, for example: /path?tab=x", "Menu deleted"],
  "PatientManager": ["Manage patient information for use across care modules", "Add patient", "Edit patient", "label=\"ID number\"", ">Clinical profile<", "Hemodialysis (HD)", "Peritoneal dialysis (PD)", "Select a dialysis type", "label=\"Dialysis type\"", "Dialysis start date", "Arteriovenous fistula (AVF)", "Arteriovenous graft (AVG)", "Central venous catheter (CATH)", "Target dry weight (kg)", "For example: chronic glomerulonephritis or diabetic kidney disease", "Underlying condition / primary diagnosis", "List medication allergies", "Medication allergy history", "Daily fluid limit (ml)", "Patient clinical information", "Emergency contact name", "Emergency contact phone", "label=\"Emergency contact\"", "Emergency phone", "Brief medical history", "Additional notes", "placeholder=\"Select a date\""],
  "ComplicationTrackingManager": ["Record dialysis complications and track their frequency and severity", "Total records", "Type distribution", "Complication records", "label=\"Date of occurrence\"", "Severity", "Related dialysis summary", "Select a dialysis record (optional)", "Related dialysis record", "Related dialysis data:", "Complication type", "Intradialytic hypotension", "Vascular access issue", "Describe the complication", "Describe the treatment measures taken", "Describe the outcome, for example: improved, stable, or hospitalization needed", "Additional notes", "Edit complication record", "Add complication record", "Select a date of occurrence", "Select a complication type", "Select a severity level", "placeholder=\"Select a date\""],
  "NutritionAssessmentManager": ["Assess nutrition in dialysis patients and track SGA scores and biochemical trends", "Add assessment", "Assessment records", "label=\"Assessment date\"", "Nutrition status", "SGA grade", "SGA score", "Prealbumin", "Supplement advice", "Edit nutrition assessment", "Add nutrition assessment", "Weight (kg)", "Height (cm)", "Calculated automatically", "Albumin (g/L)", "Prealbumin (mg/L)", "Fluid intake (ml)", "Protein intake (g)", "Calorie intake (kcal)", "Potassium intake (mg)", "Phosphorus intake (mg)", "Additional notes", "Calculation preview", "Preview calculation", "Select an assessment date", "Mild to moderate malnutrition", "Severe malnutrition", "At risk", "placeholder=\"Select a date\""],
  "NutritionDiaryManager": ["Record daily meals and symptoms to track changes in nutritional health", "Record count", "Latest weight", "Latest appetite", "Record overview", "label=\"Record date\"", "Weight (kg)", ">Poor<", "Meals", "Symptoms", "Select all that apply", "Record meal details, symptoms, or other observations", "Daily records", "label=\"Meals\"", "Delete this record?"],
  "BpSelfMonitorManager": ["Blood pressure and glucose records", "Record daily blood pressure and glucose readings to track changes over time", "Record count", "Latest blood pressure", "Latest blood glucose", "Record overview", "Blood pressure + blood glucose", "label=\"Record date\"", "label=\"Record time\"", "Blood glucose value", "Two hours after a meal", "Measurement period", "Record the measurement context, meal timing, symptoms, or other observations", "Monitoring records", "Delete this record?", "Select a measurement type"],
  "BpPatternManager": ["Review blood pressure variability, orthostatic hypotension, and the relationship between weight gain and blood pressure", "Run analysis", "Elevated", "Orthostatic hypotension", "Low blood pressure (<90)", "Weight–blood pressure correlation", "Variability (σ)", "Analysis summary", "Elevated variability", "Blood pressure pattern details", ">Low: {{ row.lowBpCount }}<", ">High: {{ row.highBpCount }}<", ">Orthostatic: {{ row.orthostaticCount }}<"],
}

for (const [view, phrases] of Object.entries(expectedCopy)) {
  test(`English ${view} uses readable interface copy`, () => {
    const source = readFileSync(new URL(`../src/views/${view}.vue`, import.meta.url), 'utf8')
    for (const phrase of phrases) assert.ok(source.includes(phrase), `${view}: missing ${phrase}`)
  })
}
