<template>
  <section class="care-plan-detail" aria-label="Collaboration plan details">
    <p v-if="state.opening || loading" role="status">Loading authorized plan…</p><p v-if="message" role="status" class="feedback">{{ message }}</p>
    <template v-if="enabled && state.plan">
      <header><div><span>Collaboration plan · Version {{ state.plan.revisionNo }} · {{ lifecycleLabel(state.plan.lifecycle) }}</span><h2>{{ state.plan.title }}</h2></div><button type="button" data-testid="reload-detail" :disabled="busy" @click="requestReload">Reload server state</button></header>
      <p class="instructions">{{ state.plan.instructions }}</p><p v-if="state.plan.revisionStatus==='DRAFT'" class="notice">Private clinical draft. It has not been published to the patient or care partners.</p>
      <label v-if="revisions.length">Version history <select :value="historyRevisionId || ''" @change="selectHistory($event.target.value)"><option value="">Current published version</option><option v-for="revision in revisions" :key="revision.id" :value="revision.id">Version {{ revision.revisionNo }} · {{ revisionLabel(revision.status) }} · {{ displayTime(revision.publishedAt || revision.createdAt) }}</option></select></label><button v-if="revisionCursor" type="button" :disabled="busy" @click="loadRevisions(revisionCursor)">More versions</button>
      <p v-if="historical" class="notice">Historical snapshot. Receipts remain attached to this version. Viewing history requires current permission.</p>
      <article v-for="action in state.plan.actions || []" :key="action.id || action.ordinal" class="action-card">
        <header><h3>{{ action.ordinal }}. {{ action.instruction }}</h3><span>{{ actionLabel(action.status) }}<template v-if="action.overdue"> · Currently overdue</template></span></header>
        <p>Deadline: {{ displayTime(action.dueAt) }} · Responsible account #{{ action.assignedUserId }}</p>
        <p v-if="action.firstSubmittedAt">Original submission: {{ displayTime(action.firstSubmittedAt) }} · {{ originalTiming(action) }}</p><p v-if="action.latestSubmittedAt">Latest submission: {{ displayTime(action.latestSubmittedAt) }}</p><p v-if="action.reviewWaitingSince">Waiting for doctor review since {{ displayTime(action.reviewWaitingSince) }}. Submitted records awaiting review do not mean patient delay.</p>
        <ul v-if="action.evidence?.length" class="evidence-list"><li v-for="(e,index) in action.evidence" :key="index"><span v-if="e.restricted">A restricted linked record exists</span><a v-else-if="safeLink(e.detailLink)" :href="e.detailLink">{{ e.title || evidenceLabel(e.sourceType) }}</a><span v-else>{{ e.title || evidenceLabel(e.sourceType) }} #{{ e.sourceId }}</span></li></ul>
        <div class="event-list"><article v-for="event in action.events || []" :key="event.id"><strong>{{ eventLabel(event.eventType) }}</strong><p>{{ event.actorName }} · {{ roleLabel(event.actorRole) }}<template v-if="event.entryMode"> · {{ event.entryMode==='SELF' ? 'Account-owner self-entry declaration' : 'Assisted entry' }}</template></p><p v-if="event.occurredAt">Occurred: {{ displayTime(event.occurredAt) }}</p><p>Recorded: {{ displayTime(event.recordedAt) }}</p><p class="instructions" v-if="event.note">{{ event.note }}</p><ul><li v-for="(e,index) in event.evidence || []" :key="index"><span v-if="e.restricted">A restricted linked record exists</span><a v-else-if="safeLink(e.detailLink)" :href="e.detailLink">{{ e.title || evidenceLabel(e.sourceType) }}</a><span v-else>{{ e.title || evidenceLabel(e.sourceType) }} #{{ e.sourceId }}</span></li></ul></article></div>
        <div v-if="actionAllowed(action,'REVIEW_RECEIPT')" class="controls"><button type="button" :data-testid="`review-confirm-${action.id}`" :disabled="busy || unresolved" @click="confirmReview(action)">Mark record reviewed</button><button type="button" :data-testid="`review-return-${action.id}`" :disabled="busy || unresolved" @click="prepareReturn(action)">Return for more information…</button></div>
        <slot v-if="!historical" name="action-controls" :action="action" :plan="state.plan" :refresh="requestReload" />
      </article>
      <p class="notice">Doctor review means the execution record was reviewed. It does not verify treatment effectiveness or disease improvement. Self-entry is a declaration, not patient identity verification.</p>
      <section v-if="reviewTarget" class="notice"><h3>Return action #{{ reviewTarget.id }} for more information</h3><label>Required explanation (1–1000 characters) <textarea v-model="reviewNote" rows="3" /></label><p v-if="!returnReady">The server review context changed or this action is no longer reviewable. Your explanation is kept. Recheck the latest record before sending.</p><button v-if="!returnReady && reviewContextCurrent && actionAllowed(reviewAction,'REVIEW_RECEIPT')" type="button" data-testid="recheck-return" :disabled="busy || unresolved" @click="recheckReturn">Recheck this latest record and keep my explanation</button><button type="button" data-testid="send-return" :disabled="busy || unresolved || !returnReady" @click="sendReturn">Request more information</button><button type="button" :disabled="busy || unresolved" @click="reviewTarget=null">Keep unchanged</button></section>
      <div class="controls"><button v-if="planAllowed('SAVE_DRAFT') && state.plan.draftRevisionId" type="button" :disabled="busy || unresolved" @click="editRevision(state.plan.draftRevisionId)">Edit private draft</button><button v-if="planAllowed('CREATE_REVISION')" type="button" data-testid="create-revision" :disabled="busy || unresolved" @click="createRevision">Create next private revision</button><button v-if="planAllowed('CANCEL_PLAN')" type="button" data-testid="cancel-plan" :disabled="busy || unresolved" @click="prepareTransition('CANCEL')">Cancel plan…</button><button v-if="canClose" type="button" data-testid="close-plan" :disabled="busy || unresolved" @click="prepareTransition('CLOSE')">Close reviewed plan…</button></div>
      <section v-if="transitionAction" class="notice"><h3>{{ transitionAction==='CANCEL' ? 'Cancel this plan' : 'Close this plan' }}</h3><p>{{ transitionAction==='CANCEL' ? 'Open, help-needed and submitted actions will be cancelled. Existing receipts remain in history.' : 'All current actions have reviewed records. Closing is final; it does not demonstrate clinical success.' }}</p><label v-if="transitionAction==='CANCEL'">Required reason (1–1000 characters)<textarea v-model="transitionReason" rows="3" /></label><button type="button" data-testid="confirm-transition" :disabled="busy || unresolved" @click="transition">{{ transitionAction==='CANCEL' ? 'Confirm cancellation' : 'Confirm closure' }}</button><button type="button" :disabled="busy || unresolved" @click="transitionAction=null">Keep unchanged</button></section>
      <section v-if="unresolved" class="notice" role="alert"><p>The original command may already have committed. Retry replays the same frozen command, target and input. A fresh command requires acknowledged reload first.</p><button type="button" data-testid="retry-detail-original" :disabled="busy" @click="retryOriginal">Retry original submission</button></section>
      <PlanEditor v-if="editingRevision" :patient-id="state.plan.patientId" :plan-id="planId" :revision-id="editingRevision" @saved="editorSaved" @closed="editorClosed" />
      <slot :plan="state.plan" :reload="requestReload" />
    </template>
    <p v-else-if="!loading && !state.opening">This plan is unavailable or access has changed.</p>
    <section v-if="abandonIntent" class="notice" role="alert"><p>This submission may already exist. Changing context discards its in-memory retry key. Acknowledge and reload server state before another command.</p><button type="button" data-testid="confirm-detail-abandon" @click="confirmAbandon">Acknowledge and reload</button><button type="button" @click="abandonIntent=null">Keep this context</button></section>
  </section>
</template>
<script setup>
import { computed, ref, watch, onMounted, onUnmounted } from 'vue'
import { useCarePlan } from '@/composables/useCarePlan'
import { getCarePlanCapabilities, listPlanRevisions } from '@/api/carePlan'
import { captureAuthSession, isAuthSessionCurrent } from '@/utils/authSession'
import { formatPlanTime } from '@/utils/carePlanTime'
import PlanEditor from './PlanEditor.vue'
const props=defineProps({planId:{type:Number,required:true}}),emit=defineEmits(['changed'])
const client=useCarePlan(ref(null)),{state}=client,enabled=ref(false),loading=ref(false),message=ref(''),revisions=ref([]),revisionCursor=ref(null),historyRevisionId=ref(null),reviewTarget=ref(null),reviewNote=ref(''),transitionAction=ref(null),transitionReason=ref(''),editingRevision=ref(null),abandonIntent=ref(null)
let generation=0,controller=null,lastCommand=null,historyGeneration=0
const busy=computed(()=>loading.value||state.opening||state.commandPhase==='pending'),unresolved=computed(()=>state.commandPhase==='unknown')
const historical=computed(()=>!!historyRevisionId.value && state.plan?.revisionId!==state.plan?.currentRevisionId && state.plan?.revisionStatus==='PUBLISHED')
const planAllowed=name=>!historical.value && !!state.editor && !!state.plan?.allowedActions?.includes(name)
const actionAllowed=(a,name)=>!historical.value && !!state.editor && !!state.plan?.actions?.find(current=>current.id===a?.id)?.allowedActions?.includes(name)
const canClose=computed(()=>planAllowed('CLOSE_PLAN') && state.plan?.actions?.length>0 && state.plan.actions.every(a=>a.status==='CONFIRMED'))
const reviewAction=computed(()=>state.plan?.actions?.find(action=>action.id===reviewTarget.value?.id)||null)
const reviewContextCurrent=computed(()=>!!reviewTarget.value && reviewTarget.value.planId===state.plan?.id && reviewTarget.value.revisionId===state.plan?.revisionId)
const returnReady=computed(()=>reviewContextCurrent.value && reviewTarget.value.version===state.plan?.version && actionAllowed(reviewAction.value,'REVIEW_RECEIPT'))
function recheckReturn(){if(busy.value||unresolved.value||!reviewContextCurrent.value||!actionAllowed(reviewAction.value,'REVIEW_RECEIPT'))return;reviewTarget.value={...reviewTarget.value,version:state.plan.version};state.draft={decision:'RETURN',note:reviewNote.value}}
const context=()=>({generation,auth:captureAuthSession(),actor:localStorage.getItem('userId')})
const owns=c=>c.generation===generation && isAuthSessionCurrent(c.auth) && c.actor===localStorage.getItem('userId')
const options=c=>({expectedAuth:{...c.auth,actorId:c.actor},signal:controller.signal})
async function initialize(){const g=++generation;historyGeneration++;controller?.abort();controller=new AbortController();enabled.value=false;loading.value=true;message.value='';revisions.value=[];revisionCursor.value=null;reviewTarget.value=null;reviewNote.value='';transitionAction.value=null;transitionReason.value='';editingRevision.value=null;historyRevisionId.value=null;lastCommand=null;abandonIntent.value=null;client.reset();const c=context();try{const response=await getCarePlanCapabilities(options(c));if(!owns(c))return;if(!response.data?.enabled)return;enabled.value=true;await loadDetail();if(owns(c)&&state.plan)await loadRevisions()}catch{if(owns(c)){enabled.value=false;client.reset();message.value='Unable to load this plan in the current session.'}}finally{if(g===generation)loading.value=false}}
async function loadDetail(){const result=await client.open(props.planId,{revisionId:historyRevisionId.value});if(result.status!=='succeeded'&&result.status!=='stale')feedback(result);return result}
async function loadRevisions(cursor=null){const c=context(),h=++historyGeneration;try{const result=await listPlanRevisions(props.planId,{limit:50,...(cursor?{cursor}:{})},options(c));if(!owns(c)||h!==historyGeneration||!state.editor)return;revisions.value=cursor?[...revisions.value,...(result.data?.items||[])]:result.data?.items||[];revisionCursor.value=result.data?.nextCursor||null}catch(error){if(owns(c)){if([401,403,404].includes(Number(error.response?.status||error.code))){client.reset();message.value='Access is no longer available.'}else message.value='Version history could not be loaded. Current plan content remains available.'}}}
function feedback(result){message.value=({unknown:'The result is unknown. The original command may already be committed.',conflict:'The plan changed on the server. Your input is kept. Reload before another command.',failed:'The command was rejected. Your input is kept; correct it and try again.',stale:'Context or input changed. Current input is kept; reload server state before another command.',forbidden:'Access is no longer available.',unauthenticated:'Sign in again to continue.',unavailable:'This plan is unavailable.',cancelled:'The request was not sent.'})[result.status]||'Unable to complete the command.'}
function prepareReturn(action){if(!actionAllowed(action,'REVIEW_RECEIPT')||busy.value||unresolved.value)return;reviewTarget.value={id:action.id,planId:state.plan.id,revisionId:state.plan.revisionId,version:state.plan.version};reviewNote.value='';state.draft={decision:'RETURN',note:''}}
watch(reviewNote,note=>{if(reviewTarget.value && state.editor && state.draft)state.draft={decision:'RETURN',note}},{flush:'sync'})
watch(transitionReason,reason=>{if(transitionAction.value==='CANCEL' && state.editor && state.draft)state.draft={reason}},{flush:'sync'})
async function command(name,settings){if(busy.value||unresolved.value)return;const c=context();state.draft=settings.payload;lastCommand=name;const result=await client.runCommand(name,{...settings,expectedVersion:state.plan.version});if(owns(c))await settle(result,name)}
async function settle(result,name){if(result.status!=='succeeded'){feedback(result);return}const keep=result.draftUnchanged===false,input=keep?JSON.parse(JSON.stringify(state.draft)):null,c=context();const refreshed=await client.open(props.planId,{revisionId:historyRevisionId.value,draft:input});if(!owns(c))return;if(refreshed.status!=='succeeded'){feedback(refreshed);return}if(!keep){reviewTarget.value=null;transitionAction.value=null;reviewNote.value='';transitionReason.value=''}message.value=keep?'The original command succeeded. Your newer input is kept; server state was reloaded.':'Server record updated. Review confirms the record, not clinical effectiveness.';if(name==='revisePlan'){editingRevision.value=result.data.draftRevisionId||result.data.revisionId}emit('changed',result.data);await loadRevisions()}
function confirmReview(action){if(!actionAllowed(action,'REVIEW_RECEIPT'))return;return command('reviewReceipt',{id:action.id,payload:{decision:'CONFIRM'}})}
function sendReturn(){if(!returnReady.value||busy.value||unresolved.value)return;const note=reviewNote.value.trim();if(!note||Array.from(note).length>1000){message.value='A return explanation needs 1–1000 characters.';return}return command('reviewReceipt',{id:reviewTarget.value.id,payload:{decision:'RETURN',note}})}
function prepareTransition(action){if(action==='CLOSE'?!canClose.value:!planAllowed('CANCEL_PLAN'))return;transitionAction.value=action;transitionReason.value='';state.draft=action==='CANCEL'?{reason:''}:{}}
function transition(){const action=transitionAction.value;if(!action||(action==='CLOSE'?!canClose.value:!planAllowed('CANCEL_PLAN')))return;const payload={};if(action==='CANCEL'){const reason=transitionReason.value.trim();if(!reason||Array.from(reason).length>1000){message.value='Cancellation needs 1–1000 characters.';return}payload.reason=reason}return command('transitionPlan',{action,payload})}
function createRevision(){if(!planAllowed('CREATE_REVISION'))return;return command('revisePlan',{payload:{}})}
function editRevision(id){if(!planAllowed('SAVE_DRAFT')||unresolved.value||busy.value)return;editingRevision.value=id}
async function editorSaved(result){emit('changed',result);await requestReload()}
async function editorClosed(){editingRevision.value=null;await requestReload()}
async function retryOriginal(){if(!unresolved.value||busy.value||!lastCommand)return;const c=context();const result=await client.runCommand(lastCommand,{retry:true});if(owns(c))await settle(result,lastCommand)}
function requestLeave(){if(editingRevision.value){message.value='Close the private draft editor before leaving this plan.';return false}if(unresolved.value||state.commandPhase==='pending'){abandonIntent.value={kind:'reload'};return false}return true}
async function requestReload(){if(editingRevision.value){message.value='Close the private draft editor before reloading this plan.';return {status:'editor-open'}}if(unresolved.value||state.commandPhase==='pending'){abandonIntent.value={kind:'reload'};return {status:'confirmation-required'}}return reloadPreservingInput()}
async function reloadPreservingInput(){const input=state.draft && JSON.parse(JSON.stringify(state.draft));const result=await client.open(props.planId,{revisionId:historyRevisionId.value,draft:input});if(result.status==='succeeded')message.value='Server state reloaded. Local input is kept.';else if(result.status!=='stale')feedback(result);return result}
function selectHistory(value){if(editingRevision.value){message.value='Close the private draft editor before changing history.';return}const id=value?Number(value):null;if(id && !revisions.value.some(r=>r.id===id))return;if(unresolved.value||state.commandPhase==='pending'){abandonIntent.value={kind:'history',id};return}historyRevisionId.value=id}
async function confirmAbandon(){const intent=abandonIntent.value;abandonIntent.value=null;if(intent?.kind==='history'){historyRevisionId.value=intent.id;if(historyRevisionId.value===intent.id)await loadDetail()}else await reloadPreservingInput()}
function displayTime(value){if(!value)return 'Time unavailable';try{return formatPlanTime(value,'en')}catch{return 'Invalid server time'}}
function safeLink(link){return typeof link==='string'&&link.startsWith('/')&&!link.startsWith('//')&&!/[\s\\]/.test(link)}
function instantMicros(value){const millis=Date.parse(value),fraction=value.match(/\.(\d+)(?:Z|[+-]\d{2}:\d{2})$/)?.[1]||'';return BigInt(millis)*1000n+BigInt(fraction.padEnd(6,'0').slice(3,6))}
function originalTiming(action){try{return instantMicros(action.firstSubmittedAt)<=instantMicros(action.dueAt)?'Originally submitted by the deadline':'Originally submitted after the deadline'}catch{return 'Original submission timing unavailable'}}
function revisionLabel(status){return ({DRAFT:'Private draft',PUBLISHED:'Published version'})[status]||'Unknown state'}
function actionLabel(status){return ({OPEN:'Awaiting execution or more information',NEEDS_HELP:'Help requested',SUBMITTED:'Submitted, awaiting doctor review',CONFIRMED:'Record reviewed',SUPERSEDED:'Replaced by a new version',CANCELLED:'Cancelled',DRAFT:'Private draft'})[status]||'Unknown state'}
function lifecycleLabel(status){return ({DRAFT:'Private draft',ACTIVE:'Active',COMPLETED:'Closed after review',CANCELLED:'Cancelled'})[status]||'Unknown state'}
function roleLabel(role){return ({user:'User',family:'Family caregiver',doctor:'Doctor',nurse:'Nurse',admin:'Administrator'})[String(role||'').toLowerCase()]||'Account'}
function evidenceLabel(type){return type==='MEASUREMENT'?'Measurement':'Medical record'}
function eventLabel(type){return ({SUBMITTED:'Execution record submitted',RECEIPT_SUBMITTED:'Execution record submitted',CONFIRMED:'Doctor reviewed the record',RECEIPT_CONFIRMED:'Doctor reviewed the record',RETURNED:'More information requested',RECEIPT_RETURNED:'More information requested',HELP_REQUESTED:'Help requested',FOLLOW_UP:'Care-team follow-up',FOLLOW_UP_RECORDED:'Care-team follow-up',PUBLISHED:'Version published',PLAN_CANCELLED:'Plan cancelled',PLAN_CLOSED:'Plan closed'})[type]||type}
function beforeUnload(event){if(unresolved.value||state.commandPhase==='pending'){event.preventDefault();event.returnValue=''}}
watch(()=>props.planId,initialize,{immediate:true,flush:'sync'})
watch(historyRevisionId,()=>{if(enabled.value)loadDetail()},{flush:'sync'})
watch(()=>state.editor,editor=>{if(!editor){revisions.value=[];revisionCursor.value=null;reviewTarget.value=null;reviewNote.value='';transitionAction.value=null;transitionReason.value='';editingRevision.value=null;abandonIntent.value=null}},{flush:'sync'})
onMounted(()=>window.addEventListener('beforeunload',beforeUnload))
onUnmounted(()=>{generation++;historyGeneration++;controller?.abort();window.removeEventListener('beforeunload',beforeUnload)})
defineExpose({requestLeave})
</script>
<style scoped>
.care-plan-detail{min-width:0;color:var(--ink-800)}header,.controls{display:flex;flex-wrap:wrap;gap:12px;align-items:center;justify-content:space-between}h2,h3{margin:8px 0;overflow-wrap:anywhere}p,li{line-height:1.6;overflow-wrap:anywhere}.instructions{white-space:pre-wrap}.action-card,.notice,.event-list article{padding:16px;border:1px solid var(--line);border-radius:12px;margin:16px 0}.notice{background:var(--care-50)}.event-list article{background:var(--surface-subtle);border-left:3px solid var(--care-600)}.feedback{padding:12px;background:var(--surface-subtle)}label{display:grid;gap:6px;margin:12px 0;font-weight:600}select,textarea{width:100%;box-sizing:border-box;min-height:44px;min-width:0;padding:10px;border:1px solid var(--line);border-radius:8px;background:var(--paper);color:var(--ink-800);font:inherit}button{min-height:44px;max-width:100%;padding:10px 14px;border:1px solid var(--care-600);border-radius:8px;background:var(--paper);color:var(--care-800);font:inherit;cursor:pointer}button:disabled{opacity:.5;cursor:default}button:focus-visible,select:focus-visible,textarea:focus-visible,a:focus-visible{outline:3px solid var(--care-600);outline-offset:3px}.controls{justify-content:flex-start}a{color:var(--care-700)}@media(max-width:600px){.controls button{width:100%}.action-card,.notice{padding:12px}header>div{width:100%;min-width:0}}
</style>
