<template>
  <section class="care-plan-editor" aria-labelledby="editor-heading">
    <header><div><h2 id="editor-heading">{{ planId ? 'Edit private draft' : 'New collaboration draft' }}</h2><p>Saving keeps this draft private. Publishing makes its actions visible to this patient and currently authorized care partners.</p></div><button type="button" data-testid="close-editor" @click="requestClose">Close editor</button></header>
    <p v-if="loading" role="status">Loading authorized plan context…</p>
    <p v-if="message" role="status" class="feedback">{{ message }}</p>
    <p v-if="!loading && !enabled">Collaboration plans are unavailable in this session.</p>
    <template v-if="enabled && state.draft && state.editor">
      <p v-if="legacySource" class="notice">Copied from a historical internal plan. The original stays unchanged. Add an explicit deadline and assignee for every new action; the old target date does not set a time.</p>
      <fieldset :disabled="!canSave || state.commandPhase === 'pending'">
        <label>Plan title <input v-model="state.draft.title" aria-required="true" /></label>
        <label>Plan type <select v-model="state.draft.planType"><option value="FOLLOW_UP">Follow-up</option><option value="MEDICATION">Medication</option><option value="DIALYSIS">Dialysis</option><option value="NUTRITION">Nutrition</option></select></label>
        <label>Clinical instructions <textarea v-model="state.draft.instructions" rows="4" aria-required="true" /></label>
        <p>1–50 one-time actions. Title: 160 characters; instructions: 4000; each action: 2000. Limits count Unicode characters.</p>
        <article v-for="(action,index) in state.draft.actions" :key="index" class="action-editor">
          <h3>Action {{ index + 1 }}</h3>
          <label>Action instructions <textarea v-model="action.instruction" rows="2" aria-required="true" /></label>
          <label>Responsible person <select v-model="action.assignedUserId" aria-required="true"><option :value="null">Select an authorized person</option><option v-for="person in assignees" :key="person.userId" :value="person.userId">{{ person.displayName }} · {{ roleLabel(person.role) }}</option></select></label>
          <p v-if="action.assignedUserId && !assignees.some(p=>p.userId===action.assignedUserId)">This assignee is no longer available. Choose a currently authorized person.</p>
          <label>Deadline, ISO date/time with explicit offset <input v-model="action.dueAt" placeholder="2026-10-04T14:30:00+08:00" aria-required="true" /></label>
          <p>{{ displayTime(action.dueAt) }}</p>
          <details><summary>Choose a browser-local time ({{ timeZone }})</summary><label>Local deadline <input v-model="localClocks[index]" type="datetime-local" step="1" @change="localOffsets[index]=null" /></label><label>Explicit UTC offset <select v-model="localOffsets[index]"><option :value="null">Select an offset</option><option v-for="offset in offsetsFor(index)" :key="offset" :value="offset">{{ offsetLabel(offset) }}</option></select></label><p v-if="localClocks[index] && !offsetsFor(index).length">This local time does not exist. Correct it; it will not be silently shifted.</p><button type="button" @click="applyLocalTime(index)">Use this exact time and offset</button></details>
          <details><summary>Existing record references ({{ action.evidence.length }}/5)</summary><p>Reference existing measurement or medical-record IDs only. Saving and publishing recheck patient ownership and current record permissions. No new uploads.</p><div v-for="(evidence,e) in action.evidence" :key="e" class="evidence-row"><label>Record type <select v-model="evidence.sourceType"><option value="MEASUREMENT">Measurement</option><option value="MEDICAL_RECORD">Medical record</option></select></label><label>Existing record ID <input v-model.number="evidence.sourceId" type="number" min="1" step="1" /></label><button type="button" @click="action.evidence.splice(e,1)">Remove reference</button></div><button type="button" :disabled="action.evidence.length>=5" @click="action.evidence.push({sourceType:'MEASUREMENT',sourceId:null})">Add existing reference</button></details>
          <button type="button" :disabled="state.draft.actions.length<=1" @click="removeAction(index)">Remove action</button>
        </article>
        <button type="button" :disabled="state.draft.actions.length>=50" @click="addAction">Add action ({{ state.draft.actions.length }}/50)</button>
      </fieldset>
      <section v-if="createReconciliation" class="notice" role="alert"><p>An uncertain new draft may already exist. Review this patient’s server history before creating another.</p><ul><li v-for="existing in state.items" :key="existing.id"><span>{{ existing.title }} · {{ lifecycleLabel(existing.lifecycle) }}</span><button type="button" @click="useExistingDraft(existing)">Use this existing plan</button></li></ul><button v-if="state.nextCursor" type="button" data-testid="more-create-history" :disabled="busy" @click="moreCreateHistory">More server history</button><button v-else-if="reconciliationReady" type="button" :disabled="busy" data-testid="acknowledge-create-history" @click="acknowledgeCreateHistory">I checked this history; allow a new private draft</button></section>
      <div class="controls"><button v-if="canSave" type="button" data-testid="save-draft" :disabled="busy || unresolved || createReconciliation || needsReload" @click="save">Save private draft</button><button v-if="allowed('PUBLISH_PLAN')" type="button" data-testid="prepare-publish" :disabled="busy || unresolved || dirty || needsReload" @click="preparePublish">Review and publish…</button><button type="button" data-testid="reload-server" :disabled="busy" @click="requestReload">Reload server state, keep my input</button></div>
      <p v-if="dirty && allowed('PUBLISH_PLAN')">Save your changes before reviewing publication.</p>
      <section v-if="publishVisible" class="notice" aria-label="Publication confirmation">
        <h3>Confirm publication scope</h3><p>The patient and currently authorized care partners will see these clinical instructions and new actions.</p>
        <template v-if="state.plan?.currentRevisionId"><h4>Published version → new version</h4><p>{{ currentPublished?.title }} → {{ state.draft.title }}</p><p>{{ currentPublished?.instructions }} → {{ state.draft.instructions }}</p><ul><li v-for="old in currentPublished?.actions || []" :key="old.id">Previous #{{ old.id }}: {{ old.instruction }} · {{ displayTime(old.dueAt) }} · {{ actionLabel(old.status) }} · Responsible account #{{ old.assignedUserId }} · Existing references: {{ (old.evidence || []).map(e=>e.restricted?'Restricted linked record':`${evidenceLabel(e.sourceType)} #${e.sourceId}`).join(', ') || 'None' }}</li></ul><p>Unfinished or waiting-for-review actions superseded: {{ impact?.actionIds?.join(', ') || 'None' }}. Historical receipts remain with their original version; new actions start open.</p></template>
        <ul><li v-for="(action,index) in state.draft.actions" :key="index">New {{ index+1 }}: {{ action.instruction }} · {{ displayTime(action.dueAt) }} · {{ assignees.find(p=>p.userId===action.assignedUserId)?.displayName }} · Existing references: {{ action.evidence.map(e=>`${evidenceLabel(e.sourceType)} #${e.sourceId}`).join(', ') || 'None' }}</li></ul>
        <label class="check"><input v-model="publishConfirmed" type="checkbox" />I explicitly confirm this scope and the revision impact shown above</label><div class="controls"><button type="button" data-testid="confirm-publish" :disabled="!publishConfirmed || busy || dirty" @click="publish">Publish this version</button><button type="button" @click="publishVisible=false">Keep private</button></div>
      </section>
      <section v-if="unresolved" class="notice" role="alert"><p>The server may already have committed the original submission. Do not create a replacement blindly. Retry replays the original frozen input and command key, even if you have edited this form.</p><button type="button" data-testid="retry-original" :disabled="busy" @click="retryOriginal">Retry original submission</button></section>
    </template>
    <section v-if="createReconciliation && !reconciliationReady" class="notice" role="alert"><p>Server history is incomplete. Retry authorized loading before creating a new draft.</p><button type="button" data-testid="retry-create-history" :disabled="busy" @click="retryCreateHistory">Retry authorized history loading</button></section>
    <section v-if="abandonIntent" class="notice" role="alert"><p v-if="unresolved || state.commandPhase==='pending'">This submission may already exist on the server. Leaving discards its in-memory retry key. Before any fresh command, reload authoritative server state; edited input is not proof that the previous command failed.</p><p v-else>Closing discards your unsaved private draft changes. Keep editing to save them first.</p><button type="button" data-testid="confirm-abandon" @click="confirmAbandon">{{ abandonIntent==='close' ? 'Acknowledge and close' : 'Acknowledge and reload' }}</button><button type="button" data-testid="keep-editing" @click="abandonIntent=null">Keep editing</button></section>
  </section>
</template>

<script setup>
import { computed, ref, watch, onMounted, onUnmounted } from 'vue'
import { useCarePlan } from '@/composables/useCarePlan'
import { getCarePlanCapabilities, listAssignees, getPlan } from '@/api/carePlan'
import { captureAuthSession, isAuthSessionCurrent } from '@/utils/authSession'
import { formatPlanTime, getLocalTimeOffsets, toOffsetIso } from '@/utils/carePlanTime'
const props=defineProps({patientId:{type:Number,required:true},planId:{type:Number,default:null},revisionId:{type:Number,default:null},legacySource:{type:Object,default:null}})
const emit=defineEmits(['saved','closed'])
const patient=computed(()=>props.patientId),client=useCarePlan(patient),{state}=client
const enabled=ref(false),loading=ref(false),assignees=ref([]),message=ref(''),savedSnapshot=ref(''),publishVisible=ref(false),publishConfirmed=ref(false),currentPublished=ref(null),impact=ref(null),abandonIntent=ref(null),localClocks=ref({}),localOffsets=ref({}),createReconciliation=ref(false),reconciliationReady=ref(false),needsReload=ref(false)
const timeZone=Intl.DateTimeFormat().resolvedOptions().timeZone
const copy=x=>x==null?x:JSON.parse(JSON.stringify(x)),count=x=>Array.from(x.trim()).length
let generation=0,controller=null,lastCommand=null,historyOwner=null,editorOwner=null
const allowed=name=>enabled.value && !!state.editor && !!state.plan?.allowedActions?.includes(name)
const canSave=computed(()=>enabled.value && !!state.editor && (!state.plan || allowed('SAVE_DRAFT')))
const busy=computed(()=>loading.value || state.loading || state.opening || state.commandPhase==='pending')
const unresolved=computed(()=>state.commandPhase==='unknown')
const dirty=computed(()=>!!state.draft && JSON.stringify(state.draft)!==savedSnapshot.value)
function draftOf(view){return {patientId:props.patientId,title:view?.title||'',instructions:view?.instructions||'',planType:view?.planType||'FOLLOW_UP',...(view?.legacySourceId||props.legacySource?.id?{legacySourceId:view?.legacySourceId||props.legacySource.id}:{}),actions:view?.actions?.map((a,i)=>({ordinal:i+1,instruction:a.instruction,dueAt:a.dueAt,assignedUserId:a.assignedUserId,evidence:(a.evidence||[]).map(e=>({sourceType:e.sourceType,sourceId:e.sourceId}))}))||[{ordinal:1,instruction:'',dueAt:'',assignedUserId:null,evidence:[]}]}}
function context(){return {generation,auth:captureAuthSession(),actor:localStorage.getItem('userId')}}
function owns(c){return c.generation===generation && isAuthSessionCurrent(c.auth) && c.actor===localStorage.getItem('userId')}
function options(c){return {expectedAuth:{...c.auth,actorId:c.actor},signal:controller.signal}}
async function initialize(){const g=++generation;controller?.abort();controller=new AbortController();enabled.value=false;loading.value=true;assignees.value=[];publishVisible.value=false;publishConfirmed.value=false;impact.value=null;currentPublished.value=null;abandonIntent.value=null;localClocks.value={};localOffsets.value={};createReconciliation.value=false;reconciliationReady.value=false;historyOwner=null;editorOwner=null;needsReload.value=false;lastCommand=null;client.reset();const c=context();try{const capabilities=await getCarePlanCapabilities(options(c));if(!owns(c))return;if(!capabilities.data?.enabled){message.value='Collaboration plans are unavailable in this session.';return}const candidates=await listAssignees(props.patientId,options(c));if(!owns(c))return;assignees.value=candidates.data||[];const result=await client.open(props.planId,{revisionId:props.revisionId,draft:props.planId?null:draftOf(props.legacySource)});if(!owns(c)||!['opened','succeeded'].includes(result.status)){if(owns(c))message.value='This plan is unavailable or access has changed.';return}state.draft=draftOf(result.data||props.legacySource);savedSnapshot.value=JSON.stringify(state.draft);editorOwner=c;enabled.value=true;message.value='';if(!props.planId)await reconcileCreateHistory(false)}catch(error){if(owns(c)){client.reset();message.value='Unable to load authorized plan context. Try reopening after checking your session.'}}finally{if(g===generation)loading.value=false}}
function validate(){const d=state.draft;if(!d||!count(d.title)||count(d.title)>160||!count(d.instructions)||count(d.instructions)>4000||!['FOLLOW_UP','MEDICATION','DIALYSIS','NUTRITION'].includes(d.planType))throw new Error('Enter a valid title (1–160), instructions (1–4000) and plan type.');if(!Array.isArray(d.actions)||d.actions.length<1||d.actions.length>50)throw new Error('A version needs 1–50 actions.');return {...d,title:d.title.trim(),instructions:d.instructions.trim(),actions:d.actions.map((a,i)=>{if(!count(a.instruction)||count(a.instruction)>2000)throw new Error('Each action needs 1–2000 characters.');if(!Number.isSafeInteger(a.assignedUserId)||!assignees.value.some(p=>p.userId===a.assignedUserId))throw new Error('Select a currently authorized assignee.');try{formatPlanTime(a.dueAt,'en')}catch{throw new Error('Invalid deadline: use an exact ISO time with offset.')};if(!Array.isArray(a.evidence)||a.evidence.length>5)throw new Error('Use at most 5 existing references per action.');const seen=new Set();const evidence=a.evidence.map(e=>{const key=`${e.sourceType}:${e.sourceId}`;if(!['MEASUREMENT','MEDICAL_RECORD'].includes(e.sourceType)||!Number.isSafeInteger(e.sourceId)||e.sourceId<=0||seen.has(key))throw new Error('References need a valid type, positive ID and no duplicate.');seen.add(key);return {sourceType:e.sourceType,sourceId:e.sourceId}});return {ordinal:i+1,instruction:a.instruction.trim(),dueAt:a.dueAt,assignedUserId:a.assignedUserId,evidence}})}}
function clearClinicalContext(){generation++;controller?.abort();client.reset();enabled.value=false;loading.value=false;assignees.value=[];savedSnapshot.value='';publishVisible.value=false;publishConfirmed.value=false;currentPublished.value=null;impact.value=null;localClocks.value={};localOffsets.value={};abandonIntent.value=null;lastCommand=null;reconciliationReady.value=false;historyOwner=null;editorOwner=null}
function requireOwnedEditor(){if(editorOwner && owns(editorOwner))return true;if(editorOwner?.generation===generation){clearClinicalContext();message.value='Access is no longer available.'}return false}
function feedback(result){if(['forbidden','unauthenticated','unavailable'].includes(result.status))clearClinicalContext();if(result.status==='stale')needsReload.value=true;message.value=({unknown:'The result is unknown. Retry the original submission or acknowledge and reload before a new command.',conflict:'The plan changed on the server. Your input is kept. Reload server state before trying again.',failed:'The server rejected this command. Your input is kept; correct it and try again.',stale:'The context or input changed. Your current draft is kept. Reload server state before trying again.',cancelled:'The request was not sent. Your input is kept.',forbidden:'Access is no longer available.',unauthenticated:'Sign in again to continue.',unavailable:'Collaboration plans are unavailable.', 'editor-required':'Reopen the editor to continue.'})[result.status]||'The command could not be completed.'}
async function refreshPreservingInput(id=state.plan?.id,revisionId=state.plan?.draftRevisionId||state.plan?.revisionId){if(!requireOwnedEditor())return false;const input=copy(state.draft),c=context();const result=await client.open(id,{revisionId,draft:input});if(!owns(c))return false;if(result.status!=='succeeded'){feedback(result);return false}editorOwner=c;savedSnapshot.value=JSON.stringify(draftOf(result.data));needsReload.value=false;return true}
async function settle(result,name,submitted){if(result.status!=='succeeded'){feedback(result);return}const unchanged=result.draftUnchanged;const id=result.data.id||result.data.planId||state.plan?.id,revisionId=result.data.draftRevisionId||result.data.revisionId||state.plan?.draftRevisionId||state.plan?.revisionId;if(!await refreshPreservingInput(id,revisionId))return;if(name!=='publishPlan' && unchanged)savedSnapshot.value=JSON.stringify(submitted);publishVisible.value=false;publishConfirmed.value=false;message.value=unchanged?'Private draft saved. Publish only when you explicitly confirm.':'The original command succeeded. Your newer input is kept; server state has been reloaded.';if(name==='publishPlan')message.value='Version published. Review server state before any further changes.';emit('saved',result.data)}
async function save(){if(!canSave.value||busy.value||unresolved.value||createReconciliation.value||needsReload.value||!requireOwnedEditor())return;try{const body=validate(),name=state.plan?'saveDraft':'createDraft',c=context();state.draft=body;lastCommand=name;const result=await client.runCommand(name,{payload:body,expectedVersion:state.plan?.version||0});if(owns(c))await settle(result,name,body)}catch(error){message.value=error.message}}
async function preparePublish(){if(!allowed('PUBLISH_PLAN')||busy.value||unresolved.value||dirty.value||needsReload.value||!requireOwnedEditor())return;const c=context(),editor=state.editor;try{validate();impact.value=copy(state.plan.revisionImpact);if(state.plan.currentRevisionId){if(!impact.value||impact.value.currentRevisionId!==state.plan.currentRevisionId||typeof impact.value.digest!=='string')throw new Error('Reload the server revision impact before publishing.');const response=await getPlan(state.plan.id,options(c));if(!owns(c)||editor!==state.editor)return;currentPublished.value=response.data;if(currentPublished.value.currentRevisionId!==impact.value.currentRevisionId)throw new Error('The published version changed. Reload before publishing.')}publishConfirmed.value=false;publishVisible.value=true}catch(error){if(owns(c)&&editor===state.editor){if([401,403,404].includes(Number(error.response?.status||error.response?.data?.code||error.code))){clearClinicalContext();message.value='Access is no longer available.'}else message.value=error.message}}}
async function publish(){if(!publishConfirmed.value||!publishVisible.value||!allowed('PUBLISH_PLAN')||busy.value||dirty.value)return;const c=context(),body=state.plan.currentRevisionId?{currentRevisionId:impact.value.currentRevisionId,supersededActionDigest:impact.value.digest}:{currentRevisionId:null,supersededActionDigest:null};lastCommand='publishPlan';const result=await client.runCommand('publishPlan',{payload:body,expectedVersion:state.plan.version});if(owns(c))await settle(result,'publishPlan',state.draft)}
async function retryOriginal(){if(!unresolved.value||busy.value||!lastCommand)return;const c=context(),name=lastCommand;const result=await client.runCommand(name,{retry:true});if(owns(c))await settle(result,name,state.draft)}
function validHistory(result){return result.status==='succeeded' && Array.isArray(result.data?.items) && (result.data.nextCursor==null || (typeof result.data.nextCursor==='string' && result.data.nextCursor.length>0))}
async function reconcileCreateHistory(reopen=false){if(!requireOwnedEditor())return {status:'stale'};const input=copy(state.draft),c=context();createReconciliation.value=true;reconciliationReady.value=false;historyOwner=null;const result=await client.load({queue:'HISTORY'});if(!owns(c))return result;if(!validHistory(result)){if(result.status==='succeeded')message.value='Server history is incomplete. Retry authorized loading before creating a new draft.';else feedback(result);return result}if(reopen){const opened=await client.open(null,{draft:input});if(!owns(c))return opened;if(opened.status!=='opened'){feedback(opened);return opened}editorOwner=c}historyOwner=c;reconciliationReady.value=true;needsReload.value=false;message.value='Your input is kept. Check authoritative history before creating another private draft.';return result}
async function reload(){if(!state.plan?.id)return reconcileCreateHistory(true);const success=await refreshPreservingInput();if(success){publishVisible.value=false;message.value='Server state reloaded. Your input is kept; save changes explicitly.'}}
async function moreCreateHistory(){if(busy.value||!state.nextCursor||!requireOwnedEditor())return;const c=context();reconciliationReady.value=false;historyOwner=null;const result=await client.load({queue:'HISTORY',cursor:state.nextCursor});if(!owns(c))return;if(result.status==='stale-cursor')return reconcileCreateHistory(false);if(!validHistory(result)){if(result.status==='succeeded')message.value='Server history is incomplete. Retry authorized loading before creating a new draft.';else feedback(result);return}historyOwner=c;reconciliationReady.value=true}
function acknowledgeCreateHistory(){if(!requireOwnedEditor())return;if(createReconciliation.value && reconciliationReady.value && !busy.value && !state.nextCursor && enabled.value && state.editor && owns(historyOwner)){createReconciliation.value=false;reconciliationReady.value=false;historyOwner=null}}
function retryCreateHistory(){if(busy.value)return;return !enabled.value||!state.editor?initialize():reconcileCreateHistory(false)}
async function useExistingDraft(existing){const c=context();const result=await client.open(existing.id,{revisionId:existing.draftRevisionId||null});if(!owns(c))return;if(result.status!=='succeeded'){feedback(result);return}editorOwner=c;state.draft=draftOf(result.data);savedSnapshot.value=JSON.stringify(state.draft);createReconciliation.value=false;message.value='Existing server plan loaded. Edit only an allowed private draft.'}
function requestReload(){if(unresolved.value||state.commandPhase==='pending'){abandonIntent.value='reload';return}return reload()}
function requestLeave(){if(unresolved.value||state.commandPhase==='pending'||dirty.value){abandonIntent.value='close';return false}return true}
function requestClose(){if(!requestLeave())return;client.reset();emit('closed')}
async function confirmAbandon(){const intent=abandonIntent.value;abandonIntent.value=null;if(intent==='close'){client.reset();emit('closed')}else await reload()}
function addAction(){if(!canSave.value||state.draft.actions.length>=50)return;state.draft.actions.push({ordinal:state.draft.actions.length+1,instruction:'',dueAt:'',assignedUserId:null,evidence:[]})}
function removeAction(index){if(state.draft.actions.length<=1)return;state.draft.actions.splice(index,1);state.draft.actions.forEach((a,i)=>{a.ordinal=i+1});localClocks.value={};localOffsets.value={}}
function roleLabel(role){return ({user:'User',family:'Family caregiver',doctor:'Doctor',nurse:'Nurse',admin:'Administrator'})[String(role||'').toLowerCase()]||'Account'}
function evidenceLabel(type){return type==='MEASUREMENT'?'Measurement':'Medical record'}
function actionLabel(status){return ({OPEN:'Awaiting execution or more information',NEEDS_HELP:'Help requested',SUBMITTED:'Submitted, awaiting doctor review',CONFIRMED:'Record reviewed',SUPERSEDED:'Replaced by a new version',CANCELLED:'Cancelled',DRAFT:'Private draft'})[status]||'Unknown state'}
function lifecycleLabel(status){return ({DRAFT:'Private draft',ACTIVE:'Active',COMPLETED:'Closed after review',CANCELLED:'Cancelled'})[status]||'Unknown state'}
function displayTime(value){if(!value)return 'Deadline needs an explicit time and offset.';try{return formatPlanTime(value,'en')}catch{return 'Invalid deadline: use an exact ISO time with offset.'}}
function offsetsFor(index){try{return getLocalTimeOffsets(localClocks.value[index],{timeZone})}catch{return []}}
function offsetLabel(minutes){return `UTC${minutes<0?'-':'+'}${String(Math.floor(Math.abs(minutes)/60)).padStart(2,'0')}:${String(Math.abs(minutes)%60).padStart(2,'0')}`}
function applyLocalTime(index){try{state.draft.actions[index].dueAt=toOffsetIso(localClocks.value[index],localOffsets.value[index],{timeZone});message.value=''}catch{message.value='Choose a valid browser-local time and explicit UTC offset.'}}
function beforeUnload(event){if(unresolved.value||state.commandPhase==='pending'||dirty.value){event.preventDefault();event.returnValue=''}}
watch(()=>[props.patientId,props.planId,props.revisionId,props.legacySource],initialize,{immediate:true,flush:'sync'})
watch(()=>state.editor,editor=>{if(!editor){assignees.value=[];savedSnapshot.value='';publishVisible.value=false;publishConfirmed.value=false;currentPublished.value=null;impact.value=null;localClocks.value={};localOffsets.value={};reconciliationReady.value=false;historyOwner=null;editorOwner=null}},{flush:'sync'})
onMounted(()=>window.addEventListener('beforeunload',beforeUnload))
onUnmounted(()=>{generation++;controller?.abort();window.removeEventListener('beforeunload',beforeUnload)})
defineExpose({requestClose,requestLeave})
</script>
<style scoped>
.care-plan-editor{min-width:0;color:var(--ink-800)}header,.controls,.evidence-row{display:flex;gap:12px;align-items:center;flex-wrap:wrap}header{align-items:flex-start;justify-content:space-between}h2,h3{margin:0 0 10px}p{line-height:1.6;overflow-wrap:anywhere}fieldset{border:0;padding:0;min-width:0}label{display:grid;gap:6px;margin:12px 0;font-weight:600}input,select,textarea{box-sizing:border-box;width:100%;min-width:0;min-height:44px;padding:10px;border:1px solid var(--line);border-radius:8px;background:var(--paper);color:var(--ink-800);font:inherit}textarea{resize:vertical}button{min-height:44px;max-width:100%;padding:10px 14px;border:1px solid var(--care-600);border-radius:8px;background:var(--paper);color:var(--care-800);font:inherit;cursor:pointer}button:disabled{opacity:.5;cursor:default}button:focus-visible,input:focus-visible,select:focus-visible,textarea:focus-visible,summary:focus-visible{outline:3px solid var(--care-600);outline-offset:3px}.action-editor,.notice{border:1px solid var(--line);border-radius:12px;padding:16px;margin:16px 0;overflow-wrap:anywhere}.notice{background:var(--care-50)}.feedback{padding:12px;background:var(--surface-subtle)}details{margin:14px 0}summary{min-height:44px;cursor:pointer}.check{display:flex;align-items:center}.check input{width:24px;flex-shrink:0}.evidence-row>*{flex:1 1 160px}@media(max-width:600px){.controls button{width:100%}.action-editor,.notice{padding:12px}header>div{min-width:0;width:100%}}
</style>
