<template>
  <main class="journey-page">
    <header class="journey-hero">
      <div><span>全程照护</span><h1>健康照护全流程</h1><p>在一个可追溯的工作台中统一管理健康指标、预约复诊、远程问诊、康复、急救信息、专项健康、隐私与运营。</p></div>
      <el-tag effect="plain">患者：{{ currentPatientName || currentPatientId || '未选择' }}</el-tag>
    </header>

    <el-alert v-if="patientRequired && !currentPatientId" title="使用本模块前，请先在工作台顶部选择患者。" type="warning" show-icon :closable="false" />
    <el-tabs v-model="tab" class="journey-tabs" @tab-change="syncTab">
      <el-tab-pane label="健康指标" name="measurements">
        <section class="panel-grid two">
          <el-card><template #header><b>录入健康指标</b></template><el-form label-position="top">
            <div class="form-grid"><el-form-item label="指标"><el-select v-model="measurement.metricType"><el-option v-for="item in metricOptions" :key="item.value" v-bind="item" /></el-select></el-form-item><el-form-item label="测量时间"><el-date-picker v-model="measurement.measuredAt" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss" /></el-form-item><el-form-item label="主数值"><el-input-number v-model="measurement.valuePrimary" :precision="2" /></el-form-item><el-form-item v-if="measurement.metricType==='BP'" label="舒张压"><el-input-number v-model="measurement.valueSecondary" /></el-form-item><el-form-item label="Unit"><el-input v-model="measurement.unit" /></el-form-item><el-form-item label="备注"><el-input v-model="measurement.remark" /></el-form-item></div>
            <el-button type="primary" :loading="busy" @click="recordMeasurement">保存并自动评估</el-button>
          </el-form></el-card>
          <el-card><template #header><div class="card-head"><b>趋势记录</b><el-button @click="load健康指标">刷新</el-button></div></template><el-table :data="measurements" max-height="440"><el-table-column prop="measured_at" label="时间" width="165"/><el-table-column prop="metric_type" label="指标" width="110"/><el-table-column label="数值"><template #default="{row}">{{row.value_primary}}{{row.value_secondary!=null?'/'+row.value_secondary:''}} {{row.unit}}</template></el-table-column><el-table-column prop="status" label="状态" width="100"><template #default="{row}"><el-tag :type="row.status==='NORMAL'?'success':'danger'">{{row.status}}</el-tag></template></el-table-column><el-table-column v-if="is医生" label="医生标注" width="130"><template #default="{row}"><el-button link @click="annotate(row)">添加标注</el-button></template></el-table-column></el-table></el-card>
        </section>
      </el-tab-pane>

      <el-tab-pane label="预约与复诊" name="appointments">
        <section class="panel-grid two">
          <el-card><template #header><b>预约或改约</b></template><el-form label-position="top"><div class="form-grid"><el-form-item label="医生"><el-select v-model="appointment.doctorUserId" @change="load医生设置计划s"><el-option v-for="d in clinicians" :key="d.id" :label="d.real_name||d.username" :value="d.id"/></el-select></el-form-item><el-form-item label="可预约时段"><el-select v-model="appointment.scheduleId" clearable @change="select设置计划"><el-option v-for="s in doctor设置计划s" :key="s.id" :value="s.id" :label="`${s.work_date} ${s.start_time}-${s.end_time}`"/></el-select></el-form-item><el-form-item label="方式"><el-select v-model="appointment.consultation方式"><el-option label="线下面诊" value="IN_PERSON"/><el-option label="图文" value="TEXT"/><el-option label="语音" value="VOICE"/><el-option label="视频" value="VIDEO"/></el-select></el-form-item><el-form-item label="开始时间"><el-date-picker v-model="appointment.startAt" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss"/></el-form-item><el-form-item label="结束时间"><el-date-picker v-model="appointment.endAt" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss"/></el-form-item><el-form-item label="复诊周期（天）"><el-input-number v-model="appointment.recurrenceDays" :min="0"/></el-form-item><el-form-item label="就诊原因"><el-input v-model="appointment.reason"/></el-form-item></div><el-button type="primary" @click="bookAppointment">保存预约</el-button></el-form></el-card>
          <el-card><template #header><b>三方共享日程</b></template><el-table :data="appointments" max-height="430"><el-table-column prop="start_at" label="开始时间" width="165"/><el-table-column prop="doctor_name" label="医生"/><el-table-column prop="consultation_mode" label="方式"/><el-table-column prop="status" label="状态"/><el-table-column label="操作" width="150"><template #default="{row}"><el-button link @click="editAppointment(row)">改约</el-button><el-button link type="danger" @click="cancel(row)">取消</el-button></template></el-table-column></el-table></el-card>
        </section>
        <el-card v-if="is医生" class="section-card"><template #header><b>诊后小结、电子处方与复诊</b></template><el-form label-position="top"><div class="form-grid"><el-form-item label="诊断摘要"><el-input v-model="visit.diagnosisSummary" type="textarea"/></el-form-item><el-form-item label="治疗摘要"><el-input v-model="visit.treatmentSummary" type="textarea"/></el-form-item><el-form-item label="复诊建议"><el-input v-model="visit.followUpAdvice" type="textarea"/></el-form-item><el-form-item label="复诊时间"><el-date-picker v-model="visit.followUpAt" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss"/></el-form-item></div><el-button type="primary" @click="createVisit">保存小结</el-button></el-form><el-divider>电子处方留档</el-divider><el-form label-position="top"><div class="form-grid"><el-form-item label="药品"><el-input v-model="prescription.drugName"/></el-form-item><el-form-item label="剂量"><el-input v-model="prescription.dosage" placeholder="e.g. 5 mg"/></el-form-item><el-form-item label="频次"><el-input v-model="prescription.frequency" placeholder="e.g. twice daily"/></el-form-item><el-form-item label="用法"><el-input v-model="prescription.administration用法" placeholder="oral / topical"/></el-form-item><el-form-item label="疗程天数"><el-input-number v-model="prescription.durationDays" :min="1"/></el-form-item><el-form-item label="医嘱说明"><el-input v-model="prescription.instructions"/></el-form-item></div><el-button type="primary" @click="savePrescription">发布新处方版本</el-button></el-form></el-card>
        <el-card class="section-card"><template #header><b>历史就诊时间轴</b></template><el-timeline><el-timeline-item v-for="v in visits" :key="v.id" :timestamp="v.visited_at"><b>{{v.diagnosis_summary||'就诊小结'}}</b><p>{{v.treatment_summary}}</p><el-button v-if="is医生&&v.status!=='PUBLISHED'" link @click="publish(v)">推送给患者与家属</el-button></el-timeline-item></el-timeline></el-card>
      </el-tab-pane>

      <el-tab-pane label="远程问诊" name="consultation">
        <section class="panel-grid two"><el-card><template #header><b>开始时间 consultation</b></template><el-form label-position="top"><div class="form-grid"><el-form-item label="方式"><el-select v-model="consultForm.mode"><el-option label="图文" value="TEXT"/><el-option label="语音" value="VOICE"/><el-option label="视频" value="VIDEO"/></el-select></el-form-item><el-form-item label="医生"><el-select v-model="consultForm.doctorUserId"><el-option v-for="d in clinicians" :key="d.id" :label="d.real_name||d.username" :value="d.id"/></el-select></el-form-item><el-form-item label="症状"><el-input v-model="consultForm.symptom"/></el-form-item><el-form-item label="持续时间"><el-input v-model="consultForm.duration图文"/></el-form-item><el-form-item label="既往史"><el-input v-model="consultForm.medicalHistory" type="textarea"/></el-form-item><el-form-item label="家属可见性"><el-switch v-model="consult可见" active-text="可见" inactive-text="私密"/></el-form-item></div><el-button type="primary" @click="beginConsultation">开始时间</el-button></el-form></el-card>
          <el-card><template #header><b>问诊记录</b></template><el-table :data="consultations"><el-table-column prop="started_at" label="开始时间ed"/><el-table-column prop="mode" label="方式"/><el-table-column prop="symptom" label="症状"/><el-table-column prop="status" label="状态"/><el-table-column label=""><template #default="{row}"><el-button link @click="openConsultation(row)">打开</el-button></template></el-table-column></el-table></el-card></section>
        <el-card v-if="activeConsultation" class="section-card"><template #header><div class="card-head"><div><b>{{activeConsultation.mode}} 问诊 · {{activeConsultation.status}}</b><span v-if="activeConsultation.status==='OPEN'" class="realtime-state"><i></i>{{chatSyncing?'同步中…':'实时更新已开启'}}</span></div><div><el-button v-if="activeConsultation.status==='OPEN'&&activeConsultation.mode!=='TEXT'" :type="callActive?'danger':'primary'" @click="callActive?stopCall():startCall()">{{callActive?'离开通话':`加入通话`}}</el-button><el-button v-if="activeConsultation.status==='OPEN'" @click="finishConsultation">结束并归档</el-button></div></div></template><div v-if="callActive" class="media-room"><video ref="local视频" autoplay muted playsinline/><video v-for="entry in remoteEntries" :key="entry[0]" :ref="el=>attachRemote视频(entry[0],el)" autoplay playsinline/><p v-if="!remoteEntries.length">正在等待其他参与者…</p></div><div ref="messageList" class="message-list" aria-live="polite"><article v-for="m in activeConsultation.messages" :key="m.id"><b>{{m.sender_name||m.sender_user_id}}</b><span>{{m.sent_at}}</span><p>{{m.content}}</p></article></div><div v-if="activeConsultation.status==='OPEN'" class="message-compose"><el-select v-model="message.messageType"><el-option label="图文" value="TEXT"/><el-option label="图片或化验单" value="IMAGE"/><el-option label="文件记录" value="FILE"/><el-option label="语音消息" value="VOICE"/></el-select><el-input v-model="message.content" placeholder="消息或附件说明" @keyup.enter="sendMessage"/><el-input-number v-if="message.messageType!=='TEXT'" v-model="message.attachmentRecordId" placeholder="医疗记录编号"/><el-button type="primary" @click="sendMessage">发送</el-button></div></el-card>
      </el-tab-pane>

      <el-tab-pane label="住院与康复" name="recovery">
        <section class="panel-grid two"><el-card v-if="is医生"><template #header><b>治疗计划</b></template><el-form label-position="top"><el-form-item label="计划类型"><el-select v-model="plan.planType"><el-option v-for="x in ['INPATIENT','SURGERY','REHAB','DISCHARGE']" :key="x" :value="x" :label="x"/></el-select></el-form-item><el-form-item label="标题"><el-input v-model="plan.title"/></el-form-item><el-form-item label="结构化计划"><el-input v-model="plan图文" type="textarea" :rows="6" placeholder="检查安排、手术时间、用药调整、出院医嘱"/></el-form-item><el-button type="primary" @click="createPlan">发布计划</el-button></el-form></el-card><el-card><template #header><b>当前治疗计划</b></template><el-collapse><el-collapse-item v-for="p in plans" :key="p.id" :title="p.title"><p>{{p.plan_type}} · {{p.status}}</p><pre>{{prettyJson(p.plan_json)}}</pre></el-collapse-item></el-collapse></el-card></section>
        <el-card class="section-card"><template #header><b>康复、伤口、引流与异常症状打卡</b></template><el-form label-position="top"><div class="form-grid"><el-form-item label="记录类型"><el-select v-model="rehab.recordType"><el-option v-for="x in ['EXERCISE','WOUND','DRAIN','SYMPTOM']" :key="x" :value="x" :label="x"/></el-select></el-form-item><el-form-item label="完成度"><el-slider v-model="rehab.completionPercent"/></el-form-item><el-form-item label="动作指导视频地址"><el-input v-model="rehab.videoUrl"/></el-form-item><el-form-item label="结构化观察记录"><el-input v-model="rehab图文" type="textarea" placeholder="伤口情况、引流量、症状程度或训练记录"/></el-form-item><el-form-item label="需要医护关注"><el-switch v-model="rehab.abnormal"/></el-form-item></div><el-button type="primary" @click="checkinRehab">保存打卡</el-button></el-form><el-table :data="rehabRows"><el-table-column prop="recorded_at" label="时间"/><el-table-column prop="record_type" label="Type"/><el-table-column prop="completion_percent" label="完成度"/><el-table-column prop="abnormal" label="预警"/></el-table></el-card>
      </el-tab-pane>

      <el-tab-pane label="急诊与呼救" name="emergency">
        <section class="panel-grid two"><el-card class="emergency-card"><template #header><b>一键紧急呼救</b></template><p>将定位、病史、过敏史和当前用药推送给已绑定家属与医生。</p><el-input v-model="emergency.location图文" placeholder="位置说明"/><el-button type="danger" size="large" @click="sos">发送 emergency call</el-button></el-card><el-card><template #header><div class="card-head"><b>离线关键医疗信息卡</b><el-button @click="load急诊与呼救Card">刷新</el-button></div></template><div v-if="emergencyCard"><h3>{{emergencyCard.patient?.name}}</h3><p><b>病史：</b> {{emergencyCard.patient?.medical_history||'-'}}</p><p><b>过敏史：</b> {{emergencyCard.clinical?.allergy_drugs||'-'}}</p><p><b>血型：</b> {{emergencyCard.clinical?.blood_type||'未记录'}}</p><p><b>当前用药：</b> {{(emergencyCard.medications||[]).map(x=>x.drug_name).join(', ')||'-'}}</p><el-tag>已缓存在本设备，可离线查看</el-tag></div></el-card></section>
      </el-tab-pane>

      <el-tab-pane label="儿童与孕产" name="specialty">
        <section class="panel-grid three"><el-card><template #header><b>生长曲线</b></template><el-form label-position="top"><el-form-item label="日期"><el-date-picker v-model="growth.record日期" value-format="YYYY-MM-DD"/></el-form-item><el-form-item label="身高（厘米）"><el-input-number v-model="growth.heightCm"/></el-form-item><el-form-item label="体重 kg"><el-input-number v-model="growth.weightKg" :precision="2"/></el-form-item><el-form-item label="头围（厘米）"><el-input-number v-model="growth.headCircumferenceCm" :precision="1"/></el-form-item><el-form-item label="标准百分位"><div class="inline"><el-input-number v-model="growth.heightPercentile" placeholder="Height %"/><el-input-number v-model="growth.weightPercentile" placeholder="体重 %"/></div></el-form-item><el-button type="primary" @click="saveSpecial('growth',growth)">保存</el-button></el-form></el-card><el-card><template #header><b>疫苗接种计划</b></template><el-form label-position="top"><el-form-item label="疫苗名称"><el-input v-model="vaccine.vaccineName"/></el-form-item><el-form-item label="剂量"><el-input v-model="vaccine.doseNo"/></el-form-item><el-form-item label="计划日期"><el-date-picker v-model="vaccine.planned日期" value-format="YYYY-MM-DD"/></el-form-item><el-form-item label="提醒时间"><el-date-picker v-model="vaccine.remindAt" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss"/></el-form-item><el-button type="primary" @click="saveSpecial('vaccination',vaccine)">保存</el-button></el-form></el-card><el-card><template #header><b>产检与产后时间轴</b></template><el-form label-position="top"><el-form-item label="Type"><el-select v-model="maternity.recordType"><el-option label="产检" value="PRENATAL"/><el-option label="分娩" value="DELIVERY"/><el-option label="产后" value="POSTPARTUM"/></el-select></el-form-item><el-form-item label="日期"><el-date-picker v-model="maternity.record日期" value-format="YYYY-MM-DD"/></el-form-item><el-form-item label="标题"><el-input v-model="maternity.title"/></el-form-item><el-form-item label="详情"><el-input v-model="maternity图文" type="textarea"/></el-form-item><el-button type="primary" @click="saveMaternity">保存</el-button></el-form></el-card></section>
      </el-tab-pane>

      <el-tab-pane label="心理健康" name="mental">
        <section class="panel-grid two"><el-card><template #header><b>私密 self-assessment</b></template><el-form label-position="top"><el-form-item label="量表"><el-select v-model="mental.scaleCode"><el-option label="PHQ-9" value="PHQ9"/><el-option label="GAD-7" value="GAD7"/><el-option label="WHO-5" value="WHO5"/></el-select></el-form-item><el-form-item label="题目得分（逗号分隔）"><el-input v-model="mentalAnswers" placeholder="0,1,2,1,0"/></el-form-item><el-form-item label="可见 to family"><el-switch v-model="mental可见"/></el-form-item><el-button type="primary" @click="submitMental">私密提交</el-button></el-form></el-card><el-card><template #header><b>定期推送</b></template><el-form label-position="top"><el-form-item label="间隔天数"><el-input-number v-model="mental设置计划.intervalDays" :min="1"/></el-form-item><el-form-item label="下次推送"><el-date-picker v-model="mental设置计划.nextDueAt" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss"/></el-form-item><el-button type="primary" @click="scheduleMental">设置计划</el-button></el-form><el-table :data="mentalRows"><el-table-column prop="submitted_at" label="提交时间"/><el-table-column prop="scale_code" label="量表"/><el-table-column prop="score" label="得分"/><el-table-column prop="severity" label="程度"/></el-table></el-card></section>
      </el-tab-pane>

      <el-tab-pane label="隐私与授权" name="privacy">
        <el-card><template #header><b>患者自主授权</b></template><el-form label-position="top" class="inline-form"><el-form-item label="用户编号"><el-input-number v-model="grant.granteeUserId"/></el-form-item><el-form-item label="角色"><el-select v-model="grant.grantee角色"><el-option label="医生" value="DOCTOR"/><el-option label="家属" value="FAMILY"/><el-option label="监护人" value="GUARDIAN"/></el-select></el-form-item><el-form-item label="权限级别"><el-select v-model="grant.access权限级别"><el-option label="只读" value="READ"/><el-option label="可录入" value="WRITE"/><el-option label="可代办" value="PROXY"/></el-select></el-form-item><el-form-item label="可见 modules"><el-input v-model="grant.visibleModules" placeholder="MEASUREMENTS,APPOINTMENTS or blank for all"/></el-form-item><el-button type="primary" @click="createGrant">授权</el-button></el-form><el-table :data="grants"><el-table-column prop="real_name" label="人员"/><el-table-column prop="grantee_role" label="角色"/><el-table-column prop="access_level" label="权限级别"/><el-table-column prop="visible_modules" label="可见 modules"/><el-table-column prop="status" label="状态"/><el-table-column label=""><template #default="{row}"><el-button link type="danger" @click="revoke(row)">撤销</el-button></template></el-table-column></el-table></el-card>
      </el-tab-pane>

      <el-tab-pane v-if="is医生" label="运营管理" name="operations">
        <section class="panel-grid two"><el-card><template #header><b>医生 schedule</b></template><el-form label-position="top"><div class="form-grid"><el-form-item label="日期"><el-date-picker v-model="schedule.work日期" value-format="YYYY-MM-DD"/></el-form-item><el-form-item label="开始时间"><el-time-picker v-model="schedule.start时间" value-format="HH:mm:ss"/></el-form-item><el-form-item label="结束时间"><el-time-picker v-model="schedule.end时间" value-format="HH:mm:ss"/></el-form-item><el-form-item label="时段分钟数"><el-input-number v-model="schedule.slotMinutes" :min="10"/></el-form-item></div><el-button type="primary" @click="create设置计划">新增可预约时段</el-button></el-form></el-card><el-card><template #header><b>患者分组</b></template><div class="message-compose"><el-input v-model="group.groupName" placeholder="分组名称"/><el-input v-model="group.description" placeholder="说明"/><el-button type="primary" @click="create分组">创建</el-button></div><el-table :data="groups"><el-table-column prop="group_name" label="分组"/><el-table-column prop="patient_count" label="患者数"/><el-table-column label=""><template #default="{row}"><el-button link @click="addTo分组(row)">加入当前患者</el-button></template></el-table-column></el-table></el-card></section>
        <el-card class="section-card"><template #header><div class="card-head"><b>内部照护统计</b><el-button @click="load运营管理">刷新</el-button></div></template><div v-if="operations" class="metric-cards"><article><span>随访完成率</span><strong>{{operations.followUp?.completion_rate||0}}%</strong></article><article><span>服药依从率</span><strong>{{operations.medication?.adherence_rate||0}}%</strong></article><article><span>指标达标率</span><strong>{{operations.measurements?.target_rate||0}}%</strong></article><article><span>已处理预警</span><strong>{{operations.alerts?.resolved||0}} / {{operations.alerts?.total||0}}</strong></article></div></el-card>
      </el-tab-pane>
    </el-tabs>
  </main>
</template>

<script setup>
import { computed, nextTick, onBeforeUnmount, onMounted, reactive, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import { useCurrentPatient } from '@/composables/useCurrentPatient'
import * as api from '@/api/careJourney'

const route=useRoute(),router=useRouter(),{currentPatientId,currentPatientName}=useCurrentPatient()
const roles=JSON.parse(localStorage.getItem('userRoleCodes')||'[]'),isDoctor=computed(()=>roles.includes('doctor')||roles.includes('admin'))
const allowedTabs=['measurements','appointments','consultation','recovery','emergency','specialty','mental','privacy','operations']
const tab=ref(allowedTabs.includes(route.query.tab)?route.query.tab:'measurements'),busy=ref(false)
const patientRequired=computed(()=>!['operations'].includes(tab.value))
const clinicians=ref([]),doctorSchedules=ref([]),measurements=ref([]),appointments=ref([]),visits=ref([]),consultations=ref([]),activeConsultation=ref(null),plans=ref([]),rehabRows=ref([]),emergencyCard=ref(null),mentalRows=ref([]),grants=ref([]),groups=ref([]),operations=ref(null)
const currentUserId=Number(localStorage.getItem('userId')),localVideo=ref(null),messageList=ref(null),callActive=ref(false),chatSyncing=ref(false),remoteStreams=ref({}),remoteEntries=computed(()=>Object.entries(remoteStreams.value));let localStream=null,signalTimer=null,messageTimer=null,lastSignalId=0;const peers=new Map(),pendingIce=new Map()
const now=()=>new Date().toISOString().slice(0,19),today=()=>new Date().toISOString().slice(0,10)
const measurement=reactive({metricType:'BP',valuePrimary:120,valueSecondary:80,unit:'mmHg',measuredAt:now(),remark:''})
const appointment=reactive({id:null,doctorUserId:null,scheduleId:null,consultationMode:'IN_PERSON',startAt:'',endAt:'',recurrenceDays:0,reason:''})
const visit=reactive({diagnosisSummary:'',treatmentSummary:'',followUpAdvice:'',followUpAt:''})
const prescription=reactive({drugName:'',dosage:'',frequency:'',administrationRoute:'',durationDays:7,instructions:''})
const consultForm=reactive({mode:'TEXT',doctorUserId:null,symptom:'',durationText:'',medicalHistory:''}),consultVisible=ref(true),message=reactive({messageType:'TEXT',content:'',attachmentRecordId:null})
const plan=reactive({planType:'INPATIENT',title:''}),planText=ref(''),rehab=reactive({recordType:'EXERCISE',completionPercent:0,videoUrl:'',abnormal:false}),rehabText=ref('')
const emergency=reactive({locationText:'',latitude:null,longitude:null})
const growth=reactive({recordDate:today(),heightCm:null,weightKg:null,headCircumferenceCm:null,heightPercentile:null,weightPercentile:null}),vaccine=reactive({vaccineName:'',doseNo:'',plannedDate:today(),remindAt:''}),maternity=reactive({recordType:'PRENATAL',recordDate:today(),title:''}),maternityText=ref('')
const mental=reactive({scaleCode:'PHQ9'}),mentalAnswers=ref(''),mentalVisible=ref(false),mentalSchedule=reactive({scaleCode:'PHQ9',intervalDays:14,nextDueAt:now()})
const grant=reactive({granteeUserId:null,granteeRole:'FAMILY',accessLevel:'READ',visibleModules:''}),schedule=reactive({workDate:today(),startTime:'09:00:00',endTime:'12:00:00',slotMinutes:30}),group=reactive({groupName:'',description:''})
const metricOptions=[{label:'Blood pressure',value:'BP'},{label:'Blood glucose',value:'GLUCOSE'},{label:'Blood oxygen',value:'SPO2'},{label:'Weight',value:'WEIGHT'},{label:'Heart rate',value:'HEART_RATE'},{label:'Temperature',value:'TEMPERATURE'},{label:'Custom',value:'CUSTOM'}]
function syncTab(name){if(name!=='consultation')stopMessageSync();router.replace({query:{...route.query,tab:name}});loadTab()}
function pid(){if(!currentPatientId.value)throw new Error('请先选择患者。');return currentPatientId.value}
async function safely(action,message='已保存'){try{busy.value=true;await action();ElMessage.success(message)}catch(e){if(e.message==='请先选择患者。')ElMessage.warning(e.message)}finally{busy.value=false}}
async function loadMeasurements(){if(!currentPatientId.value)return;measurements.value=(await api.listMeasurements({patientId:pid()})).data||[]}
async function recordMeasurement(){await safely(async()=>{await api.saveMeasurement({...measurement,patientId:pid()});await loadMeasurements()})}
async function annotate(row){const {value}=await ElMessageBox.prompt('为该趋势点添加医生备注','临床标注');await safely(async()=>{await api.annotateMeasurement(row.id,value);await loadMeasurements()})}
async function loadAppointments(){if(!currentPatientId.value)return;appointments.value=(await api.listAppointments(pid())).data||[];visits.value=(await api.listVisits(pid())).data||[]}
async function loadDoctorSchedules(){doctorSchedules.value=appointment.doctorUserId?((await api.listDoctorSchedules({doctorUserId:appointment.doctorUserId})).data||[]):[]}
function selectSchedule(id){const s=doctorSchedules.value.find(x=>x.id===id);if(!s)return;appointment.startAt=`${s.work_date}T${String(s.start_time).slice(0,8)}`;const endMinutes=Number(String(s.start_time).slice(0,2))*60+Number(String(s.start_time).slice(3,5))+Number(s.slot_minutes||30);appointment.endAt=`${s.work_date}T${String(Math.floor(endMinutes/60)%24).padStart(2,'0')}:${String(endMinutes%60).padStart(2,'0')}:00`}
async function bookAppointment(){await safely(async()=>{await api.saveAppointment({...appointment,patientId:pid(),nextFollowUpAt:appointment.recurrenceDays?appointment.startAt:null});Object.assign(appointment,{id:null,startAt:'',endAt:'',reason:''});await loadAppointments()})}
function editAppointment(row){Object.assign(appointment,{id:row.id,doctorUserId:row.doctor_user_id,scheduleId:row.schedule_id,consultationMode:row.consultation_mode,startAt:String(row.start_at).replace(' ','T'),endAt:String(row.end_at).replace(' ','T'),recurrenceDays:row.recurrence_days||0,reason:row.reason||''});loadDoctorSchedules();window.scrollTo({top:0,behavior:'smooth'})}
async function cancel(row){await ElMessageBox.confirm('取消该预约并通知共享照护团队？','取消预约');await safely(async()=>{await api.cancelAppointment(row.id,'Cancelled from shared schedule');await loadAppointments()},'预约已取消')}
async function createVisit(){await safely(async()=>{await api.saveVisit({...visit,patientId:pid(),visitedAt:now()});await loadAppointments()})}
async function publish(row){await safely(async()=>{await api.publishVisit(row.id);await loadAppointments()},'小结已推送')}
async function savePrescription(){await safely(async()=>{await api.savePrescription({patientId:pid(),instructions:prescription.instructions,items:[{drugName:prescription.drugName,dosage:prescription.dosage,frequency:prescription.frequency,administrationRoute:prescription.administrationRoute,durationDays:prescription.durationDays}]});Object.assign(prescription,{drugName:'',dosage:'',frequency:'',administrationRoute:'',durationDays:7,instructions:''});await loadAppointments()},'处方已发布并同步')}
async function loadConsultations(){if(!currentPatientId.value)return;consultations.value=(await api.listConsultations(pid())).data||[]}
async function beginConsultation(){await safely(async()=>{const res=await api.startConsultation({...consultForm,patientId:pid(),familyVisibility:consultVisible.value?'VISIBLE':'PRIVATE'});activeConsultation.value=res.data;await loadConsultations();await scrollMessages();startMessageSync()},'问诊已开始')}
async function scrollMessages(){await nextTick();if(messageList.value)messageList.value.scrollTop=messageList.value.scrollHeight}
function stopMessageSync(){if(messageTimer){clearInterval(messageTimer);messageTimer=null}chatSyncing.value=false}
async function refreshActiveConsultation(){if(!activeConsultation.value||chatSyncing.value)return;chatSyncing.value=true;try{const previous=(activeConsultation.value.messages||[]).at(-1)?.id;const fresh=(await api.getConsultation(activeConsultation.value.id)).data;activeConsultation.value=fresh;if((fresh.messages||[]).at(-1)?.id!==previous)await scrollMessages();if(fresh.status!=='OPEN')stopMessageSync()}catch{}finally{chatSyncing.value=false}}
function startMessageSync(){stopMessageSync();if(activeConsultation.value?.status!=='OPEN')return;messageTimer=window.setInterval(refreshActiveConsultation,1500)}
async function openConsultation(row){activeConsultation.value=(await api.getConsultation(row.id)).data;await scrollMessages();startMessageSync()}
async function sendMessage(){await safely(async()=>{await api.sendConsultationMessage(activeConsultation.value.id,{...message});message.content='';message.attachmentRecordId=null;await openConsultation(activeConsultation.value) },'消息已保存')}
async function finishConsultation(){const {value}=await ElMessageBox.prompt('可选：转科或专科建议','结束问诊');stopMessageSync();await stopCall();await safely(async()=>{activeConsultation.value=(await api.closeConsultation(activeConsultation.value.id,value)).data;await loadConsultations()},'问诊已归档')}
function attachRemoteVideo(id,element){if(element&&remoteStreams.value[id]&&element.srcObject!==remoteStreams.value[id])element.srcObject=remoteStreams.value[id]}
function peerFor(target){if(peers.has(target))return peers.get(target);const configured=String(import.meta.env.VITE_WEBRTC_ICE_SERVERS||'').split(',').map(x=>x.trim()).filter(Boolean).map(urls=>({urls}));const pc=new RTCPeerConnection({iceServers:configured});if(localStream)localStream.getTracks().forEach(track=>pc.addTrack(track,localStream));pc.onicecandidate=e=>{if(e.candidate)api.sendConsultationSignal(activeConsultation.value.id,{targetUserId:target,signalType:'ICE',payload:e.candidate.toJSON()})};pc.ontrack=e=>{remoteStreams.value={...remoteStreams.value,[target]:e.streams[0]}};pc.onconnectionstatechange=()=>{if(['failed','closed','disconnected'].includes(pc.connectionState)){const next={...remoteStreams.value};delete next[target];remoteStreams.value=next}};peers.set(target,pc);return pc}
async function startCall(){if(!activeConsultation.value||activeConsultation.value.mode==='TEXT')return;try{localStream=await navigator.mediaDevices.getUserMedia({audio:true,video:activeConsultation.value.mode==='VIDEO'});callActive.value=true;await nextTick();if(localVideo.value)localVideo.value.srcObject=localStream;const others=(activeConsultation.value.participants||[]).map(x=>Number(x.user_id)).filter(x=>x!==currentUserId);for(const target of others){const pc=peerFor(target),offer=await pc.createOffer();await pc.setLocalDescription(offer);await api.sendConsultationSignal(activeConsultation.value.id,{targetUserId:target,signalType:'OFFER',payload:offer})}signalTimer=window.setInterval(pollSignals,1200);await pollSignals()}catch{callActive.value=false;ElMessage.error('无法启动摄像头或麦克风，请检查浏览器权限。')}}
async function pollSignals(){if(!callActive.value||!activeConsultation.value)return;try{const rows=(await api.listConsultationSignals(activeConsultation.value.id,lastSignalId)).data||[];for(const row of rows){lastSignalId=Math.max(lastSignalId,Number(row.id));const sender=Number(row.sender_user_id),pc=peerFor(sender),payload=typeof row.payload_json==='string'?JSON.parse(row.payload_json||'{}'):row.payload_json;if(row.signal_type==='OFFER'){await pc.setRemoteDescription(payload);for(const ice of pendingIce.get(sender)||[])await pc.addIceCandidate(ice);pendingIce.delete(sender);const answer=await pc.createAnswer();await pc.setLocalDescription(answer);await api.sendConsultationSignal(activeConsultation.value.id,{targetUserId:sender,signalType:'ANSWER',payload:answer})}else if(row.signal_type==='ANSWER'){await pc.setRemoteDescription(payload);for(const ice of pendingIce.get(sender)||[])await pc.addIceCandidate(ice);pendingIce.delete(sender)}else if(row.signal_type==='ICE'){if(pc.remoteDescription)await pc.addIceCandidate(payload);else pendingIce.set(sender,[...(pendingIce.get(sender)||[]),payload])}else if(row.signal_type==='HANGUP'){pc.close();peers.delete(sender)}}}catch{}}
async function stopCall(){if(signalTimer){clearInterval(signalTimer);signalTimer=null}if(activeConsultation.value)for(const target of peers.keys())api.sendConsultationSignal(activeConsultation.value.id,{targetUserId:target,signalType:'HANGUP',payload:{}}).catch(()=>{});peers.forEach(pc=>pc.close());peers.clear();pendingIce.clear();if(localStream)localStream.getTracks().forEach(track=>track.stop());localStream=null;remoteStreams.value={};callActive.value=false;lastSignalId=0}
async function loadRecovery(){if(!currentPatientId.value)return;plans.value=(await api.listTreatmentPlans(pid())).data||[];rehabRows.value=(await api.listRehabCheckins(pid())).data||[]}
async function createPlan(){await safely(async()=>{await api.saveTreatmentPlan({...plan,patientId:pid(),plan:{instructions:planText.value}});plan.title='';planText.value='';await loadRecovery()})}
async function checkinRehab(){await safely(async()=>{await api.saveRehabCheckin({...rehab,patientId:pid(),data:{observation:rehabText.value}});rehabText.value='';await loadRecovery()})}
function prettyJson(value){try{return JSON.stringify(typeof value==='string'?JSON.parse(value):value,null,2)}catch{return value}}
async function loadEmergencyCard(){if(!currentPatientId.value)return;emergencyCard.value=(await api.getEmergencyCard(pid())).data;localStorage.setItem(`offlineEmergencyCard:${pid()}`,JSON.stringify(emergencyCard.value))}
async function sos(){await ElMessageBox.confirm('这会向绑定的照护联系人发送您的位置和紧急医疗信息，是否继续？','紧急呼救',{confirmButtonText:'立即发送',type:'warning'});if(navigator.geolocation)await new Promise(resolve=>navigator.geolocation.getCurrentPosition(p=>{emergency.latitude=p.coords.latitude;emergency.longitude=p.coords.longitude;resolve()},()=>resolve(),{timeout:5000}));await safely(async()=>{await api.triggerEmergency({...emergency,patientId:pid()})},'紧急通知已发送')}
async function saveSpecial(type,data){await safely(async()=>{await api.saveSpecialty(type,{...data,patientId:pid()})})}
async function saveMaternity(){await saveSpecial('maternity',{...maternity,data:{details:maternityText.value}})}
async function loadMental(){if(!currentPatientId.value)return;mentalRows.value=(await api.listMentalAssessments(pid())).data||[]}
async function submitMental(){const answers=mentalAnswers.value.split(',').map(x=>Number(x.trim())).filter(Number.isFinite);await safely(async()=>{await api.saveMentalAssessment({...mental,patientId:pid(),answers,familyVisibility:mentalVisible.value?'VISIBLE':'PRIVATE'});mentalAnswers.value='';await loadMental()})}
async function scheduleMental(){await safely(async()=>{await api.saveMentalSchedule({...mentalSchedule,patientId:pid(),familyVisibility:mentalVisible.value?'VISIBLE':'PRIVATE'})},'量表推送计划已设置')}
async function loadGrants(){if(!currentPatientId.value)return;grants.value=(await api.listAccessGrants(pid())).data||[]}
async function createGrant(){await safely(async()=>{await api.saveAccessGrant({...grant,patientId:pid()});await loadGrants()},'授权已生效')}
async function revoke(row){await safely(async()=>{await api.revokeAccessGrant(row.id);await loadGrants()},'授权已撤销')}
async function createSchedule(){await safely(async()=>{await api.saveDoctorSchedule({...schedule})},'可预约时段已添加')}
async function createGroup(){await safely(async()=>{await api.savePatientGroup({...group});group.groupName='';group.description='';groups.value=(await api.listPatientGroups()).data||[]})}
async function addToGroup(row){await safely(async()=>{await api.addPatientToGroup(row.id,pid());groups.value=(await api.listPatientGroups()).data||[]},'患者已加入分组')}
async function loadOperations(){operations.value=(await api.getOperationsReport({})).data;groups.value=(await api.listPatientGroups()).data||[]}
async function loadTab(){if(!clinicians.value.length)clinicians.value=(await api.listClinicians()).data||[];const loaders={measurements:loadMeasurements,appointments:loadAppointments,consultation:loadConsultations,recovery:loadRecovery,emergency:async()=>{const cached=localStorage.getItem(`offlineEmergencyCard:${currentPatientId.value}`);if(cached)emergencyCard.value=JSON.parse(cached);await loadEmergencyCard()},mental:loadMental,privacy:loadGrants,operations:loadOperations};if(loaders[tab.value])await loaders[tab.value]()}
watch(currentPatientId,async()=>{stopMessageSync();await stopCall();activeConsultation.value=null;loadTab()});onMounted(loadTab);onBeforeUnmount(()=>{stopMessageSync();stopCall()})
</script>

<style scoped>
.journey-page{max-width:1500px;margin:auto;padding:26px}.journey-hero{display:flex;justify-content:space-between;gap:24px;align-items:center;padding:28px;border:1px solid #dce9e4;border-radius:20px;background:linear-gradient(120deg,#eef7f3,#fff);margin-bottom:22px}.journey-hero span{font-size:11px;letter-spacing:2px;color:#247568;font-weight:700}.journey-hero h1{margin:8px 0;font-size:32px}.journey-hero p{margin:0;max-width:820px;color:#637a75}.journey-tabs{background:#fff;border:1px solid #e1ebe7;border-radius:18px;padding:18px}.panel-grid{display:grid;gap:18px}.panel-grid.two{grid-template-columns:repeat(2,minmax(0,1fr))}.panel-grid.three{grid-template-columns:repeat(3,minmax(0,1fr))}.section-card{margin-top:18px}.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0 14px}.card-head,.message-compose,.inline{display:flex;align-items:center;justify-content:space-between;gap:12px}.realtime-state{display:inline-flex;align-items:center;gap:6px;margin-left:12px;color:#238066;font-size:11px;font-weight:600}.realtime-state i{width:8px;height:8px;border-radius:50%;background:#31af7d;box-shadow:0 0 0 4px #31af7d20}.message-list{display:grid;gap:10px;max-height:360px;overflow:auto;scroll-behavior:smooth}.message-list article{padding:12px;border:1px solid #e4ece9;border-radius:12px}.message-list article span{float:right;color:#81928d;font-size:12px}.message-list article p{margin:6px 0 0}.message-compose{margin-top:14px}.message-compose .el-input{flex:1}.media-room{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px;margin-bottom:18px;padding:12px;border-radius:14px;background:#173a36}.media-room video{width:100%;min-height:160px;max-height:320px;object-fit:cover;border-radius:10px;background:#0e2421}.media-room p{color:#d7e6e1;padding:20px}.emergency-card{border-color:#efb4aa}.emergency-card .el-input{margin:14px 0}.metric-cards{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.metric-cards article{padding:20px;border-radius:14px;background:#f2f7f5}.metric-cards span,.metric-cards strong{display:block}.metric-cards strong{font-size:26px;margin-top:8px}.inline-form{display:flex;align-items:end;gap:12px;flex-wrap:wrap}.inline-form .el-form-item{min-width:180px;margin-bottom:10px}pre{white-space:pre-wrap}.el-select,.el-date-editor{width:100%}@media(max-width:900px){.panel-grid.two,.panel-grid.three,.metric-cards{grid-template-columns:1fr 1fr}}@media(max-width:650px){.journey-page{padding:14px}.journey-hero{align-items:flex-start;flex-direction:column;padding:20px}.journey-tabs{padding:10px}.panel-grid.two,.panel-grid.three,.metric-cards,.form-grid{grid-template-columns:1fr}.message-compose{align-items:stretch;flex-direction:column}.inline{align-items:stretch;flex-direction:column}.media-room{grid-template-columns:1fr}}
</style>
