const exact = {
  success: '成功',
  'Saved successfully': '保存成功',
  'Failed to save': '保存失败',
  'Updated successfully': '更新成功',
  'Update failed': '更新失败',
  'Deleted successfully': '删除成功',
  'Failed to delete': '删除失败',
  'Created successfully': '创建成功',
  'Operation completed': '操作成功',
  'Operation failed': '操作失败',
  'Not signed in': '尚未登录',
  'User not found': '用户不存在',
  'Role not found': '角色不存在',
  'Permission denied': '没有执行此操作的权限',
  'Select a patient': '请选择患者',
  'Invalid request parameter.': '请求参数无效。',
  'The record does not exist.': '记录不存在。',
  'The patient does not exist.': '患者不存在。',
  'The alert does not exist.': '提醒不存在。',
  'Medication not found': '药品不存在',
  'Medication list cannot be empty': '药品列表不能为空',
  'No data': '暂无数据',
  'No plan': '暂无计划',
  'Normal': '正常',
  'Critical': '严重异常',
  'Needs attention': '需要关注',
  'Data overdue': '数据延迟',
  'In progress': '进行中',
  'All completed': '全部完成',
  'Overdue tasks': '存在逾期任务',
  'Awaiting health data': '等待健康数据',
  'Health status is stable': '当前状态稳定',
  'Items need attention': '存在待处理事项',
  'Immediate attention required': '需要立即关注',
  'Blood pressure': '血压监测',
  'Blood glucose': '血糖监测',
  'Dialysis monitoring': '透析监测',
  "Today's medications": '今日用药',
  'Awaiting the first measurement': '等待首次测量',
  'Awaiting the first record': '等待首次记录',
  'No medication tasks are scheduled for today': '今日未安排用药任务',
  'No updates': '暂无更新',
  'Review and document the clinical response': '复核并记录临床处置情况',
  'Confirm taken, snooze, or record the reason': '确认已服、稍后提醒或记录原因',
  'Complete, reassign, or document why it is deferred': '完成任务、重新指派或记录延期原因',
  'Imported record needs review': '导入记录需要审核',
  'Low-confidence recognition': '识别置信度较低',
  'Record context is incomplete': '记录上下文不完整',
  'Possible duplicate imported records': '可能存在重复导入记录',
  'Dialysis quality fields are incomplete': '透析质量字段不完整',
  'AI analysis draft needs clinical review': 'AI 分析草稿需要临床审核',
  'Possible duplicate therapy': '可能存在重复用药',
  'Confirm whether both active entries are intended.': '请确认这两条启用记录是否均为预期医嘱。',
  'Medication matches the recorded allergy list': '药品与已记录的过敏清单匹配',
  'Do not change treatment in the app; contact the prescribing clinician or pharmacist promptly.': '请勿在平台内自行变更治疗方案，应尽快联系开方医生或药师。',
  'Renal-dose/renal-safety review suggested': '建议复核肾功能剂量与用药安全',
  'NSAIDs may be unsuitable in advanced kidney disease; verify the prescriber plan.': 'NSAIDs 可能不适合晚期肾病患者，请核实开方方案。',
  'Potential medication interaction': '潜在药物相互作用',
  'Screening is decision support only. A clinician or pharmacist must confirm every medication change.': '筛查结果仅用于辅助决策，任何用药变更都必须由医生或药师确认。',
  'Thresholds are screening cues, not treatment targets. The dialysis team must interpret them in clinical context.': '阈值仅用于风险筛查，并非治疗目标；应由透析团队结合临床情况解读。',
  'For emergency communication only. Verify identity, medication list, and allergies with the patient or treating team.': '仅用于急救沟通。请与患者或诊疗团队核验身份、用药清单和过敏史。',
  'A critical reading was detected. Repeat the measurement now and contact a clinician promptly if symptoms are present.': '存在严重异常，请立即复测；如伴随明显不适，请按医嘱联系医生或及时就医。',
  'No recent blood pressure record is available. Consider taking one resting measurement.': '暂无近期血压记录，建议在静息状态下测量一次。',
  'The latest blood-pressure reading is outside the usual range. Rest, repeat the measurement, and continue recording results.': '最近血压超出常用范围，建议休息后复测并持续记录。',
  'No recent blood glucose record is available. Add one if it is part of the care plan.': '暂无近期血糖记录；如照护计划包含血糖监测，请补充一次。',
  'Monitoring coverage is limited. Regular entries will make trend assessments more reliable.': '当前监测数据覆盖不足，持续记录后趋势判断会更可靠。',
  'No urgent items are present. Continue recording measurements, medications, and follow-up visits as planned.': '当前没有紧急事项，请继续按计划记录、用药和复查。',
  Workspace: '健康概览',
  'Patient Center': '患者中心',
  'Patient Profiles': '患者档案',
  'Care Plan': '家庭照护',
  'Care Journey': '健康照护全流程',
  'Dialysis Management': '透析管理',
  'Dialysis Records': '透析记录',
  'Trend Analysis': '趋势分析',
  'Dry Weight Management': '干体重管理',
  'AI Health Analytics': 'AI 健康分析',
  'Dialysis Schedule': '透析计划',
  'Medical Records': '临床档案',
  'Record List': '记录列表',
  'Upload Report': '上传报告',
  'Abnormal Results': '异常结果',
  'Result Trends': '结果趋势',
  'Medication Management': '用药管理',
  'Medication List': '药品列表',
  'Medication Log': '用药记录',
  medicationrecord: '用药记录',
  'Medication Reminders': '用药提醒',
  'Health Monitoring': '健康监测',
  'Blood Pressure & Glucose': '血压与血糖',
  'Complication Tracking': '并发症跟踪',
  complicationrecord: '并发症记录',
  'Health Alerts': '健康告警',
  'Nutrition Diary': '营养日记',
  'Nutrition Assessment': '营养评估',
  'Analytics & Reports': '分析与报告',
  'Blood Pressure Pattern Analysis': '血压模式分析',
  'Blood GlucoseBlood Pressurerecord': '血压血糖记录',
  'Health Report': '健康报告',
  'Data Export': '数据导出',
  'System Administration': '系统管理',
  'User Management': '用户管理',
  'Role Management': '角色管理',
  'Menu Management': '菜单管理',
  'Notification Settings': '通知设置',
  'Audit Log': '审计日志',
  'Clinical Workbench': '临床工作台',
  'Doctor Workspace': '医生工作台',
  Administrator: '系统管理员',
  'Standard User': '普通用户',
  Doctor: '医生',
  Patient: '患者',
  'Family Caregiver': '家庭照护者',
  'Platform Branding': '平台品牌',
  'kg weight gain': 'kg 增重',
  'Dialysisschedule': '透析计划',
  'by timemedication intake': '按时服药',
  'DeletedMedication': '已删除药品',
  doses: '次',
  'Replenish stock or revise the active prescription': '请补充库存或修订当前处方。',
  'Average interdialytic weight gain is above 4% of target dry weight.': '平均透析间期体重增幅超过目标干体重的 4%。',
  'Average ultrafiltration rate is above 13 mL/kg/hour.': '平均超滤率超过 13 mL/kg/小时。',
  'Average recorded Kt/V is below 1.2.': '已记录的平均 Kt/V 低于 1.2。',
  'Average recorded URR is below 65%.': '已记录的平均 URR 低于 65%。',
  'Date missing': '缺少日期',
  'Facility missing': '缺少医疗机构'
}

const patterns = [
  [/^Failed to save: /, '保存失败：'],
  [/^Update failed: /, '更新失败：'],
  [/^Failed to load: /, '加载失败：'],
  [/^Failed to read file: /, '读取文件失败：'],
  [/^Failed to parse file: /, '解析文件失败：'],
  [/^Unsupported data type: /, '不支持的数据类型：'],
  [/^Unsupported file format: /, '不支持的文件格式：'],
  [/^Notification delivery failed: /, '通知发送失败：'],
  [/^Remaining /, '剩余 '],
  [/^Low medication stock · /, '药品库存不足 · '],
  [/^Pre-dialysis Weight\s*/i, '透析前体重 '],
  [/;\s*Post-dialysis Weight\s*/i, '；透析后体重 '],
  [/^(\d{4}-\d{2}) Monthly overview$/i, '$1 月度概览'],
  [/^(\d{4}) Year(?:level)?overview$/i, '$1 年度概览'],
  [/^(\d{4}-W\d{1,2}) (?:when week|Weekly )?overview$/i, '$1 周概览'],
  [/^(\d+) sessions include a vascular-access concern\.$/i, '$1 次透析记录存在血管通路风险。'],
  [/^(.+) · PENDING$/i, '$1 · 待处理'],
  [/^(.+) · MISSED$/i, '$1 · 已漏服'],
  [/^(.+) · SNOOZED$/i, '$1 · 已延后'],
  [/^(\d+) pending$/i, '$1 项待处理'],
  [/^Based on today's plan$/i, '依据今日计划']
]

export function localizeServerText(value) {
  if (typeof value !== 'string') return value
  if (exact[value]) return exact[value]
  let localized = value
  for (const [pattern, replacement] of patterns) {
    localized = localized.replace(pattern, replacement)
  }
  return localized
}

export function localizePayload(value, seen = new WeakSet()) {
  if (typeof value === 'string') return localizeServerText(value)
  if (!value || typeof value !== 'object' || value instanceof Blob || value instanceof ArrayBuffer) return value
  if (seen.has(value)) return value
  seen.add(value)
  if (Array.isArray(value)) return value.map(item => localizePayload(item, seen))
  for (const key of Object.keys(value)) value[key] = localizePayload(value[key], seen)
  return value
}
