const exact = {
  'You do not have access to this patient or action.': '您无权访问当前患者或执行此操作。',
  "Invalid access grant.": "授权角色或访问级别无效。",
  "The record owner already has full access.": "患者档案所有者已拥有完整访问权限，无需重复授权。",
  "The selected user does not exist or is disabled.": "所选用户不存在或已被停用。",
  "Access expiry must be in the future.": "授权到期时间必须晚于当前时间。",
  "Only the patient or guardian owner can manage access.": "只有患者本人或档案所属监护人可以管理授权。",
  "Access to this module has not been authorized by the patient.": "患者尚未授权您访问此模块。",
  "Clinician access is required.": "此操作需要医生权限。",
  "You can only manage your own schedule.": "您只能管理自己的医生排班。",
  "End time must be after start time.": "结束时间必须晚于开始时间。",
  "The slot length must fit inside the clinician availability.": "预约时段长度不能超出医生排班范围。",
  "A valid appointment time is required.": "请填写有效的预约开始和结束时间。",
  "Follow-up interval must be between 0 and 3650 days.": "复诊周期必须在 0 到 3650 天之间。",
  "The selected clinician availability is no longer available.": "所选医生排班已不可预约，请重新选择。",
  "The appointment must fit inside the selected clinician availability.": "预约起止时间必须处于所选医生的排班范围内。",
  "The clinician time slot is already occupied.": "医生的这个时段已被预约，请选择其他时段。",
  "Appointment not found.": "预约记录不存在。",
  "Only a booked appointment can be cancelled.": "只能取消已预约的就诊。",
  "Only a booked appointment can be completed.": "只能将已预约的就诊标记为完成。",
  "Only the selected clinician can complete this appointment.": "仅本次预约医生可完成就诊。",
  "Appointment not found for this patient.": "当前患者不存在此预约记录。",
  "Enter a diagnosis or treatment summary.": "请填写诊断或治疗小结。",
  "Visit record not found.": "就诊记录不存在。",
  "Visit record not found for this patient.": "当前患者不存在此就诊记录。",
  "Add at least one prescription item.": "请至少添加一项处方药品。",
  "Invalid prescription item.": "处方药品信息无效。",
  "Prescription duration must be between 1 and 3650 days.": "用药疗程必须在 1 到 3650 天之间。",
  "Invalid rehabilitation record type.": "康复记录类型无效。",
  "Treatment plan not found for this patient.": "当前患者不存在此治疗计划。",
  "Completion must be between 0 and 100.": "完成度必须在 0 到 100 之间。",
  "Unsupported specialty record type.": "不支持所选专项健康记录类型。",
  "Assessment interval must be between 1 and 3650 days.": "量表推送间隔必须在 1 到 3650 天之间。",
  "You can only manage your own groups.": "您只能管理自己创建的患者分组。",
  "Group access denied.": "您无权访问此患者分组。",
  "The end date must not precede the start date.": "结束日期不能早于开始日期。",
  "Patient not found.": "患者不存在。",
  "Measurement value is required.": "请填写指标数值。",
  "Blood pressure is outside the accepted input range.": "血压数值超出允许录入范围，请核对后重试。",
  "SpO2 must be between 0 and 100.": "血氧饱和度必须在 0 到 100 之间。",
  "The record was not created.": "记录创建失败，请重试。",
  "Enter a valid date and time.": "请输入有效的日期和时间。",
  "Enter a valid date.": "请输入有效的日期。",
  "Annotation is required.": "请填写医生标注内容。",
  success: '成功',
  'Saved successfully': '保存成功',
  'Failed to save': '保存失败',
  'Updated successfully': '更新成功',
  'Update failed': '更新失败',
  'Deleted successfully': '删除成功',
  'Failed to delete': '删除失败',
  'Created successfully': '创建成功',
  'Operation completed': '操作成功',
  'Operation failed': '操作失败',
  'Not signed in': '尚未登录',
  'User not found': '用户不存在',
  'Role not found': '角色不存在',
  'Permission denied': '没有执行此操作的权限',
  'Access denied': '无权访问此功能',
  'Only administrators can view menu configuration': '只有管理员可以查看菜单配置',
  'Built-in platform roles cannot be deleted': '平台内置角色不能删除',
  'Platform administration menus can only belong to the administrator role': '平台管理菜单只能授予管理员角色',
  'Test message sent. Check the receiving channel.': '测试消息已发送，请在接收端查看。',
  'Test failed. Check the webhook address, receiver, and network.': '测试发送失败，请检查 Webhook 地址、接收端和网络。',
  'Select a patient': '请选择患者',
  'Select an active doctor for the consultation.': '请选择当前可接诊的医生。',
  'Only invited consultation participants can send messages or join calls.': '只有本次问诊中受邀的参与者可以发送消息或加入通话。',
  'Only the patient, initiating caregiver, or selected doctor can close this consultation.': '只有患者、发起问诊的照护者或接诊医生可以结束本次问诊。',
  'Only a doctor can provide referral advice.': '转科建议只能由医生填写。',
  'The attachment does not belong to this patient.': '该附件不属于本次问诊的患者。',
  'Select a patient medical record to attach.': '请选择要共享的患者医疗记录。',
  'The shared attachment is not available. Ask the sender to upload it again.': '共享附件暂时无法读取，请联系发送者重新上传。',
  'Signal target is not another consultation participant.': '通话对象必须是本次问诊的其他参与者。',
  'The call signal is too large.': '通话连接数据过大，请重新加入通话。',
  'Invalid consultation status.': '问诊状态无效。',
  'Invalid family visibility.': '家属可见性设置无效。',
  'Invalid consultation mode.': '问诊方式无效。',
  'Unsupported consultation mode.': '不支持所选问诊方式。',
  'Invalid signal type.': '通话连接数据类型无效。',
  'This consultation is private and is not visible to family caregivers.': '本次问诊为私密问诊，家属无法查看。',
  'Invalid message type.': '消息类型无效。',
  'Consultation is closed.': '本次问诊已结束，无法继续发送消息或加入通话。',
  'Consultation not found.': '问诊记录不存在。',
  'Authentication is required.': '请先登录后再进行此操作。',
  'Unsupported assessment scale.': '不支持所选评估量表。',
  'Blood glucose unit must be mmol/L or mg/dL.': '血糖单位必须为 mmol/L 或 mg/dL。',
  'Assessment answers must be an array of item scores.': '请按题目顺序填写量表各题得分。',
  'Assessment item scores must be whole numbers.': '量表各题得分必须是整数。',
  'Invalid request parameter.': '请求参数无效。',
  'The record does not exist.': '记录不存在。',
  'The patient does not exist.': '患者不存在。',
  'The alert does not exist.': '提醒不存在。',
  'Medication not found': '药品不存在',
  'Medication list cannot be empty': '药品列表不能为空',
  'No data': '暂无数据',
  'No plan': '暂无计划',
  'Normal': '正常',
  'Critical': '严重异常',
  'Needs attention': '需要关注',
  'Data overdue': '数据延迟',
  'In progress': '进行中',
  'All completed': '全部完成',
  'Overdue tasks': '存在逾期任务',
  'Awaiting health data': '等待健康数据',
  'Health status is stable': '当前状态稳定',
  'Items need attention': '存在待处理事项',
  'Immediate attention required': '需要立即关注',
  'Blood pressure': '血压监测',
  'Blood glucose': '血糖监测',
  'Dialysis monitoring': '透析监测',
  "Today's medications": '今日用药',
  'Awaiting the first measurement': '等待首次测量',
  'Awaiting the first record': '等待首次记录',
  'No medication tasks are scheduled for today': '今日未安排用药任务',
  'No updates': '暂无更新',
  'Review and document the clinical response': '复核并记录临床处置情况',
  'Confirm taken, snooze, or record the reason': '确认已服、稍后提醒或记录原因',
  'Complete, reassign, or document why it is deferred': '完成任务、重新指派或记录延期原因',
  'Imported record needs review': '导入记录需要审核',
  'Low-confidence recognition': '识别置信度较低',
  'Record context is incomplete': '记录上下文不完整',
  'Possible duplicate imported records': '可能存在重复导入记录',
  'Dialysis quality fields are incomplete': '透析质量字段不完整',
  'AI analysis draft needs clinical review': 'AI 分析草稿需要临床审核',
  'Possible duplicate therapy': '可能存在重复用药',
  'Confirm whether both active entries are intended.': '请确认这两条启用记录是否均为预期医嘱。',
  'Medication matches the recorded allergy list': '药品与已记录的过敏清单匹配',
  'Do not change treatment in the app; contact the prescribing clinician or pharmacist promptly.': '请勿在平台内自行变更治疗方案，应尽快联系开方医生或药师。',
  'Renal-dose/renal-safety review suggested': '建议复核肾功能剂量与用药安全',
  'NSAIDs may be unsuitable in advanced kidney disease; verify the prescriber plan.': 'NSAIDs 可能不适合晚期肾病患者，请核实开方方案。',
  'Potential medication interaction': '潜在药物相互作用',
  'Screening is decision support only. A clinician or pharmacist must confirm every medication change.': '筛查结果仅用于辅助决策，任何用药变更都必须由医生或药师确认。',
  'Thresholds are screening cues, not treatment targets. The dialysis team must interpret them in clinical context.': '阈值仅用于风险筛查，并非治疗目标；应由透析团队结合临床情况解读。',
  'For emergency communication only. Verify identity, medication list, and allergies with the patient or treating team.': '仅用于急救沟通。请与患者或诊疗团队核验身份、用药清单和过敏史。',
  'A critical reading was detected. Repeat the measurement now and contact a clinician promptly if symptoms are present.': '存在严重异常，请立即复测；如伴随明显不适，请按医嘱联系医生或及时就医。',
  'No recent blood pressure record is available. Consider taking one resting measurement.': '暂无近期血压记录，建议在静息状态下测量一次。',
  'The latest blood-pressure reading is outside the usual range. Rest, repeat the measurement, and continue recording results.': '最近血压超出常用范围，建议休息后复测并持续记录。',
  'No recent blood glucose record is available. Add one if it is part of the care plan.': '暂无近期血糖记录；如照护计划包含血糖监测，请补充一次。',
  'Monitoring coverage is limited. Regular entries will make trend assessments more reliable.': '当前监测数据覆盖不足，持续记录后趋势判断会更可靠。',
  'No urgent items are present. Continue recording measurements, medications, and follow-up visits as planned.': '当前没有紧急事项，请继续按计划记录、用药和复查。',
  Workspace: '健康概览',
  'Patient Center': '患者中心',
  'Patient Profiles': '患者档案',
  'Care Plan': '家庭照护',
  'Care Journey': '健康照护全流程',
  'Dialysis Management': '透析管理',
  'Dialysis Records': '透析记录',
  'Trend Analysis': '趋势分析',
  'Dry Weight Management': '干体重管理',
  'AI Health Analytics': 'AI 健康分析',
  'Dialysis Schedule': '透析计划',
  'Medical Records': '临床档案',
  'Record List': '记录列表',
  'Upload Report': '上传报告',
  'Abnormal Results': '异常结果',
  'Result Trends': '结果趋势',
  'Medication Management': '用药管理',
  'Medication List': '药品列表',
  'Medication Log': '用药记录',
  medicationrecord: '用药记录',
  'Medication Reminders': '用药提醒',
  'Health Monitoring': '健康监测',
  'Blood Pressure & Glucose': '血压与血糖',
  'Complication Tracking': '并发症跟踪',
  complicationrecord: '并发症记录',
  'Health Alerts': '健康告警',
  'Nutrition Diary': '营养日记',
  'Nutrition Assessment': '营养评估',
  'Analytics & Reports': '分析与报告',
  'Blood Pressure Pattern Analysis': '血压模式分析',
  'Blood GlucoseBlood Pressurerecord': '血压血糖记录',
  'Health Report': '健康报告',
  'Data Export': '数据导出',
  'System Administration': '系统管理',
  'User Management': '用户管理',
  'Role Management': '角色管理',
  'Menu Management': '菜单管理',
  'Notification Settings': '通知设置',
  'Audit Log': '审计日志',
  'Clinical Workbench': '临床工作台',
  'Doctor Workspace': '医生工作台',
  Administrator: '系统管理员',
  'Standard User': '普通用户',
  Doctor: '医生',
  Patient: '患者',
  'Family Caregiver': '家庭照护者',
  'Platform Branding': '平台品牌',
  'kg weight gain': 'kg 增重',
  'Dialysisschedule': '透析计划',
  'by timemedication intake': '按时服药',
  'DeletedMedication': '已删除药品',
  doses: '次',
  'Replenish stock or revise the active prescription': '请补充库存或修订当前处方。',
  'Average interdialytic weight gain is above 4% of target dry weight.': '平均透析间期体重增幅超过目标干体重的 4%。',
  'Average ultrafiltration rate is above 13 mL/kg/hour.': '平均超滤率超过 13 mL/kg/小时。',
  'Average recorded Kt/V is below 1.2.': '已记录的平均 Kt/V 低于 1.2。',
  'Average recorded URR is below 65%.': '已记录的平均 URR 低于 65%。',
  'Date missing': '缺少日期',
  'Facility missing': '缺少医疗机构'
}

const patterns = [
  [/^The entered text is too long \(maximum (\d+) characters\)\.$/, '输入内容过长，最多允许 $1 个字符。'],
  [/^Measurement unit must be (.+) for (.+)\.$/, '$2 指标的单位必须为 $1。'],
  [/^(PHQ9|GAD7|WHO5) requires (\d+) item scores\.$/, '$1 需要填写 $2 题得分。'],
  [/^(PHQ9|GAD7|WHO5) item scores must be between 0 and (\d+)\.$/, '$1 各题得分必须在 0 到 $2 之间。'],
  [/^Failed to save: /, '保存失败：'],
  [/^Update failed: /, '更新失败：'],
  [/^Failed to load: /, '加载失败：'],
  [/^Failed to read file: /, '读取文件失败：'],
  [/^Failed to parse file: /, '解析文件失败：'],
  [/^Unsupported data type: /, '不支持的数据类型：'],
  [/^Unsupported file format: /, '不支持的文件格式：'],
  [/^Notification delivery failed: /, '通知发送失败：'],
  [/^Remaining /, '剩余 '],
  [/^Low medication stock · /, '药品库存不足 · '],
  [/^Pre-dialysis Weight\s*/i, '透析前体重 '],
  [/;\s*Post-dialysis Weight\s*/i, '；透析后体重 '],
  [/^(\d{4}-\d{2}) Monthly overview$/i, '$1 月度概览'],
  [/^(\d{4}) Year(?:level)?overview$/i, '$1 年度概览'],
  [/^(\d{4}-W\d{1,2}) (?:when week|Weekly )?overview$/i, '$1 周概览'],
  [/^(\d+) sessions include a vascular-access concern\.$/i, '$1 次透析记录存在血管通路风险。'],
  [/^(.+) · PENDING$/i, '$1 · 待处理'],
  [/^(.+) · MISSED$/i, '$1 · 已漏服'],
  [/^(.+) · SNOOZED$/i, '$1 · 已延后'],
  [/^(\d+) pending$/i, '$1 项待处理'],
  [/^Based on today's plan$/i, '依据今日计划']
]

export function localizeServerText(value) {
  if (typeof value !== 'string') return value
  if (exact[value]) return exact[value]
  const fields = { symptom: '症状或咨询问题', content: '消息内容', medicalHistory: '既往史', durationText: '持续时间', patientId: '患者', doctorUserId: '接诊医生', targetUserId: '通话对象', transferAdvice: '转科建议' }
  const required = value.match(/^(\w+) is required\.$/)
  if (required && fields[required[1]]) return fields[required[1]] + '不能为空。'
  const limit = value.match(/^(\w+) exceeds (\d+) characters\.$/)
  if (limit && fields[limit[1]]) return fields[limit[1]] + '不能超过 ' + limit[2] + ' 个字符。'
  let localized = value
  for (const [pattern, replacement] of patterns) {
    localized = localized.replace(pattern, replacement)
  }
  return localized
}

export function localizePayload(value, seen = new WeakSet()) {
  if (typeof value === 'string') return localizeServerText(value)
  if (!value || typeof value !== 'object' || value instanceof Blob || value instanceof ArrayBuffer) return value
  if (seen.has(value)) return value
  seen.add(value)
  if (Array.isArray(value)) return value.map(item => localizePayload(item, seen))
  for (const key of Object.keys(value)) value[key] = localizePayload(value[key], seen)
  return value
}
