(() => {
  const M = window.HealthDemo, zh = document.documentElement.lang.startsWith('zh');
  let state = M.createState(), range = 7, action = null, toastTimer, returnFocus;
  try { const saved=JSON.parse(localStorage.getItem('chengxin-demo-branding')||'null'); if(saved) M.updateBranding(state,saved); } catch {}
  const $ = id => document.getElementById(id), l = value => value && typeof value === 'object' ? value[zh ? 'zh' : 'en'] : value;
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' }[c]));
  const tx = (en, cn) => zh ? cn : en, p = () => M.current(state);
  const copy = {
    doctor: { name:tx('Doctor','医生'), workspace:tx('Clinical workspace','医生工作台'), account:tx('Dr. Sarah Chen','陈医生'), avatar:tx('DR','医'), start:'overview', nav:{ overview:tx('Work overview','工作概览'), consultation:tx('Live consultation','实时问诊'), journey:tx('Care journey','照护全流程'), patients:tx('Patient panel','患者面板'), reviews:tx('Review queue','复核队列'), plans:tx('Care plans','照护计划'), clinical:tx('Clinical workbench','临床工作台'), monitoring:tx('Health overview','健康概览'), dialysis:tx('Dialysis','透析管理'), records:tx('Medical records','医疗记录'), medications:tx('Medications','用药管理'), analytics:tx('Health analytics','健康分析') } },
    patient: { name:tx('Patient','患者'), workspace:tx('My health workspace','我的健康工作台'), account:l(state.patients[0].name), avatar:tx('AZ','患'), start:'today', nav:{ today:tx('Today','今日任务'), consultation:tx('Live consultation','实时问诊'), journey:tx('Care journey','照护全流程'), monitoring:tx('Health overview','健康概览'), vitals:tx('Blood pressure & glucose','血压血糖'), dialysis:tx('Dialysis','透析管理'), dryweight:tx('Dry weight','干体重管理'), medications:tx('Medications','用药管理'), records:tx('Medical records','医疗记录'), analytics:tx('Health analytics','健康分析'), careplan:tx('Care plan','照护计划'), notifications:tx('Notifications','通知设置') } },
    family: { name:tx('Family','家属'), workspace:tx('Family care workspace','家属照护工作台'), account:tx('Wei Zhang','张伟'), avatar:tx('WZ','家'), start:'care', nav:{ care:tx('Care schedule','照护日程'), consultation:tx('Live consultation','实时问诊'), journey:tx('Care journey','照护全流程'), monitoring:tx('Health overview','健康概览'), medications:tx('Medication check-ins','用药打卡'), appointments:tx('Appointments','复诊安排'), handover:tx('Family handover','家庭交接'), records:tx('Shared records','共享档案'), analytics:tx('Alerts & reports','预警与报告'), careplan:tx('Care plan','照护计划'), notifications:tx('Notifications','通知设置') } },
    admin: { name:tx('Admin','管理'), workspace:tx('System administration','系统管理'), account:tx('Platform administrator','平台管理员'), avatar:tx('AD','管'), start:'admin', nav:{ admin:tx('Platform overview','平台概览'), users:tx('User management','用户管理'), roles:tx('Role management','角色管理'), patientadmin:tx('Patient management','患者管理'), menus:tx('Menu management','菜单管理'), branding:tx('Platform branding','平台品牌'), audit:tx('Audit log','审计日志'), notifications:tx('Notification settings','通知设置'), automation:tx('Automated analysis','自动分析'), dataexport:tx('Data export','数据导出') } }
  };
  const guideSteps={
    doctor:[['Understand the workspace','认识工作台','The menu is filtered for clinical work.','菜单已按临床工作筛选。','Scan the highlighted navigation groups.','浏览高亮的导航分组。','#nav','Look here','看这里','Only doctor-authorized pages are visible.','只显示医生已获授权的页面。','Role-based navigation protects patient information.','按角色显示功能可以保护患者信息。'],['Start from clinical priorities','从临床优先事项开始','The overview gathers urgent signals, assigned patients, and review work.','概览集中展示紧急信号、负责患者和复核任务。','Click the highlighted overview entry, then review high-risk items first.','点击高亮的工作概览，再优先处理高风险事项。','Workload totals and the review queue appear.','页面显示工作量汇总和复核队列。','It keeps clinician attention on decisions that need judgement.','让医生优先关注需要专业判断的事项。','[data-page="overview"]','Open this page','打开此页面','overview']],
    patient:[['Understand the workspace','认识工作台','The menu focuses on your measurements, medication, records, and tasks.','菜单集中展示你的测量、用药、档案和任务。','Scan the highlighted navigation groups.','浏览高亮的导航分组。','#nav','Look here','看这里','Only your authorized health pages are visible.','只显示你已获授权的健康页面。','A focused menu makes daily self-management easier.','聚焦的菜单让日常自我管理更简单。'],['Start with today’s care','从今日照护开始','Today combines medication, measurements, appointments, and follow-ups.','今日页面整合用药、测量、预约和随访。','Click the highlighted Today entry and check unfinished tasks.','点击高亮的今日任务并检查未完成事项。','Your care plan and pending actions appear.','页面显示照护计划和待办事项。','Completing the daily list improves care continuity.','完成每日清单可以提高照护连续性。','[data-page="today"]','Start here','从这里开始','today']],
    family:[['Understand the workspace','认识工作台','Your view contains only information shared for family care.','这里只显示已授权给家属的照护信息。','Scan the highlighted navigation groups.','浏览高亮的导航分组。','#nav','Look here','看这里','Shared care pages are visible without private data.','共享照护页面可见，私密数据保持隐藏。','The boundary respects patient privacy.','清晰边界可以保护患者隐私。'],['Coordinate family care','协同家庭照护','The care schedule combines shared tasks and handovers.','照护日程整合共享任务与交接。','Click the highlighted schedule entry and review unfinished work.','点击高亮的照护日程并查看未完成任务。','Medication and measurement tasks appear together.','用药和测量任务集中显示。','Everyone can see what has been done and what remains.','所有照护者都能了解已完成和待完成事项。','[data-page="care"]','Open the schedule','打开日程','care']],
    admin:[['Understand the workspace','认识工作台','Administration is separate from clinical care.','系统管理与临床照护相互分离。','Scan the highlighted administration navigation.','浏览高亮的管理导航。','#nav','Look here','看这里','Only platform administration pages are visible.','只显示平台管理页面。','Separation reduces accidental access to clinical data.','分离管理可减少误访问临床数据。'],['Verify role scope','核对角色范围','Accounts and permissions must be reviewed before a change.','修改账号前必须核对权限。','Click the highlighted user-management entry.','点击高亮的用户管理入口。','The account list and status actions appear.','页面显示账号列表和状态操作。','Least-privilege access protects health information.','最小权限可以保护健康信息。','[data-page="users"]','Review here','在这里核对','users']]
  };
  const guideCommon=[['Open the full care journey','打开照护全流程','This page groups all 40 supported medical workflows.','此页面集中展示全部 40 项医疗流程。','Click the highlighted Care Journey entry.','点击高亮的照护全流程入口。','The ten care sections and their working actions appear.','页面显示十大照护场景及可操作功能。','It is the clearest map of the whole platform.','这是了解整个平台最清晰的地图。','[data-page="journey"]','Explore here','从这里了解','journey'],['Confirm the patient','确认当前患者','Every health action uses the patient selected in the header.','每项健康操作都使用顶部选中的患者。','Open the highlighted selector and verify the name.','打开高亮的选择器并核对姓名。','The selected name remains visible in the header.','选中的姓名持续显示在顶部。','Identity checks prevent wrong-patient records.','核对身份可以避免记录到错误患者。','#patient','Check this name','先核对姓名'],['Know the active account','确认当前账号','The role and account determine what can be seen and changed.','当前角色和账号决定可见及可操作范围。','Confirm the highlighted account name and role.','确认高亮的账号名称和角色。','The account identity matches the selected demo role.','账号身份与演示角色保持一致。','Shared accounts weaken audit traceability.','共用账号会削弱审计追踪能力。','.demo-account','Check this account','核对账号']];
  const guided=(enTitle,cnTitle,enDescription,cnDescription,enAction,cnAction,selector,enGesture,cnGesture,enResult,cnResult,path)=>({title:tx(enTitle,cnTitle),description:tx(enDescription,cnDescription),action:tx(enAction,cnAction),selector,gesture:tx(enGesture,cnGesture),result:tx(enResult,cnResult),path});
  const interactiveGuideSteps={
    doctor:[guided('Review a clinical item','复核一项临床记录','The doctor overview brings pending imported records and AI-assisted summaries into one queue.','医生概览会集中展示待确认的导入记录和 AI 辅助摘要。','Select Approve or Reject only after checking the patient and source.','核对患者与来源后，再点击“通过”或“驳回”。','[data-action="review-approve"]','Use this decision button','操作这个审核按钮','The item leaves the pending queue and an audit event is recorded.','该项目移出待复核队列，并写入审计记录。','overview'),guided('Send a consultation message','发送问诊消息','The consultation room keeps doctor, patient, and family in the same conversation.','问诊室让医生、患者和家属处于同一会话。','Enter a short message here, then use the Send button.','在这里输入简短消息，然后点击“发送消息”。','#chat-form textarea','Type here','在这里输入','The message appears in the transcript and a simulated reply follows.','消息进入会话记录，随后收到模拟回复。','consultation')],
    patient:[guided('Record today’s measurement','记录今日测量','Today’s task list connects each due measurement to its entry workflow.','今日任务会把待测指标直接连接到录入流程。','Select Record on the highlighted blood-pressure task.','点击高亮血压任务上的“记录”。','[data-action="vital"]','Open this action','打开这个操作','A structured blood-pressure form opens for confirmation.','系统打开结构化血压录入表单。','today'),guided('Send a consultation message','发送问诊消息','You can describe symptoms to the doctor while an authorized family member follows the same conversation.','你可以向医生描述症状，已授权家属可同步查看会话。','Enter the symptom or reply in this field, then send it.','在此输入症状或回复，然后发送。','#chat-form textarea','Type here','在这里输入','The message is added to the consultation transcript.','消息会加入问诊记录。','consultation')],
    family:[guided('Complete a shared care task','完成共享照护任务','The family schedule shows unfinished medication and measurement work for the selected person.','家庭日程会显示当前家人未完成的用药和测量任务。','Use the highlighted task button after the care action is actually complete.','照护操作实际完成后，点击高亮的任务按钮。','[data-action="complete"]','Confirm this task','确认这个任务','Every caregiver can see the updated completion state.','所有照护者都能看到更新后的完成状态。','care'),guided('Add a handover','新增照护交接','Handover notes tell the next caregiver exactly what remains.','交接记录会明确告诉下一位照护者还有什么待办。','Open the highlighted handover action and record only necessary care information.','打开高亮的交接操作，只记录必要的照护信息。','[data-action="handover"]','Open handover','打开交接','The note joins the shared family timeline.','记录会进入家庭共享时间线。','care')],
    admin:[guided('Change an account status','调整账号状态','User management separates account status from access to patient data.','用户管理将账号状态与患者数据授权分开。','Use the highlighted status button only after verifying the user and role.','核对用户和角色后，再使用高亮的状态按钮。','[data-action="toggle-user"]','Review this control','核对这个控件','The account status changes and the action is auditable.','账号状态更新，并留下审计记录。','users'),guided('Configure the platform identity','配置平台身份','Brand settings control the name, organization, logo, background, and ownership text.','品牌设置统一管理平台名称、机构、Logo、背景与所有权文字。','Edit the highlighted platform-name field and save the complete form.','修改高亮的平台名称字段，再保存完整表单。','#branding-form input[name="platformName"]','Edit this field','修改这个字段','The new identity is applied across the demo.','新的平台身份会应用到整个演示。','branding')]
  };
  const interactiveGuideCommon=[guided('Run a real feature demonstration','执行真实功能演示','The care journey contains working demonstrations for all supported medical workflows.','照护全流程包含全部医疗场景的可操作演示。','Click the highlighted action to update local state and create an audit event.','点击高亮操作，更新本地状态并生成审计事件。','[data-action="module-action"]','Try this button','试试这个按钮','The card changes to completed and the event appears in the audit log.','卡片变为已执行，事件写入审计日志。','journey'),guided('Confirm the current patient','确认当前患者','Every clinical action uses the patient selected in the header.','每项临床操作都使用顶部选中的患者。','Open this selector and verify the name before recording information.','录入信息前，打开选择器并核对姓名。','#patient','Check this selector','核对这个选择器','The selected patient remains visible throughout the workspace.','当前患者会持续显示在工作台顶部。'),guided('Follow the platform language','跟随平台语言','The guide always uses the same language as the current platform interface.','指引始终使用当前平台界面的语言。','Use this language control when you need to switch the whole demo.','需要切换整个演示语言时，使用这个语言入口。','.language-link','Language follows here','语言跟随这里','The page and every guide step switch together.','页面和每一步指引会同步切换语言。')];
  let guideIndex=0;
  function currentGuide(){return [...interactiveGuideSteps[state.role],...interactiveGuideCommon]}
  function guideMeta(step){return step}
  function positionGuide(target){document.querySelector('.guide-target')?.classList.remove('guide-target');target.classList.add('guide-target');const rect=target.getBoundingClientRect(),card=$('guide-popover'),anchor=$('guide-anchor'),width=Math.min(370,innerWidth-24),height=card.offsetHeight||260,gap=20;let placement,left,top,anchorLeft,anchorTop;if(innerWidth<720){const cardBelow=rect.top<innerHeight/2;placement=cardBelow?'top':'bottom';left=12;top=cardBelow?innerHeight-height-12:12;anchorLeft=rect.left+rect.width/2;anchorTop=cardBelow?rect.bottom:rect.top;}else if(rect.right+gap+width<innerWidth){placement='right';left=rect.right+gap;top=rect.top+rect.height/2-height/2;anchorLeft=rect.right;anchorTop=rect.top+rect.height/2;}else if(rect.left-width-gap>0){placement='left';left=rect.left-width-gap;top=rect.top+rect.height/2-height/2;anchorLeft=rect.left;anchorTop=rect.top+rect.height/2;}else if(rect.bottom+gap+height<innerHeight){placement='top';left=rect.left+rect.width/2-width/2;top=rect.bottom+gap;anchorLeft=rect.left+rect.width/2;anchorTop=rect.bottom;}else{placement='bottom';left=rect.left+rect.width/2-width/2;top=rect.top-height-gap;anchorLeft=rect.left+rect.width/2;anchorTop=rect.top;}card.className=`guide-popover guide-popover--${placement}`;card.style.width=`${width}px`;card.style.setProperty('left',`${Math.max(12,Math.min(left,innerWidth-width-12))}px`,'important');card.style.setProperty('top',`${Math.max(12,Math.min(top,innerHeight-height-12))}px`,'important');Object.assign(anchor.style,{left:`${anchorLeft}px`,top:`${anchorTop}px`});}
  function showGuideStep(){const step=guideMeta(currentGuide()[guideIndex]);if(step.path&&page()!==step.path){location.hash=step.path;render();}$('guide-progress').textContent=tx('GUIDED TOUR','交互指引');$('guide-count').textContent=`${guideIndex+1} / ${currentGuide().length}`;$('guide-title').textContent=step.title;$('guide-description').textContent=step.description;$('guide-action').textContent=step.action;$('guide-result').textContent=step.result;$('guide-gesture').textContent=step.gesture;$('guide-previous').disabled=guideIndex===0;$('guide-next').textContent=guideIndex===currentGuide().length-1?'✓':'›';$('guide-next').setAttribute('aria-label',guideIndex===currentGuide().length-1?tx('Finish guide','完成指引'):tx('Confirm step and continue','确认本步骤并继续'));setTimeout(()=>{const target=document.querySelector(step.selector)||$('content');target.scrollIntoView?.({block:'center',behavior:'smooth'});positionGuide(target)},120);}
  function closeGuide(){$('guide-tour').hidden=true;}
  function openGuide(){guideIndex=0;$('guide-tour').hidden=false;showGuideStep();}
  const button = (label, act, secondary=false, data='') => `<button class="button${secondary?' secondary':''}" data-action="${act}" ${data}>${label}</button>`;
  function toast(message) { const el=$('toast'); el.textContent=message; el.hidden=false; clearTimeout(toastTimer); toastTimer=setTimeout(()=>{el.hidden=true;},3200); }
  function page() { const key=location.hash.slice(1), nav=copy[state.role].nav; return Object.hasOwn(nav,key)?key:copy[state.role].start; }
  function heading(kicker,title,subtitle,art='care-moments-small.webp',actions='') { return `<header class="page-heading"><div><span class="eyebrow">${kicker}</span><h1>${title}</h1><p>${subtitle}</p>${actions?`<div class="heading-actions">${actions}</div>`:''}</div><img class="heading-art" src="assets/${art}" alt="" width="180" height="120"></header>`; }
  function risk(value) { return `<span class="tag risk-${value}">${value==='critical'?tx('Needs review','需关注'):value==='watch'?tx('Watch','观察'):tx('Stable','稳定')}</span>`; }
  function stats() { const latest=p().records.at(-1), done=p().tasks.filter(t=>t.done).length, pending=state.reviews.filter(r=>r.status==='pending').length; return `<section class="stats"><article><span>${tx('Today’s tasks','今日任务')}</span><strong>${done}<small> / ${p().tasks.length}</small></strong><p>${tx('Care plan progress','照护计划进度')}</p></article><article><span>${tx('Latest blood pressure','最近血压')}</span><strong>${latest.systolic}<small> / ${latest.diastolic}</small></strong><p>mmHg · ${latest.date}</p></article><article><span>${tx('Pending clinical reviews','待临床复核')}</span><strong>${pending}<small> ${tx('items','项')}</small></strong><p>${tx('Records and AI summaries','记录与 AI 摘要')}</p></article><article><span>${tx('Next appointment','下次复诊')}</span><strong>${state.appointments[0].date.slice(5)}<small> ${state.appointments[0].time}</small></strong><p>${l(state.appointments[0].clinic)}</p></article></section>`; }
  function tasks(filter) { const rows=p().tasks.filter(t=>!filter||t.type===filter); return `<div class="task-list">${rows.map(t=>`<article class="task ${t.done?'done':''}"><span class="time">${t.time}</span><span class="task-mark">${t.done?'✓':'◷'}</span><div class="task-copy"><b>${l(t.title)}</b><small>${l(t.detail)}</small></div>${t.done?`<span class="tag">${tx('Completed','已完成')}</span>`:button(t.type==='medication'?tx('Mark taken','标记已服'):t.type==='vital'?tx('Record','记录'):tx('Complete','完成'),t.type==='vital'?'vital':'complete',true,`data-id="${t.id}"`)}</article>`).join('')}</div>`; }
  function chart() { const rows=p().records.slice(-range), x=i=>48+i*610/Math.max(1,rows.length-1), y=v=>210-(v-50)/110*175, line=k=>rows.map((r,i)=>`${x(i)},${y(r[k])}`).join(' '); return `<div class="chart-legend"><span>● ${tx('Systolic','收缩压')}</span><span>● ${tx('Diastolic','舒张压')}</span><small>mmHg · ${tx('fictional data','虚构数据')}</small></div><svg class="chart" viewBox="0 0 700 240" role="img" aria-label="${tx('Blood pressure trend','血压趋势')}"><g class="grid-lines">${[60,90,120,150].map(v=>`<line x1="48" y1="${y(v)}" x2="658" y2="${y(v)}"/><text x="8" y="${y(v)+4}">${v}</text>`).join('')}</g><polyline class="line-primary" points="${line('systolic')}"/><polyline class="line-secondary" points="${line('diastolic')}"/>${rows.map((r,i)=>`<circle cx="${x(i)}" cy="${y(r.systolic)}" r="3.5" fill="#267266"><title>${r.date}: ${r.systolic}/${r.diastolic}</title></circle>`).join('')}</svg>`; }
  const rangeControl = () => `<div class="segmented"><button data-action="range" data-days="7" aria-pressed="${range===7}">${tx('7 days','7 天')}</button><button data-action="range" data-days="30" aria-pressed="${range===30}">${tx('30 days','30 天')}</button></div>`;
  function patientCards() { return `<div class="patient-grid">${state.patients.map(person=>`<article class="patient-card ${person.id===state.patientId?'selected':''}"><div class="card-row"><span class="avatar light">${l(person.name).slice(0,1)}</span>${risk(person.risk)}</div><h3>${l(person.name)}</h3><p>${person.age} ${tx('years','岁')} · ${l(person.condition)}</p><div class="mini-metrics"><span><b>${person.records.at(-1).systolic}/${person.records.at(-1).diastolic}</b><small>${tx('Latest BP','最近血压')}</small></span><span><b>${person.tasks.filter(t=>!t.done).length}</b><small>${tx('Open tasks','待办')}</small></span></div>${button(tx('Open patient','查看患者'),'select-patient',true,`data-id="${person.id}"`)}</article>`).join('')}</div>`; }
  function reviewQueue() { const rows=state.reviews.filter(r=>r.status==='pending'); return rows.length?`<div class="review-list">${rows.map(r=>{const patient=state.patients.find(x=>x.id===r.patientId); return `<article class="review-card"><div><span class="eyebrow">${r.kind==='ai'?tx('AI-ASSISTED · REQUIRES CLINICIAN REVIEW','AI 辅助 · 须医生复核'):tx('IMPORTED RECORD','导入记录')}</span><h3>${l(patient.name)} · ${l(r.title)}</h3><p>${r.date} · ${tx('Extraction confidence','提取可信度')} ${r.confidence}%</p></div><div class="review-actions">${button(tx('Approve','通过'),'review-approve',true,`data-id="${r.id}"`)}${button(tx('Reject','驳回'),'review-reject',true,`data-id="${r.id}"`)}</div></article>`;}).join('')}</div>`:`<div class="empty"><b>${tx('Review queue cleared','复核队列已清空')}</b><p>${tx('There are no imported records or AI summaries waiting for a clinician.','暂无等待医生确认的导入记录或 AI 摘要。')}</p></div>`; }
  function doctorOverview() { return heading(tx('CLINICAL WORKSPACE','医生工作台'),tx('Start with what needs clinical attention','先处理真正需要临床关注的事项'),tx('Risk, review, and care-plan work are organized around assigned patients.','围绕已分配患者，集中处理风险、复核与照护计划。'),'health-journal-small.webp')+stats()+`<div class="columns"><section class="panel"><header class="panel-heading"><div><span class="eyebrow">${tx('PRIORITY','优先处理')}</span><h2>${tx('Clinical review queue','临床复核队列')}</h2></div><a href="#reviews">${tx('View all','查看全部')} →</a></header>${reviewQueue()}</section><section class="panel"><header class="panel-heading"><div><span class="eyebrow">${tx('SELECTED PATIENT','当前患者')}</span><h2>${l(p().name)}</h2></div>${risk(p().risk)}</header><p>${l(p().condition)}</p><div class="note"><span class="avatar light">${tx('DR','医')}</span><div><b>${l(state.notes[0].author)}</b><p>${l(state.notes[0].text)}</p></div></div>${button(tx('Create care plan','新建照护计划'),'plan')}</section></div>`; }
  function patients() { return heading(tx('CARE TEAM','医疗团队'),tx('Assigned patient panel','已分配患者面板'),tx('Each clinician sees only the patients assigned to their care team.','医生仅能看到已分配到当前医疗团队的患者。'),'care-moments-small.webp')+`<section class="panel">${patientCards()}</section>`; }
  function reviews() { return heading(tx('CLINICAL SAFETY','临床安全'),tx('Review before information becomes clinical truth','先复核，再让信息进入临床记录'),tx('Imported records and AI-assisted analysis remain pending until a clinician decides.','导入记录与 AI 辅助分析必须经医生确认后生效。'),'records-care-small.webp')+`<section class="notice">${tx('AI output is decision support, not an autonomous diagnosis. Every decision is recorded in the full application.','AI 输出仅用于辅助决策，不会自动诊断；正式系统会记录每次复核。')}</section><section class="panel">${reviewQueue()}</section>`; }
  function plans() { const rows=state.plans.filter(x=>x.patientId===state.patientId); return heading(tx('CONTINUOUS CARE','连续照护'),tx('Care plans with clear ownership','责任清晰的照护计划'),tx('Define goals, instructions, target dates, and follow-up ownership.','明确目标、执行说明、截止日期和随访责任。'),'care-moments-small.webp',button(tx('＋ New care plan','＋ 新建计划'),'plan'))+`<section class="panel"><div class="plan-grid">${rows.map(x=>`<article class="plan-card"><span class="tag">${tx('Active','执行中')}</span><h3>${l(x.title)}</h3><p>${tx('Owner','负责人')}：${l(x.owner)}</p><strong>${tx('Target','计划日期')} · ${x.target}</strong></article>`).join('')}</div></section>`; }
  function today() { return heading(tx('MY HEALTH','我的健康'),tx('A calm plan for today','从容完成今天的健康计划'),tx('Record readings, check medications, and follow clinician guidance one step at a time.','按步骤记录指标、完成用药并查看医生建议。'),'care-moments-small.webp',button(tx('＋ Record blood pressure','＋ 记录血压'),'vital'))+stats()+`<section class="panel"><header class="panel-heading"><h2>${tx('Today’s plan','今日计划')}</h2><span class="tag">${p().tasks.length} ${tx('items','项')}</span></header>${tasks()}</section>`; }
  function vitals() { return heading(tx('VITAL SIGNS','生命体征'),tx('See change, not just a single number','看见变化，而不只是一个数值'),tx('New entries update the timeline and can be exported for a follow-up visit.','新增记录会更新趋势，也可导出用于复诊。'),'health-journal-small.webp',button(tx('＋ Record reading','＋ 记录读数'),'vital'))+`<section class="panel"><header class="panel-heading"><h2>${tx('Blood-pressure trend','血压趋势')}</h2>${rangeControl()}</header>${chart()}</section><section class="panel"><header class="panel-heading"><h2>${tx('Recent readings','近期读数')}</h2>${button(tx('Export CSV','导出 CSV'),'export',true)}</header><div class="table-wrap"><table><thead><tr><th>${tx('Date','日期')}</th><th>${tx('Time','时间')}</th><th>${tx('Systolic','收缩压')}</th><th>${tx('Diastolic','舒张压')}</th></tr></thead><tbody>${p().records.slice(-7).reverse().map(r=>`<tr><td>${r.date}</td><td>${r.time}</td><td>${r.systolic} mmHg</td><td>${r.diastolic} mmHg</td></tr>`).join('')}</tbody></table></div></section>`; }
  function medicationSnapshot() { return heading(tx('MEDICATION SAFETY','用药安全'),tx('Make every check-in visible','让每次用药都有记录'),tx('Schedules, check-ins, and stock stay connected for the patient and family.','用药计划、服药打卡和库存对患者与家属保持同步。'),'medication-care-small.webp')+`<section class="notice">${tx('Medication names and doses here are fictional and are not treatment advice.','页面中的药名和剂量均为虚构，不构成用药建议。')}</section><section class="panel"><div class="drug-grid">${p().stocks.map((s,i)=>`<article class="drug"><div class="drug-icon">✚</div><div><span class="tag ${s<10?'warm':''}">${s<10?tx('Low stock','库存偏低'):tx('In stock','库存正常')}</span><h3>${tx('Demo Medication','演示药品')} ${i?'B':'A'}</h3><strong>${s} <small>${tx('tablets left','片剩余')}</small></strong></div></article>`).join('')}</div></section><section class="panel"><h2>${tx('Today’s check-ins','今日打卡')}</h2>${tasks('medication')}</section>`; }
  function recordSnapshot() { const names=[tx('Complete blood count','血常规报告'),tx('Metabolic panel','生化检验报告'),tx('Discharge summary','出院小结')]; return heading(tx('LONGITUDINAL RECORD','连续健康档案'),tx('A shared, reviewable health history','可共享、可复核的健康记录'),tx('Reports, visits, measurements, and clinician notes remain connected.','报告、就诊、测量和医生记录彼此关联。'),'records-care-small.webp')+`<section class="panel"><div class="report-grid">${names.map((name,i)=>`<button class="report-card" data-action="detail" data-id="${i}"><span class="report-icon">▤</span><span class="tag neutral">${i===2?tx('Visit document','就诊文书'):tx('Lab report','检验报告')}</span><h3>${name}</h3><p>${p().records.at(-1-i*4).date} · ${tx('Demo Medical Center','演示医疗中心')}</p><span class="report-open">${tx('View structured record','查看结构化记录')} →</span></button>`).join('')}</div></section>`; }
  function dialysisSnapshot() { return heading(tx('DIALYSIS','透析管理'),tx('Treatment sessions in one timeline','集中管理每次治疗过程'),tx('Track pre/post weight, ultrafiltration, symptoms, and follow-up.','记录透析前后体重、超滤量、症状与随访。'),'health-journal-small.webp')+`<section class="stats"><article><span>${tx('Last session','最近一次')}</span><strong>09-19</strong><p>${tx('Completed','已完成')}</p></article><article><span>${tx('Pre / post weight','透析前 / 后体重')}</span><strong>62.4<small> / 60.2 kg</small></strong><p>${tx('Fictional session','虚构治疗记录')}</p></article><article><span>${tx('Ultrafiltration','超滤量')}</span><strong>2.2<small> L</small></strong><p>${tx('Within planned range','在计划范围内')}</p></article><article><span>${tx('Next session','下次治疗')}</span><strong>${tx('Tue','周二')}<small> 08:30</small></strong><p>${tx('Demo schedule','演示日程')}</p></article></section>`; }
  function nutrition() { return heading(tx('NUTRITION','营养管理'),tx('Daily choices linked to the care plan','让每日饮食与照护计划相连'),tx('Track fluid, sodium, protein guidance, and dietitian follow-up.','管理饮水、钠、蛋白建议及营养师随访。'),'care-moments-small.webp')+`<section class="stats"><article><span>${tx('Fluid today','今日饮水')}</span><strong>820<small> ml</small></strong><p>${tx('Target 1,200 ml','目标 1,200 ml')}</p></article><article><span>${tx('Meals logged','饮食记录')}</span><strong>2<small> / 3</small></strong><p>${tx('Breakfast and lunch','早餐与午餐')}</p></article><article><span>${tx('Sodium guidance','钠摄入建议')}</span><strong>&lt; 2<small> g</small></strong><p>${tx('Clinician-defined demo goal','医生设定的演示目标')}</p></article><article><span>${tx('Dietitian review','营养师复核')}</span><strong>${tx('Fri','周五')}</strong><p>${tx('Shared care plan','共享照护计划')}</p></article></section>`; }
  function care() { return heading(tx('FAMILY CARE','家属照护'),tx('Care together without losing context','共同照护，不丢失信息'),tx('See today’s plan, check in medication, and leave a clear handover.','查看今日计划、完成用药打卡并留下清晰交接。'),'care-moments-small.webp')+stats()+`<section class="panel"><header class="panel-heading"><h2>${tx('Care schedule','照护日程')}</h2><span class="tag">${l(p().relation)} · ${p().age}</span></header>${tasks()}</section>`; }
  function appointments() { return heading(tx('APPOINTMENTS','复诊安排'),tx('Prepare before the visit','复诊前就准备充分'),tx('Keep the time, reports, medication list, and questions together.','把时间、报告、用药清单和待咨询问题放在一起。'),'records-care-small.webp')+`<section class="panel"><article class="appointment"><div class="date-block"><b>${state.appointments[0].date.slice(8)}</b><span>${state.appointments[0].date.slice(5,7)}</span></div><div><span class="eyebrow">${tx('UPCOMING','即将到来')}</span><h2>${l(state.appointments[0].clinic)}</h2><p>${state.appointments[0].date} · ${state.appointments[0].time} · ${tx('Demo Medical Center','演示医疗中心')}</p><div class="checklist"><span>✓ ${tx('Recent reports attached','近期报告已整理')}</span><span>✓ ${tx('Medication list ready','用药清单已准备')}</span><span>○ ${tx('Add family questions','补充家属问题')}</span></div></div></article></section>`; }
  function consultation(){const chat=M.currentConsultation(state);return heading(tx('LIVE CONSULTATION','实时问诊'),tx('Doctor, patient, and family in one conversation','医生、患者与家属在同一会话'),tx('Messages in this static demo stay in this browser; the real platform persists the transcript and refreshes active sessions automatically.','静态演示消息只保留在当前浏览器；真实平台会持久化记录并自动刷新进行中的会话。'),'care-moments-small.webp')+`<section class="chat-shell panel"><aside class="chat-summary"><span class="live-pill"><i></i>${tx('Live demo','实时演示')}</span><h2>${l(chat.symptom)}</h2><p>${tx('Three-party text consultation','三方图文问诊')} · ${l(p().name)}</p><div class="participant-list">${chat.participants.map(name=>`<span><i></i>${l(name)}</span>`).join('')}</div><div class="chat-call-actions">${button(tx('Start voice','发起语音'),'chat-call',true,'data-mode="voice"')}${button(tx('Start video','发起视频'),'chat-call',true,'data-mode="video"')}</div><small>${tx('Camera and microphone are simulated on this static page.','静态页面仅模拟摄像头和麦克风操作。')}</small></aside><div class="chat-room"><div class="chat-messages" id="chat-messages" aria-live="polite">${chat.messages.map(m=>`<article class="chat-message ${m.sender===state.role?'self':''}"><div><b>${l(m.name)}</b><time>${m.time}</time></div><p>${esc(l(m.text))}</p></article>`).join('')}</div><div class="typing-indicator"><i></i><i></i><i></i><span>${tx('Participants receive new messages automatically','参与者会自动收到新消息')}</span></div><form id="chat-form" class="chat-compose"><label><span class="sr-only">${tx('Consultation message','问诊消息')}</span><textarea name="message" rows="2" maxlength="800" placeholder="${tx('Describe symptoms or reply to the care team…','描述症状或回复照护团队……')}" required></textarea></label><button class="button" type="submit">${tx('Send message','发送消息')}</button></form></div></section>`}
  function handover() { const rows=state.handovers.filter(x=>x.patientId===state.patientId); return heading(tx('FAMILY HANDOVER','家庭交接'),tx('Leave the next caregiver a clear update','给下一位照护者留下清晰信息'),tx('A shared handover reduces repeated questions and missed tasks.','共享交接可减少重复沟通和遗漏。'),'care-moments-small.webp',button(tx('＋ Add handover','＋ 新增交接'),'handover'))+`<section class="panel"><div class="timeline">${rows.map(x=>`<article><span>${x.time}</span><div><b>${l(x.author)}</b><p>${l(x.text)}</p></div></article>`).join('')}</div></section>`; }
  const featureGroups={
    clinical:[['clinical-import','Batch import & OCR','批量导入与 OCR','Extract structured results and route low-confidence fields to review.','提取结构化结果，将低可信字段送入复核。'],['clinical-abnormal','Abnormal result review','异常结果复核','Prioritize abnormal indicators with source traceability.','按优先级处理异常指标并追踪来源。'],['clinical-trend','Indicator trends','指标趋势','Compare the same indicator across reports and dates.','跨报告和日期对比同一指标。']],
    dialysis:[['dialysis-record','Dialysis records','透析记录','Record weight, ultrafiltration, blood pressure, access, and symptoms.','记录体重、超滤、血压、通路和症状。'],['dialysis-trend','Treatment trends','治疗趋势','Review weight gain, target completion, and complications.','查看体重增长、目标完成率和并发症。'],['dialysis-ai','AI-assisted analysis','AI 辅助分析','Generate a review-required longitudinal summary.','生成必须人工复核的纵向摘要。'],['dry-weight','Dry-weight management','干体重管理','Version monthly targets and compare post-dialysis weight.','按月维护目标并对比透析后体重。']],
    records:[['record-list','Record list','记录列表','Filter reports by patient, type, hospital, and date.','按患者、类型、医院和日期筛选报告。'],['record-upload','Upload & recognize','上传与识别','Simulate PDF/image intake, extraction, and verification.','模拟 PDF/图片导入、提取和核验。'],['record-abnormal','Abnormal results','异常指标','Collect abnormal values without losing the source report.','汇总异常值并保留原始报告来源。'],['record-trend','Result trends','检验趋势','Chart comparable structured results over time.','展示可比结构化结果的时间趋势。']],
    medication:[['drug-list','Medication list','药品清单','Maintain the current prescription and version history.','维护当前处方和历史版本。'],['drug-ocr','Upload & recognize','上传与识别','Extract a medication list and require confirmation.','提取用药清单并要求确认。'],['drug-log','Medication log','用药记录','Track adherence, missed doses, and caregiver check-ins.','跟踪依从性、漏服和家属打卡。'],['drug-category','Medication categories','药品分类','Browse current and historical drugs by category.','按分类查看当前及历史药品。'],['drug-reminder','Reminders & stock','提醒与库存','Link schedules, stock movements, and low-stock warnings.','关联提醒、库存流水和低库存预警。']],
    analytics:[['complication','Complication tracking','并发症跟踪','Record severity, intervention, and outcome.','记录严重程度、干预和结局。'],['alert','Health alerts','健康预警','Review candidate alerts before delivery.','发送前复核候选预警。'],['bp-pattern','Blood-pressure patterns','血压模式分析','Compare dialysis and home-monitoring patterns.','对比透析与居家监测模式。'],['nutrition-diary','Nutrition diary','营养日记','Track meals, fluid, sodium, and protein.','记录饮食、液体、钠和蛋白。'],['nutrition-assessment','Nutrition assessment','营养评估','Review longitudinal scores and interventions.','查看纵向评分和干预。'],['health-report','Health report','健康报告','Assemble reviewed data into a visit-ready report.','将已复核数据整理成就诊报告。'],['automation','Automated analysis','自动分析','Schedule guarded analysis with review gates.','通过复核门禁执行定时分析。'],['data-export','Data export','数据导出','Export the selected patient and date range.','导出选定患者和日期范围。']],
    careplan:[['care-today','Today’s tasks','今日任务','Coordinate medication, measurements, and care activities.','协调用药、测量和照护事项。'],['timeline','Health timeline','健康时间线','Combine measurements, reports, alerts, and notes.','合并指标、报告、预警和笔记。'],['schedule','Dialysis schedule','透析计划','Plan sessions and preparation reminders.','安排治疗和准备提醒。'],['targets','Personal goals','个人目标','Set clinician-reviewed targets and effective dates.','设置经医生确认的目标及生效日期。'],['visit-summary','Visit summary','就诊摘要','Prepare recent changes and questions for follow-up.','整理近期变化和复诊问题。']],
    notifications:[['channel','Delivery channels','通知渠道','Configure browser, WeCom, or DingTalk delivery.','配置浏览器、企业微信或钉钉通知。'],['test-delivery','Test delivery','发送测试','Verify a masked channel without real delivery in this demo.','在演示中验证脱敏渠道，不会真实发送。'],['delivery-log','Delivery log','发送日志','Review outcome, retry, and failure reason.','查看结果、重试和失败原因。']]
    ,journey:[
      ['metric-entry','Manual health metrics','健康指标录入','Record blood pressure, glucose, oxygen, weight, and heart rate.','录入血压、血糖、血氧、体重和心率。'],['metric-alert','Automatic threshold alerts','指标异常自动预警','Notify the patient, family, and assigned clinician when a threshold is crossed.','指标超阈值后自动通知患者、家属和责任医生。'],['metric-note','Trend annotation','趋势标注','Let clinicians annotate a specific point on the trend.','医生可对趋势中的具体数据点添加备注。'],['prescription-sync','Prescription version sync','处方版本同步','Publish dose and frequency changes to the shared care team.','剂量和频次修改后同步到照护团队。'],['medication-missed','Missed-dose visibility','漏服提醒','Expose missed check-ins to authorized caregivers.','向已授权家属展示漏服并提醒。'],['followup-auto','Automatic follow-up tasks','自动随访任务','Generate recurring follow-up work and due reminders.','自动生成周期随访任务和到期提醒。'],
      ['appointment-slots','Conflict-checked appointments','预约时段管理','Book, reschedule, cancel, and synchronize clinician availability.','预约、改约、取消并同步医生可用时段。'],['visit-publish','Visit summary delivery','诊后小结推送','Publish structured visit summaries to patient and family.','将结构化诊后小结推送给患者和家属。'],['e-prescription','Electronic prescription archive','电子处方留档','Keep clinician orders without pharmacy integration.','保存医嘱记录，不对接药房。'],['periodic-revisit','Periodic revisit reminder','周期复诊提醒','Trigger the next revisit from the clinician-defined recurrence.','按医生设定周期自动触发下次复诊提醒。'],['visit-timeline','Visit timeline','就诊时间轴','Review consultations and visits chronologically.','按时间查看问诊与就诊记录。'],
      ['consult-text','Text consultation','图文问诊','Persist a three-party consultation transcript.','保存患者、家属和医生三方问诊记录。'],['consult-media','Voice and video consultation','语音视频问诊','Use browser media with configurable private ICE infrastructure.','使用浏览器音视频和可配置的私有网络服务。'],['consult-template','Symptom template','症状模板','Capture symptom, duration, and medical history consistently.','结构化记录症状、持续时间和既往史。'],['consult-attachment','Images and lab attachments','图片与化验单','Reference uploaded medical records from the consultation.','在问诊中关联上传的医疗记录。'],['consult-archive','Automatic consultation archive','问诊自动归档','Archive the completed transcript into the health timeline.','问诊结束后自动归档到健康时间线。'],['transfer-advice','Specialty advice','转科建议','Record clinician advice without an external referral workflow.','记录医生文字建议，不对接外部转诊。'],
      ['treatment-plan','Treatment plan','治疗计划','Publish structured checks, surgery times, and medication adjustments.','发布检查安排、手术时间和用药调整。'],['rehab-video','Rehabilitation check-ins','康复打卡','Show action video links and record completion.','展示动作视频并记录完成度。'],['wound-drain','Wound and drain forms','伤口与引流记录','Store structured recovery observations.','保存结构化康复观察。'],['discharge-summary','Structured discharge summary','结构化出院小结','Record discharge summary fields and clinician instructions.','结构化记录出院小结和出院医嘱。'],['symptom-alert','Recovery symptom alert','康复异常提醒','Notify clinicians about abnormal recovery check-ins.','异常康复打卡自动提醒医护。'],
      ['care-permissions','Multi-caregiver permissions','多照护者分级权限','Grant read, record, or proxy access per person.','按人员授予只读、录入或代办权限。'],['care-handover','Care shift handover','照护轮班交接','Coordinate medication, turning, measurements, and handovers.','协同喂药、翻身、测量与交接。'],['care-log','Daily care log','照护日志','Track diet, bowel movements, mood, and sleep.','记录饮食、排便、情绪和睡眠。'],
      ['emergency-sos','Emergency SOS','一键呼救','Send location and a medical snapshot to bound contacts.','向绑定联系人发送定位和医疗快照。'],['offline-card','Offline medical card','离线医疗卡','Cache allergy, blood type, chronic history, and medications.','离线保存过敏史、血型、慢病史和用药。'],
      ['growth-curve','Growth records','生长曲线','Track height, weight, head circumference, and reference percentiles.','记录身高、体重、头围与标准百分位。'],['vaccine-plan','Vaccination plan','疫苗计划','Maintain manual vaccine dates and reminders.','维护手工接种计划和提醒。'],['maternity-timeline','Maternity timeline','孕产时间轴','Record prenatal, delivery, and postpartum events.','记录产检、分娩和产后事件。'],['multi-guardian','Multiple guardians','多监护人','Authorize multiple guardians through patient access grants.','通过患者授权支持多名监护人。'],
      ['mental-scale','Mental-health assessment','心理量表','Schedule PHQ-9, GAD-7, or WHO-5 self-assessments.','定期推送 PHQ-9、GAD-7 或 WHO-5 自评。'],['private-consult','Private consultation','私密咨询','Hide patient-designated content from family caregivers.','按患者设置对家属隐藏私密内容。'],['mental-alert','Assessment risk alert','量表异常提醒','Notify assigned clinicians of moderate or severe results.','中重度结果自动提醒责任医生。'],
      ['data-grant','Patient-controlled visibility','患者自主可见范围','Choose the people, modules, and access level for shared data.','自主设置共享人员、模块和权限级别。'],['multi-doctor','Multi-clinician authorization','多医生授权','Require an active grant or assignment for clinician access.','医生访问必须具备有效授权或诊疗分配。'],['audit-detail','Detailed operation trail','操作留痕','Record actor, action, target, time, and safe metadata.','记录操作者、动作、目标、时间与安全元数据。'],['masked-export','De-identified export','脱敏导出','Mask phone and identity numbers in portable CSV data.','导出 CSV 时脱敏手机号和证件号码。'],
      ['doctor-roster','Clinician schedule and groups','医生排班与分组','Manage availability and clinician-owned patient groups.','管理医生可用时段和患者分组。'],['operations-report','Internal outcome report','内部统计报表','Measure follow-up completion, adherence, target rate, and alert resolution.','统计随访完成率、依从率、指标达标率和预警处理率。']
    ]
  };
  function featurePanel(group,keys,title){const features=keys?featureGroups[group].filter(([key])=>keys.includes(key)):featureGroups[group];return `<section class="panel"><header class="panel-heading"><div><h2>${title?tx(title[0],title[1]):tx('Real-system capabilities','真实系统功能')}</h2><p>${tx('Every action below changes local demo state and writes an audit event.','下列操作都会修改本地演示状态并写入审计事件。')}</p></div></header><div class="capability-grid">${features.map(([key,en,cn,enDesc,cnDesc])=>{const count=state.featureRuns[key]||0;return `<article class="capability-card"><div><span class="tag ${count?'':'neutral'}">${count?tx(`Completed ${count}×`,`已执行 ${count} 次`):tx('Ready','可操作')}</span><h3>${tx(en,cn)}</h3><p>${tx(enDesc,cnDesc)}</p></div>${button(count?tx('Run again','再次执行'):tx('Run demo','执行演示'),'module-action',true,`data-key="${key}"`)}</article>`}).join('')}</div></section>`}
  function clinical(){return heading(tx('CLINICAL WORKBENCH','临床工作台'),tx('Import, structure, verify, and compare','导入、结构化、复核与对比'),tx('The demo follows the same guarded information flow as the full system.','演示遵循与正式系统一致的受控信息流程。'),'records-care-small.webp')+featurePanel('clinical')}
  function monitoring(){return heading(tx('HEALTH OVERVIEW','健康概览'),tx('One longitudinal view of the selected patient','纵向查看当前患者的完整健康状态'),tx('Measurements, adherence, records, alerts, and care activity are combined here.','集中呈现指标、依从性、记录、预警和照护动态。'),'health-journal-small.webp')+stats()+`<section class="panel"><header class="panel-heading"><h2>${tx('Blood-pressure trend','血压趋势')}</h2>${rangeControl()}</header>${chart()}</section>`}
  function medications(){return medicationSnapshot()+featurePanel('medication')}
  function records(){return recordSnapshot()+featurePanel('records')}
  function dialysis(){return dialysisSnapshot()+featurePanel('dialysis')}
  function dryweight(){return heading(tx('DRY WEIGHT','干体重管理'),tx('Manage targets as clinical versions','按临床版本管理目标'),tx('Compare monthly targets with post-dialysis observations.','对比每月目标与透析后观察值。'),'health-journal-small.webp')+`<section class="stats"><article><span>${tx('Current target','当前目标')}</span><strong>60.0<small> kg</small></strong><p>${tx('Effective Sep 1','9 月 1 日生效')}</p></article><article><span>${tx('Latest post weight','最近透后体重')}</span><strong>60.2<small> kg</small></strong><p>${tx('Difference +0.2 kg','偏差 +0.2 kg')}</p></article><article><span>${tx('Monthly records','月度记录')}</span><strong>9</strong><p>${tx('Versioned history','版本化历史')}</p></article><article><span>${tx('Review state','复核状态')}</span><strong>${tx('Current','有效')}</strong><p>${tx('Clinician confirmed','医生已确认')}</p></article></section>`+featurePanel('dialysis',['dry-weight'])}
  function analytics(){return heading(tx('HEALTH ANALYTICS','健康分析'),tx('From signals to reviewed action','从信号到经复核的行动'),tx('All analytics remain traceable and require human review where clinical judgment is involved.','所有分析均可追溯，涉及临床判断时必须人工复核。'),'health-journal-small.webp')+featurePanel('analytics')}
  function careplan(){return heading(tx('CARE PLAN','照护计划'),tx('Turn clinical guidance into daily coordination','把临床建议转化为每日协作'),tx('Tasks, schedules, goals, timeline, and visit summaries share one context.','任务、计划、目标、时间线和就诊摘要共享同一上下文。'),'care-moments-small.webp')+featurePanel('careplan')}
  function notifications(){return heading(tx('NOTIFICATIONS','通知设置'),tx('Deliver the right message through the right channel','通过合适渠道发送合适的信息'),tx('Secrets are masked and this static demo never sends a real notification.','密钥会脱敏，静态演示不会真实发送通知。'),'care-moments-small.webp')+featurePanel('notifications')}
  function journey(){const groups=[
    [['metric-entry','metric-alert','metric-note','prescription-sync','medication-missed','followup-auto'],['Daily chronic-disease management','日常慢病管理']],
    [['appointment-slots','visit-publish','e-prescription','periodic-revisit','visit-timeline'],['Appointments and follow-up','门诊与复诊']],
    [['consult-text','consult-media','consult-template','consult-attachment','consult-archive','transfer-advice'],['Remote consultation','远程问诊']],
    [['treatment-plan','rehab-video','wound-drain','discharge-summary','symptom-alert'],['Inpatient and recovery','住院与术后康复']],
    [['care-permissions','care-handover','care-log'],['Home care','居家照护']],
    [['emergency-sos','offline-card'],['Emergency information','急诊与紧急情况']],
    [['growth-curve','vaccine-plan','maternity-timeline','multi-guardian'],['Child and maternity care','儿童与孕产妇']],
    [['mental-scale','private-consult','mental-alert'],['Mental health','心理与精神健康']],
    [['data-grant','multi-doctor','audit-detail','masked-export'],['Privacy and access','权限与隐私']],
    [['doctor-roster','operations-report'],['Clinical operations','系统运营']]
  ];return heading(tx('FULL CARE JOURNEY','全程健康照护'),tx('The same workflows as the real system','与真实系统一致的业务流程'),tx('Switch roles to see the permitted view; every demo action updates local state and the audit trail.','切换角色可查看相应权限页面；每个演示操作都会更新本地状态和审计记录。'),'care-moments-small.webp')+groups.map(([keys,title])=>featurePanel('journey',keys,title)).join('')}
  function admin(){return heading(tx('SYSTEM ADMINISTRATION','系统管理'),tx('Operate the platform with clear boundaries','边界清晰地管理平台'),tx('Identity, authorization, patient records, configuration, and auditing remain separate.','身份、授权、患者档案、配置和审计相互分离。'),'health-journal-small.webp')+`<section class="stats"><article><span>${tx('Active users','启用用户')}</span><strong>${state.users.filter(x=>x.active).length}</strong><p>${tx('Across four roles','覆盖四类角色')}</p></article><article><span>${tx('Patients','患者')}</span><strong>${state.patients.length}</strong><p>${tx('Scoped access','按范围授权')}</p></article><article><span>${tx('Menu modules','菜单模块')}</span><strong>29</strong><p>${tx('Permission-backed','权限驱动')}</p></article><article><span>${tx('Audit events','审计事件')}</span><strong>${state.audit.length}</strong><p>${tx('Traceable operations','操作可追溯')}</p></article></section>`}
  function users(){return heading(tx('USER MANAGEMENT','用户管理'),tx('Accounts and status','账号与状态'),tx('Role assignment is independent from patient access assignment.','角色分配与患者数据授权彼此独立。'),'care-moments-small.webp')+`<section class="panel"><div class="table-wrap"><table><thead><tr><th>${tx('User','用户')}</th><th>${tx('Role','角色')}</th><th>${tx('Status','状态')}</th><th>${tx('Action','操作')}</th></tr></thead><tbody>${state.users.map(x=>`<tr><td>${l(x.name)}</td><td>${l(x.role)}</td><td><span class="tag ${x.active?'':'warm'}">${x.active?tx('Active','启用'):tx('Disabled','停用')}</span></td><td>${button(x.active?tx('Disable','停用'):tx('Enable','启用'),'toggle-user',true,`data-id="${x.id}"`)}</td></tr>`).join('')}</tbody></table></div></section>`}
  function roles(){return capabilityPage(tx('ROLE MANAGEMENT','角色管理'),tx('Role and permission boundaries','角色与权限边界'),[['role-doctor','Doctor','医生'],['role-patient','Patient','患者'],['role-family','Family caregiver','家属照护者'],['role-admin','Administrator','管理员']])}
  function patientadmin(){return heading(tx('PATIENT MANAGEMENT','患者管理'),tx('Patient identity and care assignment','患者身份与照护分配'),tx('Manage the patient profile separately from account ownership and clinical assignment.','患者档案与账号归属、临床分配分别管理。'),'care-moments-small.webp')+`<section class="panel">${patientCards()}</section>`}
  function menus(){return capabilityPage(tx('MENU MANAGEMENT','菜单管理'),tx('Stable routes and permission codes','稳定路由与权限标识'),[['menu-clinical','Clinical modules','临床模块'],['menu-care','Patient and family modules','患者与家属模块'],['menu-system','System administration','系统管理'],['menu-mobile','Mobile primary navigation','移动端主导航']])}
  function branding(){const b=state.branding;return heading(tx('PLATFORM BRANDING','平台品牌'),tx('Make the platform unmistakably yours','让平台呈现专属品牌'),tx('Configure the page background, logo, platform name, organization, and centered ownership text.','配置页面背景、Logo、平台名称、公司或医院名称及居中所有权文字。'),'care-moments-small.webp')+`<section class="panel"><form id="branding-form" class="branding-form"><label>${tx('Platform name','平台名称（包括晨星健康／澄心健康等）')}<input name="platformName" maxlength="80" value="${esc(l(b.platformName))}" required></label><label>${tx('Company or hospital','公司或医院名称')}<input name="organizationName" maxlength="120" value="${esc(l(b.organizationName))}"></label><label>${tx('Page background','页面背景色')}<span class="color-config"><input name="pageBackground" type="color" value="${esc(b.pageBackground)}"><input name="backgroundText" maxlength="7" value="${esc(b.pageBackground)}" pattern="#[0-9A-Fa-f]{6}" required></span></label><label>${tx('Platform logo','平台 Logo')}<input name="logoFile" type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml"><small>${tx('Up to 1 MB; stored only in this browser.','最大 1 MB，仅保存在当前浏览器。')}</small></label><label class="full">${tx('Centered ownership text','页面正中间所有权文字')}<textarea name="ownershipText" maxlength="240" rows="3" required>${esc(l(b.ownershipText))}</textarea></label><div class="full dialog-actions"><button type="submit" class="button">${tx('Save and apply','保存并应用')}</button></div></form></section>`}
  function audit(){return heading(tx('AUDIT LOG','审计日志'),tx('Trace every sensitive operation','追踪每项敏感操作'),tx('Review actor, action, time, and outcome without exposing secrets.','查看操作者、动作、时间和结果，同时不暴露密钥。'),'records-care-small.webp')+`<section class="panel"><div class="table-wrap"><table><thead><tr><th>${tx('Time','时间')}</th><th>${tx('Actor','操作者')}</th><th>${tx('Action','操作')}</th><th>${tx('Result','结果')}</th></tr></thead><tbody>${state.audit.map(x=>`<tr><td>${x.time}</td><td>${l(x.actor)}</td><td>${l(x.action)}</td><td><span class="tag">${tx('Success','成功')}</span></td></tr>`).join('')}</tbody></table></div></section>`}
  function automation(){return capabilityPage(tx('AUTOMATED ANALYSIS','自动分析'),tx('Automation with review gates','带复核门禁的自动流程'),[['automation-daily','Daily monitoring summary','每日监测摘要'],['automation-weekly','Weekly dialysis analysis','每周透析分析'],['automation-alert','Alert candidate generation','预警候选生成'],['automation-report','Scheduled health report','定时健康报告']])}
  function dataexport(){return heading(tx('DATA EXPORT','数据导出'),tx('Portable patient-owned data','可携带、归患者所有的数据'),tx('Select a patient and export only the intended scope.','选择患者，仅导出明确的数据范围。'),'records-care-small.webp',button(tx('Export selected patient CSV','导出当前患者 CSV'),'export'))+featurePanel('analytics',['data-export'])}
  function capabilityPage(kicker,title,items){return heading(kicker,title,tx('Each control below performs a local, auditable demo action.','下列每个控件都会执行本地且可审计的演示操作。'),'records-care-small.webp')+`<section class="panel"><div class="capability-grid">${items.map(([key,en,cn])=>`<article class="capability-card"><div><span class="tag neutral">${tx('Configured','已配置')}</span><h3>${tx(en,cn)}</h3><p>${tx('Open the corresponding configuration and permission flow.','打开对应配置与权限流程。')}</p></div>${button(tx('Verify','验证'),'module-action',true,`data-key="${key}"`)}</article>`).join('')}</div></section>`}
  const renderers={overview:doctorOverview,consultation,journey,patients,reviews,plans,clinical,monitoring,today,vitals,medications,records,dialysis,dryweight,nutrition,analytics,careplan,notifications,care,appointments,handover,admin,users,roles,patientadmin,menus,branding,audit,automation,dataexport};
  function applyBranding(){const b=state.branding;document.body.style.background=b.pageBackground;$('brand-logo').src=b.logo;$('brand-name').textContent=l(b.platformName);$('brand-organization').textContent=l(b.organizationName);$('ownership').textContent=l(b.ownershipText);}
  function shell() { const role=copy[state.role]; $('role-switch').innerHTML=Object.entries(copy).map(([k,v])=>`<button data-role="${k}" aria-pressed="${state.role===k}">${v.name}</button>`).join(''); $('nav').innerHTML=Object.entries(role.nav).map(([k,v])=>`<a href="#${k}" data-page="${k}"><span>${{overview:'⌂',consultation:'✉',journey:'⚕',patients:'♙',reviews:'✓',plans:'◇',clinical:'⚕',monitoring:'▥',today:'☀',vitals:'⌁',medications:'✚',records:'▤',dialysis:'◉',dryweight:'⚖',analytics:'⌁',careplan:'◇',notifications:'♢',care:'⌂',appointments:'◷',handover:'⇄',admin:'⌂',users:'♙',roles:'◎',patientadmin:'♧',menus:'☷',audit:'▤',automation:'◴',dataexport:'⇩'}[k]||'·'}</span>${v}</a>`).join(''); $('role-caption').textContent=role.workspace; $('workspace-label').textContent=role.workspace; $('account-name').textContent=state.role==='patient'?l(p().name):role.account; $('account-avatar').textContent=role.avatar; $('member-label').textContent=state.role==='family'?tx('Family member','家人'):tx('Patient','患者'); $('patient').innerHTML=state.patients.map(x=>`<option value="${x.id}" ${x.id===state.patientId?'selected':''}>${l(x.name)} (${tx('demo','演示')})</option>`).join(''); }
  function render() { applyBranding(); shell(); const key=page(); $('breadcrumb').textContent=copy[state.role].nav[key]; document.querySelectorAll('[data-page]').forEach(a=>a.toggleAttribute('aria-current',a.dataset.page===key)); $('content').innerHTML=renderers[key](); document.title=`${copy[state.role].nav[key]} · ${l(state.branding.platformName)}`; }
  function openAction(kind) { action=kind; const config={vital:{title:tx('Record blood pressure','记录血压'),help:tx('The entry updates this demo only.','记录仅更新当前演示。'),fields:`<label>${tx('Systolic (mmHg)','收缩压 (mmHg)')}<input name="systolic" type="number" min="50" max="260" value="126" required></label><label>${tx('Diastolic (mmHg)','舒张压 (mmHg)')}<input name="diastolic" type="number" min="30" max="160" value="78" required></label>`},plan:{title:tx('Create care plan','新建照护计划'),help:tx('Assign a clear goal and target date.','设置清晰目标和计划日期。'),fields:`<label class="full">${tx('Plan title','计划名称')}<input name="title" value="${tx('Seven-day symptom review','七日症状复核计划')}" required></label><label>${tx('Target date','计划日期')}<input name="target" type="date" required></label>`},handover:{title:tx('Add family handover','新增家庭交接'),help:tx('Share only what the next caregiver needs.','只记录下一位照护者需要的信息。'),fields:`<label class="full">${tx('Handover note','交接内容')}<textarea name="text" rows="4" required>${tx('Medication check-in is complete. Please record the evening blood pressure.','用药打卡已完成，请记录晚间血压。')}</textarea></label>`}}[kind]; $('action-title').textContent=config.title; $('action-help').textContent=config.help; $('action-fields').innerHTML=config.fields; $('form-error').textContent=''; returnFocus=document.activeElement; $('action-dialog').showModal(); }
  function download() { const blob=new Blob([M.csv(state,zh?'zh':'en')],{type:'text/csv;charset=utf-8'}), url=URL.createObjectURL(blob), a=document.createElement('a'); a.href=url;a.download=`chengxin-health-${p().id}.csv`;a.click();URL.revokeObjectURL(url);toast(tx('CSV export created.','CSV 已导出。')); }
  document.addEventListener('click',e=>{ const role=e.target.closest('[data-role]'); if(role){state.role=role.dataset.role;location.hash=copy[state.role].start;render();return;} const el=e.target.closest('[data-action]'); if(!el)return; const a=el.dataset.action,id=el.dataset.id; if(a==='complete'){M.complete(state,id);toast(tx('Care task completed.','照护任务已完成。'));render();} if(a==='vital'||a==='plan'||a==='handover')openAction(a); if(a==='range'){range=Number(el.dataset.days);render();} if(a==='select-patient'){state.patientId=Number(id);render();} if(a==='module-action'){M.runFeature(state,el.dataset.key);toast(tx('Demo action completed and added to the audit log.','演示操作已完成并写入审计日志。'));render();} if(a==='toggle-user'){M.toggleUser(state,id);toast(tx('Account status updated.','账号状态已更新。'));render();} if(a.startsWith('review-')){M.review(state,id,a.endsWith('approve')?'approved':'rejected');toast(a.endsWith('approve')?tx('Item approved and audit event recorded.','已通过，并记录审核日志。'):tx('Item rejected for correction.','已驳回并退回修正。'));render();} if(a==='chat-call')toast(tx(`${el.dataset.mode==='video'?'Video':'Voice'} call simulated. The real platform requests device permission and connects participants.`,`${el.dataset.mode==='video'?'视频':'语音'}通话已模拟；真实平台会申请设备权限并连接参与者。`)); if(a==='export')download(); if(a==='detail'){const names=[tx('Complete blood count','血常规报告'),tx('Metabolic panel','生化检验报告'),tx('Discharge summary','出院小结')];$('detail-title').textContent=names[Number(id)];$('record-detail').innerHTML=`<div class="record-summary"><span class="tag">${tx('Clinician reviewed','医生已复核')}</span><p>${tx('This fictional structured record demonstrates report metadata, extracted measurements, source traceability, and review status.','这份虚构的结构化记录演示报告元数据、提取指标、来源追踪和复核状态。')}</p><dl><dt>${tx('Patient','患者')}</dt><dd>${l(p().name)}</dd><dt>${tx('Source','来源')}</dt><dd>${tx('Demo Medical Center','演示医疗中心')}</dd><dt>${tx('Visibility','可见范围')}</dt><dd>${tx('Patient and care team','患者与照护团队')}</dd></dl></div>`;$('detail-dialog').showModal();}});
  $('patient').addEventListener('change',e=>{state.patientId=Number(e.target.value);render();});
  $('guide-start').addEventListener('click',openGuide);$('guide-previous').addEventListener('click',()=>{if(guideIndex>0){guideIndex--;showGuideStep();}});$('guide-next').addEventListener('click',()=>{if(guideIndex===currentGuide().length-1){localStorage.setItem('chengxin-demo-guide-complete','1');closeGuide();document.querySelector('.guide-target')?.classList.remove('guide-target');toast(tx('Guide completed. You can restart it at any time.','指引已完成，可随时重新开始。'));}else{guideIndex++;showGuideStep();}});$('guide-pause').addEventListener('click',()=>{closeGuide();document.querySelector('.guide-target')?.classList.remove('guide-target');});window.addEventListener('resize',()=>{if(!$('guide-tour').hidden)showGuideStep();});
  $('reset').addEventListener('click',()=>{state=M.createState();localStorage.removeItem('chengxin-demo-branding');range=7;location.hash=copy[state.role].start;toast(tx('Demo reset.','演示已重置。'));render();});
  document.addEventListener('submit',e=>{if(e.target.id!=='chat-form')return;e.preventDefault();const text=new FormData(e.target).get('message');try{M.sendChatMessage(state,text,state.role);render();setTimeout(()=>{M.addDemoReply(state,zh?'zh':'en');render();toast(tx('A simulated clinician reply arrived.','已收到一条模拟医生回复。'));},850);}catch{toast(tx('Enter a message before sending.','请输入消息后再发送。'));}});
  document.addEventListener('submit',e=>{if(e.target.id!=='branding-form')return;e.preventDefault();const data=new FormData(e.target),file=data.get('logoFile');const commit=logo=>{try{const value={platformName:data.get('platformName'),organizationName:data.get('organizationName'),pageBackground:data.get('backgroundText'),ownershipText:data.get('ownershipText'),logo};M.updateBranding(state,value);localStorage.setItem('chengxin-demo-branding',JSON.stringify(value));toast(tx('Platform branding saved and applied.','平台品牌已保存并应用。'));render();}catch{toast(tx('Check the branding fields and try again.','请检查品牌配置后重试。'));}};if(file&&file.size){if(file.size>1024*1024){toast(tx('Choose an image no larger than 1 MB.','请选择不超过 1 MB 的图片。'));return;}const reader=new FileReader();reader.onload=()=>commit(String(reader.result));reader.readAsDataURL(file);}else commit(state.branding.logo);});
  $('action-form').addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.target);try{if(action==='vital')M.addVital(state,Number(data.get('systolic')),Number(data.get('diastolic')));if(action==='plan')M.addPlan(state,data.get('title'),data.get('target'));if(action==='handover')M.addHandover(state,data.get('text'));$('action-dialog').close();toast(tx('Demo entry saved.','演示记录已保存。'));render();}catch{$('form-error').textContent=tx('Check the fields and try again. Systolic pressure must be higher than diastolic pressure.','请检查输入后重试，收缩压必须高于舒张压。');}});
  document.querySelectorAll('[data-close]').forEach(x=>x.addEventListener('click',()=>x.closest('dialog').close())); window.addEventListener('hashchange',render); render();
})();
