<template>
  <main class="care-center" v-loading="loading">
    <header class="care-header"><div><span class="eyebrow">Family Care</span><h1>{{ mode === 'PATIENT' ? 'Take care of yourself today' : 'Care for a loved one, together' }}</h1><p>Keep schedules, prescriptions, and family handovers in one calm workspace.</p></div><picture class="care-header-art"><source media="(max-width:800px)" :srcset="careMomentsSmall"/><img :src="careMoments" alt="" width="210" height="140" decoding="async"/></picture><div class="mode-switch"><el-radio-group v-model="mode"><el-radio-button value="PATIENT">I am the patient</el-radio-button><el-radio-button value="FAMILY">I am a caregiver</el-radio-button></el-radio-group><el-switch v-model="senior" active-text="Large text"/><el-button @click="reload">Refresh</el-button></div></header>
    <div class="care-toolbar"><el-select v-model="patientId" placeholder="Select a family member" style="max-width:260px"><el-option v-for="p in home" :key="p.patient.id" :label="p.patient.name" :value="p.patient.id"/></el-select><el-button @click="joinVisible=true">Join shared care</el-button><el-button @click="tab='backup'">Backup & restore</el-button></div>
    <section v-if="mode==='FAMILY'" class="family-cards"><button v-for="p in home" :key="p.patient.id" :class="{selected:p.patient.id===patientId}" @click="patientId=p.patient.id"><strong>{{p.patient.name}}</strong><span>{{pendingCount(p)}} items need attention</span><small>{{nextAppointment(p)}}</small></button></section>
    <el-alert v-if="!patientId" title="Select a family member, or join shared care with an invitation code." :closable="false" type="info"/>
    <el-tabs v-model="tab" class="care-tabs">
      <el-tab-pane label="Today" name="today" :disabled="!patientId">
        <section class="quick-actions"><el-button type="primary" @click="quickVisible=true">Record blood pressure or glucose</el-button><el-button @click="open('SYMPTOM')">Record a symptom</el-button><el-button @click="open('QUESTION')">Add a question for the clinician</el-button><el-button v-if="mode==='FAMILY'" @click="open('HANDOVER')">Leave a family handover</el-button></section>
        <div class="care-columns"><section class="care-card"><h2>Today's medications</h2><el-empty v-if="!activeIntakes.length" description="No medication tasks today"/><article v-for="i in activeIntakes" :key="i.id" class="care-task"><div><strong>{{i.scheduledAt?.slice(11,16)}} {{i.drugName}}</strong><p>{{i.dosage}}</p><small v-if="lastActor(i.id)">{{lastActor(i.id)}}</small><small v-if="i.status==='SNOOZED'">Remind again at {{i.snoozeUntil}}</small></div><el-tag>{{statusText(i.status)}}</el-tag><div v-if="['PENDING','MISSED','SNOOZED'].includes(i.status)" class="task-actions"><el-button type="success" :disabled="busy" @click="openIntake(i)">{{mode==='FAMILY'?'Record as taken':'I took this dose'}}</el-button><el-button :disabled="busy" @click="intakeAction(i,'SNOOZED')">Remind in 15 minutes</el-button><el-button :disabled="busy" @click="skipIntake(i)">Skip</el-button></div></article></section>
          <section class="care-card"><h2>Appointments and care tasks</h2><el-empty v-if="!dueTasks.length" description="Nothing needs attention soon"/><article v-for="item in dueTasks" :key="item.id" class="care-task"><div><strong>{{item.title}}</strong><p>{{item.eventAt || 'Time not set'}}</p><small>Assigned to: {{memberName(item.assignedUserId)}} · Recorded by: {{item.actorName||'Family member'}}</small><p>{{item.details?.note || item.details?.preparation}}</p></div><el-button :disabled="busy" type="primary" @click="action(item,'DONE')">Complete</el-button><el-button @click="open(item.kind,item)">View</el-button></article></section></div>
        <el-alert v-for="s in lowStocks" :key="s.id" :title="s.drugName + ' has ' + s.quantity + ' ' + s.unit + ' remaining' + (s.estimatedDays != null ? ' (about ' + s.estimatedDays + ' days). Please plan a refill.' : '. Please check the supply.')" type="warning" :closable="false"/>
      </el-tab-pane>
      <el-tab-pane label="Appointments" name="appointments" :disabled="!patientId">
        <div class="section-head"><h2>Appointments, follow-ups, and companions</h2><el-button type="primary" @click="open('APPOINTMENT')">Add appointment</el-button></div>
        <el-calendar v-model="calendarDate"><template #date-cell="{data}"><div class="calendar-cell"><span>{{data.day.slice(8)}}</span><button v-for="a in appointments.filter(x=>x.eventAt?.startsWith(data.day)&&x.status!=='CANCELLED')" :key="a.id" @click.stop="open('APPOINTMENT',a)">{{a.title}}</button></div></template></el-calendar>
        <el-table :data="appointments"><el-table-column label="Time" prop="eventAt" min-width="165"/><el-table-column label="Appointment" prop="title" min-width="150"/><el-table-column label="Hospital / Department" min-width="150"><template #default="{row}">{{row.details.hospital}} {{row.details.department}}</template></el-table-column><el-table-column label="Companion"><template #default="{row}">{{memberName(row.assignedUserId)}}</template></el-table-column><el-table-column label="Status"><template #default="{row}">{{statusText(row.status)}}</template></el-table-column><el-table-column label="Actions" min-width="190"><template #default="{row}"><el-button link @click="open('APPOINTMENT',row)">Edit / link report</el-button><el-button v-if="row.status==='OPEN'" link type="success" :disabled="busy" @click="action(row,'DONE')">Complete</el-button><el-button v-if="row.status!=='CANCELLED'" link :disabled="busy" @click="action(row,'CANCELLED')">Cancel</el-button></template></el-table-column></el-table>
      </el-tab-pane>
      <el-tab-pane label="Prescriptions" name="orders" :disabled="!patientId">
        <div class="section-head"><div><h2>Follow the current prescription and preserve every change</h2><p>Add the medication first, then enter the clinician's directions and effective date.</p></div><div><el-button @click="$router.push('/medication')">Medication list</el-button><el-button type="primary" @click="open('ORDER')">Add prescription</el-button></div></div>
        <el-empty v-if="!orders.length" description="No prescription versions yet"/>
        <article v-for="order in orders" :key="order.id" class="care-card order-card"><div class="section-head"><h3>{{order.title}}</h3><el-tag>{{statusText(order.status)}}</el-tag></div><p>{{drugName(order.details.medicationId)}} · Starts {{order.details.startDate}}{{order.details.endDate?', ends '+order.details.endDate:''}} · Clinician: {{order.details.doctor||'Not provided'}}</p><p v-if="order.details.action!=='STOP'">{{order.details.doses?.map(d=>d.time+' '+d.quantity+order.details.unit).join('; ')}} · {{daysText(order.details.repeatDays)}}</p><p v-else>This medication was stopped.</p><p>{{order.details.instructions}}</p><div class="attachment-links"><a v-for="(a,i) in order.details.attachments||[]" :key="i" :href="a.dataUrl" :download="a.name">{{a.name}}</a></div><small>Recorded by {{order.actorName}} · Version #{{order.id}}</small><div class="task-actions"><el-button @click="changeOrder(order,'CHANGE')">Add revised version</el-button><el-button v-if="order.status==='ACTIVE'" @click="changeOrder(order,'STOP')">Record stop order</el-button><el-button v-if="order.status==='SCHEDULED'" :disabled="busy" @click="action(order,'CANCELLED')">Cancel scheduled version</el-button></div></article>
      </el-tab-pane>
      <el-tab-pane label="Medication stock" name="stock" :disabled="!patientId">
        <div class="section-head"><h2>Remaining medication</h2><el-button type="primary" @click="openStock()">Set or correct stock</el-button></div><p>Use the same unit as the prescription. Check-ins deduct the prescribed numeric dose; temporary doses can be entered when confirmed.</p>
        <el-table :data="context.stocks||[]"><el-table-column prop="drugName" label="Medication" min-width="150"/><el-table-column label="Remaining"><template #default="{row}">{{row.quantity}} {{row.unit}} <el-tag v-if="row.low" type="warning">Low stock</el-tag></template></el-table-column><el-table-column label="Estimated days"><template #default="{row}">{{row.estimatedDays==null?'No numeric regimen':row.estimatedDays+' days'}}</template></el-table-column><el-table-column label="Actions" min-width="180"><template #default="{row}"><el-button link @click="purchase(row)">Restock</el-button><el-button link @click="openStock(row)">Correct</el-button><el-button link @click="showStockHistory(row)">History</el-button></template></el-table-column></el-table>
      </el-tab-pane>
      <el-tab-pane label="Symptoms" name="symptoms" :disabled="!patientId">
        <div class="section-head"><h2>Track when symptoms started and how they change</h2><el-button type="primary" @click="open('SYMPTOM')">Record symptom</el-button></div><el-select v-model="symptomFilter" clearable placeholder="Select a symptom to view its history"><el-option v-for="name in [...new Set(symptoms.map(s=>s.title))]" :key="name" :value="name"/></el-select>
        <article v-for="s in filteredSymptoms" :key="s.id" class="care-card"><div class="section-head"><h3>{{s.title}}</h3><span>{{s.eventAt}} · {{s.actorName}}</span></div><el-progress :percentage="Number(s.details.severity)*10" :format="()=>s.details.severity+'/10'"/><p>Duration: {{s.details.duration||'Not provided'}}; {{progressText(s.details.progress)}}; {{symptomChange(s)}}</p><p>{{s.details.context}}</p><p>{{s.details.response}}</p><el-button link @click="open('SYMPTOM',s)">Edit</el-button><el-button link @click="open('SYMPTOM',{...s,id:null,eventAt:null})">Record again</el-button><el-popconfirm title="Delete this symptom entry?" @confirm="removeItem(s)"><template #reference><el-button link type="danger">Delete</el-button></template></el-popconfirm></article><el-empty v-if="!filteredSymptoms.length" description="No symptom entries"/>
      </el-tab-pane>
      <el-tab-pane label="Questions" name="questions" :disabled="!patientId">
        <div class="section-head"><h2>Prepare questions before a visit and record answers afterward</h2><div><el-button @click="$router.push('/family-health')">Visit summary & print</el-button><el-button type="primary" @click="open('QUESTION')">Add question</el-button></div></div>
        <article v-for="q in questions" :key="q.id" class="care-card"><div class="section-head"><h3>{{q.title}}</h3><el-tag>{{statusText(q.status)}}</el-tag></div><p>{{q.details.description}}</p><p v-if="q.details.appointmentId">Appointment: {{appointments.find(a=>a.id===q.details.appointmentId)?.title||'Appointment deleted'}}</p><p>Clinician's answer: {{q.details.answer||'Not asked yet'}}</p><p>Follow-up: {{q.details.followUp||'None'}}</p><el-button @click="open('QUESTION',q)">Edit question / answer</el-button><el-button v-if="q.status==='OPEN'" :disabled="busy" @click="answer(q)">Mark answered</el-button><el-button v-if="q.details.followUp" @click="open('HANDOVER',{title:q.details.followUp,details:{note:q.details.answer},kind:'HANDOVER'})">Create care task</el-button><el-popconfirm title="Delete this question?" @confirm="removeItem(q)"><template #reference><el-button link>Delete</el-button></template></el-popconfirm></article><el-empty v-if="!questions.length" description="Keep questions here whenever they come to mind"/>
      </el-tab-pane>
      <el-tab-pane label="Family collaboration" name="family" :disabled="!patientId">
        <div class="section-head"><h2>Shared caregivers</h2><el-button v-if="canManage" type="primary" @click="invite">Generate invitation code</el-button></div><p v-if="inviteCode" class="invite-code">Invitation code (valid for 7 days and one use): <strong>{{inviteCode}}</strong><el-button @click="copyInvite">Copy</el-button></p>
        <el-table :data="context.members||[]"><el-table-column prop="name" label="Name"/><el-table-column prop="username" label="Account"/><el-table-column prop="relationName" label="Relationship"/><el-table-column label="Actions"><template #default="{row}"><el-popconfirm v-if="canManage&&row.userId!==context.patient?.userId" title="Remove this account from shared care?" @confirm="removeMember(row)"><template #reference><el-button link type="danger">Remove</el-button></template></el-popconfirm></template></el-table-column></el-table>
        <div class="section-head"><h2>Care handovers</h2><el-button @click="open('HANDOVER')">Add handover</el-button></div><article v-for="h in handovers" :key="h.id" class="care-card"><strong>{{h.title}}</strong><p>{{h.details.note}}</p><small>{{h.actorName}} assigned this to {{memberName(h.assignedUserId)}} · {{h.eventAt||'No due time'}} · {{statusText(h.status)}}</small><div class="task-actions"><el-button @click="open('HANDOVER',h)">Edit</el-button><el-button v-if="h.status==='OPEN'" :disabled="busy" @click="action(h,'DONE')">Complete</el-button></div></article>
        <h2>Recent activity</h2><el-table :data="activities.slice(0,50)"><el-table-column prop="eventAt" label="Time"/><el-table-column prop="actorName" label="Recorded by"/><el-table-column prop="title" label="Action"/></el-table>
      </el-tab-pane>
      <el-tab-pane label="Care settings" name="settings" :disabled="!patientId">
        <el-form label-position="top" style="max-width:650px"><h2>{{context.patient?.name}}'s care settings</h2><el-form-item label="Enable dialysis features"><el-switch v-model="profile.dialysisEnabled"/><p>When disabled, dialysis and dry-weight links are hidden. Existing records remain available.</p></el-form-item><el-form-item label="Notify a caregiver about overdue tasks"><el-select v-model="profile.escalationUserId" clearable placeholder="No additional follow-up notification"><el-option v-for="m in context.members||[]" :key="m.userId" :value="m.userId" :label="m.name"/></el-select></el-form-item><el-form-item label="Minutes overdue before caregiver follow-up"><el-input-number v-model="profile.escalationMinutes" :min="15" :step="15"/></el-form-item><el-button type="primary" :loading="busy" @click="saveProfile">Save settings</el-button><el-button @click="$router.push('/settings/notifications')">Notification channels</el-button></el-form>
      </el-tab-pane>
      <el-tab-pane label="Backup & restore" name="backup"><FamilyBackupPanel @restored="reload"/></el-tab-pane>
    </el-tabs>
    <CareEntryDialog v-model="entryVisible" :kind="entryKind" :row="entryRow" :patient-id="patientId" :members="context.members" :medications="context.medications" :reports="context.reports" :appointments="appointments" @saved="reload"/>
    <el-dialog v-model="quickVisible" title="Record blood pressure / glucose" width="min(460px,94vw)"><el-form label-position="top"><el-form-item label="Systolic / diastolic (mmHg)"><el-input-number v-model="quick.systolicBp" :min="1"/> / <el-input-number v-model="quick.diastolicBp" :min="1"/></el-form-item><el-form-item label="Blood glucose (mmol/L, optional)"><el-input-number v-model="quick.bloodGlucose" :min="0.1" :precision="1"/></el-form-item><el-form-item label="Measurement period"><el-select v-model="quick.measurePeriod"><el-option label="Fasting" value="Fasting"/><el-option label="After meal" value="After Meal"/><el-option label="Random" value="Random"/></el-select></el-form-item><el-form-item label="Notes"><el-input v-model="quick.remark"/></el-form-item></el-form><template #footer><el-button :loading="busy" type="primary" @click="submitQuick">Save reading</el-button></template></el-dialog>
    <el-dialog v-model="intakeVisible" :title="mode==='FAMILY'?'Record a dose for a family member':'Confirm this dose'" width="min(460px,94vw)"><p>{{selectedIntake?.drugName}} · {{selectedIntake?.dosage}}</p><el-form label-position="top"><el-form-item label="Actual quantity (optional, in the inventory unit)"><el-input-number v-model="intakeQuantity" :min="0.001" :precision="3"/></el-form-item><p>If left blank, stock is deducted only when the prescribed dose and inventory use the same unit.</p></el-form><template #footer><el-button :loading="busy" type="success" @click="confirmIntake">Confirm taken</el-button></template></el-dialog>
    <el-dialog v-model="stockVisible" title="Set or correct inventory" width="min(480px,94vw)"><el-form label-position="top"><el-form-item label="Medication"><el-select v-model="stockForm.medicationId" :disabled="!!stockForm.id"><el-option v-for="m in context.medications||[]" :key="m.id" :value="m.id" :label="m.drugName"/></el-select></el-form-item><el-form-item label="Actual quantity remaining"><el-input-number v-model="stockForm.quantity" :min="0" :precision="3"/></el-form-item><el-form-item label="Unit (must match the prescription)"><el-input v-model="stockForm.unit"/></el-form-item><el-form-item label="Warn when this many days remain"><el-input-number v-model="stockForm.warningDays" :min="0"/></el-form-item><el-form-item label="Or warn below this quantity"><el-input-number v-model="stockForm.warningQuantity" :min="0"/></el-form-item></el-form><template #footer><el-button :loading="busy" type="primary" @click="submitStock">Save</el-button></template></el-dialog>
    <el-dialog v-model="historyVisible" title="Inventory history" width="min(800px,94vw)"><el-table :data="stockHistory"><el-table-column prop="created_at" label="Time"/><el-table-column prop="quantity" label="Quantity change"/><el-table-column prop="reason" label="Reason"/><el-table-column prop="actor_name" label="Recorded by"/></el-table></el-dialog>
    <el-dialog v-model="joinVisible" title="Join shared care" width="min(460px,94vw)"><p>Ask the owner of this family member's record for an invitation code.</p><el-input v-model="joinCode" placeholder="Paste invitation code"/><el-input v-model="joinRelation" placeholder="Your relationship to the patient, for example: Daughter" style="margin-top:14px"/><template #footer><el-button type="primary" :loading="busy" @click="join">Join</el-button></template></el-dialog>
  </main>
</template>
<script setup>
import {ref,reactive,computed,watch,onMounted,onUnmounted} from 'vue'
import {ElMessage,ElMessageBox} from 'element-plus'
import {useCurrentPatient} from '@/composables/useCurrentPatient'
import * as api from '@/api/care'
import CareEntryDialog from '@/components/CareEntryDialog.vue'
import FamilyBackupPanel from '@/components/FamilyBackupPanel.vue'
import {localDateKey} from '@/utils/familyHealth'
import careMoments from '@/assets/illustrations/care-moments.webp'
import careMomentsSmall from '@/assets/illustrations/care-moments-small.webp'
const {currentPatientId:patientId,setPatientList}=useCurrentPatient()
const mode=ref(localStorage.getItem('care-mode')||'PATIENT'),senior=ref(localStorage.getItem('care-senior')==='true'),tab=ref('today'),home=ref([]),context=ref({}),loading=ref(false),busy=ref(false)
const entryVisible=ref(false),entryKind=ref('APPOINTMENT'),entryRow=ref(null),calendarDate=ref(new Date()),symptomFilter=ref('')
const quickVisible=ref(false),quick=reactive({systolicBp:undefined,diastolicBp:undefined,bloodGlucose:undefined,measurePeriod:localStorage.getItem('care-measure-period')||'Fasting',remark:''})
const intakeVisible=ref(false),selectedIntake=ref(null),intakeQuantity=ref(undefined),stockVisible=ref(false),stockForm=reactive({}),historyVisible=ref(false),stockHistory=ref([])
const joinVisible=ref(false),joinCode=ref(''),joinRelation=ref('family caregiver'),inviteCode=ref(''),profile=reactive({dialysisEnabled:true,escalationUserId:null,escalationMinutes:60})
const items=computed(()=>context.value.items||[]),byKind=kind=>computed(()=>items.value.filter(i=>i.kind===kind))
const appointments=byKind('APPOINTMENT'),orders=byKind('ORDER'),symptoms=byKind('SYMPTOM'),questions=byKind('QUESTION'),handovers=byKind('HANDOVER'),activities=byKind('ACTIVITY')
const activeIntakes=computed(()=>(context.value.intakes||[]).filter(i=>i.status!=='CANCELLED')),lowStocks=computed(()=>(context.value.stocks||[]).filter(s=>s.low))
const filteredSymptoms=computed(()=>symptoms.value.filter(s=>!symptomFilter.value||s.title===symptomFilter.value))
const dueTasks=computed(()=>items.value.filter(i=>['APPOINTMENT','HANDOVER'].includes(i.kind)&&i.status==='OPEN'&&(!i.eventAt||new Date(i.eventAt.replace(' ','T')).getTime()<Date.now()+7*86400000)))
const canManage=computed(()=>Number(localStorage.getItem('userId'))===context.value.patient?.userId||JSON.parse(localStorage.getItem('userRoleCodes')||'[]').includes('admin'))
watch(mode,v=>localStorage.setItem('care-mode',v));watch(senior,v=>{localStorage.setItem('care-senior',v);document.body.classList.toggle('care-senior',v)},{immediate:true})
let generation=0,timer
async function reload(){const v=++generation;loading.value=true;try{const r=await api.getCareHome();if(v!==generation)return;home.value=r.data||[];setPatientList(home.value.map(x=>({id:x.patient.id,patientName:x.patient.name})));if(!patientId.value&&home.value.length){patientId.value=home.value[0].patient.id;return}if(patientId.value){const id=patientId.value,c=await api.getCareContext(id);if(v!==generation||id!==patientId.value)return;context.value=c.data||{};const p=items.value.find(x=>x.kind==='PROFILE');Object.assign(profile,{dialysisEnabled:true,escalationUserId:null,escalationMinutes:60},p?.details||{});localStorage.setItem(`care-profile:${id}`,JSON.stringify(profile));window.dispatchEvent(new Event('care-profile-changed'))}}finally{if(v===generation)loading.value=false}}
watch(patientId,()=>{generation++;context.value={};entryVisible.value=false;quickVisible.value=false;intakeVisible.value=false;stockVisible.value=false;inviteCode.value='';reload()})
onMounted(()=>{reload();timer=setInterval(()=>{if(!busy.value&&!entryVisible.value&&!stockVisible.value&&!quickVisible.value&&!intakeVisible.value&&tab.value==='today')reload()},60000)})
onUnmounted(()=>{generation++;clearInterval(timer)})
async function perform(operation){if(busy.value)return;busy.value=true;try{await operation();ElMessage.success('Saved successfully.');await reload()}finally{busy.value=false}}
function open(kind,row){if(!patientId.value)return;entryKind.value=kind;entryRow.value=row||null;entryVisible.value=true}
function changeOrder(row,action){const data=JSON.parse(JSON.stringify(row));delete data.id;data.details.action=action;data.details.startDate=localDateKey();data.details.endDate=null;data.title=`${drugName(data.details.medicationId)}${action==='STOP'?'stop medication':'medication adjustment'}`;open('ORDER',data)}
async function action(row,status){await perform(()=>api.careAction(row.id,status))}
async function removeItem(row){await perform(()=>api.deleteCareItem(row.id))}
async function answer(row){const r=await ElMessageBox.prompt("Record the clinician's answer",'Visit answer',{inputType:'textarea',inputValue:row.details.answer||''}).catch(()=>null);if(r)await perform(()=>api.careAction(row.id,'ANSWERED',r.value))}
async function submitQuick(){const data={...quick,patientId:patientId.value};await perform(async()=>{await api.quickVitals(data);quickVisible.value=false;localStorage.setItem('care-measure-period',quick.measurePeriod);Object.assign(quick,{systolicBp:undefined,diastolicBp:undefined,bloodGlucose:undefined,remark:''})})}
function openIntake(i){selectedIntake.value=i;intakeQuantity.value=undefined;intakeVisible.value=true}
async function confirmIntake(){await intakeAction(selectedIntake.value,'TAKEN','',intakeQuantity.value);intakeVisible.value=false}
async function intakeAction(i,status,reason='',quantity){await perform(()=>api.recordIntake(i.id,status,reason,quantity,mode.value==='FAMILY'?'FAMILY':'SELF'))}
async function skipIntake(i){const r=await ElMessageBox.prompt('Reason for skipping','Skip this dose').catch(()=>null);if(r)await intakeAction(i,'SKIPPED',r.value)}
function openStock(row){Object.assign(stockForm,{id:null,medicationId:null,quantity:0,unit:'tablet',warningDays:7,warningQuantity:0},row?{id:row.id,medicationId:row.medication_id,quantity:Number(row.quantity),unit:row.unit,warningDays:row.warning_days,warningQuantity:Number(row.warning_quantity)}:{});stockVisible.value=true}
async function submitStock(){await perform(async()=>{await api.saveStock({...stockForm,patientId:patientId.value});stockVisible.value=false})}
async function purchase(row){const pid=patientId.value,r=await ElMessageBox.prompt(`How many ${row.unit} should be added?`,row.drugName,{inputPattern:/^\d+(\.\d{1,3})?$/,inputErrorMessage:'Enter a valid number'}).catch(()=>null);if(r&&pid===patientId.value)await perform(()=>api.purchaseStock({patientId:pid,medicationId:row.medication_id,quantity:Number(r.value),reason:'Restock'}))}
async function showStockHistory(row){stockHistory.value=(await api.getStockHistory(patientId.value,row.medication_id)).data||[];historyVisible.value=true}
async function invite(){inviteCode.value=(await api.createCareInvite(patientId.value)).data}
async function copyInvite(){try{await navigator.clipboard.writeText(inviteCode.value);ElMessage.success('Invitation code copied.')}catch{ElMessage.info('Select and copy the invitation code manually.')}}
async function join(){await perform(async()=>{const r=await api.joinCare(joinCode.value.trim(),joinRelation.value);joinVisible.value=false;patientId.value=r.data;window.dispatchEvent(new Event('care-patients-changed'))})}
async function removeMember(row){await perform(()=>api.removeCareMember(patientId.value,row.userId))}
async function saveProfile(){await perform(()=>api.saveCareItem({patientId:patientId.value,kind:'PROFILE',title:'Care settings',details:{...profile}}))}
function memberName(id){return context.value.members?.find(m=>m.userId===id)?.name||'not specified'}
function drugName(id){return context.value.medications?.find(m=>m.id===id)?.drugName||'Medication'}
function lastActor(id){const a=context.value.actions?.find(x=>x.intake_id===id);return a?`${a.actor_name||'Family member'} ${a.recorded_for==='FAMILY'?'recorded for the patient':'recorded'}: ${statusText(a.status)}`:''}
function pendingCount(p){return(p.intakes||[]).filter(i=>['PENDING','MISSED','SNOOZED'].includes(i.status)).length+(p.items||[]).filter(i=>['APPOINTMENT','HANDOVER'].includes(i.kind)&&i.status==='OPEN').length}
function nextAppointment(p){const a=(p.items||[]).filter(i=>i.kind==='APPOINTMENT'&&i.status==='OPEN').sort((a,b)=>(a.eventAt||'').localeCompare(b.eventAt||''))[0];return a?`${a.eventAt?.slice(0,16)} ${a.title}`:'No upcoming appointment'}
function symptomChange(s){const previous=symptoms.value.filter(x=>x.title===s.title&&x.id!==s.id&&(x.eventAt||'')<(s.eventAt||'')).sort((a,b)=>(b.eventAt||'').localeCompare(a.eventAt||''))[0];if(!previous)return'First entry';const diff=Number(s.details.severity)-Number(previous.details.severity);return diff===0?'Same score as the previous entry':`${Math.abs(diff)} point${Math.abs(diff)===1?'':'s'} ${diff>0?'higher':'lower'} than the previous entry`}
const progressText=s=>({ONGOING:'Symptoms continue',IMPROVED:'Improved',RESOLVED:'Resolved'}[s]||'Not provided')
const statusText=s=>({OPEN:'Open',DONE:'Completed',CANCELLED:'Cancelled',ACTIVE:'Active',SCHEDULED:'Scheduled',STOPPED:'Stopped',ANSWERED:'Answered',RESOLVED:'Resolved',PENDING:'Due',MISSED:'Missed',SNOOZED:'Snoozed',TAKEN:'Taken',SKIPPED:'Skipped'}[s]||s)
const daysText=s=>String(s||'').split(',').map(x=>['','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'][Number(x)]).join(', ')
</script>
<style scoped>
.care-header{position:relative}
.care-center{max-width:1400px;margin:auto;padding:30px}.care-header,.section-head{display:flex;justify-content:space-between;gap:20px;align-items:center;margin-bottom:20px}.care-header>div:first-child{min-width:0;flex:1}.care-header-art{width:210px;height:140px;flex:0 0 auto}.care-header-art img{display:block;width:100%;height:100%;object-fit:contain}.care-header h1{font-size:28px;margin:8px 0}.care-header p,.care-center small{color:#64748b}.eyebrow{color:#267266;font-weight:700}.mode-switch,.care-toolbar,.quick-actions,.task-actions,.attachment-links{display:flex;gap:12px;flex-wrap:wrap;align-items:center}.mode-switch{justify-content:flex-end}.care-toolbar,.quick-actions{margin:18px 0}.family-cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:14px;margin:20px 0}.family-cards button{background:#fff;border:1px solid #dde8e5;border-radius:14px;padding:18px;text-align:left;display:flex;flex-direction:column;gap:8px;cursor:pointer}.family-cards button.selected{border:2px solid #267266;background:#f0f9f6}.family-cards strong{font-size:20px}.care-tabs{background:#fff;border:1px solid #dde8e5;border-radius:16px;padding:22px}.care-columns{display:grid;grid-template-columns:1fr 1fr;gap:20px}.care-card{padding:20px;border:1px solid #e3ece9;border-radius:14px;margin-bottom:18px;background:#fff}.care-card h2,.care-card h3{margin:0 0 12px}.care-card p{line-height:1.7}.care-task{padding:16px 0;display:flex;flex-wrap:wrap;gap:10px;align-items:center;border-bottom:1px solid #e7eeeb}.care-task>div:first-child{flex:1;min-width:180px}.care-task small{display:block}.task-actions{margin-top:12px}.calendar-cell button{display:block;border:0;background:#e8f4ee;color:#226854;padding:3px;text-align:left;width:100%;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;border-radius:4px;cursor:pointer;margin-top:4px}.invite-code{padding:16px;background:#f0f9f6;overflow-wrap:anywhere}.attachment-links{margin:14px 0}.order-card small{display:block}@media(max-width:1050px){.care-header-art{width:150px;height:100px}}@media(max-width:800px){.care-center{padding:16px}.care-header,.section-head{align-items:flex-start;flex-direction:column}.care-header-art{position:absolute;right:16px;width:108px;height:72px;opacity:.9}.care-header>div:first-child{padding-right:100px}.mode-switch{justify-content:flex-start}.care-columns{grid-template-columns:1fr}.care-tabs{padding:12px}.quick-actions .el-button{flex:1;min-width:140px;margin:0}.care-header h1{font-size:25px}.care-tabs :deep(.el-calendar__body){padding:0}.care-tabs :deep(.el-calendar-day){height:85px;padding:4px}}
</style>
