<template>
  <main class="journey-page">
    <header class="journey-hero">
      <div><span>CONTINUOUS CARE</span><h1>Care journey</h1><p>Measurements, appointments, consultation, recovery, emergency information, specialty care, privacy, and operations in one traceable workspace.</p></div>
      <el-tag v-if="tab === 'consultation' && isDoctor" effect="plain">Consultation inbox</el-tag>
      <el-tag v-else effect="plain">Patient {{ currentPatientName || currentPatientId || 'not selected' }}</el-tag>
    </header>

    <el-alert v-if="patientRequired && !currentPatientId" title="Select a patient from the workspace header before using this module." type="warning" show-icon :closable="false" />
    <el-tabs v-model="tab" class="journey-tabs" @tab-change="syncTab">
      <el-tab-pane label="Measurements" name="measurements">
        <section class="panel-grid two">
          <el-card><template #header><b>Record a health measurement</b></template><el-form :disabled="busy || (patientRequired && !currentPatientId)" label-position="top">
            <div class="form-grid"><el-form-item label="Metric"><el-select v-model="measurement.metricType"><el-option v-for="item in metricOptions" :key="item.value" v-bind="item" /></el-select></el-form-item><el-form-item label="Measured at"><el-date-picker v-model="measurement.measuredAt" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss" /></el-form-item><el-form-item label="Primary value"><el-input-number v-model="measurement.valuePrimary" :precision="2" /></el-form-item><el-form-item v-if="measurement.metricType==='BP'" label="Diastolic"><el-input-number v-model="measurement.valueSecondary" /></el-form-item><el-form-item label="Unit"><el-input v-model="measurement.unit" /></el-form-item><el-form-item label="Notes"><el-input v-model="measurement.remark" /></el-form-item></div>
            <el-button type="primary" :loading="busy" @click="recordMeasurement">Save and evaluate</el-button>
          </el-form></el-card>
          <el-card><template #header><div class="card-head"><b>Trend records</b><el-button @click="loadMeasurements">Refresh</el-button></div></template><el-table :data="measurements" max-height="440"><el-table-column prop="measured_at" label="Time" width="165"/><el-table-column prop="metric_type" label="Metric" width="110"/><el-table-column label="Value"><template #default="{row}">{{row.value_primary}}{{row.value_secondary!=null?'/'+row.value_secondary:''}} {{row.unit}}</template></el-table-column><el-table-column prop="status" label="Status" width="100"><template #default="{row}"><el-tag :type="row.status==='NORMAL'?'success':'danger'">{{row.status}}</el-tag></template></el-table-column><el-table-column v-if="isDoctor" label="Clinical note" width="130"><template #default="{row}"><el-button link @click="annotate(row)">Annotate</el-button></template></el-table-column></el-table></el-card>
        </section>
      </el-tab-pane>

      <el-tab-pane label="Appointments & visits" name="appointments">
        <section class="panel-grid two">
          <el-card><template #header><b>Book or reschedule</b></template><el-form :disabled="busy || (patientRequired && !currentPatientId)" label-position="top"><div class="form-grid"><el-form-item label="Clinician"><el-select v-model="appointment.doctorUserId" @change="changeAppointmentDoctor"><el-option v-for="d in clinicians" :key="d.id" :label="d.real_name||d.username" :value="d.id"/></el-select></el-form-item><el-form-item label="Available session"><el-select v-model="appointment.scheduleId" clearable @change="selectSchedule"><el-option v-for="s in doctorSchedules" :key="s.id" :value="s.id" :label="`${s.work_date} ${s.start_time}-${s.end_time}`"/></el-select></el-form-item><el-form-item label="Mode"><el-select v-model="appointment.consultationMode"><el-option label="In person" value="IN_PERSON"/><el-option label="Text" value="TEXT"/><el-option label="Voice" value="VOICE"/><el-option label="Video" value="VIDEO"/></el-select></el-form-item><el-form-item label="Start"><el-date-picker v-model="appointment.startAt" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss"/></el-form-item><el-form-item label="End"><el-date-picker v-model="appointment.endAt" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss"/></el-form-item><el-form-item label="Repeat follow-up every (days)"><el-input-number v-model="appointment.recurrenceDays" :min="0"/></el-form-item><el-form-item label="Reason"><el-input v-model="appointment.reason"/></el-form-item></div><el-button type="primary" @click="bookAppointment">Save appointment</el-button></el-form></el-card>
          <el-card><template #header><b>Shared schedule</b></template><el-table :data="appointments" max-height="430"><el-table-column prop="start_at" label="Start" width="165"/><el-table-column prop="doctor_name" label="Clinician"/><el-table-column prop="consultation_mode" label="Mode"/><el-table-column prop="status" label="Status"/><el-table-column label="Actions" width="150"><template #default="{row}"><el-button v-if="row.status==='BOOKED'" link @click="editAppointment(row)">Reschedule</el-button><el-button v-if="row.status==='BOOKED'" link type="danger" @click="cancel(row)">Cancel</el-button></template></el-table-column></el-table></el-card>
        </section>
        <el-card v-if="isDoctor" class="section-card"><template #header><b>Post-visit summary, prescription, and follow-up</b></template><el-form :disabled="busy || (patientRequired && !currentPatientId)" label-position="top"><div class="form-grid"><el-form-item label="Diagnosis summary"><el-input v-model="visit.diagnosisSummary" type="textarea"/></el-form-item><el-form-item label="Treatment summary"><el-input v-model="visit.treatmentSummary" type="textarea"/></el-form-item><el-form-item label="Follow-up advice"><el-input v-model="visit.followUpAdvice" type="textarea"/></el-form-item><el-form-item label="Follow-up time"><el-date-picker v-model="visit.followUpAt" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss"/></el-form-item></div><el-button type="primary" @click="createVisit">Save summary</el-button></el-form><el-divider>Electronic prescription record</el-divider><el-form :disabled="busy || (patientRequired && !currentPatientId)" label-position="top"><div class="form-grid"><el-form-item label="Drug"><el-input v-model="prescription.drugName"/></el-form-item><el-form-item label="Dose"><el-input v-model="prescription.dosage" placeholder="e.g. 5 mg"/></el-form-item><el-form-item label="Frequency"><el-input v-model="prescription.frequency" placeholder="e.g. twice daily"/></el-form-item><el-form-item label="Route"><el-input v-model="prescription.administrationRoute" placeholder="oral / topical"/></el-form-item><el-form-item label="Duration days"><el-input-number v-model="prescription.durationDays" :min="1"/></el-form-item><el-form-item label="Instructions"><el-input v-model="prescription.instructions"/></el-form-item></div><el-button type="primary" @click="savePrescription">Publish prescription version</el-button></el-form></el-card>
        <el-card class="section-card"><template #header><b>Visit timeline</b></template><el-timeline><el-timeline-item v-for="v in visits" :key="v.id" :timestamp="v.visited_at"><b>{{v.diagnosis_summary||'Visit summary'}}</b><p>{{v.treatment_summary}}</p><el-button v-if="isDoctor&&v.status!=='PUBLISHED'" link @click="publish(v)">Publish to patient and family</el-button></el-timeline-item></el-timeline></el-card>
        <el-card class="section-card"><template #header><b>Electronic prescriptions and medication instructions</b></template><el-empty v-if="!prescriptions.length" description="No published prescriptions yet" :image-size="60"/><article v-for="entry in prescriptions" :key="entry.id" class="prescription-version"><div class="card-head"><b>Version {{entry.version_no}}</b><el-tag :type="entry.status==='ACTIVE'?'success':'info'">{{entry.status==='ACTIVE'?'Current instructions':'Previous version'}}</el-tag></div><p>{{String(entry.published_at||'').replace('T',' ')}} · {{entry.instructions}}</p><el-table :data="entry.items||[]"><el-table-column prop="drug_name" label="Medicine" min-width="140"/><el-table-column prop="dosage" label="Dose" min-width="110"/><el-table-column prop="frequency" label="Frequency" min-width="110"/><el-table-column prop="administration_route" label="Route" min-width="100"/><el-table-column prop="duration_days" label="Days" width="105"/></el-table></article></el-card>
      </el-tab-pane>

      <el-tab-pane label="Remote consultation" name="consultation">
        <ConsultationWorkspace :patient-id="currentPatientId" :is-doctor="isDoctor" :enabled="tab === 'consultation'" locale="en" />
      </el-tab-pane>

      <el-tab-pane label="Inpatient & recovery" name="recovery">
        <section class="panel-grid two"><el-card v-if="isDoctor"><template #header><b>Treatment plan</b></template><el-form :disabled="busy || (patientRequired && !currentPatientId)" label-position="top"><el-form-item label="Plan type"><el-select v-model="plan.planType"><el-option v-for="x in ['INPATIENT','SURGERY','REHAB','DISCHARGE']" :key="x" :value="x" :label="x"/></el-select></el-form-item><el-form-item label="Title"><el-input v-model="plan.title"/></el-form-item><el-form-item label="Structured plan"><el-input v-model="planText" type="textarea" :rows="6" placeholder="Checks, surgery time, medication adjustment, discharge instructions"/></el-form-item><el-button type="primary" @click="createPlan">Publish plan</el-button></el-form></el-card><el-card><template #header><b>Active treatment plans</b></template><el-collapse><el-collapse-item v-for="p in plans" :key="p.id" :title="p.title"><p>{{p.plan_type}} · {{p.status}}</p><pre>{{prettyJson(p.plan_json)}}</pre></el-collapse-item></el-collapse></el-card></section>
        <el-card class="section-card"><template #header><b>Rehabilitation, wound, drain, and symptom check-in</b></template><el-form :disabled="busy || (patientRequired && !currentPatientId)" label-position="top"><div class="form-grid"><el-form-item label="Record type"><el-select v-model="rehab.recordType"><el-option v-for="x in ['EXERCISE','WOUND','DRAIN','SYMPTOM']" :key="x" :value="x" :label="x"/></el-select></el-form-item><el-form-item label="Completion"><el-slider v-model="rehab.completionPercent"/></el-form-item><el-form-item label="Instruction/action video URL"><el-input v-model="rehab.videoUrl"/></el-form-item><el-form-item label="Structured observation"><el-input v-model="rehabText" type="textarea" placeholder="Wound appearance, drainage volume, symptom severity, or exercise notes"/></el-form-item><el-form-item label="Needs clinician attention"><el-switch v-model="rehab.abnormal"/></el-form-item></div><el-button type="primary" @click="checkinRehab">Save check-in</el-button></el-form><el-table :data="rehabRows"><el-table-column prop="recorded_at" label="Time"/><el-table-column prop="record_type" label="Type"/><el-table-column prop="completion_percent" label="Completion"/><el-table-column prop="abnormal" label="Alert"/></el-table></el-card>
      </el-tab-pane>

      <el-tab-pane label="Emergency" name="emergency">
        <section class="panel-grid two"><el-card class="emergency-card"><template #header><b>One-touch emergency call</b></template><p>Records your location and medical snapshot, then attempts to notify bound family and clinicians. Check the delivery result after sending.</p><el-input v-model="emergency.locationText" placeholder="Location description"/><el-button type="danger" size="large" :loading="busy" :disabled="!currentPatientId" @click="sos">Send emergency call</el-button></el-card><el-card><template #header><div class="card-head"><b>Offline medical information card</b><el-button @click="loadEmergencyCard">Refresh</el-button></div></template><div v-if="emergencyCard"><h3>{{emergencyCard.patient?.name}}</h3><p><b>History:</b> {{emergencyCard.patient?.medical_history||'-'}}</p><p><b>Allergies:</b> {{emergencyCard.clinical?.allergy_drugs||'-'}}</p><p><b>Blood type:</b> {{emergencyCard.clinical?.blood_type||'Not recorded'}}</p><p><b>Medication:</b> {{(emergencyCard.medications||[]).map(x=>x.drug_name).join(', ')||'-'}}</p><el-tag>Cached for offline reading on this device</el-tag></div></el-card></section>
        <el-card class="section-card"><template #header><div class="card-head"><b>Emergency events</b><el-button @click="loadEmergencyEvents">Refresh</el-button></div></template>
          <el-table :data="emergencyEvents" empty-text="No emergency events for this patient"><el-table-column prop="triggered_at" label="Time" min-width="165"/><el-table-column prop="location_text" label="Location" min-width="160"/><el-table-column label="Details" width="110"><template #default="{row}"><el-button link @click="openEmergency(row)">View</el-button></template></el-table-column></el-table>
          <div v-if="selectedEmergency" class="emergency-event-detail"><h3>Emergency #{{ selectedEmergency.id }}</h3><p>Location: {{selectedEmergency.location_text||'-'}} <span v-if="selectedEmergency.latitude!=null&&selectedEmergency.longitude!=null">({{selectedEmergency.latitude}}, {{selectedEmergency.longitude}})</span></p><p>History: {{selectedEmergency.snapshot?.patient?.medical_history||'-'}}</p><p>Allergies: {{selectedEmergency.snapshot?.clinical?.allergy_drugs||'-'}}</p><p>Medication: {{(selectedEmergency.snapshot?.medications||[]).map(x=>x.drug_name).join(', ')||'-'}}</p></div>
        </el-card>
      </el-tab-pane>

      <el-tab-pane label="Children & maternity" name="specialty">
        <section class="panel-grid three"><el-card><template #header><b>Growth curve</b></template><el-form :disabled="busy || (patientRequired && !currentPatientId)" label-position="top"><el-form-item label="Date"><el-date-picker v-model="growth.recordDate" value-format="YYYY-MM-DD"/></el-form-item><el-form-item label="Height cm"><el-input-number v-model="growth.heightCm"/></el-form-item><el-form-item label="Weight kg"><el-input-number v-model="growth.weightKg" :precision="2"/></el-form-item><el-form-item label="Head circumference cm"><el-input-number v-model="growth.headCircumferenceCm" :precision="1"/></el-form-item><el-form-item label="Standard percentiles"><div class="inline"><el-input-number v-model="growth.heightPercentile" placeholder="Height %"/><el-input-number v-model="growth.weightPercentile" placeholder="Weight %"/></div></el-form-item><el-button type="primary" @click="saveSpecial('growth',growth)">Save</el-button></el-form></el-card><el-card><template #header><b>Vaccination plan</b></template><el-form :disabled="busy || (patientRequired && !currentPatientId)" label-position="top"><el-form-item label="Vaccine"><el-input v-model="vaccine.vaccineName"/></el-form-item><el-form-item label="Dose"><el-input v-model="vaccine.doseNo"/></el-form-item><el-form-item label="Planned date"><el-date-picker v-model="vaccine.plannedDate" value-format="YYYY-MM-DD"/></el-form-item><el-form-item label="Reminder"><el-date-picker v-model="vaccine.remindAt" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss"/></el-form-item><el-button type="primary" @click="saveSpecial('vaccination',vaccine)">Save</el-button></el-form></el-card><el-card><template #header><b>Prenatal/postpartum timeline</b></template><el-form :disabled="busy || (patientRequired && !currentPatientId)" label-position="top"><el-form-item label="Type"><el-select v-model="maternity.recordType"><el-option label="Prenatal" value="PRENATAL"/><el-option label="Delivery" value="DELIVERY"/><el-option label="Postpartum" value="POSTPARTUM"/></el-select></el-form-item><el-form-item label="Date"><el-date-picker v-model="maternity.recordDate" value-format="YYYY-MM-DD"/></el-form-item><el-form-item label="Title"><el-input v-model="maternity.title"/></el-form-item><el-form-item label="Details"><el-input v-model="maternityText" type="textarea"/></el-form-item><el-button type="primary" @click="saveMaternity">Save</el-button></el-form></el-card></section>
        <el-card class="section-card"><template #header><div class="card-head"><b>Specialty health records</b><el-button @click="loadSpecialty">Refresh</el-button></div></template><el-tabs><el-tab-pane label="Growth"><el-table :data="specialtyRows.growth"><el-table-column prop="record_date" label="Date"/><el-table-column prop="height_cm" label="Height (cm)"/><el-table-column prop="weight_kg" label="Weight (kg)"/><el-table-column prop="head_circumference_cm" label="Head circumference (cm)"/></el-table></el-tab-pane><el-tab-pane label="Vaccinations"><el-table :data="specialtyRows.vaccination"><el-table-column prop="vaccine_name" label="Vaccine"/><el-table-column prop="dose_no" label="Dose"/><el-table-column prop="planned_date" label="Planned date"/><el-table-column prop="remind_at" label="Reminder"/></el-table></el-tab-pane><el-tab-pane label="Maternity"><el-table :data="specialtyRows.maternity"><el-table-column prop="record_date" label="Date"/><el-table-column prop="title" label="Title"/><el-table-column label="Details"><template #default="{row}">{{specialtyDetail(row.data_json)}}</template></el-table-column></el-table></el-tab-pane></el-tabs></el-card>
      </el-tab-pane>

      <el-tab-pane label="Mental health" name="mental">
        <section class="panel-grid two"><el-card><template #header><b>Private self-assessment</b></template><el-form :disabled="busy || (patientRequired && !currentPatientId)" label-position="top"><el-form-item label="Scale"><el-select v-model="mental.scaleCode"><el-option label="PHQ-9" value="PHQ9"/><el-option label="GAD-7" value="GAD7"/><el-option label="WHO-5" value="WHO5"/></el-select></el-form-item><el-form-item label="Completed questionnaire scores (in question order)"><el-input v-model="mentalAnswers" :placeholder="mental.scaleCode==='PHQ9'?'0,1,2,1,0,1,0,0,0':mental.scaleCode==='GAD7'?'0,1,2,1,0,1,0':'3,4,3,4,3'"/></el-form-item><el-form-item label="Visible to family"><el-switch v-model="mentalVisible"/></el-form-item><el-button type="primary" @click="submitMental">Submit privately</el-button></el-form></el-card><el-card><template #header><b>Periodic delivery</b></template><el-form :disabled="busy || (patientRequired && !currentPatientId)" label-position="top"><el-form-item label="Interval days"><el-input-number v-model="mentalSchedule.intervalDays" :min="1"/></el-form-item><el-form-item label="Next due"><el-date-picker v-model="mentalSchedule.nextDueAt" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss"/></el-form-item><el-button type="primary" @click="scheduleMental">Schedule</el-button></el-form><el-table :data="mentalRows"><el-table-column prop="submitted_at" label="Submitted"/><el-table-column prop="scale_code" label="Scale"/><el-table-column prop="score" label="Score"/><el-table-column prop="severity" label="Screening result"><template #default="{row}">{{mentalSeverityLabel(row)}}</template></el-table-column></el-table></el-card></section>
        <el-card class="section-card"><template #header><b>Assessment reminder plans</b></template><el-table :data="mentalSchedules" empty-text="No reminder plans"><el-table-column prop="scale_code" label="Scale"/><el-table-column prop="interval_days" label="Interval (days)"/><el-table-column prop="next_due_at" label="Next due"/><el-table-column label="Status"><template #default="{row}">{{row.enabled===1?'Active':'Stopped'}}</template></el-table-column><el-table-column label="Action"><template #default="{row}"><el-button v-if="row.enabled===1" link type="danger" :disabled="busy" @click="disableMentalSchedule(row)">Stop reminders</el-button></template></el-table-column></el-table></el-card>
      </el-tab-pane>

      <el-tab-pane label="Privacy & access" name="privacy">
        <el-card><template #header><b>Patient-controlled access</b></template>
          <el-form :disabled="busy || (patientRequired && !currentPatientId)" label-position="top" class="inline-form">
            <el-form-item label="Role"><el-select v-model="grant.granteeRole" @change="grant.granteeUserId=null"><el-option label="Doctor" value="DOCTOR"/><el-option label="Family" value="FAMILY"/><el-option label="Guardian" value="GUARDIAN"/></el-select></el-form-item>
            <el-form-item v-if="grant.granteeRole==='DOCTOR'" label="Doctor" class="grant-choice"><el-select v-model="grant.granteeUserId" filterable clearable placeholder="Search platform doctors"><el-option v-for="doctor in clinicians" :key="doctor.id" :value="doctor.id" :label="doctor.real_name && doctor.real_name!==doctor.username ? `${doctor.real_name} (${doctor.username})` : doctor.username"/></el-select></el-form-item>
            <el-form-item v-else label="Recipient user ID"><el-input-number v-model="grant.granteeUserId"/></el-form-item>
            <el-form-item label="Level"><el-select v-model="grant.accessLevel"><el-option label="Read only" value="READ"/><el-option label="Can record" value="WRITE"/><el-option label="Can act for patient" value="PROXY"/></el-select></el-form-item>
            <el-form-item label="Visible modules" class="grant-choice"><el-select v-model="grantModules" multiple collapse-tags collapse-tags-tooltip clearable placeholder="Leave empty for all modules"><el-option v-for="module in grantModuleOptions" :key="module.value" :label="module.label" :value="module.value"/></el-select></el-form-item>
            <el-button type="primary" @click="createGrant">Authorize</el-button>
          </el-form>
          <el-table :data="grants"><el-table-column prop="real_name" label="Person"/><el-table-column prop="grantee_role" label="Role"/><el-table-column prop="access_level" label="Level"/><el-table-column prop="visible_modules" label="Visible modules"/><el-table-column prop="status" label="Status"/><el-table-column label=""><template #default="{row}"><el-button link type="danger" @click="revoke(row)">Revoke</el-button></template></el-table-column></el-table>
        </el-card>
      </el-tab-pane>

      <el-tab-pane v-if="isDoctor" label="Operations" name="operations">
        <el-card class="appointment-inbox"><template #header><div class="card-head"><b>My appointment inbox</b><el-button :loading="appointmentInboxLoading" @click="loadAppointmentInbox">Refresh appointments</el-button></div></template><p class="inbox-description">Appointments addressed to you appear here without selecting a patient above. You can view or cancel this appointment; other medical records remain private.</p><el-table :data="appointmentInbox" max-height="420" empty-text="No appointments addressed to you"><el-table-column prop="patient_name" label="Patient" min-width="110"/><el-table-column label="Start" min-width="160"><template #default="{row}">{{String(row.start_at||'').replace('T',' ')}}</template></el-table-column><el-table-column label="End" min-width="160"><template #default="{row}">{{String(row.end_at||'').replace('T',' ')}}</template></el-table-column><el-table-column label="Mode" min-width="100"><template #default="{row}">{{appointmentModeLabel(row.consultation_mode)}}</template></el-table-column><el-table-column prop="reason" label="Reason" min-width="160"/><el-table-column label="Status" min-width="100"><template #default="{row}">{{appointmentStatusLabel(row.status)}}</template></el-table-column><el-table-column label="Actions" width="180"><template #default="{row}"><el-button v-if="row.status==='BOOKED'" link type="primary" :disabled="busy" @click="completeInboxAppointment(row)">Complete</el-button><el-button v-if="row.status==='BOOKED'" link type="danger" :disabled="busy" @click="cancelInboxAppointment(row)">Cancel</el-button></template></el-table-column></el-table></el-card>
        <section class="panel-grid two"><el-card><template #header><b>Clinician schedule</b></template><el-form :disabled="busy || (patientRequired && !currentPatientId)" label-position="top"><div class="form-grid"><el-form-item v-if="roles.includes('admin')" label="Doctor"><el-select v-model="schedule.doctorUserId" filterable placeholder="Choose a doctor"><el-option v-for="d in clinicians" :key="d.id" :label="d.real_name||d.username" :value="d.id"/></el-select></el-form-item><el-form-item label="Date"><el-date-picker v-model="schedule.workDate" value-format="YYYY-MM-DD"/></el-form-item><el-form-item label="Start"><el-time-picker v-model="schedule.startTime" value-format="HH:mm:ss"/></el-form-item><el-form-item label="End"><el-time-picker v-model="schedule.endTime" value-format="HH:mm:ss"/></el-form-item><el-form-item label="Slot minutes"><el-input-number v-model="schedule.slotMinutes" :min="10"/></el-form-item></div><el-button type="primary" @click="createSchedule">Add availability</el-button></el-form></el-card><el-card><template #header><b>Patient groups</b></template><div class="message-compose"><el-input v-model="group.groupName" placeholder="Group name"/><el-input v-model="group.description" placeholder="Description"/><el-button type="primary" @click="createGroup">Create</el-button></div><el-table :data="groups"><el-table-column prop="group_name" label="Group"/><el-table-column prop="patient_count" label="Patients"/><el-table-column label=""><template #default="{row}"><el-button link @click="addToGroup(row)">Add selected patient</el-button></template></el-table-column></el-table></el-card></section>
        <el-card class="section-card"><template #header><div class="card-head"><b>Internal care outcomes</b><el-button @click="loadOperations">Refresh</el-button></div></template><div v-if="operations" class="metric-cards"><article><span>Follow-up completion</span><strong>{{operations.followUp?.completion_rate||0}}%</strong></article><article><span>Medication adherence</span><strong>{{operations.medication?.adherence_rate||0}}%</strong></article><article><span>Indicators on target</span><strong>{{operations.measurements?.target_rate||0}}%</strong></article><article><span>Resolved alerts</span><strong>{{operations.alerts?.resolved||0}} / {{operations.alerts?.total||0}}</strong></article></div></el-card>
      </el-tab-pane>
    </el-tabs>
  </main>
</template>

<script setup>
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import { useCurrentPatient } from '@/composables/useCurrentPatient'
import * as api from '@/api/careJourney'
import ConsultationWorkspace from '@/components/ConsultationWorkspace.vue'

const route=useRoute(),router=useRouter(),{currentPatientId,currentPatientName}=useCurrentPatient()
const roles=JSON.parse(localStorage.getItem('userRoleCodes')||'[]'),isDoctor=computed(()=>roles.includes('doctor')||roles.includes('admin'))
const allowedTabs=['measurements','appointments','consultation','recovery','emergency','specialty','mental','privacy',...(isDoctor.value?['operations']:[])]
const tab=ref(allowedTabs.includes(route.query.tab)?route.query.tab:'measurements'),busy=ref(false)
const patientRequired=computed(()=>!['operations','consultation'].includes(tab.value))
const clinicians=ref([]),doctorSchedules=ref([]),measurements=ref([]),appointments=ref([]),visits=ref([]),prescriptions=ref([]),specialtyRows=reactive({growth:[],vaccination:[],maternity:[]}),plans=ref([]),rehabRows=ref([]),emergencyCard=ref(null),emergencyEvents=ref([]),selectedEmergency=ref(null),mentalRows=ref([]),mentalSchedules=ref([]),grants=ref([]),groups=ref([]),operations=ref(null)
const now=()=>{const date=new Date();return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,19)},today=()=>now().slice(0,10)
const measurement=reactive({metricType:'BP',valuePrimary:120,valueSecondary:80,unit:'mmHg',measuredAt:now(),remark:''})
const appointment=reactive({id:null,doctorUserId:null,scheduleId:null,consultationMode:'IN_PERSON',startAt:'',endAt:'',recurrenceDays:0,reason:''})
const visit=reactive({diagnosisSummary:'',treatmentSummary:'',followUpAdvice:'',followUpAt:''})
const prescription=reactive({drugName:'',dosage:'',frequency:'',administrationRoute:'',durationDays:7,instructions:''})
const plan=reactive({planType:'INPATIENT',title:''}),planText=ref(''),rehab=reactive({recordType:'EXERCISE',completionPercent:0,videoUrl:'',abnormal:false}),rehabText=ref('')
const emergency=reactive({locationText:'',latitude:null,longitude:null})
const growth=reactive({recordDate:today(),heightCm:null,weightKg:null,headCircumferenceCm:null,heightPercentile:null,weightPercentile:null}),vaccine=reactive({vaccineName:'',doseNo:'',plannedDate:today(),remindAt:''}),maternity=reactive({recordType:'PRENATAL',recordDate:today(),title:''}),maternityText=ref('')
const mental=reactive({scaleCode:'PHQ9'}),mentalAnswers=ref(''),mentalVisible=ref(false),mentalSchedule=reactive({scaleCode:'PHQ9',intervalDays:14,nextDueAt:now()})
const grant=reactive({granteeUserId:null,granteeRole:'DOCTOR',accessLevel:'READ'}),grantModules=ref([]),schedule=reactive({doctorUserId:null,workDate:today(),startTime:'09:00:00',endTime:'12:00:00',slotMinutes:30}),group=reactive({groupName:'',description:''})
const grantModuleOptions=[{value:'MEASUREMENTS',label:'Measurements'},{value:'APPOINTMENTS',label:'Appointments'},{value:'VISITS',label:'Visit summaries'},{value:'MEDICATION',label:'Medication'},{value:'CONSULTATION',label:'Consultations'},{value:'TREATMENT',label:'Treatment plans'},{value:'REHAB',label:'Recovery'},{value:'EMERGENCY',label:'Emergency'},{value:'SPECIALTY',label:'Child and maternity'},{value:'MENTAL',label:'Mental health'},{value:'MEDICAL',label:'Medical records'},{value:'DIALYSIS',label:'Dialysis'}]
const metricOptions=[{label:'Blood pressure',value:'BP'},{label:'Blood glucose',value:'GLUCOSE'},{label:'Blood oxygen',value:'SPO2'},{label:'Weight',value:'WEIGHT'},{label:'Heart rate',value:'HEART_RATE'},{label:'Temperature',value:'TEMPERATURE'},{label:'Custom',value:'CUSTOM'}]
function syncTab(name){const query={...route.query,tab:name};if(name!=='consultation')delete query.consultationId;router.replace({query})}
function pid(){if(!currentPatientId.value)throw new Error('Select a patient first.');return currentPatientId.value}
async function safely(action,message='Saved'){if(busy.value)return;try{busy.value=true;await action();ElMessage.success(message)}catch(e){if(e.validation)ElMessage.warning(e.message);else if(e.message==='Select a patient first.')ElMessage.warning(e.message)}finally{busy.value=false}}
async function loadMeasurements(){await loadPatientData('measurements',id=>api.listMeasurements({patientId:id}),response=>{measurements.value=response.data||[]})}
async function recordMeasurement(){await safely(async()=>{validate(measurement.measuredAt && Number(measurement.valuePrimary)>0, 'Enter a measurement time and a positive value.');if(measurement.metricType==='BP')validate(Number(measurement.valueSecondary)>0,'Enter a positive diastolic value.');await api.saveMeasurement({...measurement,patientId:pid()});await loadMeasurements()})}
async function annotate(row){const {value}=await ElMessageBox.prompt('Add a clinician note to this exact trend point','Clinical annotation');await safely(async()=>{await api.annotateMeasurement(row.id,value);await loadMeasurements()})}
async function loadAppointments(){await loadPatientData('appointments',id=>Promise.all([api.listAppointments(id),api.listVisits(id),api.listPrescriptions(id)]),responses=>{appointments.value=responses[0].data||[];visits.value=responses[1].data||[];prescriptions.value=responses[2].data||[]})}
function changeAppointmentDoctor(){appointment.scheduleId=null;appointment.startAt='';appointment.endAt='';doctorSchedules.value=[];loadDoctorSchedules()}
async function loadDoctorSchedules(){const doctor=appointment.doctorUserId,selected=currentPatientId.value;if(!doctor){doctorSchedules.value=[];return}try{const response=await api.listDoctorSchedules({doctorUserId:doctor});if(doctor===appointment.doctorUserId&&selected===currentPatientId.value)doctorSchedules.value=response.data||[]}catch{}}
function selectSchedule(id){const s=doctorSchedules.value.find(x=>x.id===id);if(!s)return;appointment.startAt=`${s.work_date}T${String(s.start_time).slice(0,8)}`;const endMinutes=Number(String(s.start_time).slice(0,2))*60+Number(String(s.start_time).slice(3,5))+Number(s.slot_minutes||30);appointment.endAt=`${s.work_date}T${String(Math.floor(endMinutes/60)%24).padStart(2,'0')}:${String(endMinutes%60).padStart(2,'0')}:00`}
async function bookAppointment(){await safely(async()=>{validate(appointment.doctorUserId && appointment.startAt && appointment.endAt && new Date(appointment.endAt)>new Date(appointment.startAt),'Choose a doctor and an appointment ending after its start time.');await api.saveAppointment({...appointment,patientId:pid()});Object.assign(appointment,{id:null,startAt:'',endAt:'',reason:''});await loadAppointments()})}
function editAppointment(row){if(row.status!=='BOOKED')return;Object.assign(appointment,{id:row.id,doctorUserId:row.doctor_user_id,scheduleId:row.schedule_id,consultationMode:row.consultation_mode,startAt:String(row.start_at).replace(' ','T'),endAt:String(row.end_at).replace(' ','T'),recurrenceDays:row.recurrence_days||0,reason:row.reason||''});loadDoctorSchedules();window.scrollTo({top:0,behavior:'smooth'})}
async function cancel(row){await ElMessageBox.confirm('Cancel this appointment and notify the shared care team?','Cancel appointment');await safely(async()=>{await api.cancelAppointment(row.id,'Cancelled from shared schedule');await loadAppointments()},'Appointment cancelled')}
async function createVisit(){await safely(async()=>{validate(visit.diagnosisSummary.trim() || visit.treatmentSummary.trim(),'Enter a diagnosis or treatment summary.');await api.saveVisit({...visit,patientId:pid(),visitedAt:now()});await loadAppointments()})}
async function publish(row){await safely(async()=>{await api.publishVisit(row.id);await loadAppointments()},'Summary published')}
async function savePrescription(){await safely(async()=>{validate(prescription.drugName.trim() && prescription.dosage.trim() && prescription.frequency.trim(),'Enter the medicine, dose and frequency.');await api.savePrescription({patientId:pid(),instructions:prescription.instructions,items:[{drugName:prescription.drugName,dosage:prescription.dosage,frequency:prescription.frequency,administrationRoute:prescription.administrationRoute,durationDays:prescription.durationDays}]});Object.assign(prescription,{drugName:'',dosage:'',frequency:'',administrationRoute:'',durationDays:7,instructions:''});await loadAppointments()},'Prescription published and shared')}
async function loadRecovery(){await loadPatientData('recovery',id=>Promise.all([api.listTreatmentPlans(id),api.listRehabCheckins(id)]),responses=>{plans.value=responses[0].data||[];rehabRows.value=responses[1].data||[]})}
async function createPlan(){await safely(async()=>{validate(plan.title.trim() && planText.value.trim(),'Enter a plan title and instructions.');await api.saveTreatmentPlan({...plan,patientId:pid(),plan:{instructions:planText.value}});plan.title='';planText.value='';await loadRecovery()})}
async function checkinRehab(){await safely(async()=>{validate(rehabText.value.trim(),'Enter the rehabilitation or symptom observation.');await api.saveRehabCheckin({...rehab,patientId:pid(),data:{observation:rehabText.value}});rehabText.value='';await loadRecovery()})}
function specialtyDetail(value){try{return (typeof value==='string'?JSON.parse(value):value)?.details||'—'}catch{return value}}
function prettyJson(value){try{return JSON.stringify(typeof value==='string'?JSON.parse(value):value,null,2)}catch{return value}}
async function loadEmergencyCard(){
  const selected=currentPatientId.value,userId=localStorage.getItem('userId')
  emergencyCard.value=null
  if(!selected||!userId)return
  const key=`offlineEmergencyCard:${userId}:${selected}`,version=(loadVersions.get('emergency')||0)+1
  loadVersions.set('emergency',version)
  const isCurrent=()=>currentPatientId.value===selected&&localStorage.getItem('userId')===userId&&loadVersions.get('emergency')===version
  try{
    const response=await api.getEmergencyCard(selected)
    if(!isCurrent())return
    if(response.code&&response.code!==200)throw Object.assign(new Error(response.msg||'Request failed'),{code:response.code})
    emergencyCard.value=response.data
    try{localStorage.setItem(key,JSON.stringify(response.data))}catch{}
  }catch(error){
    if(!isCurrent())return
    const networkFailure=!error.response&&!Number(error.code)&&(['ERR_NETWORK','ECONNABORTED','ETIMEDOUT'].includes(error.code)||(typeof navigator!=='undefined'&&navigator.onLine===false))
    if(networkFailure){
      try{emergencyCard.value=JSON.parse(localStorage.getItem(key)||'null')}catch{emergencyCard.value=null}
    }else{
      emergencyCard.value=null
      localStorage.removeItem(key)
    }
  }
}
async function loadEmergencyEvents(){await loadPatientData('emergencyEvents',id=>api.listEmergencies(id),response=>{emergencyEvents.value=response.data||[]})}
async function loadEmergencyTab(){await Promise.allSettled([loadEmergencyCard(),loadEmergencyEvents()])}
async function openEmergency(row){const patientId=currentPatientId.value;selectedEmergency.value=null;const response=await api.getEmergency(row.id);if(patientId===currentPatientId.value&&Number(response.data?.patient_id)===Number(patientId))selectedEmergency.value=response.data}
async function sos(){if(busy.value||!currentPatientId.value)return;const selected=pid();busy.value=true;try{await ElMessageBox.confirm('This records an emergency event and attempts to notify bound care contacts. Continue?','Emergency call',{confirmButtonText:'Send now',type:'warning'})}catch{busy.value=false;return}if(currentPatientId.value!==selected){busy.value=false;return}try{emergency.latitude=null;emergency.longitude=null;if(navigator.geolocation)await new Promise(resolve=>navigator.geolocation.getCurrentPosition(p=>{emergency.latitude=p.coords.latitude;emergency.longitude=p.coords.longitude;resolve()},()=>resolve(),{timeout:5000}));if(currentPatientId.value!==selected)return;const response=await api.triggerEmergency({...emergency,patientId:selected});if(currentPatientId.value!==selected)return;const {deliveryCount=0,recipientCount=0,id}=response.data||{};if(deliveryCount===0)ElMessage.warning(`Emergency #${id} was recorded, but no contact received a notification. Use another way to reach help now.`);else if(deliveryCount<recipientCount)ElMessage.warning(`Emergency #${id} was recorded; ${deliveryCount} of ${recipientCount} contacts received a notification.`);else ElMessage.success(`Emergency #${id} was recorded and ${deliveryCount} contact(s) received a notification.`);await loadEmergencyEvents()}catch{}finally{busy.value=false}}
async function saveSpecial(type,data){await safely(async()=>{if(type==='growth')validate(data.recordDate && [data.heightCm,data.weightKg,data.headCircumferenceCm].some(value=>Number(value)>0),'Enter a date and at least one positive growth measurement.');if(type==='vaccination')validate(data.vaccineName?.trim() && data.plannedDate,'Enter the vaccine name and planned date.');if(type==='maternity')validate(data.recordDate && data.title?.trim(),'Enter a record date and title.');await api.saveSpecialty(type,{...data,patientId:pid()});await loadSpecialty()})}
async function saveMaternity(){await saveSpecial('maternity',{...maternity,data:{details:maternityText.value}})}
async function loadMental(){await loadPatientData('mental',id=>Promise.allSettled([api.listMentalAssessments(id),api.listMentalSchedules(id)]),responses=>{if(responses[0].status==='fulfilled')mentalRows.value=responses[0].value.data||[];if(responses[1].status==='fulfilled')mentalSchedules.value=responses[1].value.data||[]})}
async function submitMental(){await safely(async()=>{const values=mentalAnswers.value.split(/[,，]/).map(value=>value.trim()),count={PHQ9:9,GAD7:7,WHO5:5}[mental.scaleCode],maximum=mental.scaleCode==='WHO5'?5:3;validate(values.length===count && values.every(value=>/^\d+$/.test(value) && Number(value)<=maximum),`Enter ${count} integer scores from 0 to ${maximum}, separated by commas.`);const answers=values.map(Number);await api.saveMentalAssessment({...mental,patientId:pid(),answers,familyVisibility:mentalVisible.value?'VISIBLE':'PRIVATE'});mentalAnswers.value='';await loadMental()})}
async function scheduleMental(){await safely(async()=>{validate(mentalSchedule.nextDueAt && Number(mentalSchedule.intervalDays)>0,'Enter the next delivery time and a positive interval.');await api.saveMentalSchedule({...mentalSchedule,scaleCode:mental.scaleCode,patientId:pid(),familyVisibility:mentalVisible.value?'VISIBLE':'PRIVATE'});await loadMental()},'Assessment scheduled')}
async function disableMentalSchedule(row){if(!row||row.enabled!==1)return;await safely(async()=>{await api.disableMentalSchedule(row.id);await loadMental()},'Assessment schedule disabled')}
async function loadGrants(){await loadPatientData('grants',id=>api.listAccessGrants(id),response=>{grants.value=response.data||[]})}
async function createGrant(){await safely(async()=>{validate(Number(grant.granteeUserId)>0,'Select a recipient.');if(grant.granteeRole==='DOCTOR')validate(clinicians.value.some(doctor=>Number(doctor.id)===Number(grant.granteeUserId)),'Select a doctor from the list.');await api.saveAccessGrant({...grant,visibleModules:grantModules.value.join(','),patientId:pid()});await loadGrants()},'Access authorized')}
async function revoke(row){await safely(async()=>{await api.revokeAccessGrant(row.id);await loadGrants()},'Access revoked')}
async function createSchedule(){await safely(async()=>{validate(!roles.includes('admin') || schedule.doctorUserId,'Choose the doctor whose schedule you are creating.');validate(schedule.workDate && schedule.startTime && schedule.endTime && schedule.endTime>schedule.startTime,'Enter a date and a schedule ending after its start time.');await api.saveDoctorSchedule({...schedule})},'Availability added')}
async function createGroup(){await safely(async()=>{validate(group.groupName.trim(),'Enter the patient group name.');await api.savePatientGroup({...group});group.groupName='';group.description='';groups.value=(await api.listPatientGroups()).data||[]})}
async function addToGroup(row){await safely(async()=>{await api.addPatientToGroup(row.id,pid());groups.value=(await api.listPatientGroups()).data||[]},'Patient added')}
const appointmentInbox=ref([]),appointmentInboxLoading=ref(false)
let appointmentInboxVersion=0
const appointmentModeLabel=value=>({IN_PERSON:'In person',TEXT:'Text',VOICE:'Voice',VIDEO:'Video'})[value]||value
const appointmentStatusLabel=value=>({BOOKED:'Booked',CANCELLED:'Cancelled',COMPLETED:'Completed'})[value]||value
async function loadAppointmentInbox(){
  if(!isDoctor.value)return
  const version=++appointmentInboxVersion,userId=localStorage.getItem('userId')
  appointmentInboxLoading.value=true
  try{const response=await api.listAppointmentInbox();if(version===appointmentInboxVersion&&userId===localStorage.getItem('userId'))appointmentInbox.value=response.data||[]}
  catch{if(version===appointmentInboxVersion)appointmentInbox.value=[]}
  finally{if(version===appointmentInboxVersion)appointmentInboxLoading.value=false}
}
async function completeInboxAppointment(row){
  if(busy.value||row.status!=='BOOKED')return
  busy.value=true
  try{
    await ElMessageBox.confirm('Mark this visit as completed? This does not create a visit summary or prescription.','Complete appointment')
    await api.completeAppointment(row.id)
    ElMessage.success('Appointment completed')
    await loadAppointmentInbox()
  }catch{}finally{busy.value=false}
}
async function cancelInboxAppointment(row){
  if(busy.value||row.status!=='BOOKED')return
  busy.value=true
  try{
    await ElMessageBox.confirm('Cancel this appointment and notify the patient and care team?','Cancel appointment')
    await api.cancelAppointment(row.id,'Cancelled by the doctor from appointment inbox')
    ElMessage.success('Appointment cancelled')
    await loadAppointmentInbox()
  }catch{}finally{busy.value=false}
}
async function loadOperations(){await Promise.allSettled([loadAppointmentInbox(),(async()=>{operations.value=(await api.getOperationsReport({})).data})(),(async()=>{groups.value=(await api.listPatientGroups()).data||[]})()])}
async function loadTab(){const current=tab.value;const loaders={measurements:loadMeasurements,appointments:loadAppointments,recovery:loadRecovery,specialty:loadSpecialty,emergency:loadEmergencyTab,mental:loadMental,privacy:loadGrants,operations:loadOperations};if(['appointments','operations','privacy'].includes(current)&&!clinicians.value.length){try{clinicians.value=(await api.listClinicians()).data||[]}catch{clinicians.value=[]}}try{if(loaders[current])await loaders[current]()}catch{}}
const mentalSeverityLabel=row=>({MINIMAL:'Below review threshold',MILD:'Mild',MODERATE:'Moderate',MODERATELY_SEVERE:'Moderately severe',SEVERE:'Severe',REVIEW_REQUIRED:'Further assessment suggested'})[row.severity]||row.severity||'—'
function validate(valid,text){if(!valid){const error=new Error(text);error.validation=true;throw error}}
async function loadSpecialty(){await loadPatientData('specialty',id=>Promise.all(['growth','vaccination','maternity'].map(type=>api.listSpecialty(type,id))),responses=>{['growth','vaccination','maternity'].forEach((type,index)=>{specialtyRows[type]=responses[index].data||[]})})}
watch(()=>measurement.metricType,type=>{measurement.unit=({BP:'mmHg',GLUCOSE:'mmol/L',SPO2:'%',WEIGHT:'kg',HEART_RATE:'bpm',TEMPERATURE:'°C',CUSTOM:''})[type];measurement.valuePrimary=null;measurement.valueSecondary=type==='BP'?80:null})
const loadVersions=new Map()
const patientForms=[measurement,appointment,visit,prescription,plan,rehab,emergency,growth,vaccine,maternity,mental,mentalSchedule,grant]
const formDefaults=patientForms.map(model=>JSON.parse(JSON.stringify(model)))
async function loadPatientData(key,fetcher,apply){
  const selected=currentPatientId.value
  if(!selected)return
  const version=(loadVersions.get(key)||0)+1
  loadVersions.set(key,version)
  const response=await fetcher(selected)
  if(currentPatientId.value===selected&&loadVersions.get(key)===version)apply(response,selected)
}
watch(currentPatientId,()=>{
  for(const [key,version]of loadVersions)loadVersions.set(key,version+1)
  measurements.value=[];appointments.value=[];visits.value=[];prescriptions.value=[];Object.keys(specialtyRows).forEach(key=>{specialtyRows[key]=[]});plans.value=[];rehabRows.value=[];emergencyCard.value=null;emergencyEvents.value=[];selectedEmergency.value=null;mentalRows.value=[];mentalSchedules.value=[];grants.value=[];doctorSchedules.value=[]
  patientForms.forEach((model,index)=>Object.assign(model,formDefaults[index]))
  planText.value='';rehabText.value='';maternityText.value='';mentalAnswers.value='';mentalVisible.value=false
  measurement.measuredAt=now();mentalSchedule.nextDueAt=now();growth.recordDate=today();vaccine.plannedDate=today();maternity.recordDate=today()
  loadTab()
})
watch(()=>route.query.tab,value=>{const next=allowedTabs.includes(value)?value:'measurements';if(tab.value!==next)tab.value=next;if(value&&value!==next){syncTab(next);return}loadTab()})
onMounted(()=>{if(route.query.tab&&!allowedTabs.includes(route.query.tab))syncTab(tab.value);else loadTab()})
</script>

<style scoped>
.inline-form .grant-choice{flex:1 1 260px;min-width:min(260px,100%)}
.appointment-inbox{margin-bottom:18px;min-width:0}.inbox-description{margin:0 0 16px;color:#637a75;line-height:1.7}
.prescription-version+.prescription-version{margin-top:22px;padding-top:18px;border-top:1px solid #e4ece8}.prescription-version p{color:#6a7e79;white-space:pre-wrap}.form-grid{min-width:0}.form-grid :deep(.el-form-item__content){min-width:0}.form-grid :deep(.el-date-editor){max-width:100%}.card-head{flex-wrap:wrap}

.journey-page{max-width:1500px;margin:auto;padding:26px}.journey-hero{display:flex;justify-content:space-between;gap:24px;align-items:center;padding:28px;border:1px solid #dce9e4;border-radius:20px;background:linear-gradient(120deg,#eef7f3,#fff);margin-bottom:22px}.journey-hero span{font-size:11px;letter-spacing:2px;color:#247568;font-weight:700}.journey-hero h1{margin:8px 0;font-size:32px}.journey-hero p{margin:0;max-width:820px;color:#637a75}.journey-tabs{background:#fff;border:1px solid #e1ebe7;border-radius:18px;padding:18px}.panel-grid{display:grid;gap:18px}.panel-grid.two{grid-template-columns:repeat(2,minmax(0,1fr))}.panel-grid.three{grid-template-columns:repeat(3,minmax(0,1fr))}.section-card{margin-top:18px}.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0 14px}.card-head,.message-compose,.inline{display:flex;align-items:center;justify-content:space-between;gap:12px}.realtime-state{display:inline-flex;align-items:center;gap:6px;margin-left:12px;color:#238066;font-size:11px;font-weight:600}.realtime-state i{width:8px;height:8px;border-radius:50%;background:#31af7d;box-shadow:0 0 0 4px #31af7d20}.message-list{display:grid;gap:10px;max-height:360px;overflow:auto;scroll-behavior:smooth}.message-list article{padding:12px;border:1px solid #e4ece9;border-radius:12px}.message-list article span{float:right;color:#81928d;font-size:12px}.message-list article p{margin:6px 0 0}.message-compose{margin-top:14px}.message-compose .el-input{flex:1}.media-room{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px;margin-bottom:18px;padding:12px;border-radius:14px;background:#173a36}.media-room video{width:100%;min-height:160px;max-height:320px;object-fit:cover;border-radius:10px;background:#0e2421}.media-room p{color:#d7e6e1;padding:20px}.emergency-card{border-color:#efb4aa}.emergency-card .el-input{margin:14px 0}.metric-cards{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.metric-cards article{padding:20px;border-radius:14px;background:#f2f7f5}.metric-cards span,.metric-cards strong{display:block}.metric-cards strong{font-size:26px;margin-top:8px}.inline-form{display:flex;align-items:end;gap:12px;flex-wrap:wrap}.inline-form .el-form-item{min-width:180px;margin-bottom:10px}pre{white-space:pre-wrap}.el-select,.el-date-editor{width:100%}@media(max-width:900px){.panel-grid.two,.panel-grid.three,.metric-cards{grid-template-columns:1fr 1fr}}@media(max-width:650px){.journey-page{padding:14px}.journey-hero{align-items:flex-start;flex-direction:column;padding:20px}.journey-tabs{padding:10px}.panel-grid.two,.panel-grid.three,.metric-cards,.form-grid{grid-template-columns:1fr}.message-compose{align-items:stretch;flex-direction:column}.inline{align-items:stretch;flex-direction:column}.media-room{grid-template-columns:1fr}}
</style>
