<template>
  <section class="care-plan-editor" aria-labelledby="editor-heading">
    <header><div><h2 id="editor-heading">{{ planId ? '编辑私有草稿' : '新建协作草稿' }}</h2><p>保存后草稿仍为医护内部可见。发布后，本患者及当前获授权的照护协作者可以查看行动项。</p></div><button type="button" data-testid="close-editor" @click="requestClose">关闭编辑器</button></header>
    <p v-if="loading" role="status">正在加载获授权的计划上下文…</p>
    <p v-if="message" role="status" class="feedback">{{ message }}</p>
    <p v-if="!loading && !enabled">当前会话无法使用协作计划。</p>
    <template v-if="enabled && state.draft && state.editor">
      <p v-if="legacySource" class="notice">复制自历史内部计划，原记录保持不变。请为每个新行动明确截止时间和负责人；旧目标日期不会自动设定时间。</p>
      <fieldset :disabled="!canSave || state.commandPhase === 'pending'">
        <label>计划标题 <input v-model="state.draft.title" aria-required="true" /></label>
        <label>计划类型 <select v-model="state.draft.planType"><option value="FOLLOW_UP">随访</option><option value="MEDICATION">用药</option><option value="DIALYSIS">透析</option><option value="NUTRITION">营养</option></select></label>
        <label>临床说明 <textarea v-model="state.draft.instructions" rows="4" aria-required="true" /></label>
        <p>每版本包含 1–50 个一次性行动。标题最多 160 字，临床说明最多 4000 字，每项行动最多 2000 字，按 Unicode 字符计数。</p>
        <article v-for="(action,index) in state.draft.actions" :key="index" class="action-editor">
          <h3>行动 {{ index + 1 }}</h3>
          <label>行动说明 <textarea v-model="action.instruction" rows="2" aria-required="true" /></label>
          <label>负责人 <select v-model="action.assignedUserId" aria-required="true"><option :value="null">选择当前获授权的负责人</option><option v-for="person in assignees" :key="person.userId" :value="person.userId">{{ person.displayName }} · {{ roleLabel(person.role) }}</option></select></label>
          <p v-if="action.assignedUserId && !assignees.some(p=>p.userId===action.assignedUserId)">此负责人已不可用，请选择当前获授权的负责人。</p>
          <label>截止时间：包含明确偏移的 ISO 日期时间 <input v-model="action.dueAt" placeholder="2026-10-04T14:30:00+08:00" aria-required="true" /></label>
          <p>{{ displayTime(action.dueAt) }}</p>
          <details><summary>选择浏览器本地时间 ({{ timeZone }})</summary><label>本地截止时间 <input v-model="localClocks[index]" type="datetime-local" step="1" @change="localOffsets[index]=null" /></label><label>明确 UTC 偏移 <select v-model="localOffsets[index]"><option :value="null">请选择偏移</option><option v-for="offset in offsetsFor(index)" :key="offset" :value="offset">{{ offsetLabel(offset) }}</option></select></label><p v-if="localClocks[index] && !offsetsFor(index).length">此本地时间不存在，请修改；系统不会静默调整时间。</p><button type="button" @click="applyLocalTime(index)">使用此准确时间和偏移</button></details>
          <details><summary>既有记录引用 ({{ action.evidence.length }}/5)</summary><p>仅引用既有测量或医疗记录 ID。保存和发布时重新检查患者归属与原模块当前权限，不上传新文件。</p><div v-for="(evidence,e) in action.evidence" :key="e" class="evidence-row"><label>记录类型 <select v-model="evidence.sourceType"><option value="MEASUREMENT">测量</option><option value="MEDICAL_RECORD">医疗记录</option></select></label><label>既有记录 ID <input v-model.number="evidence.sourceId" type="number" min="1" step="1" /></label><button type="button" @click="action.evidence.splice(e,1)">移除引用</button></div><button type="button" :disabled="action.evidence.length>=5" @click="action.evidence.push({sourceType:'MEASUREMENT',sourceId:null})">添加既有记录引用</button></details>
          <button type="button" :disabled="state.draft.actions.length<=1" @click="removeAction(index)">移除行动</button>
        </article>
        <button type="button" :disabled="state.draft.actions.length>=50" @click="addAction">添加行动 ({{ state.draft.actions.length }}/50)</button>
      </fieldset>
      <section v-if="createReconciliation" class="notice" role="alert"><p>结果不明的新草稿可能已经存在。新建前，请先检查此患者的服务器历史记录。</p><ul><li v-for="existing in state.items" :key="existing.id"><span>{{ existing.title }} · {{ lifecycleLabel(existing.lifecycle) }}</span><button type="button" @click="useExistingDraft(existing)">使用此既有计划</button></li></ul><button v-if="state.nextCursor" type="button" data-testid="more-create-history" :disabled="busy" @click="moreCreateHistory">更多服务器历史记录</button><button v-else-if="reconciliationReady" type="button" :disabled="busy" data-testid="acknowledge-create-history" @click="acknowledgeCreateHistory">我已核对历史记录，允许新建私有草稿</button></section>
      <div class="controls"><button v-if="canSave" type="button" data-testid="save-draft" :disabled="busy || unresolved || createReconciliation || needsReload" @click="save">保存私有草稿</button><button v-if="allowed('PUBLISH_PLAN')" type="button" data-testid="prepare-publish" :disabled="busy || unresolved || dirty || needsReload" @click="preparePublish">核对后发布…</button><button type="button" data-testid="reload-server" :disabled="busy" @click="requestReload">重新加载服务器状态，保留输入</button></div>
      <p v-if="dirty && allowed('PUBLISH_PLAN')">请先保存修改，再核对发布内容。</p>
      <section v-if="publishVisible" class="notice" aria-label="发布确认">
        <h3>确认发布范围</h3><p>本患者和当前获授权的照护协作者将看到以下临床说明和新行动。</p>
        <template v-if="state.plan?.currentRevisionId"><h4>已发布版本 → 新版本</h4><p>{{ currentPublished?.title }} → {{ state.draft.title }}</p><p>{{ currentPublished?.instructions }} → {{ state.draft.instructions }}</p><ul><li v-for="old in currentPublished?.actions || []" :key="old.id">原行动 #{{ old.id }}: {{ old.instruction }} · {{ displayTime(old.dueAt) }} · {{ actionLabel(old.status) }} · 负责账号 #{{ old.assignedUserId }} · 既有引用： {{ (old.evidence || []).map(e=>e.restricted?'受限关联记录':`${evidenceLabel(e.sourceType)} #${e.sourceId}`).join(', ') || '无' }}</li></ul><p>将被替代的未完成或待复核行动： {{ impact?.actionIds?.join(', ') || '无' }}。历史回执仍属于原版本，新行动从待执行状态开始。</p></template>
        <ul><li v-for="(action,index) in state.draft.actions" :key="index">新行动 {{ index+1 }}: {{ action.instruction }} · {{ displayTime(action.dueAt) }} · {{ assignees.find(p=>p.userId===action.assignedUserId)?.displayName }} · 既有引用： {{ action.evidence.map(e=>`${evidenceLabel(e.sourceType)} #${e.sourceId}`).join(', ') || '无' }}</li></ul>
        <label class="check"><input v-model="publishConfirmed" type="checkbox" />我明确确认此发布范围及上述修订影响</label><div class="controls"><button type="button" data-testid="confirm-publish" :disabled="!publishConfirmed || busy || dirty" @click="publish">发布此版本</button><button type="button" @click="publishVisible=false">保持私有</button></div>
      </section>
      <section v-if="unresolved" class="notice" role="alert"><p>服务器可能已经提交原请求，请勿盲目重新创建。重试将重放冻结的原输入和命令键，即使此表单已被修改。</p><button type="button" data-testid="retry-original" :disabled="busy" @click="retryOriginal">重试原提交</button></section>
    </template>
    <section v-if="createReconciliation && !reconciliationReady" class="notice" role="alert"><p>服务器历史尚未完整加载。新建草稿前，请重试获授权的历史加载。</p><button type="button" data-testid="retry-create-history" :disabled="busy" @click="retryCreateHistory">重试获授权的历史加载</button></section>
    <section v-if="abandonIntent" class="notice" role="alert"><p v-if="unresolved || state.commandPhase==='pending'">此提交可能已在服务器存在。离开会丢弃内存中的重试键。发起新命令前，请重新加载服务器状态；修改输入不代表上次提交失败。</p><p v-else>关闭会丢弃尚未保存的私有草稿修改。请继续编辑并先保存。</p><button type="button" data-testid="confirm-abandon" @click="confirmAbandon">{{ abandonIntent==='close' ? '确认风险并关闭' : '确认风险并重新加载' }}</button><button type="button" data-testid="keep-editing" @click="abandonIntent=null">继续编辑</button></section>
  </section>
</template>

<script setup>
import { computed, ref, watch, onMounted, onUnmounted } from 'vue'
import { useCarePlan } from '@/composables/useCarePlan'
import { getCarePlanCapabilities, listAssignees, getPlan } from '@/api/carePlan'
import { captureAuthSession, isAuthSessionCurrent } from '@/utils/authSession'
import { formatPlanTime, getLocalTimeOffsets, toOffsetIso } from '@/utils/carePlanTime'
const props=defineProps({patientId:{type:Number,required:true},planId:{type:Number,default:null},revisionId:{type:Number,default:null},legacySource:{type:Object,default:null}})
const emit=defineEmits(['saved','closed'])
const patient=computed(()=>props.patientId),client=useCarePlan(patient),{state}=client
const enabled=ref(false),loading=ref(false),assignees=ref([]),message=ref(''),savedSnapshot=ref(''),publishVisible=ref(false),publishConfirmed=ref(false),currentPublished=ref(null),impact=ref(null),abandonIntent=ref(null),localClocks=ref({}),localOffsets=ref({}),createReconciliation=ref(false),reconciliationReady=ref(false),needsReload=ref(false)
const timeZone=Intl.DateTimeFormat().resolvedOptions().timeZone
const copy=x=>x==null?x:JSON.parse(JSON.stringify(x)),count=x=>Array.from(x.trim()).length
let generation=0,controller=null,lastCommand=null,historyOwner=null,editorOwner=null
const allowed=name=>enabled.value && !!state.editor && !!state.plan?.allowedActions?.includes(name)
const canSave=computed(()=>enabled.value && !!state.editor && (!state.plan || allowed('SAVE_DRAFT')))
const busy=computed(()=>loading.value || state.loading || state.opening || state.commandPhase==='pending')
const unresolved=computed(()=>state.commandPhase==='unknown')
const dirty=computed(()=>!!state.draft && JSON.stringify(state.draft)!==savedSnapshot.value)
function draftOf(view){return {patientId:props.patientId,title:view?.title||'',instructions:view?.instructions||'',planType:view?.planType||'FOLLOW_UP',...(view?.legacySourceId||props.legacySource?.id?{legacySourceId:view?.legacySourceId||props.legacySource.id}:{}),actions:view?.actions?.map((a,i)=>({ordinal:i+1,instruction:a.instruction,dueAt:a.dueAt,assignedUserId:a.assignedUserId,evidence:(a.evidence||[]).map(e=>({sourceType:e.sourceType,sourceId:e.sourceId}))}))||[{ordinal:1,instruction:'',dueAt:'',assignedUserId:null,evidence:[]}]}}
function context(){return {generation,auth:captureAuthSession(),actor:localStorage.getItem('userId')}}
function owns(c){return c.generation===generation && isAuthSessionCurrent(c.auth) && c.actor===localStorage.getItem('userId')}
function options(c){return {expectedAuth:{...c.auth,actorId:c.actor},signal:controller.signal}}
async function initialize(){const g=++generation;controller?.abort();controller=new AbortController();enabled.value=false;loading.value=true;assignees.value=[];publishVisible.value=false;publishConfirmed.value=false;impact.value=null;currentPublished.value=null;abandonIntent.value=null;localClocks.value={};localOffsets.value={};createReconciliation.value=false;reconciliationReady.value=false;historyOwner=null;editorOwner=null;needsReload.value=false;lastCommand=null;client.reset();const c=context();try{const capabilities=await getCarePlanCapabilities(options(c));if(!owns(c))return;if(!capabilities.data?.enabled){message.value='当前会话无法使用协作计划。';return}const candidates=await listAssignees(props.patientId,options(c));if(!owns(c))return;assignees.value=candidates.data||[];const result=await client.open(props.planId,{revisionId:props.revisionId,draft:props.planId?null:draftOf(props.legacySource)});if(!owns(c)||!['opened','succeeded'].includes(result.status)){if(owns(c))message.value='此计划不可用，或访问权限已变化。';return}state.draft=draftOf(result.data||props.legacySource);savedSnapshot.value=JSON.stringify(state.draft);editorOwner=c;enabled.value=true;message.value='';if(!props.planId)await reconcileCreateHistory(false)}catch(error){if(owns(c)){client.reset();message.value='无法加载获授权的计划上下文。请检查会话后重新打开。'}}finally{if(g===generation)loading.value=false}}
function validate(){const d=state.draft;if(!d||!count(d.title)||count(d.title)>160||!count(d.instructions)||count(d.instructions)>4000||!['FOLLOW_UP','MEDICATION','DIALYSIS','NUTRITION'].includes(d.planType))throw new Error('请填写有效标题（1–160 字）、临床说明（1–4000 字）和计划类型。');if(!Array.isArray(d.actions)||d.actions.length<1||d.actions.length>50)throw new Error('每个版本需要 1–50 个行动。');return {...d,title:d.title.trim(),instructions:d.instructions.trim(),actions:d.actions.map((a,i)=>{if(!count(a.instruction)||count(a.instruction)>2000)throw new Error('每项行动说明需要 1–2000 字。');if(!Number.isSafeInteger(a.assignedUserId)||!assignees.value.some(p=>p.userId===a.assignedUserId))throw new Error('请选择当前获授权的负责人。');try{formatPlanTime(a.dueAt,'zh-CN')}catch{throw new Error('截止时间无效，请使用含偏移的准确 ISO 时间。')};if(!Array.isArray(a.evidence)||a.evidence.length>5)throw new Error('每项行动最多引用 5 条既有记录。');const seen=new Set();const evidence=a.evidence.map(e=>{const key=`${e.sourceType}:${e.sourceId}`;if(!['MEASUREMENT','MEDICAL_RECORD'].includes(e.sourceType)||!Number.isSafeInteger(e.sourceId)||e.sourceId<=0||seen.has(key))throw new Error('引用需要有效类型、正整数 ID，且不能重复。');seen.add(key);return {sourceType:e.sourceType,sourceId:e.sourceId}});return {ordinal:i+1,instruction:a.instruction.trim(),dueAt:a.dueAt,assignedUserId:a.assignedUserId,evidence}})}}
function clearClinicalContext(){generation++;controller?.abort();client.reset();enabled.value=false;loading.value=false;assignees.value=[];savedSnapshot.value='';publishVisible.value=false;publishConfirmed.value=false;currentPublished.value=null;impact.value=null;localClocks.value={};localOffsets.value={};abandonIntent.value=null;lastCommand=null;reconciliationReady.value=false;historyOwner=null;editorOwner=null}
function requireOwnedEditor(){if(editorOwner && owns(editorOwner))return true;if(editorOwner?.generation===generation){clearClinicalContext();message.value='访问权限已不可用。'}return false}
function feedback(result){if(['forbidden','unauthenticated','unavailable'].includes(result.status))clearClinicalContext();if(result.status==='stale')needsReload.value=true;message.value=({unknown:'结果不明，请重试原提交，或确认风险并重新加载后再发起新命令。',conflict:'服务器上的计划已变化，输入已保留。重试前请重新加载服务器状态。',failed:'服务器拒绝了此命令，输入已保留；请修改后重试。',stale:'上下文或输入已变化，当前草稿已保留。重试前请重新加载服务器状态。',cancelled:'请求未发送，输入已保留。',forbidden:'访问权限已不可用。',unauthenticated:'请重新登录以继续。',unavailable:'协作计划不可用。', 'editor-required':'请重新打开编辑器以继续。'})[result.status]||'无法完成此命令。'}
async function refreshPreservingInput(id=state.plan?.id,revisionId=state.plan?.draftRevisionId||state.plan?.revisionId){if(!requireOwnedEditor())return false;const input=copy(state.draft),c=context();const result=await client.open(id,{revisionId,draft:input});if(!owns(c))return false;if(result.status!=='succeeded'){feedback(result);return false}editorOwner=c;savedSnapshot.value=JSON.stringify(draftOf(result.data));needsReload.value=false;return true}
async function settle(result,name,submitted){if(result.status!=='succeeded'){feedback(result);return}const unchanged=result.draftUnchanged;const id=result.data.id||result.data.planId||state.plan?.id,revisionId=result.data.draftRevisionId||result.data.revisionId||state.plan?.draftRevisionId||state.plan?.revisionId;if(!await refreshPreservingInput(id,revisionId))return;if(name!=='publishPlan' && unchanged)savedSnapshot.value=JSON.stringify(submitted);publishVisible.value=false;publishConfirmed.value=false;message.value=unchanged?'私有草稿已保存，只有明确确认后才会发布。':'原命令已成功，新输入已保留，服务器状态已重新加载。';if(name==='publishPlan')message.value='版本已发布。进一步修改前，请核对服务器状态。';emit('saved',result.data)}
async function save(){if(!canSave.value||busy.value||unresolved.value||createReconciliation.value||needsReload.value||!requireOwnedEditor())return;try{const body=validate(),name=state.plan?'saveDraft':'createDraft',c=context();state.draft=body;lastCommand=name;const result=await client.runCommand(name,{payload:body,expectedVersion:state.plan?.version||0});if(owns(c))await settle(result,name,body)}catch(error){message.value=error.message}}
async function preparePublish(){if(!allowed('PUBLISH_PLAN')||busy.value||unresolved.value||dirty.value||needsReload.value||!requireOwnedEditor())return;const c=context(),editor=state.editor;try{validate();impact.value=copy(state.plan.revisionImpact);if(state.plan.currentRevisionId){if(!impact.value||impact.value.currentRevisionId!==state.plan.currentRevisionId||typeof impact.value.digest!=='string')throw new Error('发布前请重新加载服务器修订影响。');const response=await getPlan(state.plan.id,options(c));if(!owns(c)||editor!==state.editor)return;currentPublished.value=response.data;if(currentPublished.value.currentRevisionId!==impact.value.currentRevisionId)throw new Error('已发布版本已变化，发布前请重新加载。')}publishConfirmed.value=false;publishVisible.value=true}catch(error){if(owns(c)&&editor===state.editor){if([401,403,404].includes(Number(error.response?.status||error.response?.data?.code||error.code))){clearClinicalContext();message.value='访问权限已不可用。'}else message.value=error.message}}}
async function publish(){if(!publishConfirmed.value||!publishVisible.value||!allowed('PUBLISH_PLAN')||busy.value||dirty.value)return;const c=context(),body=state.plan.currentRevisionId?{currentRevisionId:impact.value.currentRevisionId,supersededActionDigest:impact.value.digest}:{currentRevisionId:null,supersededActionDigest:null};lastCommand='publishPlan';const result=await client.runCommand('publishPlan',{payload:body,expectedVersion:state.plan.version});if(owns(c))await settle(result,'publishPlan',state.draft)}
async function retryOriginal(){if(!unresolved.value||busy.value||!lastCommand)return;const c=context(),name=lastCommand;const result=await client.runCommand(name,{retry:true});if(owns(c))await settle(result,name,state.draft)}
function validHistory(result){return result.status==='succeeded' && Array.isArray(result.data?.items) && (result.data.nextCursor==null || (typeof result.data.nextCursor==='string' && result.data.nextCursor.length>0))}
async function reconcileCreateHistory(reopen=false){if(!requireOwnedEditor())return {status:'stale'};const input=copy(state.draft),c=context();createReconciliation.value=true;reconciliationReady.value=false;historyOwner=null;const result=await client.load({queue:'HISTORY'});if(!owns(c))return result;if(!validHistory(result)){if(result.status==='succeeded')message.value='服务器历史尚未完整加载。新建草稿前，请重试获授权的历史加载。';else feedback(result);return result}if(reopen){const opened=await client.open(null,{draft:input});if(!owns(c))return opened;if(opened.status!=='opened'){feedback(opened);return opened}editorOwner=c}historyOwner=c;reconciliationReady.value=true;needsReload.value=false;message.value='输入已保留，新建其他私有草稿前请核对服务器历史记录。';return result}
async function reload(){if(!state.plan?.id)return reconcileCreateHistory(true);const success=await refreshPreservingInput();if(success){publishVisible.value=false;message.value='服务器状态已重新加载，输入已保留；请明确保存修改。'}}
async function moreCreateHistory(){if(busy.value||!state.nextCursor||!requireOwnedEditor())return;const c=context();reconciliationReady.value=false;historyOwner=null;const result=await client.load({queue:'HISTORY',cursor:state.nextCursor});if(!owns(c))return;if(result.status==='stale-cursor')return reconcileCreateHistory(false);if(!validHistory(result)){if(result.status==='succeeded')message.value='服务器历史尚未完整加载。新建草稿前，请重试获授权的历史加载。';else feedback(result);return}historyOwner=c;reconciliationReady.value=true}
function acknowledgeCreateHistory(){if(!requireOwnedEditor())return;if(createReconciliation.value && reconciliationReady.value && !busy.value && !state.nextCursor && enabled.value && state.editor && owns(historyOwner)){createReconciliation.value=false;reconciliationReady.value=false;historyOwner=null}}
function retryCreateHistory(){if(busy.value)return;return !enabled.value||!state.editor?initialize():reconcileCreateHistory(false)}
async function useExistingDraft(existing){const c=context();const result=await client.open(existing.id,{revisionId:existing.draftRevisionId||null});if(!owns(c))return;if(result.status!=='succeeded'){feedback(result);return}editorOwner=c;state.draft=draftOf(result.data);savedSnapshot.value=JSON.stringify(state.draft);createReconciliation.value=false;message.value='已加载服务器既有计划，仅可编辑获允许的私有草稿。'}
function requestReload(){if(unresolved.value||state.commandPhase==='pending'){abandonIntent.value='reload';return}return reload()}
function requestLeave(){if(unresolved.value||state.commandPhase==='pending'||dirty.value){abandonIntent.value='close';return false}return true}
function requestClose(){if(!requestLeave())return;client.reset();emit('closed')}
async function confirmAbandon(){const intent=abandonIntent.value;abandonIntent.value=null;if(intent==='close'){client.reset();emit('closed')}else await reload()}
function addAction(){if(!canSave.value||state.draft.actions.length>=50)return;state.draft.actions.push({ordinal:state.draft.actions.length+1,instruction:'',dueAt:'',assignedUserId:null,evidence:[]})}
function removeAction(index){if(state.draft.actions.length<=1)return;state.draft.actions.splice(index,1);state.draft.actions.forEach((a,i)=>{a.ordinal=i+1});localClocks.value={};localOffsets.value={}}
function roleLabel(role){return ({user:'个人用户',family:'家庭照护者',doctor:'医生',nurse:'护士',admin:'管理员'})[String(role||'').toLowerCase()]||'账号'}
function evidenceLabel(type){return type==='MEASUREMENT'?'测量':'医疗记录'}
function actionLabel(status){return ({OPEN:'待执行或待补充信息',NEEDS_HELP:'已请求帮助',SUBMITTED:'已提交，等待医生复核',CONFIRMED:'记录已复核',SUPERSEDED:'已被新版本替代',CANCELLED:'已取消',DRAFT:'私有草稿'})[status]||'未知状态'}
function lifecycleLabel(status){return ({DRAFT:'私有草稿',ACTIVE:'进行中',COMPLETED:'复核后已关闭',CANCELLED:'已取消'})[status]||'未知状态'}
function displayTime(value){if(!value)return '截止时间需要明确的时间和偏移。';try{return formatPlanTime(value,'zh-CN')}catch{return '截止时间无效，请使用含偏移的准确 ISO 时间。'}}
function offsetsFor(index){try{return getLocalTimeOffsets(localClocks.value[index],{timeZone})}catch{return []}}
function offsetLabel(minutes){return `UTC${minutes<0?'-':'+'}${String(Math.floor(Math.abs(minutes)/60)).padStart(2,'0')}:${String(Math.abs(minutes)%60).padStart(2,'0')}`}
function applyLocalTime(index){try{state.draft.actions[index].dueAt=toOffsetIso(localClocks.value[index],localOffsets.value[index],{timeZone});message.value=''}catch{message.value='请选择有效的浏览器本地时间和明确的 UTC 偏移。'}}
function beforeUnload(event){if(unresolved.value||state.commandPhase==='pending'||dirty.value){event.preventDefault();event.returnValue=''}}
watch(()=>[props.patientId,props.planId,props.revisionId,props.legacySource],initialize,{immediate:true,flush:'sync'})
watch(()=>state.editor,editor=>{if(!editor){assignees.value=[];savedSnapshot.value='';publishVisible.value=false;publishConfirmed.value=false;currentPublished.value=null;impact.value=null;localClocks.value={};localOffsets.value={};reconciliationReady.value=false;historyOwner=null;editorOwner=null}},{flush:'sync'})
onMounted(()=>window.addEventListener('beforeunload',beforeUnload))
onUnmounted(()=>{generation++;controller?.abort();window.removeEventListener('beforeunload',beforeUnload)})
defineExpose({requestClose,requestLeave})
</script>
<style scoped>
.care-plan-editor{min-width:0;color:var(--ink-800)}header,.controls,.evidence-row{display:flex;gap:12px;align-items:center;flex-wrap:wrap}header{align-items:flex-start;justify-content:space-between}h2,h3{margin:0 0 10px}p{line-height:1.6;overflow-wrap:anywhere}fieldset{border:0;padding:0;min-width:0}label{display:grid;gap:6px;margin:12px 0;font-weight:600}input,select,textarea{box-sizing:border-box;width:100%;min-width:0;min-height:44px;padding:10px;border:1px solid var(--line);border-radius:8px;background:var(--paper);color:var(--ink-800);font:inherit}textarea{resize:vertical}button{min-height:44px;max-width:100%;padding:10px 14px;border:1px solid var(--care-600);border-radius:8px;background:var(--paper);color:var(--care-800);font:inherit;cursor:pointer}button:disabled{opacity:.5;cursor:default}button:focus-visible,input:focus-visible,select:focus-visible,textarea:focus-visible,summary:focus-visible{outline:3px solid var(--care-600);outline-offset:3px}.action-editor,.notice{border:1px solid var(--line);border-radius:12px;padding:16px;margin:16px 0;overflow-wrap:anywhere}.notice{background:var(--care-50)}.feedback{padding:12px;background:var(--surface-subtle)}details{margin:14px 0}summary{min-height:44px;cursor:pointer}.check{display:flex;align-items:center}.check input{width:24px;flex-shrink:0}.evidence-row>*{flex:1 1 160px}@media(max-width:600px){.controls button{width:100%}.action-editor,.notice{padding:12px}header>div{min-width:0;width:100%}}
</style>
