<template>
  <section class="care-plan-detail" aria-label="协作计划详情">
    <p v-if="state.opening || loading" role="status">正在加载获授权的计划…</p><p v-if="message" role="status" class="feedback">{{ message }}</p>
    <template v-if="enabled && state.plan">
      <header><div><span>协作计划 · 版本 {{ state.plan.revisionNo }} · {{ lifecycleLabel(state.plan.lifecycle) }}</span><h2>{{ state.plan.title }}</h2></div><button type="button" data-testid="reload-detail" :disabled="busy" @click="requestReload">重新加载服务器状态</button></header>
      <router-link v-if="state.plan.revisionStatus!=='DRAFT'" :to="`/care-plans/reports?patientId=${state.plan.patientId}&planId=${planId}`" class="execution-report-entry" data-testid="detail-execution-report">此计划执行报告</router-link>
      <p class="instructions">{{ state.plan.instructions }}</p><p v-if="state.plan.revisionStatus==='DRAFT'" class="notice">私有临床草稿，尚未向患者或照护协作者发布。</p>
      <label v-if="revisions.length">版本历史 <select :value="historyRevisionId || ''" @change="selectHistory($event.target.value)"><option value="">当前已发布版本</option><option v-for="revision in revisions" :key="revision.id" :value="revision.id">版本 {{ revision.revisionNo }} · {{ revisionLabel(revision.status) }} · {{ displayTime(revision.publishedAt || revision.createdAt) }}</option></select></label><button v-if="revisionCursor" type="button" :disabled="busy" @click="loadRevisions(revisionCursor)">更多版本</button>
      <p v-if="historical" class="notice">历史快照，回执仍属于此版本。查看历史也需要当前权限。</p>
      <article v-for="action in state.plan.actions || []" :key="action.id || action.ordinal" class="action-card">
        <header><h3>{{ action.ordinal }}. {{ action.instruction }}</h3><span>{{ actionLabel(action.status) }}<template v-if="action.overdue"> · 当前逾期</template></span></header>
        <p>截止时间： {{ displayTime(action.dueAt) }} · 负责账号 #{{ action.assignedUserId }}</p>
        <p v-if="action.firstSubmittedAt">原始提交时间： {{ displayTime(action.firstSubmittedAt) }} · {{ originalTiming(action) }}</p><p v-if="action.latestSubmittedAt">最近提交时间： {{ displayTime(action.latestSubmittedAt) }}</p><p v-if="action.reviewWaitingSince">等待医生复核始于 {{ displayTime(action.reviewWaitingSince) }}. 已提交且待复核的记录不表示患者延迟。</p>
        <ul v-if="action.evidence?.length" class="evidence-list"><li v-for="(e,index) in action.evidence" :key="index"><span v-if="e.restricted">存在受限关联记录</span><a v-else-if="safeLink(e.detailLink)" :href="e.detailLink">{{ e.title || evidenceLabel(e.sourceType) }}</a><span v-else>{{ e.title || evidenceLabel(e.sourceType) }} #{{ e.sourceId }}</span></li></ul>
        <div class="event-list"><article v-for="event in action.events || []" :key="event.id"><strong>{{ eventLabel(event.eventType) }}</strong><p>{{ event.actorName }} · {{ roleLabel(event.actorRole) }}<template v-if="event.entryMode"> · {{ event.entryMode==='SELF' ? '账号所有者声明本人录入' : '协助录入' }}</template></p><p v-if="event.occurredAt">实际发生时间： {{ displayTime(event.occurredAt) }}</p><p>系统记录时间： {{ displayTime(event.recordedAt) }}</p><p class="instructions" v-if="event.note">{{ event.note }}</p><ul><li v-for="(e,index) in event.evidence || []" :key="index"><span v-if="e.restricted">存在受限关联记录</span><a v-else-if="safeLink(e.detailLink)" :href="e.detailLink">{{ e.title || evidenceLabel(e.sourceType) }}</a><span v-else>{{ e.title || evidenceLabel(e.sourceType) }} #{{ e.sourceId }}</span></li></ul></article></div>
        <div v-if="actionAllowed(action,'REVIEW_RECEIPT')" class="controls"><button type="button" :data-testid="`review-confirm-${action.id}`" :disabled="busy || unresolved" @click="confirmReview(action)">标记记录已复核</button><button type="button" :data-testid="`review-return-${action.id}`" :disabled="busy || unresolved" @click="prepareReturn(action)">退回补充信息…</button></div>
        <slot v-if="!historical" name="action-controls" :action="action" :plan="state.plan" :refresh="requestReload" />
      </article>
      <p class="notice">医生复核仅表示执行记录已处理，不验证治疗有效性或疾病改善。本人录入是账号声明，不是患者身份认证。</p>
      <section v-if="reviewTarget" class="notice"><h3>退回行动 #{{ reviewTarget.id }} 要求补充信息</h3><label>必填说明（1–1000 字） <textarea v-model="reviewNote" rows="3" /></label><p v-if="!returnReady">服务器复核上下文已变化，或此行动已不可复核。说明已保留，发送前请重新核对最新记录。</p><button v-if="!returnReady && reviewContextCurrent && actionAllowed(reviewAction,'REVIEW_RECEIPT')" type="button" data-testid="recheck-return" :disabled="busy || unresolved" @click="recheckReturn">重新核对最新记录并保留说明</button><button type="button" data-testid="send-return" :disabled="busy || unresolved || !returnReady" @click="sendReturn">要求补充信息</button><button type="button" :disabled="busy || unresolved" @click="reviewTarget=null">保持不变</button></section>
      <div class="controls"><button v-if="planAllowed('SAVE_DRAFT') && state.plan.draftRevisionId" type="button" :disabled="busy || unresolved" @click="editRevision(state.plan.draftRevisionId)">编辑私有草稿</button><button v-if="planAllowed('CREATE_REVISION')" type="button" data-testid="create-revision" :disabled="busy || unresolved" @click="createRevision">创建下一私有修订</button><button v-if="planAllowed('CANCEL_PLAN')" type="button" data-testid="cancel-plan" :disabled="busy || unresolved" @click="prepareTransition('CANCEL')">取消计划…</button><button v-if="canClose" type="button" data-testid="close-plan" :disabled="busy || unresolved" @click="prepareTransition('CLOSE')">关闭已复核计划…</button></div>
      <section v-if="transitionAction" class="notice"><h3>{{ transitionAction==='CANCEL' ? '取消此计划' : '关闭此计划' }}</h3><p>{{ transitionAction==='CANCEL' ? '待执行、需要帮助及已提交行动将被取消，既有回执保留在历史中。' : '当前所有行动的记录均已复核。关闭后不可重开；这不证明临床治疗成功。' }}</p><label v-if="transitionAction==='CANCEL'">必填原因（1–1000 字）<textarea v-model="transitionReason" rows="3" /></label><button type="button" data-testid="confirm-transition" :disabled="busy || unresolved" @click="transition">{{ transitionAction==='CANCEL' ? '确认取消' : '确认关闭' }}</button><button type="button" :disabled="busy || unresolved" @click="transitionAction=null">保持不变</button></section>
      <section v-if="unresolved" class="notice" role="alert"><p>原命令可能已提交。重试将重放冻结的原命令、目标和输入。发起新命令前需要确认风险并重新加载。</p><button type="button" data-testid="retry-detail-original" :disabled="busy" @click="retryOriginal">重试原提交</button></section>
      <PlanEditor v-if="editingRevision" :patient-id="state.plan.patientId" :plan-id="planId" :revision-id="editingRevision" @saved="editorSaved" @closed="editorClosed" />
      <slot :plan="state.plan" :reload="requestReload" />
    </template>
    <p v-else-if="!loading && !state.opening">此计划不可用，或访问权限已变化。</p>
    <section v-if="abandonIntent" class="notice" role="alert"><p>此提交可能已存在。切换上下文会丢弃内存中的重试键。发起其他命令前，请确认风险并重新加载服务器状态。</p><button type="button" data-testid="confirm-detail-abandon" @click="confirmAbandon">确认风险并重新加载</button><button type="button" @click="abandonIntent=null">保留当前上下文</button></section>
  </section>
</template>
<script setup>
import { computed, ref, watch, onMounted, onUnmounted } from 'vue'
import { useCarePlan } from '@/composables/useCarePlan'
import { getCarePlanCapabilities, listPlanRevisions } from '@/api/carePlan'
import { captureAuthSession, isAuthSessionCurrent } from '@/utils/authSession'
import { formatPlanTime } from '@/utils/carePlanTime'
import PlanEditor from './PlanEditor.vue'
const props=defineProps({planId:{type:Number,required:true}}),emit=defineEmits(['changed'])
const client=useCarePlan(ref(null)),{state}=client,enabled=ref(false),loading=ref(false),message=ref(''),revisions=ref([]),revisionCursor=ref(null),historyRevisionId=ref(null),reviewTarget=ref(null),reviewNote=ref(''),transitionAction=ref(null),transitionReason=ref(''),editingRevision=ref(null),abandonIntent=ref(null)
let generation=0,controller=null,lastCommand=null,historyGeneration=0
const busy=computed(()=>loading.value||state.opening||state.commandPhase==='pending'),unresolved=computed(()=>state.commandPhase==='unknown')
const historical=computed(()=>!!historyRevisionId.value && state.plan?.revisionId!==state.plan?.currentRevisionId && state.plan?.revisionStatus==='PUBLISHED')
const planAllowed=name=>!historical.value && !!state.editor && !!state.plan?.allowedActions?.includes(name)
const actionAllowed=(a,name)=>!historical.value && !!state.editor && !!state.plan?.actions?.find(current=>current.id===a?.id)?.allowedActions?.includes(name)
const canClose=computed(()=>planAllowed('CLOSE_PLAN') && state.plan?.actions?.length>0 && state.plan.actions.every(a=>a.status==='CONFIRMED'))
const reviewAction=computed(()=>state.plan?.actions?.find(action=>action.id===reviewTarget.value?.id)||null)
const reviewContextCurrent=computed(()=>!!reviewTarget.value && reviewTarget.value.planId===state.plan?.id && reviewTarget.value.revisionId===state.plan?.revisionId)
const returnReady=computed(()=>reviewContextCurrent.value && reviewTarget.value.version===state.plan?.version && actionAllowed(reviewAction.value,'REVIEW_RECEIPT'))
function recheckReturn(){if(busy.value||unresolved.value||!reviewContextCurrent.value||!actionAllowed(reviewAction.value,'REVIEW_RECEIPT'))return;reviewTarget.value={...reviewTarget.value,version:state.plan.version};state.draft={decision:'RETURN',note:reviewNote.value}}
const context=()=>({generation,auth:captureAuthSession(),actor:localStorage.getItem('userId')})
const owns=c=>c.generation===generation && isAuthSessionCurrent(c.auth) && c.actor===localStorage.getItem('userId')
const options=c=>({expectedAuth:{...c.auth,actorId:c.actor},signal:controller.signal})
async function initialize(){const g=++generation;historyGeneration++;controller?.abort();controller=new AbortController();enabled.value=false;loading.value=true;message.value='';revisions.value=[];revisionCursor.value=null;reviewTarget.value=null;reviewNote.value='';transitionAction.value=null;transitionReason.value='';editingRevision.value=null;historyRevisionId.value=null;lastCommand=null;abandonIntent.value=null;client.reset();const c=context();try{const response=await getCarePlanCapabilities(options(c));if(!owns(c))return;if(!response.data?.enabled)return;enabled.value=true;await loadDetail();if(owns(c)&&state.plan)await loadRevisions()}catch{if(owns(c)){enabled.value=false;client.reset();message.value='当前会话无法加载此计划。'}}finally{if(g===generation)loading.value=false}}
async function loadDetail(){const result=await client.open(props.planId,{revisionId:historyRevisionId.value});if(result.status!=='succeeded'&&result.status!=='stale')feedback(result);return result}
async function loadRevisions(cursor=null){const c=context(),h=++historyGeneration;try{const result=await listPlanRevisions(props.planId,{limit:50,...(cursor?{cursor}:{})},options(c));if(!owns(c)||h!==historyGeneration||!state.editor)return;revisions.value=cursor?[...revisions.value,...(result.data?.items||[])]:result.data?.items||[];revisionCursor.value=result.data?.nextCursor||null}catch(error){if(owns(c)){if([401,403,404].includes(Number(error.response?.status||error.code))){client.reset();message.value='访问权限已不可用。'}else message.value='版本历史加载失败，当前计划内容仍可用。'}}}
function feedback(result){message.value=({unknown:'结果不明，原命令可能已提交。',conflict:'服务器上的计划已变化，输入已保留。发起其他命令前请重新加载。',failed:'命令已被拒绝，输入已保留；请修改后重试。',stale:'上下文或输入已变化，当前输入已保留；发起其他命令前请重新加载服务器状态。',forbidden:'访问权限已不可用。',unauthenticated:'请重新登录以继续。',unavailable:'此计划不可用。',cancelled:'请求未发送。'})[result.status]||'无法完成此命令。'}
function prepareReturn(action){if(!actionAllowed(action,'REVIEW_RECEIPT')||busy.value||unresolved.value)return;reviewTarget.value={id:action.id,planId:state.plan.id,revisionId:state.plan.revisionId,version:state.plan.version};reviewNote.value='';state.draft={decision:'RETURN',note:''}}
watch(reviewNote,note=>{if(reviewTarget.value && state.editor && state.draft)state.draft={decision:'RETURN',note}},{flush:'sync'})
watch(transitionReason,reason=>{if(transitionAction.value==='CANCEL' && state.editor && state.draft)state.draft={reason}},{flush:'sync'})
async function command(name,settings){if(busy.value||unresolved.value)return;const c=context();state.draft=settings.payload;lastCommand=name;const result=await client.runCommand(name,{...settings,expectedVersion:state.plan.version});if(owns(c))await settle(result,name)}
async function settle(result,name){if(result.status!=='succeeded'){feedback(result);return}const keep=result.draftUnchanged===false,input=keep?JSON.parse(JSON.stringify(state.draft)):null,c=context();const refreshed=await client.open(props.planId,{revisionId:historyRevisionId.value,draft:input});if(!owns(c))return;if(refreshed.status!=='succeeded'){feedback(refreshed);return}if(!keep){reviewTarget.value=null;transitionAction.value=null;reviewNote.value='';transitionReason.value=''}message.value=keep?'原命令已成功，新输入已保留，服务器状态已重新加载。':'服务器记录已更新。复核确认的是记录，不是临床疗效。';if(name==='revisePlan'){editingRevision.value=result.data.draftRevisionId||result.data.revisionId}emit('changed',result.data);await loadRevisions()}
function confirmReview(action){if(!actionAllowed(action,'REVIEW_RECEIPT'))return;return command('reviewReceipt',{id:action.id,payload:{decision:'CONFIRM'}})}
function sendReturn(){if(!returnReady.value||busy.value||unresolved.value)return;const note=reviewNote.value.trim();if(!note||Array.from(note).length>1000){message.value='退回说明需要 1–1000 字。';return}return command('reviewReceipt',{id:reviewTarget.value.id,payload:{decision:'RETURN',note}})}
function prepareTransition(action){if(action==='CLOSE'?!canClose.value:!planAllowed('CANCEL_PLAN'))return;transitionAction.value=action;transitionReason.value='';state.draft=action==='CANCEL'?{reason:''}:{}}
function transition(){const action=transitionAction.value;if(!action||(action==='CLOSE'?!canClose.value:!planAllowed('CANCEL_PLAN')))return;const payload={};if(action==='CANCEL'){const reason=transitionReason.value.trim();if(!reason||Array.from(reason).length>1000){message.value='取消原因需要 1–1000 字。';return}payload.reason=reason}return command('transitionPlan',{action,payload})}
function createRevision(){if(!planAllowed('CREATE_REVISION'))return;return command('revisePlan',{payload:{}})}
function editRevision(id){if(!planAllowed('SAVE_DRAFT')||unresolved.value||busy.value)return;editingRevision.value=id}
async function editorSaved(result){emit('changed',result);await requestReload()}
async function editorClosed(){editingRevision.value=null;await requestReload()}
async function retryOriginal(){if(!unresolved.value||busy.value||!lastCommand)return;const c=context();const result=await client.runCommand(lastCommand,{retry:true});if(owns(c))await settle(result,lastCommand)}
function requestLeave(){if(editingRevision.value){message.value='离开计划前，请先关闭私有草稿编辑器。';return false}if(unresolved.value||state.commandPhase==='pending'){abandonIntent.value={kind:'reload'};return false}return true}
async function requestReload(){if(editingRevision.value){message.value='重新加载计划前，请先关闭私有草稿编辑器。';return {status:'editor-open'}}if(unresolved.value||state.commandPhase==='pending'){abandonIntent.value={kind:'reload'};return {status:'confirmation-required'}}return reloadPreservingInput()}
async function reloadPreservingInput(){const input=state.draft && JSON.parse(JSON.stringify(state.draft));const result=await client.open(props.planId,{revisionId:historyRevisionId.value,draft:input});if(result.status==='succeeded')message.value='服务器状态已重新加载，本地输入已保留。';else if(result.status!=='stale')feedback(result);return result}
function selectHistory(value){if(editingRevision.value){message.value='切换历史版本前，请先关闭私有草稿编辑器。';return}const id=value?Number(value):null;if(id && !revisions.value.some(r=>r.id===id))return;if(unresolved.value||state.commandPhase==='pending'){abandonIntent.value={kind:'history',id};return}historyRevisionId.value=id}
async function confirmAbandon(){const intent=abandonIntent.value;abandonIntent.value=null;if(intent?.kind==='history'){historyRevisionId.value=intent.id;if(historyRevisionId.value===intent.id)await loadDetail()}else await reloadPreservingInput()}
function displayTime(value){if(!value)return '时间不可用';try{return formatPlanTime(value,'zh-CN')}catch{return '服务器时间无效'}}
function safeLink(link){return typeof link==='string'&&link.startsWith('/')&&!link.startsWith('//')&&!/[\s\\]/.test(link)}
function instantMicros(value){const millis=Date.parse(value),fraction=value.match(/\.(\d+)(?:Z|[+-]\d{2}:\d{2})$/)?.[1]||'';return BigInt(millis)*1000n+BigInt(fraction.padEnd(6,'0').slice(3,6))}
function originalTiming(action){try{return instantMicros(action.firstSubmittedAt)<=instantMicros(action.dueAt)?'原始提交在截止时间内':'原始提交晚于截止时间'}catch{return '原始提交时限信息不可用'}}
function revisionLabel(status){return ({DRAFT:'私有草稿',PUBLISHED:'已发布版本'})[status]||'未知状态'}
function actionLabel(status){return ({OPEN:'待执行或待补充信息',NEEDS_HELP:'已请求帮助',SUBMITTED:'已提交，等待医生复核',CONFIRMED:'记录已复核',SUPERSEDED:'已被新版本替代',CANCELLED:'已取消',DRAFT:'私有草稿'})[status]||'未知状态'}
function lifecycleLabel(status){return ({DRAFT:'私有草稿',ACTIVE:'进行中',COMPLETED:'复核后已关闭',CANCELLED:'已取消'})[status]||'未知状态'}
function roleLabel(role){return ({user:'个人用户',family:'家庭照护者',doctor:'医生',nurse:'护士',admin:'管理员'})[String(role||'').toLowerCase()]||'账号'}
function evidenceLabel(type){return type==='MEASUREMENT'?'测量':'医疗记录'}
function eventLabel(type){return ({SUBMITTED:'执行记录已提交',RECEIPT_SUBMITTED:'执行记录已提交',CONFIRMED:'医生已复核记录',RECEIPT_CONFIRMED:'医生已复核记录',RETURNED:'已要求补充信息',RECEIPT_RETURNED:'已要求补充信息',HELP_REQUESTED:'已请求帮助',FOLLOW_UP:'照护团队跟进',FOLLOW_UP_RECORDED:'照护团队跟进',PUBLISHED:'版本已发布',PLAN_CANCELLED:'计划已取消',PLAN_CLOSED:'计划已关闭'})[type]||type}
function beforeUnload(event){if(unresolved.value||state.commandPhase==='pending'){event.preventDefault();event.returnValue=''}}
watch(()=>props.planId,initialize,{immediate:true,flush:'sync'})
watch(historyRevisionId,()=>{if(enabled.value)loadDetail()},{flush:'sync'})
watch(()=>state.editor,editor=>{if(!editor){revisions.value=[];revisionCursor.value=null;reviewTarget.value=null;reviewNote.value='';transitionAction.value=null;transitionReason.value='';editingRevision.value=null;abandonIntent.value=null}},{flush:'sync'})
onMounted(()=>window.addEventListener('beforeunload',beforeUnload))
onUnmounted(()=>{generation++;historyGeneration++;controller?.abort();window.removeEventListener('beforeunload',beforeUnload)})
defineExpose({requestLeave})
</script>
<style scoped>
.execution-report-entry{display:inline-flex;align-items:center;min-height:44px;box-sizing:border-box;padding:10px 14px;max-width:100%;overflow-wrap:anywhere}

.care-plan-detail{min-width:0;color:var(--ink-800)}header,.controls{display:flex;flex-wrap:wrap;gap:12px;align-items:center;justify-content:space-between}h2,h3{margin:8px 0;overflow-wrap:anywhere}p,li{line-height:1.6;overflow-wrap:anywhere}.instructions{white-space:pre-wrap}.action-card,.notice,.event-list article{padding:16px;border:1px solid var(--line);border-radius:12px;margin:16px 0}.notice{background:var(--care-50)}.event-list article{background:var(--surface-subtle);border-left:3px solid var(--care-600)}.feedback{padding:12px;background:var(--surface-subtle)}label{display:grid;gap:6px;margin:12px 0;font-weight:600}select,textarea{width:100%;box-sizing:border-box;min-height:44px;min-width:0;padding:10px;border:1px solid var(--line);border-radius:8px;background:var(--paper);color:var(--ink-800);font:inherit}button{min-height:44px;max-width:100%;padding:10px 14px;border:1px solid var(--care-600);border-radius:8px;background:var(--paper);color:var(--care-800);font:inherit;cursor:pointer}button:disabled{opacity:.5;cursor:default}button:focus-visible,select:focus-visible,textarea:focus-visible,a:focus-visible{outline:3px solid var(--care-600);outline-offset:3px}.controls{justify-content:flex-start}a{color:var(--care-700)}@media(max-width:600px){.controls button{width:100%}.action-card,.notice{padding:12px}header>div{width:100%;min-width:0}}
</style>
