package org.familyhealthcare.common;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/** Known system messages only. Never apply this catalog to clinical or user-entered data. */
final class SystemMessageCatalog {
    private static final Map<String, String> ENGLISH = new LinkedHashMap<>();
    private static final Map<String, String> CHINESE = new LinkedHashMap<>();
    private static final Map<String, String[]> FIELDS = new LinkedHashMap<>();
    static {
        ENGLISH.put("Automated Analysistaskdoes not exist", "Automated analysis task does not exist.");
        ENGLISH.put("BOOTSTRAP_ADMIN_PASSWORD to fewneedneed 12 character", "BOOTSTRAP_ADMIN_PASSWORD must contain at least 12 characters.");
        ENGLISH.put("Current Passwordincorrect", "The current password is incorrect.");
        ENGLISH.put("End DatecannotmorninginStart Date", "The end date must not precede the start date.");
        ENGLISH.put("Inventory and Reminderthresholdcannotfor negativecount", "Stock quantities and reminder thresholds must not be negative.");
        ENGLISH.put("InventoryUnitshould and positivein run prescriptiononecause", "The stock unit must match the active prescription.");
        ENGLISH.put("Notificationchanneldoes not exist or does not belong tocurrentuser", "The notification channel does not exist or belongs to another user.");
        ENGLISH.put("Notificationchannelformatincorrect", "Invalid notification channel format.");
        ENGLISH.put("Notificationchanneltypecannot be empty", "Select a notification channel type.");
        ENGLISH.put("Nutrition DiaryFailed to load, Please Confirm nutrition_diary tablestructureUpdated successfully", "Nutrition diary could not be loaded. Verify that the nutrition_diary table is up to date.");
        ENGLISH.put("Permission deniedActionsthis Notificationchannel", "You do not have permission to manage this notification channel.");
        ENGLISH.put("Please Confirmalready based onClinicianprescriptionverifysolution", "Confirm that this plan has been checked against the clinician's prescription.");
        ENGLISH.put("Please fillwrite200charactertowithin title", "Enter a title of no more than 200 characters.");
        ENGLISH.put("Please fillwriteInventoryUnit", "Enter the stock unit.");
        ENGLISH.put("Please fillwriteeach Daymedication intakeTime and dosage", "Enter each daily medication time and dose.");
        ENGLISH.put("Please first Sign In", "Please sign in first.");
        ENGLISH.put("Please first settingsInventoryUnit and initialquantity", "Set the stock unit and initial quantity first.");
        ENGLISH.put("Please to fewselectoneitemExaminationcontent", "Select at least one item to analyze.");
        ENGLISH.put("ReminderTimecannotlater thanappointmentTime", "The reminder time must not be after the appointment.");
        ENGLISH.put("ReminderTimeformatshouldfor  HH:mm", "Reminder time must use HH:mm.");
        ENGLISH.put("Reportdoes not belong tocurrentFamily Member", "The report does not belong to this family member.");
        ENGLISH.put("Restockquantitymustgreater than0", "The restock quantity must be greater than zero.");
        ENGLISH.put("SelectDialysis Date", "Select a dialysis date.");
        ENGLISH.put("SelectFamily Member", "Select a family member.");
        ENGLISH.put("SelectRun Time", "Select a valid run time.");
        ENGLISH.put("SelectappointmentTime", "Select an appointment time.");
        ENGLISH.put("SelectcurrentFamily Member Medication", "Select a medication belonging to this family member.");
        ENGLISH.put("SelectcurrentFamily Member appointment", "Select an appointment for this family member.");
        ENGLISH.put("Selectduplicatestarperiod", "Select the repeating weekdays.");
        ENGLISH.put("Selecthas valid follow-upfamily caregiver", "Select an available caregiver for follow-up.");
        ENGLISH.put("SelectscheduleDate", "Select a schedule date.");
        ENGLISH.put("SelectsymptomoccurTime", "Select when the symptoms occurred.");
        ENGLISH.put("Start Datecannotlater thanEnd Date", "The start date must not be after the end date.");
        ENGLISH.put("Timecannotduplicate, dosagemustgreater than0", "Medication times must be unique and doses must be greater than zero.");
        ENGLISH.put("Username or Passworderror", "Incorrect username or password.");
        ENGLISH.put("Usernamealready storein ", "The username already exists.");
        ENGLISH.put("Webhook Addresscannot be empty", "Enter a webhook URL.");
        ENGLISH.put("Weekreferencecountexceedrange", "The analysis period is outside the supported range.");
        ENGLISH.put("You do not have permission to ActionsRole", "You do not have permission to manage this role.");
        ENGLISH.put("You do not have permission to Createuser", "You do not have permission to create users.");
        ENGLISH.put("You do not have permission to DeleteRole", "You do not have permission to delete this role.");
        ENGLISH.put("You do not have permission to Deleteuser", "You do not have permission to delete users.");
        ENGLISH.put("You do not have permission to EditOtheruserinformation", "You do not have permission to edit another user's information.");
        ENGLISH.put("You do not have permission to ResetPassword", "You do not have permission to reset passwords.");
        ENGLISH.put("You do not have permission to assignMenu", "You do not have permission to assign menus.");
        ENGLISH.put("You do not have permission to assignRole", "You do not have permission to assign roles.");
        ENGLISH.put("actualdosagemustgreater than0", "The actual dose must be greater than zero.");
        ENGLISH.put("adminRole MenuPermissioncannot in pageEdit, for example needadjustPlease Manualrefreshdatabase", "Administrator menu permissions cannot be edited here. Update the database configuration if changes are required.");
        ENGLISH.put("adminRolecannot Edit", "The administrator role cannot be edited.");
        ENGLISH.put("adminRolecannot Delete", "The administrator role cannot be deleted.");
        ENGLISH.put("adminusercannot Delete", "The administrator account cannot be deleted.");
        ENGLISH.put("backupcopyformat or versionthis not receivesupport", "The backup format or version is not supported.");
        ENGLISH.put("backupcopyin Family Memberrelateddoes not exist", "A referenced family member is missing from the backup.");
        ENGLISH.put("backupcopymissingFamily Memberrecord", "The backup contains no family member records.");
        ENGLISH.put("backupcopymissingFamily Memberrelated", "The backup is missing a required family member reference.");
        ENGLISH.put("batchFailed to save", "Failed to save the batch.");
        ENGLISH.put("batchSaved successfully", "Batch saved successfully.");
        ENGLISH.put("cannotchangerecordbelongFamily Member or type", "The family member and record type cannot be changed.");
        ENGLISH.put("cannotwill Remindermoveto OtherFamily Member", "A reminder cannot be moved to another family member.");
        ENGLISH.put("decompressafter  backupcopyexceed200MB, Please by Family Membersplitbackupcopy", "The expanded backup exceeds 200 MB. Split the backup by family member.");
        ENGLISH.put("down timesfollow-up examinationshouldlater thanthis timesappointment", "The next follow-up must be after this appointment.");
        ENGLISH.put("duplicateWeekshouldfor weekoneto weekDay", "Repeating weekdays must be Monday through Sunday (1 to 7).");
        ENGLISH.put("not Yeshas valid familyhealthbackupcopyfile", "This is not a valid family health backup file.");
        ENGLISH.put("onlymanagementmembercan ViewauditDaylog", "Only administrators can view the audit log.");
        ENGLISH.put("onlymanagementmembercan maintainMenu", "Only administrators can manage menus.");
        ENGLISH.put("prescriptionActionsNonevalid", "Invalid prescription action.");
        ENGLISH.put("prescriptionchangePlease Addversionthis , keeporiginalsolution", "Create a new prescription version to preserve the original plan.");
        ENGLISH.put("prescriptiondosageUnitmust and MedicationInventoryUnitonecause, Please first verifyInventory", "The prescription dose unit must match the medication stock unit. Verify stock settings first.");
        ENGLISH.put("prescriptionhistorycannotDelete, Please Cancelnot take effectversionthis  or Addstop medicationprescription", "Prescription history cannot be deleted. Cancel an inactive version or create a stop-medication order.");
        ENGLISH.put("recordtypeNonevalid", "Invalid record type.");
        ENGLISH.put("responsible forpersonmustYesthis Family Member carecompletemember", "The assignee must belong to this family member's care team.");
        ENGLISH.put("runWeekNonevalid", "Invalid run frequency.");
        ENGLISH.put("scheduleInvalid status.", "Invalid schedule status.");
        ENGLISH.put("scheduleTimeformatincorrect", "Invalid schedule time format.");
        ENGLISH.put("scheduledoes not exist or does not belong tocurrentFamily Member", "The schedule does not exist or belongs to another family member.");
        ENGLISH.put("symptomlevelshouldin 0to 10between", "Symptom severity must be between 0 and 10.");
        ENGLISH.put("take effectprescriptionPlease throughAddchange or stop medicationprescriptionprocess", "Change an active prescription by creating a new version or a stop-medication order.");
        ENGLISH.put("this Datealready has schedule, Please Editoriginalschedule", "A schedule already exists for this date. Edit the existing schedule.");
        ENGLISH.put("this WeekNoneDialysisdata", "There are no dialysis records for this period.");
        ENGLISH.put("Confirmsuccessful", "Confirmed successfully.");
        ENGLISH.put("resolvesuccessful", "Resolved successfully.");
        ENGLISH.put("alertExaminationcomplete", "Alert check completed.");
        ENGLISH.put("Menuassignsuccessful", "Menus assigned successfully.");
        ENGLISH.put("PasswordUpdated successfully, Please sign in again", "Password updated successfully. Please sign in again.");
        CHINESE.put("Invalid nurse grant fields.", "护理授权字段无效。");
        CHINESE.put("A nurse grant must explicitly include CARE_PLAN.", "护理授权必须明确包含 CARE_PLAN。");
        CHINESE.put("Access denied to this care-plan grant.", "无权管理该照护计划授权。");
        CHINESE.put("success", "成功");
        CHINESE.put("Saved successfully", "保存成功");
        CHINESE.put("Failed to save", "保存失败");
        CHINESE.put("Updated successfully", "更新成功");
        CHINESE.put("Update failed", "更新失败");
        CHINESE.put("Deleted successfully", "删除成功");
        CHINESE.put("Failed to delete", "删除失败");
        CHINESE.put("Created successfully", "创建成功");
        CHINESE.put("Operation completed", "操作成功");
        CHINESE.put("Operation failed", "操作失败");
        CHINESE.put("Deleted", "已删除");
        CHINESE.put("Not signed in", "尚未登录");
        CHINESE.put("User not found", "用户不存在");
        CHINESE.put("Role not found", "角色不存在");
        CHINESE.put("The record does not exist.", "记录不存在。");
        CHINESE.put("Select a patient", "请选择患者");
        CHINESE.put("Invalid request parameter.", "请求参数无效。");
        CHINESE.put("Invalid date range", "日期范围无效");
        CHINESE.put("Invalid status.", "状态无效。");
        CHINESE.put("The account is disabled.", "账号已停用。");
        CHINESE.put("Username or Passworderror", "用户名或密码错误。");
        CHINESE.put("Password reset successfully", "密码重置成功");
        CHINESE.put("Password reset failed", "密码重置失败");
        CHINESE.put("Record verified", "记录已核验");
        CHINESE.put("Record rejected", "记录已驳回");
        CHINESE.put("Removed successfully.", "移除成功。");
        CHINESE.put("Inventory settings saved.", "库存设置已保存。");
        CHINESE.put("Restock recorded.", "补货记录已保存。");
        CHINESE.put("Recorded successfully.", "记录成功。");
        CHINESE.put("Configure a valid webhook URL.", "请配置有效的 Webhook 地址。");
        CHINESE.put("The webhook URL must begin with http:// or https://.", "Webhook 地址必须以 http:// 或 https:// 开头。");
        CHINESE.put("Unsupported notification channel type.", "不支持的通知渠道类型。");
        CHINESE.put("Preview the data and explicitly confirm the import first.", "请先预览数据并明确确认导入。");
        CHINESE.put("There are no records to save.", "没有可保存的记录。");
        CHINESE.put("No recognizable image was found.", "未找到可识别的图片。");
        CHINESE.put("Word recognition is not supported yet. Upload an image or PDF.", "暂不支持 Word 识别，请上传图片或 PDF。");
        CHINESE.put("Vital-sign records could not be loaded. Verify that the database is initialized.", "生命体征记录加载失败，请确认数据库已完成初始化。");
        CHINESE.put("Complication records could not be loaded. Verify that the database is initialized.", "并发症记录加载失败，请确认数据库已完成初始化。");
        CHINESE.put("Complication statistics could not be loaded. Verify that the database is initialized.", "并发症统计加载失败，请确认数据库已完成初始化。");
        CHINESE.put("Nutrition DiaryFailed to load, Please Confirm nutrition_diary tablestructureUpdated successfully", "营养日记加载失败，请确认 nutrition_diary 表结构已完成更新。");
        CHINESE.put("The patient does not exist.", "患者不存在。");
        CHINESE.put("The alert does not exist.", "提醒不存在。");
        CHINESE.put("The task status changed. Refresh and try again.", "任务状态已变化，请刷新后重试。");
        CHINESE.put("This task has been cancelled.", "该任务已取消。");
        CHINESE.put("This task has already been processed. Refresh the page.", "该任务已处理，请刷新页面。");
        CHINESE.put("A target minimum cannot exceed its maximum.", "目标最小值不能大于最大值。");
        CHINESE.put("Enter an event title.", "请输入事件标题。");
        CHINESE.put("The title may contain up to 120 characters and the description up to 500.", "标题最多 120 个字符，描述最多 500 个字符。");
        CHINESE.put("Invalid event type.", "事件类型无效。");
        CHINESE.put("Select an event date.", "请选择事件日期。");
        CHINESE.put("Invalid event time format.", "事件时间格式无效。");
        CHINESE.put("The event does not exist.", "事件不存在。");
        CHINESE.put("The event does not exist or belongs to another patient.", "事件不存在或属于其他患者。");
        CHINESE.put("Edit this item from its original record page.", "请前往原始记录页面编辑此项目。");
        CHINESE.put("Delete this item from its original record page.", "请前往原始记录页面删除此项目。");
        CHINESE.put("Medication not found", "药品不存在");
        CHINESE.put("Medication list cannot be empty", "药品列表不能为空");
        CHINESE.put("Upload at least one file.", "请至少上传一个文件。");
        CHINESE.put("Upload no more than 10 files at a time.", "每次最多上传 10 个文件。");
        CHINESE.put("Image data cannot be empty", "图片数据不能为空");
        CHINESE.put("batchSaved successfully", "批量保存成功。");
        CHINESE.put("batchFailed to save", "批量保存失败。");
        CHINESE.put("Confirmsuccessful", "确认成功。");
        CHINESE.put("resolvesuccessful", "处理成功。");
        CHINESE.put("alertExaminationcomplete", "提醒检查完成。");
        CHINESE.put("Password update failed", "密码更新失败");
        CHINESE.put("Role assigned successfully", "角色分配成功");
        CHINESE.put("You do not have permission to ActionsRole", "您无权管理此角色。");
        CHINESE.put("adminRolecannot Edit", "管理员角色不能编辑。");
        CHINESE.put("You do not have permission to DeleteRole", "您无权删除此角色。");
        CHINESE.put("adminRolecannot Delete", "管理员角色不能删除。");
        CHINESE.put("You do not have permission to assignMenu", "您无权分配菜单。");
        CHINESE.put("adminRole MenuPermissioncannot in pageEdit, for example needadjustPlease Manualrefreshdatabase", "管理员菜单权限不能在此编辑，如需调整请更新数据库配置。");
        CHINESE.put("Menuassignsuccessful", "菜单分配成功。");
        CHINESE.put("You do not have permission to Createuser", "您无权创建用户。");
        CHINESE.put("Usernamealready storein ", "用户名已存在。");
        CHINESE.put("You do not have permission to EditOtheruserinformation", "您无权编辑其他用户的信息。");
        CHINESE.put("You do not have permission to Deleteuser", "您无权删除用户。");
        CHINESE.put("adminusercannot Delete", "管理员账号不能删除。");
        CHINESE.put("You do not have permission to ResetPassword", "您无权重置密码。");
        CHINESE.put("PasswordUpdated successfully, Please sign in again", "密码更新成功，请重新登录。");
        CHINESE.put("You do not have permission to assignRole", "您无权分配角色。");
        CHINESE.put("The system could not process the request. Please try again later.", "系统暂时无法处理该请求，请稍后重试。");
        CHINESE.put("A required parameter is missing or has an invalid format.", "必填参数缺失或格式无效。");
        CHINESE.put("A resolved alert cannot be reopened. Run a new assessment instead.", "已处理的提醒不能重新开启，请发起新的评估。");
        CHINESE.put("An assessment cannot be moved to another patient.", "不能将评估移至其他患者。");
        CHINESE.put("Analysis draft does not exist.", "分析草稿不存在。");
        CHINESE.put("Assessment schedule not found.", "评估计划不存在。");
        CHINESE.put("Blood glucose is required.", "请填写血糖数值。");
        CHINESE.put("Blood glucose must be greater than zero.", "血糖数值必须大于零。");
        CHINESE.put("Choose a valid schedule date range.", "请选择有效的计划日期范围。");
        CHINESE.put("Dialysis care is not enabled for this patient.", "当前患者尚未启用透析照护。");
        CHINESE.put("Dialysis time must use HH:mm.", "透析时间必须使用 HH:mm 格式。");
        CHINESE.put("Doctor access is required.", "此操作需要医生权限。");
        CHINESE.put("Document the action taken before resolving an alert.", "处理提醒前，请记录已采取的措施。");
        CHINESE.put("Emergency event not found.", "紧急事件不存在。");
        CHINESE.put("Enter blood pressure or blood glucose.", "请填写血压或血糖。");
        CHINESE.put("Enter both systolic and diastolic blood pressure.", "请同时填写收缩压和舒张压。");
        CHINESE.put("Invalid alert status.", "提醒状态无效。");
        CHINESE.put("Invalid note visibility.", "笔记可见性设置无效。");
        CHINESE.put("Invalid review decision.", "复核决定无效。");
        CHINESE.put("Invalid source selector.", "来源选择无效。");
        CHINESE.put("Kt/V must be between 0 and 10.", "Kt/V 必须在 0 到 10 之间。");
        CHINESE.put("Logo must be a local path, HTTPS URL, or supported image data URL.", "标志必须使用本地路径、HTTPS 地址或支持的图片数据地址。");
        CHINESE.put("Measurement not found.", "测量记录不存在。");
        CHINESE.put("Notification acknowledgement was unavailable.", "未收到通知接收确认。");
        CHINESE.put("Only a booked appointment can be rescheduled.", "只能改期已预约的就诊。");
        CHINESE.put("Only administrators can assign doctors.", "只有管理员可以分配医生。");
        CHINESE.put("Only administrators can change platform branding.", "只有管理员可以更改平台品牌设置。");
        CHINESE.put("Only administrators can perform this action.", "只有管理员可以执行此操作。");
        CHINESE.put("Only the patient owner or an administrator can assign specialty roles.", "只有患者档案所有者或管理员可以分配专科角色。");
        CHINESE.put("Only the record owner can manage caregivers.", "只有档案所有者可以管理照护者。");
        CHINESE.put("Organization name must not exceed 120 characters.", "机构名称不能超过 120 个字符。");
        CHINESE.put("Ownership text is required and must not exceed 240 characters.", "请填写不超过 240 个字符的归属说明。");
        CHINESE.put("Page background must be a six-digit hex color.", "页面背景必须使用六位十六进制颜色值。");
        CHINESE.put("Password must be 10 to 128 characters long", "密码长度必须为 10 至 128 个字符。");
        CHINESE.put("Password must contain letters, numbers, and special characters", "密码必须包含字母、数字和特殊字符。");
        CHINESE.put("Platform name is required and must not exceed 80 characters.", "请填写不超过 80 个字符的平台名称。");
        CHINESE.put("Preview no more than 93 days at a time.", "每次最多预览 93 天。");
        CHINESE.put("Record date is required.", "请填写记录日期。");
        CHINESE.put("Select a patient.", "请选择患者。");
        CHINESE.put("Select a valid measurement type.", "请选择有效的测量类型。");
        CHINESE.put("Select at least one confirmed dialysis weekday.", "请至少选择一个已确认的透析星期。");
        CHINESE.put("Select valid specialty roles.", "请选择有效的专科角色。");
        CHINESE.put("Session duration must be between 30 and 1440 minutes.", "单次透析时长必须在 30 到 1440 分钟之间。");
        CHINESE.put("Specialty roles belong to patient records, not user accounts.", "专科角色应分配给患者档案，而非用户账号。");
        CHINESE.put("Systolic and diastolic blood pressure are required.", "请填写收缩压和舒张压。");
        CHINESE.put("The family member record does not exist.", "家庭成员档案不存在。");
        CHINESE.put("The invitation code is invalid, expired, or already used.", "邀请码无效、已过期或已使用。");
        CHINESE.put("The review record does not exist or has no patient.", "复核记录不存在或未关联患者。");
        CHINESE.put("This analysis draft has already been reviewed.", "该分析草稿已完成审核。");
        CHINESE.put("This patient is not assigned to you.", "当前患者尚未分配给您。");
        CHINESE.put("This status is reserved for collaborative care plans.", "此状态仅用于协作照护计划。");
        CHINESE.put("URR must be between 0 and 100 percent.", "URR 必须在 0% 到 100% 之间。");
        CHINESE.put("Unsupported medical-record source type.", "不支持此医疗记录来源类型。");
        CHINESE.put("Unsupported metric type.", "不支持此指标类型。");
        CHINESE.put("Unsupported review source.", "不支持此复核来源。");
        CHINESE.put("You are not signed in. Please sign in first.", "您尚未登录，请先登录。");
        CHINESE.put("Your session has expired. Please sign in again.", "登录已过期，请重新登录。");
        CHINESE.put("The account does not exist or is disabled.", "账号不存在或已停用。");
        CHINESE.put("Access denied to source record.", "您无权访问原始记录。");
        CHINESE.put("This grant is read-only.", "此授权仅允许查看。");
        CHINESE.put("This module is outside the authorized visibility scope.", "此模块不在已授权的可见范围内。");
        CHINESE.put("Nurse module scope must explicitly include CARE_PLAN.", "护理模块范围必须明确包含 CARE_PLAN。");
        CHINESE.put("Only doctors can receive doctor access.", "只有医生可以获得医生访问权限。");
        CHINESE.put("Only nurses can receive nurse access.", "只有护理人员可以获得护理访问权限。");
        CHINESE.put("The draft was saved, but no enabled notification channel accepted the message.", "草稿已保存，但没有已启用的通知渠道接收该消息。");
        CHINESE.put("Failed to sign the DingTalk request. Check the signing secret.", "钉钉请求签名失败，请检查签名密钥。");
        CHINESE.put("You do not have access to this patient or action.", "您无权访问当前患者或执行此操作。");
        CHINESE.put("Invalid access grant.", "授权角色或访问级别无效。");
        CHINESE.put("The record owner already has full access.", "患者档案所有者已拥有完整访问权限，无需重复授权。");
        CHINESE.put("The selected user does not exist or is disabled.", "所选用户不存在或已被停用。");
        CHINESE.put("Access expiry must be in the future.", "授权到期时间必须晚于当前时间。");
        CHINESE.put("Only the patient or guardian owner can manage access.", "只有患者本人或档案所属监护人可以管理授权。");
        CHINESE.put("Access to this module has not been authorized by the patient.", "患者尚未授权您访问此模块。");
        CHINESE.put("Clinician access is required.", "此操作需要医生权限。");
        CHINESE.put("You can only manage your own schedule.", "您只能管理自己的医生排班。");
        CHINESE.put("End time must be after start time.", "结束时间必须晚于开始时间。");
        CHINESE.put("The slot length must fit inside the clinician availability.", "预约时段长度不能超出医生排班范围。");
        CHINESE.put("A valid appointment time is required.", "请填写有效的预约开始和结束时间。");
        CHINESE.put("Follow-up interval must be between 0 and 3650 days.", "复诊周期必须在 0 到 3650 天之间。");
        CHINESE.put("The selected clinician availability is no longer available.", "所选医生排班已不可预约，请重新选择。");
        CHINESE.put("The appointment must fit inside the selected clinician availability.", "预约起止时间必须处于所选医生的排班范围内。");
        CHINESE.put("The clinician time slot is already occupied.", "医生的这个时段已被预约，请选择其他时段。");
        CHINESE.put("Appointment not found.", "预约记录不存在。");
        CHINESE.put("Only a booked appointment can be cancelled.", "只能取消已预约的就诊。");
        CHINESE.put("Only a booked appointment can be completed.", "只能将已预约的就诊标记为完成。");
        CHINESE.put("Only the selected clinician can complete this appointment.", "仅本次预约医生可完成就诊。");
        CHINESE.put("Appointment not found for this patient.", "当前患者不存在此预约记录。");
        CHINESE.put("Enter a diagnosis or treatment summary.", "请填写诊断或治疗小结。");
        CHINESE.put("Visit record not found.", "就诊记录不存在。");
        CHINESE.put("Visit record not found for this patient.", "当前患者不存在此就诊记录。");
        CHINESE.put("Add at least one prescription item.", "请至少添加一项处方药品。");
        CHINESE.put("Invalid prescription item.", "处方药品信息无效。");
        CHINESE.put("Prescription duration must be between 1 and 3650 days.", "用药疗程必须在 1 到 3650 天之间。");
        CHINESE.put("Invalid rehabilitation record type.", "康复记录类型无效。");
        CHINESE.put("Treatment plan not found for this patient.", "当前患者不存在此治疗计划。");
        CHINESE.put("Completion must be between 0 and 100.", "完成度必须在 0 到 100 之间。");
        CHINESE.put("Unsupported specialty record type.", "不支持所选专项健康记录类型。");
        CHINESE.put("Assessment interval must be between 1 and 3650 days.", "量表推送间隔必须在 1 到 3650 天之间。");
        CHINESE.put("You can only manage your own groups.", "您只能管理自己创建的患者分组。");
        CHINESE.put("Group access denied.", "您无权访问此患者分组。");
        CHINESE.put("The end date must not precede the start date.", "结束日期不能早于开始日期。");
        CHINESE.put("Patient not found.", "患者不存在。");
        CHINESE.put("Measurement value is required.", "请填写指标数值。");
        CHINESE.put("Blood pressure is outside the accepted input range.", "血压数值超出允许录入范围，请核对后重试。");
        CHINESE.put("SpO2 must be between 0 and 100.", "血氧饱和度必须在 0 到 100 之间。");
        CHINESE.put("The record was not created.", "记录创建失败，请重试。");
        CHINESE.put("Enter a valid date and time.", "请输入有效的日期和时间。");
        CHINESE.put("Enter a valid date.", "请输入有效的日期。");
        CHINESE.put("Annotation is required.", "请填写医生标注内容。");
        CHINESE.put("Permission denied", "没有执行此操作的权限");
        CHINESE.put("Access denied", "无权访问此功能");
        CHINESE.put("Test message sent. Check the receiving channel.", "测试消息已发送，请在接收端查看。");
        CHINESE.put("Test failed. Check the webhook address, receiver, and network.", "测试发送失败，请检查 Webhook 地址、接收端和网络。");
        CHINESE.put("Select an active doctor for the consultation.", "请选择当前可接诊的医生。");
        CHINESE.put("Only invited consultation participants can send messages or join calls.", "只有本次问诊中受邀的参与者可以发送消息或加入通话。");
        CHINESE.put("Only the patient, initiating caregiver, or selected doctor can close this consultation.", "只有患者、发起问诊的照护者或接诊医生可以结束本次问诊。");
        CHINESE.put("Only a doctor can provide referral advice.", "转科建议只能由医生填写。");
        CHINESE.put("The attachment does not belong to this patient.", "该附件不属于本次问诊的患者。");
        CHINESE.put("Select a patient medical record to attach.", "请选择要共享的患者医疗记录。");
        CHINESE.put("The shared attachment is not available. Ask the sender to upload it again.", "共享附件暂时无法读取，请联系发送者重新上传。");
        CHINESE.put("Signal target is not another consultation participant.", "通话对象必须是本次问诊的其他参与者。");
        CHINESE.put("The call signal is too large.", "通话连接数据过大，请重新加入通话。");
        CHINESE.put("Invalid consultation status.", "问诊状态无效。");
        CHINESE.put("Invalid family visibility.", "家属可见性设置无效。");
        CHINESE.put("Invalid consultation mode.", "问诊方式无效。");
        CHINESE.put("Unsupported consultation mode.", "不支持所选问诊方式。");
        CHINESE.put("Invalid signal type.", "通话连接数据类型无效。");
        CHINESE.put("This consultation is private and is not visible to family caregivers.", "本次问诊为私密问诊，家属无法查看。");
        CHINESE.put("Invalid message type.", "消息类型无效。");
        CHINESE.put("Consultation is closed.", "本次问诊已结束，无法继续发送消息或加入通话。");
        CHINESE.put("Consultation not found.", "问诊记录不存在。");
        CHINESE.put("Authentication is required.", "请先登录后再进行此操作。");
        CHINESE.put("Unsupported assessment scale.", "不支持所选评估量表。");
        CHINESE.put("Blood glucose unit must be mmol/L or mg/dL.", "血糖单位必须为 mmol/L 或 mg/dL。");
        CHINESE.put("Assessment answers must be an array of item scores.", "请按题目顺序填写量表各题得分。");
        CHINESE.put("Assessment item scores must be whole numbers.", "量表各题得分必须是整数。");
        CHINESE.put("Confirm whether both active entries are intended.", "请确认这两条启用记录是否均为预期医嘱。");
        CHINESE.put("Do not change treatment in the app; contact the prescribing clinician or pharmacist promptly.", "请勿在平台内自行变更治疗方案，应尽快联系开方医生或药师。");
        CHINESE.put("NSAIDs may be unsuitable in advanced kidney disease; verify the prescriber plan.", "NSAIDs 可能不适合晚期肾病患者，请核实开方方案。");
        CHINESE.put("Screening is decision support only. A clinician or pharmacist must confirm every medication change.", "筛查结果仅用于辅助决策，任何用药变更都必须由医生或药师确认。");
        CHINESE.put("Thresholds are screening cues, not treatment targets. The dialysis team must interpret them in clinical context.", "阈值仅用于风险筛查，并非治疗目标；应由透析团队结合临床情况解读。");
        CHINESE.put("For emergency communication only. Verify identity, medication list, and allergies with the patient or treating team.", "仅用于急救沟通。请与患者或诊疗团队核验身份、用药清单和过敏史。");
        CHINESE.put("A critical reading was detected. Repeat the measurement now and contact a clinician promptly if symptoms are present.", "存在严重异常，请立即复测；如伴随明显不适，请按医嘱联系医生或及时就医。");
        CHINESE.put("No recent blood pressure record is available. Consider taking one resting measurement.", "暂无近期血压记录，建议在静息状态下测量一次。");
        CHINESE.put("The latest blood-pressure reading is outside the usual range. Rest, repeat the measurement, and continue recording results.", "最近血压超出常用范围，建议休息后复测并持续记录。");
        CHINESE.put("No recent blood glucose record is available. Add one if it is part of the care plan.", "暂无近期血糖记录；如照护计划包含血糖监测，请补充一次。");
        CHINESE.put("Monitoring coverage is limited. Regular entries will make trend assessments more reliable.", "当前监测数据覆盖不足，持续记录后趋势判断会更可靠。");
        CHINESE.put("No urgent items are present. Continue recording measurements, medications, and follow-up visits as planned.", "当前没有紧急事项，请继续按计划记录、用药和复查。");
        CHINESE.put("Average interdialytic weight gain is above 4% of target dry weight.", "平均透析间期体重增幅超过目标干体重的 4%。");
        CHINESE.put("Average ultrafiltration rate is above 13 mL/kg/hour.", "平均超滤率超过 13 mL/kg/小时。");
        CHINESE.put("Average recorded Kt/V is below 1.2.", "已记录的平均 Kt/V 低于 1.2。");
        CHINESE.put("Average recorded URR is below 65%.", "已记录的平均 URR 低于 65%。");
        CHINESE.put("Automated Analysistaskdoes not exist", "自动分析任务不存在。");
        CHINESE.put("Automated analysis task does not exist.", "自动分析任务不存在。");
        CHINESE.put("BOOTSTRAP_ADMIN_PASSWORD to fewneedneed 12 character", "BOOTSTRAP_ADMIN_PASSWORD 必须至少包含 12 个字符。");
        CHINESE.put("BOOTSTRAP_ADMIN_PASSWORD must contain at least 12 characters.", "BOOTSTRAP_ADMIN_PASSWORD 必须至少包含 12 个字符。");
        CHINESE.put("Current Passwordincorrect", "当前密码错误。");
        CHINESE.put("The current password is incorrect.", "当前密码错误。");
        CHINESE.put("End DatecannotmorninginStart Date", "结束日期不能早于开始日期。");
        CHINESE.put("Inventory and Reminderthresholdcannotfor negativecount", "库存数量和提醒阈值不能为负数。");
        CHINESE.put("Stock quantities and reminder thresholds must not be negative.", "库存数量和提醒阈值不能为负数。");
        CHINESE.put("InventoryUnitshould and positivein run prescriptiononecause", "库存单位必须与当前生效处方一致。");
        CHINESE.put("The stock unit must match the active prescription.", "库存单位必须与当前生效处方一致。");
        CHINESE.put("Notificationchanneldoes not exist or does not belong tocurrentuser", "通知渠道不存在或不属于当前用户。");
        CHINESE.put("The notification channel does not exist or belongs to another user.", "通知渠道不存在或不属于当前用户。");
        CHINESE.put("Notificationchannelformatincorrect", "通知渠道格式无效。");
        CHINESE.put("Invalid notification channel format.", "通知渠道格式无效。");
        CHINESE.put("Notificationchanneltypecannot be empty", "请选择通知渠道类型。");
        CHINESE.put("Select a notification channel type.", "请选择通知渠道类型。");
        CHINESE.put("Nutrition diary could not be loaded. Verify that the nutrition_diary table is up to date.", "营养日记加载失败，请确认 nutrition_diary 表结构已完成更新。");
        CHINESE.put("Permission deniedActionsthis Notificationchannel", "您无权管理此通知渠道。");
        CHINESE.put("You do not have permission to manage this notification channel.", "您无权管理此通知渠道。");
        CHINESE.put("Please Confirmalready based onClinicianprescriptionverifysolution", "请确认已根据医生处方核对该方案。");
        CHINESE.put("Confirm that this plan has been checked against the clinician's prescription.", "请确认已根据医生处方核对该方案。");
        CHINESE.put("Please fillwrite200charactertowithin title", "请输入不超过 200 个字符的标题。");
        CHINESE.put("Enter a title of no more than 200 characters.", "请输入不超过 200 个字符的标题。");
        CHINESE.put("Please fillwriteInventoryUnit", "请输入库存单位。");
        CHINESE.put("Enter the stock unit.", "请输入库存单位。");
        CHINESE.put("Please fillwriteeach Daymedication intakeTime and dosage", "请填写每日各次服药时间和剂量。");
        CHINESE.put("Enter each daily medication time and dose.", "请填写每日各次服药时间和剂量。");
        CHINESE.put("Please first Sign In", "请先登录。");
        CHINESE.put("Please sign in first.", "请先登录。");
        CHINESE.put("Please first settingsInventoryUnit and initialquantity", "请先设置库存单位和初始数量。");
        CHINESE.put("Set the stock unit and initial quantity first.", "请先设置库存单位和初始数量。");
        CHINESE.put("Please to fewselectoneitemExaminationcontent", "请至少选择一项分析内容。");
        CHINESE.put("Select at least one item to analyze.", "请至少选择一项分析内容。");
        CHINESE.put("ReminderTimecannotlater thanappointmentTime", "提醒时间不能晚于预约时间。");
        CHINESE.put("The reminder time must not be after the appointment.", "提醒时间不能晚于预约时间。");
        CHINESE.put("ReminderTimeformatshouldfor  HH:mm", "提醒时间必须使用 HH:mm 格式。");
        CHINESE.put("Reminder time must use HH:mm.", "提醒时间必须使用 HH:mm 格式。");
        CHINESE.put("Reportdoes not belong tocurrentFamily Member", "该报告不属于当前家庭成员。");
        CHINESE.put("The report does not belong to this family member.", "该报告不属于当前家庭成员。");
        CHINESE.put("Restockquantitymustgreater than0", "补货数量必须大于零。");
        CHINESE.put("The restock quantity must be greater than zero.", "补货数量必须大于零。");
        CHINESE.put("SelectDialysis Date", "请选择透析日期。");
        CHINESE.put("Select a dialysis date.", "请选择透析日期。");
        CHINESE.put("SelectFamily Member", "请选择家庭成员。");
        CHINESE.put("Select a family member.", "请选择家庭成员。");
        CHINESE.put("SelectRun Time", "请选择有效的运行时间。");
        CHINESE.put("Select a valid run time.", "请选择有效的运行时间。");
        CHINESE.put("SelectappointmentTime", "请选择预约时间。");
        CHINESE.put("Select an appointment time.", "请选择预约时间。");
        CHINESE.put("SelectcurrentFamily Member Medication", "请选择属于当前家庭成员的药品。");
        CHINESE.put("Select a medication belonging to this family member.", "请选择属于当前家庭成员的药品。");
        CHINESE.put("SelectcurrentFamily Member appointment", "请选择当前家庭成员的预约。");
        CHINESE.put("Select an appointment for this family member.", "请选择当前家庭成员的预约。");
        CHINESE.put("Selectduplicatestarperiod", "请选择重复提醒的星期。");
        CHINESE.put("Select the repeating weekdays.", "请选择重复提醒的星期。");
        CHINESE.put("Selecthas valid follow-upfamily caregiver", "请选择有效的跟进照护者。");
        CHINESE.put("Select an available caregiver for follow-up.", "请选择有效的跟进照护者。");
        CHINESE.put("SelectscheduleDate", "请选择计划日期。");
        CHINESE.put("Select a schedule date.", "请选择计划日期。");
        CHINESE.put("SelectsymptomoccurTime", "请选择症状发生时间。");
        CHINESE.put("Select when the symptoms occurred.", "请选择症状发生时间。");
        CHINESE.put("Start Datecannotlater thanEnd Date", "开始日期不能晚于结束日期。");
        CHINESE.put("The start date must not be after the end date.", "开始日期不能晚于结束日期。");
        CHINESE.put("Timecannotduplicate, dosagemustgreater than0", "服药时间不能重复，剂量必须大于零。");
        CHINESE.put("Medication times must be unique and doses must be greater than zero.", "服药时间不能重复，剂量必须大于零。");
        CHINESE.put("Incorrect username or password.", "用户名或密码错误。");
        CHINESE.put("The username already exists.", "用户名已存在。");
        CHINESE.put("Webhook Addresscannot be empty", "请输入 Webhook 地址。");
        CHINESE.put("Enter a webhook URL.", "请输入 Webhook 地址。");
        CHINESE.put("Weekreferencecountexceedrange", "分析周期超出支持范围。");
        CHINESE.put("The analysis period is outside the supported range.", "分析周期超出支持范围。");
        CHINESE.put("You do not have permission to manage this role.", "您无权管理此角色。");
        CHINESE.put("You do not have permission to create users.", "您无权创建用户。");
        CHINESE.put("You do not have permission to delete this role.", "您无权删除此角色。");
        CHINESE.put("You do not have permission to delete users.", "您无权删除用户。");
        CHINESE.put("You do not have permission to edit another user's information.", "您无权编辑其他用户的信息。");
        CHINESE.put("You do not have permission to reset passwords.", "您无权重置密码。");
        CHINESE.put("You do not have permission to assign menus.", "您无权分配菜单。");
        CHINESE.put("You do not have permission to assign roles.", "您无权分配角色。");
        CHINESE.put("actualdosagemustgreater than0", "实际剂量必须大于零。");
        CHINESE.put("The actual dose must be greater than zero.", "实际剂量必须大于零。");
        CHINESE.put("Administrator menu permissions cannot be edited here. Update the database configuration if changes are required.", "管理员菜单权限不能在此编辑，如需调整请更新数据库配置。");
        CHINESE.put("The administrator role cannot be edited.", "管理员角色不能编辑。");
        CHINESE.put("The administrator role cannot be deleted.", "管理员角色不能删除。");
        CHINESE.put("The administrator account cannot be deleted.", "管理员账号不能删除。");
        CHINESE.put("backupcopyformat or versionthis not receivesupport", "不支持该备份格式或版本。");
        CHINESE.put("The backup format or version is not supported.", "不支持该备份格式或版本。");
        CHINESE.put("backupcopyin Family Memberrelateddoes not exist", "备份中缺少所引用的家庭成员。");
        CHINESE.put("A referenced family member is missing from the backup.", "备份中缺少所引用的家庭成员。");
        CHINESE.put("backupcopymissingFamily Memberrecord", "备份中没有家庭成员记录。");
        CHINESE.put("The backup contains no family member records.", "备份中没有家庭成员记录。");
        CHINESE.put("backupcopymissingFamily Memberrelated", "备份中缺少必需的家庭成员关联。");
        CHINESE.put("The backup is missing a required family member reference.", "备份中缺少必需的家庭成员关联。");
        CHINESE.put("Failed to save the batch.", "批量保存失败。");
        CHINESE.put("Batch saved successfully.", "批量保存成功。");
        CHINESE.put("cannotchangerecordbelongFamily Member or type", "不能更改记录所属家庭成员或类型。");
        CHINESE.put("The family member and record type cannot be changed.", "不能更改记录所属家庭成员或类型。");
        CHINESE.put("cannotwill Remindermoveto OtherFamily Member", "不能将提醒移至其他家庭成员。");
        CHINESE.put("A reminder cannot be moved to another family member.", "不能将提醒移至其他家庭成员。");
        CHINESE.put("decompressafter  backupcopyexceed200MB, Please by Family Membersplitbackupcopy", "解压后的备份超过 200 MB，请按家庭成员拆分备份。");
        CHINESE.put("The expanded backup exceeds 200 MB. Split the backup by family member.", "解压后的备份超过 200 MB，请按家庭成员拆分备份。");
        CHINESE.put("down timesfollow-up examinationshouldlater thanthis timesappointment", "下次复诊必须晚于本次预约。");
        CHINESE.put("The next follow-up must be after this appointment.", "下次复诊必须晚于本次预约。");
        CHINESE.put("duplicateWeekshouldfor weekoneto weekDay", "重复提醒的星期必须为周一至周日（1 至 7）。");
        CHINESE.put("Repeating weekdays must be Monday through Sunday (1 to 7).", "重复提醒的星期必须为周一至周日（1 至 7）。");
        CHINESE.put("not Yeshas valid familyhealthbackupcopyfile", "这不是有效的家庭健康备份文件。");
        CHINESE.put("This is not a valid family health backup file.", "这不是有效的家庭健康备份文件。");
        CHINESE.put("onlymanagementmembercan ViewauditDaylog", "只有管理员可以查看审计日志。");
        CHINESE.put("Only administrators can view the audit log.", "只有管理员可以查看审计日志。");
        CHINESE.put("onlymanagementmembercan maintainMenu", "只有管理员可以管理菜单。");
        CHINESE.put("Only administrators can manage menus.", "只有管理员可以管理菜单。");
        CHINESE.put("prescriptionActionsNonevalid", "处方操作无效。");
        CHINESE.put("Invalid prescription action.", "处方操作无效。");
        CHINESE.put("prescriptionchangePlease Addversionthis , keeporiginalsolution", "请新增处方版本，并保留原方案。");
        CHINESE.put("Create a new prescription version to preserve the original plan.", "请新增处方版本，并保留原方案。");
        CHINESE.put("prescriptiondosageUnitmust and MedicationInventoryUnitonecause, Please first verifyInventory", "处方剂量单位必须与药品库存单位一致，请先核对库存设置。");
        CHINESE.put("The prescription dose unit must match the medication stock unit. Verify stock settings first.", "处方剂量单位必须与药品库存单位一致，请先核对库存设置。");
        CHINESE.put("prescriptionhistorycannotDelete, Please Cancelnot take effectversionthis  or Addstop medicationprescription", "处方历史不能删除，请取消尚未生效的版本或新增停药医嘱。");
        CHINESE.put("Prescription history cannot be deleted. Cancel an inactive version or create a stop-medication order.", "处方历史不能删除，请取消尚未生效的版本或新增停药医嘱。");
        CHINESE.put("recordtypeNonevalid", "记录类型无效。");
        CHINESE.put("Invalid record type.", "记录类型无效。");
        CHINESE.put("responsible forpersonmustYesthis Family Member carecompletemember", "负责人必须是当前家庭成员的照护团队成员。");
        CHINESE.put("The assignee must belong to this family member's care team.", "负责人必须是当前家庭成员的照护团队成员。");
        CHINESE.put("runWeekNonevalid", "运行频率无效。");
        CHINESE.put("Invalid run frequency.", "运行频率无效。");
        CHINESE.put("scheduleInvalid status.", "计划状态无效。");
        CHINESE.put("Invalid schedule status.", "计划状态无效。");
        CHINESE.put("scheduleTimeformatincorrect", "计划时间格式无效。");
        CHINESE.put("Invalid schedule time format.", "计划时间格式无效。");
        CHINESE.put("scheduledoes not exist or does not belong tocurrentFamily Member", "计划不存在或不属于当前家庭成员。");
        CHINESE.put("The schedule does not exist or belongs to another family member.", "计划不存在或不属于当前家庭成员。");
        CHINESE.put("symptomlevelshouldin 0to 10between", "症状程度必须在 0 到 10 之间。");
        CHINESE.put("Symptom severity must be between 0 and 10.", "症状程度必须在 0 到 10 之间。");
        CHINESE.put("take effectprescriptionPlease throughAddchange or stop medicationprescriptionprocess", "请通过新增版本或停药医嘱调整已生效处方。");
        CHINESE.put("Change an active prescription by creating a new version or a stop-medication order.", "请通过新增版本或停药医嘱调整已生效处方。");
        CHINESE.put("this Datealready has schedule, Please Editoriginalschedule", "该日期已有计划，请编辑原计划。");
        CHINESE.put("A schedule already exists for this date. Edit the existing schedule.", "该日期已有计划，请编辑原计划。");
        CHINESE.put("this WeekNoneDialysisdata", "此周期没有透析记录。");
        CHINESE.put("There are no dialysis records for this period.", "此周期没有透析记录。");
        CHINESE.put("Confirmed successfully.", "确认成功。");
        CHINESE.put("Resolved successfully.", "处理成功。");
        CHINESE.put("Alert check completed.", "提醒检查完成。");
        CHINESE.put("Menus assigned successfully.", "菜单分配成功。");
        CHINESE.put("Password updated successfully. Please sign in again.", "密码更新成功，请重新登录。");
        CHINESE.put("Care-plan collaboration is not enabled.", "照护计划协作未启用。");
        CHINESE.put("Invalid request parameters. Check fields, identifiers, and timestamps with offsets.", "请求参数无效，请检查字段、编号及带时区偏移的时间。");
        CHINESE.put("The care plan or notification state changed. Refresh and try again.", "照护计划或通知状态已变更，请刷新后重试。");
        CHINESE.put("The report request is invalid.", "报告请求无效。");
        CHINESE.put("You do not have access to this patient or report.", "您无权访问该患者或报告。");
        CHINESE.put("Care-plan reporting is disabled.", "照护计划报告功能未启用。");
        CHINESE.put("Report access changed. Generate the report again.", "报告权限已变化，请重新生成。");
        CHINESE.put("The report exceeds a resource limit. Select a smaller scope or format.", "报告超出资源限制，请缩小范围或选择较小的导出格式。");
        CHINESE.put("The report data is inconsistent.", "报告数据不一致，无法生成准确报告。");
        CHINESE.put("The report cannot be rendered. Try HTML instead.", "报告无法完整渲染，请尝试HTML格式。");
        CHINESE.put("Report generation timed out. Select a smaller scope or format.", "报告生成超时，请缩小范围或选择较小的导出格式。");
        CHINESE.put("Access revoked.", "授权已撤销。");
        CHINESE.put("Appointment cancelled.", "预约已取消。");
        CHINESE.put("Assessment schedule disabled.", "评估计划已停用。");
        CHINESE.put("Patient added to group.", "患者已加入分组。");
        CHINESE.put("Clinical note saved.", "临床笔记已保存。");
        CHINESE.put("Care plan saved.", "照护计划已保存。");
        CHINESE.put("Review completed.", "复核已完成。");
        CHINESE.put("Doctor assignment saved.", "医生分配已保存。");
        CHINESE.put("Built-in platform roles cannot be deleted", "平台内置角色不能删除");
        CHINESE.put("Platform administration menus can only belong to the administrator role", "平台管理菜单只能授予管理员角色");
        CHINESE.put("Only administrators can view menu configuration", "只有管理员可以查看菜单配置");
        CHINESE.put("Access denied to this data.", "您无权访问此数据。");
        CHINESE.put("Invalid notification signing configuration.", "通知签名配置无效。");
        CHINESE.put("The bot rejected the message. Check the webhook URL, keyword, and signature settings.", "机器人拒绝接收消息，请检查 Webhook 地址、关键词和签名设置。");
        FIELDS.put("unit", new String[] {"Unit", "单位"});
        FIELDS.put("valuePrimary", new String[] {"Primary measurement value", "主要测量值"});
        FIELDS.put("granteeUserId", new String[] {"Grantee", "被授权人"});
        FIELDS.put("granteeRole", new String[] {"Grantee role", "被授权角色"});
        FIELDS.put("accessLevel", new String[] {"Access level", "访问级别"});
        FIELDS.put("workDate", new String[] {"Work date", "排班日期"});
        FIELDS.put("startTime", new String[] {"Start time", "开始时间"});
        FIELDS.put("endTime", new String[] {"End time", "结束时间"});
        FIELDS.put("plannedDate", new String[] {"Planned date", "计划日期"});
        FIELDS.put("scaleCode", new String[] {"Assessment scale", "评估量表"});
        FIELDS.put("id", new String[] {"Record ID", "记录编号"});
        FIELDS.put("patientId", new String[] {"Patient", "患者"});
        FIELDS.put("doctorUserId", new String[] {"Doctor", "医生"});
        FIELDS.put("targetUserId", new String[] {"Recipient", "接收者"});
        FIELDS.put("symptom", new String[] {"Symptom or consultation question", "症状或咨询问题"});
        FIELDS.put("content", new String[] {"Message content", "消息内容"});
        FIELDS.put("medicalHistory", new String[] {"Medical history", "既往史"});
        FIELDS.put("durationText", new String[] {"Duration", "持续时间"});
        FIELDS.put("transferAdvice", new String[] {"Referral advice", "转科建议"});
        FIELDS.put("name", new String[] {"Name", "名称"});
        FIELDS.put("title", new String[] {"Title", "标题"});
        FIELDS.put("groupName", new String[] {"Group name", "分组名称"});
        FIELDS.put("startAt", new String[] {"Start time", "开始时间"});
        FIELDS.put("endAt", new String[] {"End time", "结束时间"});
        FIELDS.put("metricType", new String[] {"Measurement type", "指标类型"});
        FIELDS.put("value", new String[] {"Measurement value", "指标数值"});
        FIELDS.put("occurredAt", new String[] {"Occurrence time", "发生时间"});
        FIELDS.put("note", new String[] {"Note", "备注"});
        FIELDS.put("planType", new String[] {"Plan type", "计划类型"});
        FIELDS.put("instructions", new String[] {"Instructions", "说明"});
        FIELDS.put("medicationName", new String[] {"Medication name", "药品名称"});
        FIELDS.put("dose", new String[] {"Dose", "剂量"});
        FIELDS.put("frequency", new String[] {"Frequency", "频次"});
        FIELDS.put("route", new String[] {"Route", "给药途径"});
        FIELDS.put("recordDate", new String[] {"Record date", "记录日期"});
        FIELDS.put("description", new String[] {"Description", "描述"});
        FIELDS.put("vaccineName", new String[] {"Vaccine name", "疫苗名称"});
        FIELDS.put("scaleType", new String[] {"Assessment scale", "评估量表"});
        FIELDS.put("reason", new String[] {"Reason", "原因"});
        FIELDS.put("relationType", new String[] {"Relationship", "关系"});
        FIELDS.put("recordType", new String[] {"Record type", "记录类型"});
        FIELDS.put("userId", new String[] {"User", "用户"});
    }
    private SystemMessageCatalog() { }

    static String localize(String message, boolean chinese) {
        if (message == null || message.trim().isEmpty()) return message;
        String normalized = ENGLISH.getOrDefault(message, message);
        String exact = chinese ? CHINESE.get(normalized) : ENGLISH.get(message);
        if (exact != null) return exact;
        if (chinese && CHINESE.containsKey(message)) return CHINESE.get(message);
        String[][] prefixes = {
            {"PDFFailed to parse file: ", "Failed to parse PDF: ", "PDF 解析失败："},
            {"backupcopyincludeduplicate or missingID: ", "The backup contains duplicate or missing IDs: ", "备份包含重复或缺失的 ID："},
            {"datadatabasemissingtable ", "The database is missing table ", "数据库缺少表："},
            {"Failed to save: ", "Failed to save: ", "保存失败："},
            {"Update failed: ", "Update failed: ", "更新失败："},
            {"Failed to load: ", "Failed to load: ", "加载失败："},
            {"Failed to read file: ", "Failed to read file: ", "读取文件失败："},
            {"Failed to parse file: ", "Failed to parse file: ", "解析文件失败："},
            {"Failed to parse Word document: ", "Failed to parse Word document: ", "Word 文档解析失败："},
            {"Failed to extract tables from Word document: ", "Failed to extract tables from Word document: ", "Word 文档表格提取失败："},
            {"Unsupported data type: ", "Unsupported data type: ", "不支持的数据类型："},
            {"Unsupported file format: ", "Unsupported file format: ", "不支持的文件格式："},
            {"Notification delivery failed: ", "Notification delivery failed: ", "通知发送失败："}
        };
        for (String[] prefix : prefixes) {
            if (message.startsWith(prefix[0])) {
                String suffix = message.substring(prefix[0].length());
                // Nested errors are known system text; filenames, codes and other unknown suffixes are preserved.
                return prefix[chinese ? 2 : 1] + localize(suffix, chinese);
            }
        }
        Matcher match = Pattern.compile("^([A-Za-z][A-Za-z0-9]*) is required\\.$").matcher(message);
        if (match.matches() && FIELDS.containsKey(match.group(1))) {
            return FIELDS.get(match.group(1))[chinese ? 1 : 0] + (chinese ? "不能为空。" : " is required.");
        }
        match = Pattern.compile("^([A-Za-z][A-Za-z0-9]*) exceeds ([0-9]+) characters\\.$").matcher(message);
        if (match.matches() && FIELDS.containsKey(match.group(1))) {
            return FIELDS.get(match.group(1))[chinese ? 1 : 0] + (chinese ? "不能超过 " : " must not exceed ") + match.group(2) + (chinese ? " 个字符。" : " characters.");
        }
        if (!chinese) return normalized;
        match = Pattern.compile("^Saved ([0-9]+) records$").matcher(message);
        if (match.matches()) return "已保存 " + match.group(1) + " 条记录";
        match = Pattern.compile("^(PHQ9|GAD7|WHO5) requires ([0-9]+) item scores\\.$").matcher(message);
        if (match.matches()) return match.group(1) + " 需要填写 " + match.group(2) + " 题得分。";
        match = Pattern.compile("^(PHQ9|GAD7|WHO5) item scores must be between 0 and ([0-9]+)\\.$").matcher(message);
        if (match.matches()) return match.group(1) + " 各题得分必须在 0 到 " + match.group(2) + " 之间。";
        match = Pattern.compile("^The entered text is too long \\(maximum ([0-9]+) characters\\)\\.$").matcher(message);
        if (match.matches()) return "输入内容过长，最多允许 " + match.group(1) + " 个字符。";
        match = Pattern.compile("^Measurement unit must be (mmHg|%|kg|bpm|°C) for (BP|SPO2|WEIGHT|HEART_RATE|TEMPERATURE)\\.$").matcher(message);
        if (match.matches()) {
            String type = match.group(2);
            String label = "BP".equals(type) ? "血压" : "SPO2".equals(type) ? "血氧" : "WEIGHT".equals(type) ? "体重" : "HEART_RATE".equals(type) ? "心率" : "体温";
            return label + "指标的单位必须为 " + match.group(1) + "。";
        }
        return normalized;
    }
}
